/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useEffect, useState } from 'react';
import {
  adaptiveApi,
  type CompleteStudentModelData,
  type TopicMasteryData,
  type AdaptiveRecommendationData,
} from '../../services/adaptiveApi';
import { quizApi } from '../../services/quizApi';
import { useStudySession } from '../../hooks/useStudySession';
import { ActiveNavTab } from '../../types';

interface AdaptiveModelViewProps {
  onNavigate?: (tab: ActiveNavTab) => void;
}

export const AdaptiveModelView: React.FC<AdaptiveModelViewProps> = ({ onNavigate }) => {
  useStudySession();

  const [model, setModel] = useState<CompleteStudentModelData | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [syncing, setSyncing] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [selectedSubject, setSelectedSubject] = useState<string>('all');
  const [launchingTopic, setLaunchingTopic] = useState<string | null>(null);
  const [showFormulaModal, setShowFormulaModal] = useState<boolean>(false);

  const fetchModel = async () => {
    try {
      setLoading(true);
      const data = await adaptiveApi.getModel();
      setModel(data);
      setError(null);
    } catch (err: any) {
      setError(err.message || 'Failed to load adaptive student model.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchModel();
  }, []);

  const handleSync = async () => {
    try {
      setSyncing(true);
      const res = await adaptiveApi.sync();
      setModel(res.model);
      setError(null);
    } catch (err: any) {
      setError(err.message || 'Failed to sync adaptive student model.');
    } finally {
      setSyncing(false);
    }
  };

  const handleLaunchPractice = async (topic: string, subject: string, difficulty: 'easy' | 'medium' | 'hard') => {
    try {
      setLaunchingTopic(topic);
      await quizApi.createQuiz({
        title: `Adaptive Practice: ${topic}`,
        description: `Targeted practice session generated by EDUMATE Adaptive Model for ${topic} (${difficulty} difficulty).`,
        mode: 'PRACTICE',
        source: 'topic',
        subject,
        topic,
        question_count: 5,
        time_limit_minutes: 10,
        difficulty,
        negative_marking: false,
        negative_mark_value: 0,
        randomization: true,
      });

      if (onNavigate) {
        onNavigate('quizzes');
      }
    } catch (err: any) {
      console.warn('[AdaptiveModelView] Practice launch note:', err);
      if (onNavigate) {
        onNavigate('quizzes');
      }
    } finally {
      setLaunchingTopic(null);
    }
  };

  // Filter topics by selected subject tab
  const filteredTopics = model?.topics
    ? selectedSubject === 'all'
      ? model.topics
      : model.topics.filter((t) => t.subject === selectedSubject)
    : [];

  const distinctSubjects = model?.subjects ? model.subjects.map((s) => s.subject) : [];

  return (
    <div className="flex flex-col gap-6 pb-16">
      {/* Header and Sync Control */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-[22px] font-bold text-[#0b1c30] tracking-tight font-['Inter']">
              EDUMATE Adaptive Student Model
            </h2>
            <button
              onClick={() => setShowFormulaModal(true)}
              className="text-[#0051d5] hover:text-[#003da5] text-[13px] font-medium flex items-center gap-1 cursor-pointer transition-colors"
              title="Inspect deterministic mastery formula"
            >
              <span className="material-symbols-outlined text-[16px]">info</span>
              <span>How it works</span>
            </button>
          </div>
          <p className="text-[13px] text-[#44474d] mt-0.5">
            Deterministic, explainable representation of your knowledge state, retention stability, and difficulty readiness.
          </p>
        </div>

        <button
          onClick={handleSync}
          disabled={syncing || loading}
          className="flex items-center justify-center gap-2 px-4 py-2 bg-[#0051d5] hover:bg-[#0041b0] disabled:opacity-50 text-white rounded-xl text-[13px] font-semibold transition-colors cursor-pointer shadow-xs"
        >
          <span className={`material-symbols-outlined text-[18px] ${syncing ? 'animate-spin' : ''}`}>
            sync
          </span>
          <span>{syncing ? 'Recalculating...' : 'Recalculate Model'}</span>
        </button>
      </div>

      {error && (
        <div className="p-4 rounded-xl bg-red-50 border border-red-200 text-red-800 text-[13px]">
          {error}
        </div>
      )}

      {/* Primary Diagnostic Metrics Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        {/* Card 1: Overall Mastery */}
        <div className="bg-white p-5 rounded-2xl border border-[#c5c6ce]/30 shadow-xs flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between">
              <span className="text-[13px] text-[#44474d] font-semibold">Overall Mastery</span>
              <span className="text-[11px] text-[#75777e] font-medium">Bayesian Shrunk</span>
            </div>
            <div className="flex items-baseline gap-2 my-2">
              <span className="text-[32px] font-bold text-[#0b1c30]">
                {loading ? '...' : `${model?.profile?.overall_mastery ?? 0}%`}
              </span>
              <span className="text-[12px] text-[#75777e]">
                (raw acc: {model?.profile?.overall_accuracy ?? 0}%)
              </span>
            </div>
          </div>
          <div className="text-[11px] text-[#75777e]">
            Guards against lucky guesses via statistical prior shrinkage.
          </div>
        </div>

        {/* Card 2: Evidence & Confidence */}
        <div className="bg-white p-5 rounded-2xl border border-[#c5c6ce]/30 shadow-xs flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between">
              <span className="text-[13px] text-[#44474d] font-semibold">Evidence Confidence</span>
              <span className="text-[11px] text-[#0051d5] font-bold">
                {model?.summary?.totalAssessedQuestions ?? 0} Qs Assessed
              </span>
            </div>
            <div className="flex items-baseline gap-2 my-2">
              <span className="text-[32px] font-bold text-[#0051d5]">
                {loading ? '...' : `${model?.profile?.overall_confidence ?? 0}%`}
              </span>
              <span className="text-[12px] text-[#44474d] font-medium">sufficiency</span>
            </div>
          </div>
          <div className="w-full bg-[#eff4ff] h-2 rounded-full overflow-hidden">
            <div
              className="bg-[#0051d5] h-full rounded-full transition-all duration-300"
              style={{ width: `${model?.profile?.overall_confidence ?? 0}%` }}
            ></div>
          </div>
        </div>

        {/* Card 3: Learning Consistency */}
        <div className="bg-white p-5 rounded-2xl border border-[#c5c6ce]/30 shadow-xs flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between">
              <span className="text-[13px] text-[#44474d] font-semibold">Learning Consistency</span>
              <span className="text-[11px] text-amber-600 font-bold">
                {model?.profile?.metadata?.activeStreakDays ?? 0} Day Streak
              </span>
            </div>
            <div className="flex items-baseline gap-2 my-2">
              <span className="text-[32px] font-bold text-amber-600">
                {loading ? '...' : `${model?.profile?.learning_consistency ?? 0}`}
              </span>
              <span className="text-[12px] text-[#75777e]">/ 100 Index</span>
            </div>
          </div>
          <div className="text-[11px] text-[#75777e]">
            Evaluated from daily study regularity and assessment cadence.
          </div>
        </div>

        {/* Card 4: Assessment Totals */}
        <div className="bg-white p-5 rounded-2xl border border-[#c5c6ce]/30 shadow-xs flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between">
              <span className="text-[13px] text-[#44474d] font-semibold">Assessment Footprint</span>
              <span className="text-[11px] text-emerald-600 font-bold">Verified Logs</span>
            </div>
            <div className="grid grid-cols-3 gap-2 my-2 text-center">
              <div className="p-1.5 rounded-lg bg-emerald-50">
                <span className="block text-[16px] font-bold text-emerald-700">
                  {model?.profile?.total_correct_answers ?? 0}
                </span>
                <span className="text-[10px] text-emerald-800 font-medium">Correct</span>
              </div>
              <div className="p-1.5 rounded-lg bg-rose-50">
                <span className="block text-[16px] font-bold text-rose-700">
                  {model?.profile?.total_incorrect_answers ?? 0}
                </span>
                <span className="text-[10px] text-rose-800 font-medium">Missed</span>
              </div>
              <div className="p-1.5 rounded-lg bg-slate-100">
                <span className="block text-[16px] font-bold text-slate-700">
                  {model?.profile?.total_skipped_answers ?? 0}
                </span>
                <span className="text-[10px] text-slate-600 font-medium">Skipped</span>
              </div>
            </div>
          </div>
          <div className="text-[11px] text-[#75777e]">
            {model?.profile?.total_quizzes_completed ?? 0} quizzes completed to date.
          </div>
        </div>
      </div>

      {/* Deterministic Learning Recommendations */}
      <div className="bg-white p-5 lg:p-6 rounded-2xl border border-[#c5c6ce]/30 shadow-xs">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="text-[16px] font-bold text-[#0b1c30]">
              Adaptive Learning Recommendations
            </h3>
            <span className="text-[12px] text-[#75777e]">
              Derived deterministically from current retention decay, conceptual error rates, and difficulty thresholds.
            </span>
          </div>
          <span className="text-[12px] text-[#0051d5] font-semibold bg-[#eff4ff] px-2.5 py-1 rounded-lg">
            Rule-Based & Explainable
          </span>
        </div>

        {loading ? (
          <div className="py-8 text-center text-[13px] text-[#75777e]">
            Synthesizing recommendations from assessment evidence...
          </div>
        ) : model?.recommendations && model.recommendations.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {model.recommendations.map((rec) => {
              const typeIcon =
                rec.type === 'revision'
                  ? 'replay'
                  : rec.type === 'retention'
                  ? 'history_edu'
                  : rec.type === 'challenge'
                  ? 'bolt'
                  : 'verified';

              const priorityBorder =
                rec.priority === 'high'
                  ? 'border-l-4 border-l-rose-500'
                  : rec.priority === 'medium'
                  ? 'border-l-4 border-l-amber-500'
                  : 'border-l-4 border-l-blue-500';

              return (
                <div
                  key={rec.id}
                  className={`p-4 rounded-xl bg-[#eff4ff] border border-[#d3e4fe] flex flex-col justify-between ${priorityBorder}`}
                >
                  <div>
                    <div className="flex items-center justify-between text-[11px] text-[#75777e] mb-1">
                      <span>{rec.subject}</span>
                      <span className="font-semibold uppercase tracking-wider">{rec.priority} Priority</span>
                    </div>

                    <h4 className="text-[14px] font-bold text-[#0b1c30] flex items-center gap-1.5 mt-1">
                      <span className="material-symbols-outlined text-[18px] text-[#0051d5]">
                        {typeIcon}
                      </span>
                      <span>{rec.title}</span>
                    </h4>

                    <p className="text-[12px] text-[#44474d] mt-2 leading-relaxed">
                      {rec.description}
                    </p>

                    <div className="mt-3 p-2.5 rounded-lg bg-white/70 border border-[#c5c6ce]/20 text-[11px] text-[#555860] leading-normal">
                      <strong className="text-[#0b1c30]">Evidence Reason:</strong> {rec.reason}
                    </div>
                  </div>

                  <div className="flex items-center justify-between mt-4 pt-3 border-t border-[#d3e4fe]">
                    <span className="text-[11px] text-[#44474d] font-medium capitalize">
                      Suggested: {rec.recommendedDifficulty} ({rec.suggestedQuestionCount} Qs)
                    </span>
                    <button
                      onClick={() => handleLaunchPractice(rec.topic, rec.subject, rec.recommendedDifficulty)}
                      disabled={launchingTopic === rec.topic}
                      className="px-3 py-1.5 bg-[#0051d5] hover:bg-[#0041b0] disabled:opacity-50 text-white rounded-lg text-[12px] font-semibold transition-colors cursor-pointer"
                    >
                      {launchingTopic === rec.topic ? 'Starting...' : 'Practice Now'}
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        ) : (
          <div className="p-8 text-center text-[13px] text-[#75777e] bg-[#eff4ff] rounded-xl">
            No recommendations generated. Complete quiz assessments to populate evidence.
          </div>
        )}
      </div>

      {/* Subject-Level Readiness Progression */}
      <div className="bg-white p-5 lg:p-6 rounded-2xl border border-[#c5c6ce]/30 shadow-xs">
        <h3 className="text-[16px] font-bold text-[#0b1c30] mb-2">Subject Mastery & Readiness</h3>
        <p className="text-[12px] text-[#75777e] mb-4">
          Holistic curriculum progression combining all assessed topics within each subject area.
        </p>

        {loading ? (
          <div className="py-8 text-center text-[13px] text-[#75777e]">Loading subject mastery...</div>
        ) : model?.subjects && model.subjects.length > 0 ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {model.subjects.map((s) => (
              <div key={s.id} className="p-4 rounded-xl bg-[#eff4ff] border border-[#d3e4fe] flex flex-col justify-between">
                <div>
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-[14px] text-[#0b1c30]">{s.subject}</span>
                    <span className="text-[12px] font-bold text-[#0051d5]">{s.mastery_score}%</span>
                  </div>
                  <div className="text-[11px] text-[#75777e] mt-0.5">
                    {s.assessed_question_count} assessed · {s.accuracy}% raw acc
                  </div>

                  <div className="w-full bg-[#d3e4fe] h-2 rounded-full overflow-hidden mt-3">
                    <div
                      className="bg-[#0051d5] h-full rounded-full transition-all duration-300"
                      style={{ width: `${s.mastery_score}%` }}
                    ></div>
                  </div>
                </div>

                <div className="flex items-center justify-between mt-4 pt-2 text-[11px] border-t border-[#d3e4fe]">
                  <span className="text-[#44474d] capitalize font-medium">Readiness: {s.readiness_indicator}</span>
                  <span className="text-[#75777e] capitalize">Trend: {s.trend.replace('_', ' ')}</span>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="p-8 text-center text-[13px] text-[#75777e] bg-[#eff4ff] rounded-xl">
            No subject assessments recorded yet. Complete quizzes to establish subject mastery.
          </div>
        )}
      </div>

      {/* Topic Mastery Matrix with Subject Filter Tabs */}
      <div className="bg-white p-5 lg:p-6 rounded-2xl border border-[#c5c6ce]/30 shadow-xs">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-4">
          <div>
            <h3 className="text-[16px] font-bold text-[#0b1c30]">Topic-Level Mastery & Retention Matrix</h3>
            <span className="text-[12px] text-[#75777e]">
              Detailed breakdown of every conceptual topic assessed, including retention status and difficulty readiness.
            </span>
          </div>

          {/* Interactive Subject Filter Tabs compliant with frontend-design */}
          {distinctSubjects.length > 0 && (
            <div className="flex items-center gap-1 p-1 bg-slate-100 rounded-lg overflow-x-auto">
              <button
                onClick={() => setSelectedSubject('all')}
                className={`px-3 py-1.5 text-xs font-medium rounded-md transition-colors cursor-pointer ${
                  selectedSubject === 'all'
                    ? 'bg-white text-slate-900 shadow-xs'
                    : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                All Subjects ({model?.topics?.length ?? 0})
              </button>
              {distinctSubjects.map((subj) => {
                const count = model?.topics?.filter((t) => t.subject === subj).length ?? 0;
                return (
                  <button
                    key={subj}
                    onClick={() => setSelectedSubject(subj)}
                    className={`px-3 py-1.5 text-xs font-medium rounded-md transition-colors cursor-pointer whitespace-nowrap ${
                      selectedSubject === subj
                        ? 'bg-white text-slate-900 shadow-xs'
                        : 'text-slate-600 hover:text-slate-900'
                    }`}
                  >
                    {subj} ({count})
                  </button>
                );
              })}
            </div>
          )}
        </div>

        {/* Topic Matrix Table */}
        {loading ? (
          <div className="py-12 text-center text-[13px] text-[#75777e]">Loading topic mastery matrix...</div>
        ) : filteredTopics.length > 0 ? (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse text-[13px]">
              <thead>
                <tr className="border-b border-slate-200 text-[#75777e] text-[11px] font-semibold uppercase tracking-wider">
                  <th className="py-3 px-3">Subject & Topic</th>
                  <th className="py-3 px-3">Mastery</th>
                  <th className="py-3 px-3">Raw Accuracy</th>
                  <th className="py-3 px-3">Evidence</th>
                  <th className="py-3 px-3">Confidence</th>
                  <th className="py-3 px-3">Trend</th>
                  <th className="py-3 px-3">Retention Status</th>
                  <th className="py-3 px-3">Recommended</th>
                  <th className="py-3 px-3 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-[#0b1c30]">
                {filteredTopics.map((t) => {
                  const retentionColor =
                    t.retention_indicator === 'fresh'
                      ? 'text-emerald-700'
                      : t.retention_indicator === 'consolidating'
                      ? 'text-blue-700'
                      : t.retention_indicator === 'decaying'
                      ? 'text-amber-700'
                      : t.retention_indicator === 'needs_revision'
                      ? 'text-rose-700'
                      : 'text-slate-600';

                  const trendIcon =
                    t.trend === 'improving'
                      ? 'trending_up'
                      : t.trend === 'declining'
                      ? 'trending_down'
                      : t.trend === 'steady'
                      ? 'trending_flat'
                      : 'remove';

                  const trendColor =
                    t.trend === 'improving'
                      ? 'text-emerald-600'
                      : t.trend === 'declining'
                      ? 'text-rose-600'
                      : 'text-slate-400';

                  return (
                    <tr key={`${t.subject}-${t.topic}`} className="hover:bg-[#eff4ff]/40 transition-colors">
                      <td className="py-3 px-3 font-semibold">
                        <div className="flex flex-col">
                          <span className="text-[13px] text-[#0b1c30]">{t.topic}</span>
                          <span className="text-[11px] text-[#75777e]">{t.subject}</span>
                        </div>
                      </td>
                      <td className="py-3 px-3 font-bold text-[#0051d5]">
                        {t.mastery_score}%
                      </td>
                      <td className="py-3 px-3 text-[#44474d]">
                        {t.accuracy}%
                      </td>
                      <td className="py-3 px-3 text-[#555860]">
                        {t.attempts} att ({t.correct}C / {t.incorrect}M)
                      </td>
                      <td className="py-3 px-3">
                        <div className="flex items-center gap-1.5">
                          <span className="text-[12px] font-medium">{t.confidence_score}%</span>
                          <div className="w-12 bg-slate-100 h-1.5 rounded-full overflow-hidden">
                            <div
                              className="bg-[#0051d5] h-full rounded-full"
                              style={{ width: `${t.confidence_score}%` }}
                            ></div>
                          </div>
                        </div>
                      </td>
                      <td className="py-3 px-3">
                        <div className={`flex items-center gap-1 text-[12px] font-medium ${trendColor}`}>
                          <span className="material-symbols-outlined text-[16px]">{trendIcon}</span>
                          <span className="capitalize">{t.trend.replace('_', ' ')}</span>
                        </div>
                      </td>
                      <td className="py-3 px-3 font-medium">
                        <span className={`capitalize ${retentionColor}`}>
                          {t.retention_indicator.replace('_', ' ')}
                        </span>
                      </td>
                      <td className="py-3 px-3">
                        <span className="text-[12px] font-medium capitalize text-slate-700">
                          {t.recommended_difficulty}
                        </span>
                      </td>
                      <td className="py-3 px-3 text-right">
                        <button
                          onClick={() => handleLaunchPractice(t.topic, t.subject, t.recommended_difficulty)}
                          disabled={launchingTopic === t.topic}
                          className="px-2.5 py-1 text-[12px] font-semibold text-[#0051d5] hover:bg-[#eff4ff] rounded-md transition-colors cursor-pointer"
                        >
                          {launchingTopic === t.topic ? '...' : 'Practice'}
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="p-8 text-center text-[13px] text-[#75777e] bg-[#eff4ff] rounded-xl">
            No topic performance data available for this filter.
          </div>
        )}
      </div>

      {/* Model Transparency & Mathematics Modal */}
      {showFormulaModal && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 backdrop-blur-xs">
          <div className="bg-white rounded-2xl max-w-xl w-full p-6 shadow-2xl border border-slate-200 flex flex-col gap-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100">
              <h3 className="text-[18px] font-bold text-[#0b1c30] flex items-center gap-2">
                <span className="material-symbols-outlined text-[#0051d5]">functions</span>
                <span>Deterministic Mastery Formulation</span>
              </h3>
              <button
                onClick={() => setShowFormulaModal(false)}
                className="p-1 rounded-lg text-slate-400 hover:text-slate-700 hover:bg-slate-100 cursor-pointer"
              >
                <span className="material-symbols-outlined text-[20px]">close</span>
              </button>
            </div>

            <div className="text-[13px] text-[#44474d] space-y-3 leading-relaxed">
              <p>
                The EDUMATE Adaptive Student Model is completely deterministic, explainable, and grounded in empirical assessment history. It does not use LLMs or random values.
              </p>

              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 font-mono text-[12px]">
                <strong>Confidence Formula:</strong>
                <br />
                Confidence = min(1.0, attempts / 10) * 100%
              </div>

              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 font-mono text-[12px]">
                <strong>Bayesian Mastery Shrinkage:</strong>
                <br />
                Mastery = (Confidence * Performance) + ((1 - Confidence) * 50% Baseline Prior)
              </div>

              <p>
                <strong>Why Bayesian Shrinkage?</strong> A student with 1 attempt and 1 correct answer has 100% raw accuracy, but only 10% evidence confidence. Their mastery score is shrunk to 55%, preventing a single lucky answer from prematurely classifying them as a master.
              </p>

              <p>
                <strong>Forgetting Curve Retention Decay:</strong> If a topic is not assessed for more than 14 days, its retention indicator transitions to <em>decaying</em>, triggering targeted spaced repetition recommendations.
              </p>
            </div>

            <div className="pt-3 border-t border-slate-100 flex justify-end">
              <button
                onClick={() => setShowFormulaModal(false)}
                className="px-4 py-2 bg-[#0051d5] text-white rounded-xl text-[13px] font-semibold hover:bg-[#0041b0] cursor-pointer"
              >
                Got It
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
