/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface SeedQuestion {
  subject: string;
  topic: string;
  difficulty: 'easy' | 'medium' | 'hard';
  question_type: 'MCQ' | 'MULTIPLE_SELECT' | 'TRUE_FALSE' | 'FILL_BLANK' | 'VERY_SHORT' | 'SHORT' | 'LONG';
  question_text: string;
  options: { id: string; text: string }[];
  correct_option_ids: string[];
  correct_answer_text?: string;
  explanation: string;
  formula_hint?: string;
  default_marks: number;
  section: string;
}

export const SEED_QUESTION_BANK: SeedQuestion[] = [
  // ==================== PHYSICS ====================
  // Physics - Gauss Law & Spherical Shells
  {
    subject: 'Physics',
    topic: 'Gauss Law & Spherical Shells',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'A spherical Gaussian surface encloses a point charge q. If the radius of the sphere is doubled, how does the total electric flux through the surface change?',
    options: [
      { id: 'a', text: 'It doubles' },
      { id: 'b', text: 'It quadruples' },
      { id: 'c', text: 'It remains unchanged' },
      { id: 'd', text: 'It halves' },
    ],
    correct_option_ids: ['c'],
    explanation: 'By Gauss’s Law (Φ = q / ε₀), total electric flux depends solely on the net enclosed charge, not on the dimensions or geometry of the Gaussian boundary.',
    formula_hint: 'Φ = Q_enclosed / ε₀',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Physics',
    topic: 'Gauss Law & Spherical Shells',
    difficulty: 'hard',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Consider an isolated conducting spherical shell carrying a net charge +Q. Which of the following statements are physically correct?',
    options: [
      { id: 'a', text: 'The electric field at any point inside the inner cavity (with no enclosed charge) is zero.' },
      { id: 'b', text: 'The electrostatic potential inside the conducting material is non-zero and constant.' },
      { id: 'c', text: 'All excess charge resides entirely on the outer surface of the shell.' },
      { id: 'd', text: 'The electric field just outside the surface is parallel to the surface.' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'For a static conductor: (a) E = 0 inside cavities with no charge; (b) V is constant throughout the conductor equal to kQ/R; (c) charges repel to the outer surface; (d) E is perpendicular (normal) to the surface, not parallel.',
    formula_hint: 'E_inside = 0, V_inside = kQ/R',
    default_marks: 2.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Physics',
    topic: 'Gauss Law & Spherical Shells',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'The electric field inside a hollow charged spherical conductor with zero cavity charge is always zero.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Any Gaussian surface drawn within the interior volume encloses zero net charge, resulting in zero electric flux and zero electric field in electrostatic equilibrium.',
    formula_hint: '∮ E · dA = Q_enc / ε₀ = 0',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Physics',
    topic: 'Gauss Law & Spherical Shells',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'According to Gauss’s Law, the total outward electric flux through any closed surface is equal to the net enclosed charge divided by the permittivity of free space. Write the standard symbol for free space permittivity.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'ε0',
    explanation: 'Electric flux Φ = Q_enc / ε₀, where ε₀ (epsilon naught) represents the electric permittivity of free space.',
    formula_hint: 'ε₀ ≈ 8.854 × 10⁻¹² F/m',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Physics',
    topic: 'Gauss Law & Spherical Shells',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'State Gauss’s Law in electrostatics in one concise sentence.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'The total electric flux through any closed surface is proportional to the total net electric charge enclosed within that surface divided by permittivity.',
    explanation: 'Gauss’s Law states that the surface integral of the electric field over a closed boundary equals 1/ε₀ times the total charge enclosed within that boundary.',
    formula_hint: '∮ E · dA = Q_enc / ε₀',
    default_marks: 2.0,
    section: 'Section B: Conceptual Analysis',
  },
  {
    subject: 'Physics',
    topic: 'Gauss Law & Spherical Shells',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain why the electric field immediately outside a charged conductor is E = σ / ε₀, whereas for a thin non-conducting sheet of charge it is E = σ / (2ε₀).',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'In a conductor, the electric field inside is zero, so all electric flux exits through the outer face of a Gaussian pillbox (EA = σA/ε₀ → E = σ/ε₀). For a thin non-conducting sheet, flux emerges from both opposite faces (2EA = σA/ε₀ → E = σ/(2ε₀)).',
    explanation: 'A conductor has zero internal field in static equilibrium, so only the outer surface of a Gaussian cylinder contributes flux. A non-conducting sheet has field lines radiating outward from both sides symmetrically.',
    formula_hint: 'Conductor: EA = Q/ε₀; Sheet: 2EA = Q/ε₀',
    default_marks: 3.0,
    section: 'Section B: Conceptual Analysis',
  },
  {
    subject: 'Physics',
    topic: 'Gauss Law & Spherical Shells',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'Using Gauss’s Law, derive the expressions for the electric field due to a uniformly charged solid non-conducting sphere of radius R and total charge Q for both (i) r ≥ R and (ii) r < R.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'For r ≥ R: E(4πr²) = Q/ε₀ => E = kQ / r². For r < R: Q_enc = Q(r³/R³), so E(4πr²) = Q(r³/R³)/ε₀ => E = (kQ / R³) * r.',
    explanation: 'Outside the sphere (r ≥ R), the enclosed charge is Q, giving an inverse square field E = Q/(4πε₀r²). Inside (r < R), charge density ρ = Q / (4/3 π R³), so Q_enc = ρ(4/3 π r³) = Q(r³/R³). Gauss’s law yields E = Qr / (4πε₀R³), increasing linearly with radial distance.',
    formula_hint: 'Outside: E ∝ 1/r²; Inside: E ∝ r',
    default_marks: 5.0,
    section: 'Section C: Extended Problem Solving',
  },

  // Physics - Electric Potential & Capacitance
  {
    subject: 'Physics',
    topic: 'Electric Potential & Capacitance',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'Two conducting plates separated by distance d have potential difference V. If a dielectric slab with dielectric constant κ = 4 fills the gap while the battery is disconnected, what happens to the electric field E?',
    options: [
      { id: 'a', text: 'E increases 4 times' },
      { id: 'b', text: 'E decreases to E₀ / 4' },
      { id: 'c', text: 'E remains constant' },
      { id: 'd', text: 'E drops to zero' },
    ],
    correct_option_ids: ['b'],
    explanation: 'When disconnected, the charge Q is fixed. Inserting dielectric increases capacitance C = κC₀. Since V = Q/C, V becomes V₀/κ, and E = V/d = E₀/κ = E₀/4.',
    formula_hint: 'E = E₀ / κ',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Physics',
    topic: 'Electric Potential & Capacitance',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the equivalent capacitance of three 6 µF capacitors connected in series?',
    options: [
      { id: 'a', text: '18 µF' },
      { id: 'b', text: '2 µF' },
      { id: 'c', text: '6 µF' },
      { id: 'd', text: '3 µF' },
    ],
    correct_option_ids: ['b'],
    explanation: 'For n identical capacitors in series, 1/C_eq = n / C, so C_eq = C / n = 6 µF / 3 = 2 µF.',
    formula_hint: '1/C_eq = 1/C₁ + 1/C₂ + 1/C₃',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Physics',
    topic: 'Electric Potential & Capacitance',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'The electrostatic potential is always zero at any point where the electric field is zero.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['false'],
    explanation: 'False. E is the negative spatial derivative (gradient) of potential: E = -dV/dr. Inside a charged hollow conductor, E = 0 but V is a non-zero constant (V = kQ/R).',
    formula_hint: 'E = -dV/dr',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },

  // Physics - Magnetic Forces & Induction
  {
    subject: 'Physics',
    topic: 'Magnetic Forces & Induction',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'A charged particle moves with velocity v parallel to a uniform magnetic field B. What is the magnetic Lorentz force acting on it?',
    options: [
      { id: 'a', text: 'F = q · v · B' },
      { id: 'b', text: 'F = 0' },
      { id: 'c', text: 'F = ½ q v B' },
      { id: 'd', text: 'F = q / (v · B)' },
    ],
    correct_option_ids: ['b'],
    explanation: 'The magnetic force is F = q(v × B) = q · v · B · sin(θ). For parallel motion θ = 0°, so sin(0°) = 0, giving F = 0.',
    formula_hint: 'F = q (v × B) = q v B sin θ',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Physics',
    topic: 'Magnetic Forces & Induction',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'According to Lenz’s Law, the direction of an induced current is such that it always:',
    options: [
      { id: 'a', text: 'Aids the magnetic flux change that produced it' },
      { id: 'b', text: 'Opposes the change in magnetic flux that caused it' },
      { id: 'c', text: 'Increases the resistance of the circuit' },
      { id: 'd', text: 'Points towards the magnetic north pole' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Lenz’s Law states that an induced electromotive force always generates a magnetic field that opposes the original change in magnetic flux, preserving conservation of energy.',
    formula_hint: 'ε = -dΦ_B / dt',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },

  // ==================== MATHEMATICS ====================
  // Mathematics - Calculus & Limits
  {
    subject: 'Mathematics',
    topic: 'Calculus & Limits',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Evaluate the limit: lim(x → 0) [sin(5x) / x].',
    options: [
      { id: 'a', text: '0' },
      { id: 'b', text: '1' },
      { id: 'c', text: '5' },
      { id: 'd', text: 'Does not exist' },
    ],
    correct_option_ids: ['c'],
    explanation: 'Using standard trigonometric limit lim(u → 0) [sin(u)/u] = 1, multiply and divide by 5: lim [5 * sin(5x)/(5x)] = 5 * 1 = 5.',
    formula_hint: 'lim(x→0) sin(kx)/x = k',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Mathematics',
    topic: 'Calculus & Limits',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the derivative of f(x) = x · ln(x) with respect to x?',
    options: [
      { id: 'a', text: 'ln(x)' },
      { id: 'b', text: '1 + ln(x)' },
      { id: 'c', text: '1 / x' },
      { id: 'd', text: 'x + ln(x)' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Using the product rule (u · v)’ = u’v + uv’: d/dx [x · ln(x)] = (1)·ln(x) + x·(1/x) = ln(x) + 1.',
    formula_hint: 'd/dx [u·v] = u’v + uv’',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Mathematics',
    topic: 'Calculus & Limits',
    difficulty: 'medium',
    question_type: 'TRUE_FALSE',
    question_text: 'If a function f(x) is continuous on a closed interval [a, b], it is necessarily differentiable on (a, b).',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['false'],
    explanation: 'False. Continuity does not guarantee differentiability. A classic counterexample is f(x) = |x| at x = 0, which is continuous everywhere but not differentiable at the origin.',
    formula_hint: 'Differentiability ⇒ Continuity, but Continuity ⇏ Differentiability',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Mathematics',
    topic: 'Calculus & Limits',
    difficulty: 'hard',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following functions have a horizontal asymptote at y = 0 as x → ∞?',
    options: [
      { id: 'a', text: 'f(x) = 1 / (x² + 1)' },
      { id: 'b', text: 'f(x) = e^(-x)' },
      { id: 'c', text: 'f(x) = (3x + 2) / (x² - 4)' },
      { id: 'd', text: 'f(x) = (2x² + 1) / (x + 3)' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: '(a) lim 1/(x²+1) = 0. (b) lim e^(-x) = 0. (c) Degree of denominator (2) > degree of numerator (1), so lim = 0. (d) Degree of numerator > denominator, approaches ∞.',
    formula_hint: 'lim(x→∞) f(x) = L',
    default_marks: 2.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Mathematics',
    topic: 'Calculus & Limits',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Evaluate the definite integral: ∫ from 0 to 2 of (3x²) dx.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '8',
    explanation: '∫ 3x² dx = x³ evaluated from 0 to 2 = 2³ - 0³ = 8.',
    formula_hint: '∫ x^n dx = x^(n+1)/(n+1)',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Mathematics',
    topic: 'Calculus & Limits',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'State the Mean Value Theorem (MVT) for derivatives and list its two necessary hypotheses.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Hypotheses: (1) f is continuous on [a, b], (2) f is differentiable on (a, b). Conclusion: There exists at least one c in (a, b) such that f’(c) = [f(b) - f(a)] / (b - a).',
    explanation: 'The MVT asserts that under continuity on the closed interval and differentiability on the open interval, there exists a point where the instantaneous rate of change equals the average rate of change.',
    formula_hint: 'f’(c) = (f(b) - f(a)) / (b - a)',
    default_marks: 3.0,
    section: 'Section B: Conceptual Analysis',
  },

  // Mathematics - Linear Algebra & Matrices
  {
    subject: 'Mathematics',
    topic: 'Linear Algebra & Matrices',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'For a square matrix A of order n, if det(A) = 3, what is det(2A)?',
    options: [
      { id: 'a', text: '6' },
      { id: 'b', text: '3 · 2^n' },
      { id: 'c', text: '3^n' },
      { id: 'd', text: '2^3' },
    ],
    correct_option_ids: ['b'],
    explanation: 'By determinant properties, det(k · A) = k^n · det(A). For scalar 2, det(2A) = 2^n · det(A) = 3 · 2^n.',
    formula_hint: 'det(kA) = k^n det(A)',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Mathematics',
    topic: 'Linear Algebra & Matrices',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'If the determinant of a square matrix A is zero, the system of linear equations A·x = 0 has only the trivial solution x = 0.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['false'],
    explanation: 'False. When det(A) = 0, matrix A is singular (non-invertible) and has non-trivial solutions (infinitely many solutions in its nullspace).',
    formula_hint: 'det(A) = 0 ⇔ dim(Null(A)) > 0',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },

  // ==================== CHEMISTRY ====================
  // Chemistry - Chemical Thermodynamics
  {
    subject: 'Chemistry',
    topic: 'Chemical Thermodynamics',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'For a process at constant temperature and pressure to be spontaneous, the change in Gibbs free energy (ΔG) must be:',
    options: [
      { id: 'a', text: 'Positive (ΔG > 0)' },
      { id: 'b', text: 'Negative (ΔG < 0)' },
      { id: 'c', text: 'Zero (ΔG = 0)' },
      { id: 'd', text: 'Equal to enthalpy change (ΔG = ΔH)' },
    ],
    correct_option_ids: ['b'],
    explanation: 'A negative change in Gibbs free energy (ΔG < 0) corresponds to an increase in the universe’s total entropy, indicating thermodynamic spontaneity at constant T and P.',
    formula_hint: 'ΔG = ΔH - TΔS < 0',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Chemistry',
    topic: 'Chemical Thermodynamics',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'If an endothermic reaction (ΔH > 0) has a positive entropy change (ΔS > 0), when is the reaction spontaneous?',
    options: [
      { id: 'a', text: 'At all temperatures' },
      { id: 'b', text: 'At high temperatures where T > ΔH / ΔS' },
      { id: 'c', text: 'At low temperatures where T < ΔH / ΔS' },
      { id: 'd', text: 'It is never spontaneous' },
    ],
    correct_option_ids: ['b'],
    explanation: 'In ΔG = ΔH - TΔS, as T increases, the -TΔS term becomes more negative. Spontaneity occurs when TΔS > ΔH, i.e., T > ΔH / ΔS.',
    formula_hint: 'T_equilibrium = ΔH / ΔS',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },

  // ==================== COMPUTER SCIENCE ====================
  // Computer Science - Data Structures & Algorithms
  {
    subject: 'Computer Science',
    topic: 'Data Structures & Algorithms',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the worst-case time complexity of searching for an element in a balanced Binary Search Tree (such as an AVL or Red-Black Tree) with n elements?',
    options: [
      { id: 'a', text: 'O(1)' },
      { id: 'b', text: 'O(log n)' },
      { id: 'c', text: 'O(n)' },
      { id: 'd', text: 'O(n log n)' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Self-balancing binary search trees maintain a maximum height of O(log n), ensuring that lookup, insertion, and deletion all execute in O(log n) worst-case time.',
    formula_hint: 'Height h ≤ 1.44 log₂(n+2)',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Computer Science',
    topic: 'Data Structures & Algorithms',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'A hash table guarantees O(1) worst-case lookup time regardless of hash collisions.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['false'],
    explanation: 'False. Hash tables offer O(1) average-case lookup, but in the worst case (e.g. all keys colliding into the same bucket), lookup degrades to O(n).',
    formula_hint: 'Average: O(1), Worst: O(n)',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Computer Science',
    topic: 'Data Structures & Algorithms',
    difficulty: 'hard',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following sorting algorithms are stable in their standard implementations?',
    options: [
      { id: 'a', text: 'Merge Sort' },
      { id: 'b', text: 'Insertion Sort' },
      { id: 'c', text: 'Standard Quick Sort' },
      { id: 'd', text: 'Heap Sort' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'Merge Sort and Insertion Sort preserve the relative order of identical elements (stable). Standard Quick Sort and Heap Sort perform non-adjacent swaps that violate stability.',
    formula_hint: 'Stability: duplicate keys retain original ordering',
    default_marks: 2.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Computer Science',
    topic: 'Data Structures & Algorithms',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What is the standard name of the abstract data type that operates under the First-In, First-Out (FIFO) principle?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Queue',
    explanation: 'A Queue enforces First-In, First-Out (FIFO) access order where items are enqueued at the tail and dequeued from the head.',
    formula_hint: 'FIFO vs LIFO (Stack)',
    default_marks: 1.0,
    section: 'Section A: Objective',
  },
  {
    subject: 'Computer Science',
    topic: 'Data Structures & Algorithms',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'Explain the fundamental difference between breadth-first search (BFS) and depth-first search (DFS) in graph traversal, including the primary data structure each uses.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'BFS explores neighbor nodes level by level using a FIFO Queue, finding the shortest unweighted path. DFS explores deep along each branch before backtracking using a LIFO Stack (or call stack recursion).',
    explanation: 'BFS uses a Queue for level-order traversal, optimal for shortest unweighted paths. DFS uses a Stack/recursion, optimal for topological sort, cycle detection, and maze backtracking.',
    formula_hint: 'BFS: Queue (FIFO); DFS: Stack (LIFO)',
    default_marks: 3.0,
    section: 'Section B: Conceptual Analysis',
  },
];
