/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { CurriculumQuestion } from './types.js';

export const GENERAL_APTITUDE_QUESTIONS: CurriculumQuestion[] = [
  // ============================================================================
  // 1. Percentages (8 Questions)
  // ============================================================================
  {
    subject: 'General Aptitude',
    topic: 'Percentages',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'If the price of a commodity increases by 25%, by what percentage must consumption be reduced so that the expenditure remains unchanged?',
    options: [
      { id: 'a', text: '20%' },
      { id: 'b', text: '25%' },
      { id: 'c', text: '16.67%' },
      { id: 'd', text: '15%' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Reduction % = [r / (100 + r)] × 100 = [25 / 125] × 100 = (1/5) × 100 = 20%.',
    formula_hint: 'Reduction % = [r / (100 + r)] × 100',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Percentages',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'In an election between two candidates, the winner received 56% of total valid votes and won by a majority of 1,440 votes. What was the total number of valid votes polled?',
    options: [
      { id: 'a', text: '12,000' },
      { id: 'b', text: '10,000' },
      { id: 'c', text: '14,400' },
      { id: 'd', text: '8,000' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Winner received 56%, so loser received 100 - 56 = 44%. Difference = 56% - 44% = 12%. Total votes × 12% = 1440 => Total = 1440 / 0.12 = 12,000 votes.',
    formula_hint: 'Majority = (% Winner - % Loser) × Total',
    default_marks: 1.5,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Percentages',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'A candidate who gets 20% marks in an examination fails by 30 marks, but another candidate who gets 32% gets 42 marks more than the pass mark. What is the passing percentage?',
    options: [
      { id: 'a', text: '25%' },
      { id: 'b', text: '33%' },
      { id: 'c', text: '28%' },
      { id: 'd', text: '30%' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Difference in percentage = 32% - 20% = 12%. Difference in marks = 42 - (-30) = 72 marks. Maximum marks = 72 / 0.12 = 600. Passing marks = 20% of 600 + 30 = 120 + 30 = 150 marks. Passing % = (150 / 600) × 100 = 25%.',
    formula_hint: 'Max Marks = (Score Diff) / (% Diff)',
    default_marks: 2.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Percentages',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'If a number N is successively increased by 20% and then decreased by 20%, which of the following statements are mathematically true?',
    options: [
      { id: 'a', text: 'The net change is an overall decrease of 4%' },
      { id: 'b', text: 'The final value is 0.96 N' },
      { id: 'c', text: 'The final value equals the original value N' },
      { id: 'd', text: 'The order of applying the increase and decrease does not alter the final result' },
    ],
    correct_option_ids: ['a', 'b', 'd'],
    explanation: 'Net change = a + b + (ab/100) = +20 - 20 - (400/100) = -4%. Final value = N × 1.20 × 0.80 = 0.96 N. Multiplication is commutative, so order does not matter.',
    formula_hint: 'Net % = a + b + (ab / 100)',
    default_marks: 2.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Percentages',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'x% of y is mathematically equal to y% of x for all real numbers x and y.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. (x / 100) × y = (x · y) / 100 = (y / 100) × x due to commutativity of multiplication.',
    formula_hint: 'x% of y = y% of x = (xy) / 100',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Percentages',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'A town’s population increases by 10% per year. If the present population is 50,000, what will it be after 2 years?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '60500',
    explanation: 'P_2 = 50,000 × (1 + 0.10)² = 50,000 × 1.21 = 60,500.',
    formula_hint: 'P_n = P_0 (1 + r/100)ⁿ',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Percentages',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What single percentage discount is equivalent to two successive discounts of 20% and 10%?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '28%',
    explanation: 'Equivalent discount = d₁ + d₂ - (d₁·d₂ / 100) = 20 + 10 - (200 / 100) = 30 - 2 = 28%.',
    formula_hint: 'Net discount = d₁ + d₂ - (d₁ d₂ / 100)',
    default_marks: 1.5,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Percentages',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain why successive percentage changes cannot be calculated by simple linear addition and show the formula for two successive changes.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Successive percentage changes cannot be linearly summed because each subsequent percentage is applied to an updated intermediate base value rather than the original base. For instance, a +10% increase followed by a -10% decrease does not return to 0% because the 10% decrease is calculated on 110% of the original value, resulting in 99% (a net 1% loss). The general formula for two successive percentage changes a% and b% is: Net % Change = a + b + (a × b / 100)%.',
    explanation: 'Compounding shifts the reference denominator for each successive multiplier.',
    formula_hint: 'Net = a + b + (ab / 100)',
    default_marks: 2.5,
    section: 'Section A: Quantitative Arithmetic',
  },

  // ============================================================================
  // 2. Ratios (8 Questions)
  // ============================================================================
  {
    subject: 'General Aptitude',
    topic: 'Ratios',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'If A : B = 2 : 3 and B : C = 4 : 5, what is the combined ratio A : B : C?',
    options: [
      { id: 'a', text: '8 : 12 : 15' },
      { id: 'b', text: '2 : 4 : 5' },
      { id: 'c', text: '6 : 9 : 15' },
      { id: 'd', text: '8 : 10 : 15' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Multiply A : B by 4 => 8 : 12. Multiply B : C by 3 => 12 : 15. Merged ratio A : B : C = 8 : 12 : 15.',
    formula_hint: 'Equalize common term B: LCM(3, 4) = 12',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Ratios',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'A mixture contains milk and water in the ratio 5 : 2. When 14 liters of water are added to the mixture, the ratio of milk to water becomes 5 : 4. What was the initial quantity of milk?',
    options: [
      { id: 'a', text: '35 liters' },
      { id: 'b', text: '28 liters' },
      { id: 'c', text: '42 liters' },
      { id: 'd', text: '25 liters' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Let milk = 5x, water = 2x. Adding 14 L water: 5x / (2x + 14) = 5 / 4 => 4(5x) = 5(2x + 14) => 20x = 10x + 70 => 10x = 70 => x = 7. Quantity of milk = 5 × 7 = 35 liters.',
    formula_hint: 'Milk remains constant; solve for scaling factor x',
    default_marks: 1.5,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Ratios',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'A, B, and C enter into a partnership. A invests $4,000 for 12 months, B invests $6,000 for 8 months, and C invests $8,000 for 6 months. How should a total annual profit of $4,500 be divided among them?',
    options: [
      { id: 'a', text: '$1,500, $1,500, $1,500' },
      { id: 'b', text: '$1,200, $1,500, $1,800' },
      { id: 'c', text: '$1,000, $1,500, $2,000' },
      { id: 'd', text: '$1,800, $1,500, $1,200' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Profit ratio = (Capital × Time): A = 4000 × 12 = 48,000; B = 6000 × 8 = 48,000; C = 8000 × 6 = 48,000. Ratio = 1 : 1 : 1. Each partner receives $4,500 / 3 = $1,500.',
    formula_hint: 'Profit ratio = C₁ T₁ : C₂ T₂ : C₃ T₃',
    default_marks: 2.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Ratios',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'For four numbers a, b, c, d in continued proportion (a/b = c/d), which of the following algebraic relations are mathematically true?',
    options: [
      { id: 'a', text: 'a · d = b · c (Product of extremes equals product of means)' },
      { id: 'b', text: '(a + b) / (a - b) = (c + d) / (c - d) (Componendo and Dividendo)' },
      { id: 'c', text: 'a / c = b / d (Alternendo)' },
      { id: 'd', text: 'a + d = b + c' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Cross-multiplication yields ad = bc (a); componendo and dividendo yields (a+b)/(a-b) = (c+d)/(c-d) (b); alternendo yields a/c = b/d (c). The sum of extremes does not equal the sum of means (d is false).',
    formula_hint: 'a/b = c/d => ad = bc; (a+b)/(a-b) = (c+d)/(c-d)',
    default_marks: 2.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Ratios',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'The duplicate ratio of a : b is given by a² : b².',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. By standard definition, the duplicate ratio of a : b is a² : b², triplicate is a³ : b³, and sub-duplicate is √a : √b.',
    formula_hint: 'Duplicate ratio = a² : b²',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Ratios',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Find the third proportional to 4 and 12.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '36',
    explanation: 'If c is third proportional to a and b, then a/b = b/c => c = b² / a. Here c = 12² / 4 = 144 / 4 = 36.',
    formula_hint: 'Third proportional c = b² / a',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Ratios',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What is the mean proportional between 9 and 16?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '12',
    explanation: 'Mean proportional x = √(a · b) = √(9 × 16) = √144 = 12.',
    formula_hint: 'Mean proportional = √(ab)',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Ratios',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the Rule of Alligation used to find the ratio in which two ingredients of differing costs must be mixed to produce a mixture of desired mean cost.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'The Rule of Alligation is a simplified method for solving weighted average problems. If ingredient C has a cheaper unit price and ingredient D has a dearer unit price, and they are mixed to produce a blend with mean unit price M (where C < M < D), the ratio of the quantity of cheaper ingredient (q_c) to dearer ingredient (q_d) is inversely proportional to their cost deviations from the mean:\n(Quantity of Cheaper) / (Quantity of Dearer) = (Price of Dearer - Mean Price) / (Mean Price - Price of Cheaper) = (D - M) / (M - C).',
    explanation: 'Weighted average cross-difference method for mixture problems.',
    formula_hint: 'q_c / q_d = (D - M) / (M - C)',
    default_marks: 2.5,
    section: 'Section A: Quantitative Arithmetic',
  },

  // ============================================================================
  // 3. Averages (8 Questions)
  // ============================================================================
  {
    subject: 'General Aptitude',
    topic: 'Averages',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'The average of 5 consecutive odd numbers is 27. What is the smallest of these numbers?',
    options: [
      { id: 'a', text: '23' },
      { id: 'b', text: '25' },
      { id: 'c', text: '21' },
      { id: 'd', text: '27' },
    ],
    correct_option_ids: ['a'],
    explanation: 'In any symmetric arithmetic sequence with an odd count of terms, the average equals the middle term. Middle term = 27. The 5 numbers are 23, 25, 27, 29, 31. Smallest = 23.',
    formula_hint: 'Middle term of consecutive odd sequence = Average',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Averages',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'The average weight of 24 students in a class is 40 kg. If the teacher’s weight is included, the average weight increases by 1 kg. What is the teacher’s weight?',
    options: [
      { id: 'a', text: '65 kg' },
      { id: 'b', text: '64 kg' },
      { id: 'c', text: '60 kg' },
      { id: 'd', text: '62 kg' },
    ],
    correct_option_ids: ['a'],
    explanation: 'New total weight = 25 × 41 = 1025 kg. Previous total weight = 24 × 40 = 960 kg. Teacher weight = 1025 - 960 = 65 kg. (Shortcut: 40 + 25 × 1 = 65 kg).',
    formula_hint: 'Teacher weight = Old Average + (New Count × Increase)',
    default_marks: 1.5,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Averages',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'A batsman has a certain average of runs for 11 innings. In the 12th innings, he scores 90 runs and thereby increases his average by 5 runs. What is his new batting average after the 12th innings?',
    options: [
      { id: 'a', text: '35' },
      { id: 'b', text: '40' },
      { id: 'c', text: '30' },
      { id: 'd', text: '45' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Let old average = A. Total runs after 12 innings: 11A + 90 = 12(A + 5) => 11A + 90 = 12A + 60 => A = 30. New average = A + 5 = 30 + 5 = 35.',
    formula_hint: 'New Total = Old Total + New Score = n × New Average',
    default_marks: 2.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Averages',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following operations on all values in a dataset will alter the arithmetic mean by the same amount or scale?',
    options: [
      { id: 'a', text: 'Adding a constant k to every observation increases the mean by k' },
      { id: 'b', text: 'Multiplying every observation by a constant k multiplies the mean by k' },
      { id: 'c', text: 'Subtracting a constant k decreases the mean by k' },
      { id: 'd', text: 'Squaring every observation squares the mean' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'The arithmetic mean is a linear operator: E[aX + b] = a E[X] + b. However, E[X²] ≠ (E[X])² because Var(X) = E[X²] - (E[X])² ≥ 0, so squaring observations does not square the mean.',
    formula_hint: 'Linearity of expectation: E[aX + b] = a E[X] + b',
    default_marks: 2.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Averages',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'If a person travels a distance d at speed v₁ and returns the same distance d at speed v₂, the average speed for the round trip is given by the arithmetic mean (v₁ + v₂) / 2.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['false'],
    explanation: 'False. Average speed is total distance divided by total time: 2d / (d/v₁ + d/v₂) = (2 v₁ v₂) / (v₁ + v₂), which is the Harmonic Mean, not the arithmetic mean.',
    formula_hint: 'Average speed = 2 v₁ v₂ / (v₁ + v₂)',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Averages',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'The average of 8 numbers is 14. If one number is excluded, the average becomes 12. Find the excluded number.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '28',
    explanation: 'Sum of 8 numbers = 8 × 14 = 112. Sum of remaining 7 numbers = 7 × 12 = 84. Excluded number = 112 - 84 = 28.',
    formula_hint: 'Excluded value = Original Sum - New Sum',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Averages',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What is the average of the first 50 positive integers (1 to 50)?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '25.5',
    explanation: 'Average = (n + 1) / 2 = (50 + 1) / 2 = 51 / 2 = 25.5.',
    formula_hint: 'Average of first n integers = (n + 1) / 2',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Averages',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Differentiate between Arithmetic Mean and Weighted Mean, stating the formula for weighted average.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'The Simple Arithmetic Mean assigns equal weight (1/n) to every data observation: x̄ = (∑ x_i) / n. The Weighted Mean assigns varying degrees of importance or frequency weights w_i to different observations, ensuring that values with greater prominence contribute proportionally more to the final statistic: Weighted Mean x̄_w = (∑ w_i · x_i) / (∑ w_i). It is essential in calculating course GPA, portfolio investment returns, and index fund pricing.',
    explanation: 'Weighted average accounts for relative importance or sample sizes of sub-groups.',
    formula_hint: 'x̄_w = ∑(w_i x_i) / ∑ w_i',
    default_marks: 2.5,
    section: 'Section A: Quantitative Arithmetic',
  },

  // ============================================================================
  // 4. Profit & Loss (8 Questions)
  // ============================================================================
  {
    subject: 'General Aptitude',
    topic: 'Profit & Loss',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'An article purchased for $400 is sold for $500. What is the profit percentage?',
    options: [
      { id: 'a', text: '25%' },
      { id: 'b', text: '20%' },
      { id: 'c', text: '30%' },
      { id: 'd', text: '15%' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Profit = SP - CP = 500 - 400 = $100. Profit % = (Profit / CP) × 100 = (100 / 400) × 100 = 25%.',
    formula_hint: 'Profit % = (SP - CP) / CP × 100',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Profit & Loss',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'By selling an article for $720, a shopkeeper incurs a loss of 10%. At what selling price should he sell it to gain a profit of 15%?',
    options: [
      { id: 'a', text: '$920' },
      { id: 'b', text: '$900' },
      { id: 'c', text: '$880' },
      { id: 'd', text: '$960' },
    ],
    correct_option_ids: ['a'],
    explanation: 'CP = SP / (1 - Loss%) = 720 / 0.90 = $800. Desired SP = CP × (1 + Gain%) = 800 × 1.15 = $920.',
    formula_hint: 'SP₂ = [SP₁ / (100 - L)] × (100 + G)',
    default_marks: 1.5,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Profit & Loss',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'A dishonest dealer professes to sell his goods at cost price, but uses a false weight of 900 grams for a 1-kilogram measure. What is his real gain percentage?',
    options: [
      { id: 'a', text: '11.11% (11 1/9 %)' },
      { id: 'b', text: '10%' },
      { id: 'c', text: '12.5%' },
      { id: 'd', text: '9.09%' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Gain % = [Error / (True Value - Error)] × 100 = [100 / 900] × 100 = (1/9) × 100 = 11.11%.',
    formula_hint: 'Gain % = [Error / False Weight] × 100',
    default_marks: 2.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Profit & Loss',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'A merchant sells two items at $990 each. On one he makes a 10% profit and on the other he loses 10%. Which of the following statements are correct?',
    options: [
      { id: 'a', text: 'The merchant suffers an overall loss on the combined transaction' },
      { id: 'b', text: 'The overall percentage loss is 1%' },
      { id: 'c', text: 'The net dollar loss is $20' },
      { id: 'd', text: 'The merchant breaks even with 0% net profit/loss' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'When two items have identical SP and equal gain/loss x%, there is always an overall loss of (x/10)² % = (10/10)² = 1%. Total SP = 2 × 990 = $1980. Total CP = (990/1.1) + (990/0.9) = 900 + 1100 = $2000. Dollar loss = 2000 - 1980 = $20.',
    formula_hint: 'Loss % = (x / 10)² %',
    default_marks: 2.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Profit & Loss',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Discount is always calculated on the Cost Price (CP) rather than the Marked Price (MP).',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['false'],
    explanation: 'False. Discount is strictly calculated on the Marked/List Price (MP): SP = MP - Discount. Profit or loss is calculated on Cost Price (CP).',
    formula_hint: 'Discount = MP - SP; Discount % = (Discount / MP) × 100',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Profit & Loss',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'If the Cost Price of 15 articles is equal to the Selling Price of 12 articles, calculate the profit percentage.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '25%',
    explanation: '15 CP = 12 SP => SP / CP = 15 / 12 = 5 / 4. Profit % = [(5 - 4) / 4] × 100 = (1/4) × 100 = 25%.',
    formula_hint: 'SP/CP = m / n => Profit % = (m - n)/n × 100',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Profit & Loss',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'A trader marks his goods 40% above cost price and allows a 20% discount. What is his net profit percentage?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '12%',
    explanation: 'Let CP = 100. MP = 140. SP = 140 × (1 - 0.20) = 140 × 0.80 = 112. Profit = 112 - 100 = 12%.',
    formula_hint: 'Net % = Markup - Discount - (Markup × Discount / 100)',
    default_marks: 1.5,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Profit & Loss',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the relationship between Cost Price (CP), Marked Price (MP), Selling Price (SP), Markup Percentage, and Discount Percentage.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Cost Price (CP) is the procurement cost. Marked Price (MP) is set by applying a markup percentage: MP = CP × (1 + Markup/100). The retailer offers a discount percentage on the Marked Price to arrive at Selling Price: SP = MP × (1 - Discount/100). Net profit or loss is determined by comparing SP against original CP: Profit % = [(SP - CP) / CP] × 100. Combining these gives the direct identity: CP × (100 + Profit%) = MP × (100 - Discount%).',
    explanation: 'Integration of markup on CP with discount on MP determines net transaction profit.',
    formula_hint: 'CP(100 + P%) = MP(100 - D%)',
    default_marks: 2.5,
    section: 'Section A: Quantitative Arithmetic',
  },

  // ============================================================================
  // 5. Time & Work (8 Questions)
  // ============================================================================
  {
    subject: 'General Aptitude',
    topic: 'Time & Work',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'A can complete a piece of work in 10 days and B can complete it in 15 days. How many days will they take working together?',
    options: [
      { id: 'a', text: '6 days' },
      { id: 'b', text: '8 days' },
      { id: 'c', text: '7.5 days' },
      { id: 'd', text: '5 days' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Work done per day = 1/10 + 1/15 = (3 + 2) / 30 = 5/30 = 1/6 of total work. Total days required = 6 days. (Shortcut: (A × B) / (A + B) = (10 × 15) / 25 = 150 / 25 = 6).',
    formula_hint: 'Time = (A × B) / (A + B)',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Time & Work',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Pipe A can fill a tank in 8 hours, and Pipe B can empty the full tank in 12 hours. If both pipes are opened simultaneously, in how many hours will the empty tank be filled?',
    options: [
      { id: 'a', text: '24 hours' },
      { id: 'b', text: '20 hours' },
      { id: 'c', text: '16 hours' },
      { id: 'd', text: '18 hours' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Net rate = 1/8 - 1/12 = (3 - 2) / 24 = 1/24 tank per hour. Total time to fill = 24 hours.',
    formula_hint: 'Net Rate = Inlet Rate - Outlet Rate',
    default_marks: 1.5,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Time & Work',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'A is thrice as efficient as B and is therefore able to finish a job in 60 days less than B. How many days will they take working together?',
    options: [
      { id: 'a', text: '22.5 days' },
      { id: 'b', text: '20 days' },
      { id: 'c', text: '25 days' },
      { id: 'd', text: '18 days' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Efficiency ratio A : B = 3 : 1. Time ratio A : B = 1 : 3. Difference in time = 3x - x = 2x = 60 days => x = 30 days. So A takes 30 days and B takes 90 days. Together time = (30 × 90) / (30 + 90) = 2700 / 120 = 22.5 days.',
    formula_hint: 'Efficiency ∝ 1 / Time',
    default_marks: 2.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Time & Work',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'According to the generalized Work Equivalence Rule (Chain Rule), which of the following variables are directly proportional to Total Work W?',
    options: [
      { id: 'a', text: 'Number of workers (M)' },
      { id: 'b', text: 'Number of working days (D)' },
      { id: 'c', text: 'Working hours per day (H)' },
      { id: 'd', text: 'Individual efficiency of workers (E)' },
    ],
    correct_option_ids: ['a', 'b', 'c', 'd'],
    explanation: 'Total Work W is jointly proportional to all four factors: W = M · D · H · E. Hence (M₁ · D₁ · H₁ · E₁) / W₁ = (M₂ · D₂ · H₂ · E₂) / W₂.',
    formula_hint: '(M₁ D₁ H₁) / W₁ = (M₂ D₂ H₂) / W₂',
    default_marks: 2.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Time & Work',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'If person A is twice as efficient as person B, then person A will take half the time of person B to complete the identical task.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Work efficiency is inversely proportional to time taken: E_A / E_B = T_B / T_A = 2 / 1 => T_A = T_B / 2.',
    formula_hint: 'Time taken is inversely proportional to efficiency',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Time & Work',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'If 12 men can build a wall in 20 days, how many men are required to build the same wall in 15 days?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '16',
    explanation: 'M₁ D₁ = M₂ D₂ => 12 × 20 = M₂ × 15 => 240 = 15 M₂ => M₂ = 240 / 15 = 16 men.',
    formula_hint: 'M₁ D₁ = M₂ D₂',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Time & Work',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'A and B can do a piece of work in 12 days, B and C in 15 days, and C and A in 20 days. How many days will A, B, and C take working together?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '10 days',
    explanation: '2(A + B + C)’s 1-day work = 1/12 + 1/15 + 1/20 = (5 + 4 + 3) / 60 = 12/60 = 1/5. (A + B + C)’s 1-day work = (1/5) / 2 = 1/10. Days = 10 days.',
    formula_hint: '2(A + B + C) rate = Rate(A+B) + Rate(B+C) + Rate(C+A)',
    default_marks: 1.5,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Time & Work',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the LCM Unit Work method for solving complex time and work problems with an example.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'The LCM method replaces fractions with integer work units by setting Total Work equal to the LCM of individual completion days. For example, if A finishes in 12 days and B in 15 days: LCM(12, 15) = 60 units of total work. A’s daily rate = 60 / 12 = 5 units/day; B’s daily rate = 60 / 15 = 4 units/day. Working together, their combined daily rate is 5 + 4 = 9 units/day. Total time required = 60 / 9 = 20/3 = 6.67 days. This avoids cumbersome fractional additions.',
    explanation: 'LCM method converts work rates into whole integer units per unit time.',
    formula_hint: 'Total Units = LCM(days); Daily rate = Total Units / individual days',
    default_marks: 2.5,
    section: 'Section A: Quantitative Arithmetic',
  },

  // ============================================================================
  // 6. Time, Speed & Distance (8 Questions)
  // ============================================================================
  {
    subject: 'General Aptitude',
    topic: 'Time, Speed & Distance',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Convert a speed of 72 km/h into meters per second (m/s).',
    options: [
      { id: 'a', text: '20 m/s' },
      { id: 'b', text: '25 m/s' },
      { id: 'c', text: '18 m/s' },
      { id: 'd', text: '15 m/s' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Multiply km/h by 5/18: 72 × (5/18) = 4 × 5 = 20 m/s.',
    formula_hint: '1 km/h = 5/18 m/s',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Time, Speed & Distance',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'A train 180 meters long is traveling at a speed of 54 km/h. How many seconds will it take to completely cross an electric pole?',
    options: [
      { id: 'a', text: '12 seconds' },
      { id: 'b', text: '10 seconds' },
      { id: 'c', text: '15 seconds' },
      { id: 'd', text: '8 seconds' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Speed = 54 × (5/18) = 15 m/s. Crossing a pole requires covering the train’s own length: Time = Distance / Speed = 180 / 15 = 12 seconds.',
    formula_hint: 'Time = Train Length / Speed',
    default_marks: 1.5,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Time, Speed & Distance',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'A boat travels 24 km downstream in 2 hours and travels the same distance upstream in 4 hours. What are the speed of the boat in still water and the speed of the water current?',
    options: [
      { id: 'a', text: 'Boat = 9 km/h, Stream = 3 km/h' },
      { id: 'b', text: 'Boat = 8 km/h, Stream = 4 km/h' },
      { id: 'c', text: 'Boat = 10 km/h, Stream = 2 km/h' },
      { id: 'd', text: 'Boat = 7 km/h, Stream = 5 km/h' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Downstream speed d = 24 / 2 = 12 km/h. Upstream speed u = 24 / 4 = 6 km/h. Boat in still water = (d + u) / 2 = (12 + 6) / 2 = 9 km/h. Stream speed = (d - u) / 2 = (12 - 6) / 2 = 3 km/h.',
    formula_hint: 'Boat speed = (Downstream + Upstream) / 2',
    default_marks: 2.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Time, Speed & Distance',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Two trains of lengths L₁ and L₂ move in opposite directions at speeds S₁ and S₂. Which of the following expressions correctly describe their relative crossing behavior?',
    options: [
      { id: 'a', text: 'Relative speed of approach = S₁ + S₂' },
      { id: 'b', text: 'Total distance to cross each other completely = L₁ + L₂' },
      { id: 'c', text: 'Crossing time = (L₁ + L₂) / (S₁ + S₂)' },
      { id: 'd', text: 'Relative speed = S₁ - S₂' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Moving in opposite directions, relative speed is the sum S₁ + S₂ (a). Complete crossing requires clearing both train lengths L₁ + L₂ (b), giving Time = (L₁ + L₂) / (S₁ + S₂) (c). (d is for same-direction motion).',
    formula_hint: 'Opposite directions: Relative Speed = S₁ + S₂',
    default_marks: 2.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Time, Speed & Distance',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'For a fixed distance D, the time taken to travel is directly proportional to speed.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['false'],
    explanation: 'False. For a constant distance D, Time = D / Speed, which means time is inversely proportional to speed (higher speed results in less time).',
    formula_hint: 'Time ∝ 1 / Speed (for constant distance)',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Time, Speed & Distance',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Walking at 3/4 of his usual speed, a man reaches his office 20 minutes late. What is his usual travel time in minutes?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '60',
    explanation: 'Speed ratio = 3/4 => Time ratio = 4/3 of usual time T. Extra time = (4/3)T - T = T/3 = 20 minutes => T = 20 × 3 = 60 minutes.',
    formula_hint: 'Time ratio = inverse of speed ratio',
    default_marks: 1.5,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Time, Speed & Distance',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What is the angle between the hour hand and minute hand of a clock at 3:30?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '75°',
    explanation: 'Angle = |30H - 5.5M| = |30(3) - 5.5(30)| = |90 - 165| = 75°.',
    formula_hint: 'Angle = |30 H - (11/2) M|',
    default_marks: 1.0,
    section: 'Section B: Logical & Analytical Reasoning',
  },
  {
    subject: 'General Aptitude',
    topic: 'Time, Speed & Distance',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain why two trains traveling in the same direction take much longer to cross each other than when traveling in opposite directions.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'In both cases, the total distance required for complete clearance is the sum of both train lengths: Distance = L₁ + L₂. However, when moving in opposite directions, their velocities add together to form a high relative speed of approach: S_rel = S₁ + S₂. When moving in the same direction, the faster train must overtake the slower train, so their velocities subtract: S_rel = |S₁ - S₂|. Because |S₁ - S₂| is vastly smaller than (S₁ + S₂), the crossing time T = (L₁ + L₂) / S_rel is significantly larger when moving in the same direction.',
    explanation: 'Relative velocity in same direction is the difference of speeds; in opposite directions it is the sum.',
    formula_hint: 'Same direction: S_rel = |S₁ - S₂|; Opposite direction: S_rel = S₁ + S₂',
    default_marks: 2.5,
    section: 'Section A: Quantitative Arithmetic',
  },

  // ============================================================================
  // 7. Logical Reasoning (8 Questions)
  // ============================================================================
  {
    subject: 'General Aptitude',
    topic: 'Logical Reasoning',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Find the next term in the alphanumeric series: A2C, B4E, C8G, D16I, _____?',
    options: [
      { id: 'a', text: 'E32K' },
      { id: 'b', text: 'E32J' },
      { id: 'c', text: 'F32K' },
      { id: 'd', text: 'E64K' },
    ],
    correct_option_ids: ['a'],
    explanation: 'First letter advances by +1: A, B, C, D, E. Numbers double: 2, 4, 8, 16, 32. Third letter advances by +2: C(3), E(5), G(7), I(9), K(11). Next term is E32K.',
    formula_hint: 'Letter 1: +1; Number: ×2; Letter 2: +2',
    default_marks: 1.0,
    section: 'Section B: Logical & Analytical Reasoning',
  },
  {
    subject: 'General Aptitude',
    topic: 'Logical Reasoning',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Pointing to a photograph of a boy, Suresh said, "He is the only son of my mother." How is Suresh related to that boy?',
    options: [
      { id: 'a', text: 'Father' },
      { id: 'b', text: 'Brother' },
      { id: 'c', text: 'Uncle' },
      { id: 'd', text: 'Cousin' },
    ],
    correct_option_ids: ['a'],
    explanation: '"The only son of my mother" refers to Suresh himself (assuming Suresh is a male speaker). Since the boy in the photo is his son, Suresh is the boy’s father.',
    formula_hint: 'Only son of my mother = Myself',
    default_marks: 1.5,
    section: 'Section B: Logical & Analytical Reasoning',
  },
  {
    subject: 'General Aptitude',
    topic: 'Logical Reasoning',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'Statements: 1. All roses are flowers. 2. Some flowers are red. Conclusions: I. Some roses are red. II. Some flowers are roses. Which conclusions logically follow?',
    options: [
      { id: 'a', text: 'Only conclusion II follows' },
      { id: 'b', text: 'Only conclusion I follows' },
      { id: 'c', text: 'Both I and II follow' },
      { id: 'd', text: 'Neither I nor II follows' },
    ],
    correct_option_ids: ['a'],
    explanation: 'From "All roses are flowers", conversion yields "Some flowers are roses" (Conclusion II is unconditionally valid). However, the red flowers might not intersect with roses, so Conclusion I does not necessarily follow.',
    formula_hint: 'All A are B => Some B are A (valid subalternation)',
    default_marks: 2.0,
    section: 'Section B: Logical & Analytical Reasoning',
  },
  {
    subject: 'General Aptitude',
    topic: 'Logical Reasoning',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Five persons P, Q, R, S, T sit in a row facing North. S is between T and Q. Q is to the immediate left of R. P is to the immediate left of T. Which of the following statements are correct?',
    options: [
      { id: 'a', text: 'P is at the extreme left end' },
      { id: 'b', text: 'R is at the extreme right end' },
      { id: 'c', text: 'S sits in the exact middle' },
      { id: 'd', text: 'Q sits in the exact middle' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'P is left of T => P, T. S is between T and Q => P, T, S, Q. Q is left of R => P, T, S, Q, R. Extreme left = P (a); Extreme right = R (b); Middle = S (c).',
    formula_hint: 'Order: P - T - S - Q - R',
    default_marks: 2.0,
    section: 'Section B: Logical & Analytical Reasoning',
  },
  {
    subject: 'General Aptitude',
    topic: 'Logical Reasoning',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'In a standard clock, the minute hand gains 55 minutes spaces over the hour hand in 60 minutes.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. In 60 minutes, the minute hand travels 60 minute spaces while the hour hand moves 5 minute spaces: Net gain = 60 - 5 = 55 minute spaces.',
    formula_hint: 'Minute hand gains 55 min spaces per 60 minutes',
    default_marks: 1.0,
    section: 'Section B: Logical & Analytical Reasoning',
  },
  {
    subject: 'General Aptitude',
    topic: 'Logical Reasoning',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'If in a certain code language, ROAD is written as URDG, how is SWAN written in that same code?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'VZDQ',
    explanation: 'Each letter is shifted forward by +3 positions: R(+3) = U, O(+3) = R, A(+3) = D, D(+3) = G. For SWAN: S(+3) = V, W(+3) = Z, A(+3) = D, N(+3) = Q => VZDQ.',
    formula_hint: 'Letter shift: +3 positions',
    default_marks: 1.5,
    section: 'Section B: Logical & Analytical Reasoning',
  },
  {
    subject: 'General Aptitude',
    topic: 'Logical Reasoning',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'A man walks 3 km North, turns right and walks 4 km. How far is he from his starting point?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '5 km',
    explanation: 'Using the Pythagorean theorem: Distance = √(3² + 4²) = √(9 + 16) = √25 = 5 km in the North-East direction.',
    formula_hint: 'd = √(x² + y²)',
    default_marks: 1.0,
    section: 'Section B: Logical & Analytical Reasoning',
  },
  {
    subject: 'General Aptitude',
    topic: 'Logical Reasoning',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the difference between Inductive Reasoning and Deductive Reasoning, providing an example of each.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Deductive reasoning moves from general, universally accepted premises to a logically certain specific conclusion (top-down logic): if premises are true, the conclusion MUST be true. Example: "All humans are mortal (premise 1). Socrates is human (premise 2). Therefore, Socrates is mortal (certain conclusion)." Inductive reasoning moves from specific observed instances to formulate a broad probabilistic generalization (bottom-up logic): conclusions are probable but not guaranteed. Example: "Every swan observed so far is white; therefore, all swans are probably white." (Falsified by the discovery of black swans).',
    explanation: 'Deductive guarantees truth from valid premises; inductive establishes probabilistic general trends from observations.',
    formula_hint: 'Deductive = General to Specific (Certain); Inductive = Specific to General (Probable)',
    default_marks: 2.5,
    section: 'Section B: Logical & Analytical Reasoning',
  },

  // ============================================================================
  // 8. Number Systems (8 Questions)
  // ============================================================================
  {
    subject: 'General Aptitude',
    topic: 'Number Systems',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the unit digit of the exponential expression (7)⁹⁵?',
    options: [
      { id: 'a', text: '3' },
      { id: 'b', text: '7' },
      { id: 'c', text: '9' },
      { id: 'd', text: '1' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Powers of 7 follow a cycle of 4 for unit digits: 7¹=7, 7²=9, 7³=3, 7⁴=1. 95 mod 4 = 3 (95 = 4 × 23 + 3). The 3rd value in the cycle is 3.',
    formula_hint: 'Cyclicity of 7 is 4: [7, 9, 3, 1]',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Number Systems',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the remainder when (2³¹ - 1) is divided by 7?',
    options: [
      { id: 'a', text: '1' },
      { id: 'b', text: '3' },
      { id: 'c', text: '0' },
      { id: 'd', text: '5' },
    ],
    correct_option_ids: ['a'],
    explanation: '2³ = 8 ≡ 1 (mod 7). 2³¹ = (2³)¹⁰ × 2¹ = (1)¹⁰ × 2 = 2 (mod 7). Therefore, (2³¹ - 1) ≡ 2 - 1 = 1 (mod 7). The remainder is 1.',
    formula_hint: '2³ ≡ 1 (mod 7)',
    default_marks: 1.5,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Number Systems',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'How many trailing zeros are there at the end of the number 100! (100 factorial)?',
    options: [
      { id: 'a', text: '24' },
      { id: 'b', text: '20' },
      { id: 'c', text: '25' },
      { id: 'd', text: '21' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Trailing zeros are determined by prime factors of 5 in n! using Legendre’s formula: ⌊100/5⌋ + ⌊100/25⌋ + ⌊100/125⌋ = 20 + 4 + 0 = 24 trailing zeros.',
    formula_hint: 'Zeros in n! = ∑ ⌊n / 5^k⌋',
    default_marks: 2.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Number Systems',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following numbers are prime numbers?',
    options: [
      { id: 'a', text: '97' },
      { id: 'b', text: '91' },
      { id: 'c', text: '89' },
      { id: 'd', text: '87' },
    ],
    correct_option_ids: ['a', 'c'],
    explanation: '97 and 89 are prime. 91 is composite (7 × 13 = 91). 87 is composite (3 × 29 = 87).',
    formula_hint: 'Check divisibility up to √n',
    default_marks: 2.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Number Systems',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'For any two positive integers a and b, the product of their HCF (GCD) and LCM is equal to the product of the numbers: HCF(a, b) × LCM(a, b) = a × b.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. For two numbers, taking min and max exponents across prime factorizations gives min(x, y) + max(x, y) = x + y, proving HCF × LCM = a × b.',
    formula_hint: 'HCF(a, b) × LCM(a, b) = a · b',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Number Systems',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What is the Greatest Common Divisor (GCD / HCF) of 108 and 144?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '36',
    explanation: 'Prime factors: 108 = 2² × 3³; 144 = 2⁴ × 3². GCD = 2² × 3² = 4 × 9 = 36.',
    formula_hint: 'GCD = product of common prime factors with lowest exponents',
    default_marks: 1.0,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Number Systems',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'Find the smallest number which when divided by 6, 8, and 12 leaves a remainder of 2 in each case.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '26',
    explanation: 'LCM(6, 8, 12) = 24. Required number = LCM + remainder = 24 + 2 = 26.',
    formula_hint: 'N = LCM(d₁, d₂, d₃) + r',
    default_marks: 1.5,
    section: 'Section A: Quantitative Arithmetic',
  },
  {
    subject: 'General Aptitude',
    topic: 'Number Systems',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'State the Divisibility Rules for 7 and 11, giving a test example for each.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Divisibility Rule for 7: Double the last digit and subtract it from the remaining truncated number; if the result is divisible by 7 (or 0), the original number is divisible. Example for 343: 34 - (2 × 3) = 34 - 6 = 28. Since 28 is divisible by 7, 343 is divisible by 7. Divisibility Rule for 11: Calculate the difference between the sum of digits at odd places and sum of digits at even places; if the difference is 0 or a multiple of 11, the number is divisible. Example for 1,331: Sum of odd places = 1 + 3 = 4; Sum of even places = 3 + 1 = 4; Difference = 4 - 4 = 0, so 1331 is divisible by 11.',
    explanation: 'Modular arithmetic properties underpinning base-10 divisibility shortcuts.',
    formula_hint: 'Divisibility: 7: N_trunc - 2(last); 11: |Sum_odd - Sum_even| mod 11 == 0',
    default_marks: 2.5,
    section: 'Section A: Quantitative Arithmetic',
  },
];
