/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { CurriculumQuestion } from './types.js';

export const BIOLOGY_QUESTIONS: CurriculumQuestion[] = [
  // ============================================================================
  // 1. Cell Biology (8 Questions)
  // ============================================================================
  {
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which organelle is universally referred to as the powerhouse of eukaryotic cells due to its role in oxidative phosphorylation?',
    options: [
      { id: 'a', text: 'Mitochondrion' },
      { id: 'b', text: 'Endoplasmic reticulum' },
      { id: 'c', text: 'Golgi apparatus' },
      { id: 'd', text: 'Lysosome' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Mitochondria generate the vast majority of cellular ATP via the citric acid cycle and the electron transport chain located along their inner mitochondrial membrane (cristae).',
    formula_hint: 'Site of ATP synthase and chemiosmosis',
    default_marks: 1.0,
    section: 'Section A: Cellular Organelles',
  },
  {
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'During which phase of mitosis do sister chromatids disjoin and migrate toward opposite poles of the mitotic spindle?',
    options: [
      { id: 'a', text: 'Prophase' },
      { id: 'b', text: 'Metaphase' },
      { id: 'c', text: 'Anaphase' },
      { id: 'd', text: 'Telophase' },
    ],
    correct_option_ids: ['c'],
    explanation: 'In anaphase, the enzyme separase cleaves cohesin protein complexes holding sister chromatids together at the centromere, allowing kinetochore microtubules to pull them toward opposite poles.',
    formula_hint: 'Mitotic sequence: Prophase -> Metaphase -> Anaphase -> Telophase',
    default_marks: 1.5,
    section: 'Section B: Cell Cycle & Division',
  },
  {
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'According to the fluid mosaic model proposed by Singer and Nicolson, the cell membrane is described as:',
    options: [
      { id: 'a', text: 'A rigid continuous layer of proteins surrounding fixed phospholipids' },
      { id: 'b', text: 'A quasi-fluid phospholipid bilayer in which integral proteins are embedded and float laterally' },
      { id: 'c', text: 'A solid carbohydrate mesh containing lipid droplets' },
      { id: 'd', text: 'A sandwich of lipid monolayers between two fixed protein sheets' },
    ],
    correct_option_ids: ['b'],
    explanation: 'The fluid mosaic model depicts membranes as a 2D liquid viscous lipid bilayer where amphipathic phospholipid molecules and integral/peripheral proteins diffuse laterally.',
    formula_hint: 'Singer-Nicolson Fluid Mosaic Model (1972)',
    default_marks: 2.0,
    section: 'Section A: Cellular Organelles',
  },
  {
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following cellular structures are bounded by a double membrane system?',
    options: [
      { id: 'a', text: 'Mitochondria' },
      { id: 'b', text: 'Chloroplasts' },
      { id: 'c', text: 'Nucleus' },
      { id: 'd', text: 'Lysosomes' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Mitochondria, chloroplasts, and the cell nucleus are surrounded by double lipid bilayer membranes (inner and outer envelopes). Lysosomes and peroxisomes are single-membrane organelles.',
    formula_hint: 'Endosymbiotic organelles + nuclear envelope have double membranes',
    default_marks: 2.0,
    section: 'Section A: Cellular Organelles',
  },
  {
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Prokaryotic cells possess membrane-bound nuclei and 80S cytoplasmic ribosomes.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['false'],
    explanation: 'False. Prokaryotes lack a membrane-enclosed nucleus (their DNA resides in an unmembrane-bound nucleoid) and possess 70S ribosomes (50S and 30S subunits), whereas eukaryotes have 80S ribosomes.',
    formula_hint: 'Prokaryote = 70S ribosomes, no nuclear envelope',
    default_marks: 1.0,
    section: 'Section A: Cellular Organelles',
  },
  {
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Name the cytoplasmic organelle rich in acid hydrolases responsible for intracellular digestion and autolysis.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Lysosome',
    explanation: 'Lysosomes maintain an acidic interior (pH ~4.5–5.0) via proton pumps to optimize degradative enzyme activity for cellular turnover and foreign phagocytosed material.',
    formula_hint: 'Suicidal bags / Acid hydrolase vesicles',
    default_marks: 1.0,
    section: 'Section A: Cellular Organelles',
  },
  {
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'In which stage of prophase I of meiosis does crossing over (genetic recombination) occur between non-sister chromatids?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Pachytene',
    explanation: 'Crossing over mediated by the enzyme recombinase takes place during the pachytene stage of meiotic prophase I, following synapsis in zygotene.',
    formula_hint: 'Prophase I stages: Leptotene, Zygotene, Pachytene, Diplotene, Diakinesis',
    default_marks: 1.5,
    section: 'Section B: Cell Cycle & Division',
  },
  {
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Describe the cell cycle checkpoints (G1/S, G2/M, and Spindle checkpoint) and their significance in preventing carcinogenesis.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'The G1/S restriction checkpoint verifies DNA integrity, growth factor signals, and cell size before committing to replication; damage triggers p53-mediated arrest. The G2/M checkpoint ensures DNA replication is completely and faithfully finished before mitosis begins. The M/spindle assembly checkpoint monitors bi-oriented kinetochore attachment of all chromosomes to prevent aneuploidy. Malfunction or bypass of these surveillance checkpoints leads to uncontrolled proliferation, chromosomal instability, and oncogenesis.',
    explanation: 'Checkpoints govern fidelity of genome duplication and cell division via cyclin-dependent kinase (CDK) complexes.',
    formula_hint: 'Cyclin-CDK regulation and p53 tumor suppression',
    default_marks: 3.0,
    section: 'Section B: Cell Cycle & Division',
  },

  // ============================================================================
  // 2. Biomolecules (8 Questions)
  // ============================================================================
  {
    subject: 'Biology',
    topic: 'Biomolecules',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What covalent bond links amino acid residues together in a primary polypeptide chain?',
    options: [
      { id: 'a', text: 'Glycosidic bond' },
      { id: 'b', text: 'Peptide bond' },
      { id: 'c', text: 'Phosphodiester bond' },
      { id: 'd', text: 'Ester bond' },
    ],
    correct_option_ids: ['b'],
    explanation: 'A peptide bond (-CO-NH-) forms via a condensation/dehydration reaction between the α-carboxyl group of one amino acid and the α-amino group of the next.',
    formula_hint: 'R₁-COOH + H₂N-R₂ → R₁-CONH-R₂ + H₂O',
    default_marks: 1.0,
    section: 'Section A: Carbohydrates & Proteins',
  },
  {
    subject: 'Biology',
    topic: 'Biomolecules',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'How do competitive enzyme inhibitors alter the Michaelis-Menten kinetic parameters K_m and V_max?',
    options: [
      { id: 'a', text: 'K_m increases, V_max remains unchanged' },
      { id: 'b', text: 'K_m decreases, V_max decreases' },
      { id: 'c', text: 'K_m remains unchanged, V_max decreases' },
      { id: 'd', text: 'Both K_m and V_max increase' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Competitive inhibitors bind reversibly to the catalytic active site. Excess substrate outcompetes the inhibitor, leaving maximal velocity V_max unchanged while apparent affinity decreases, increasing apparent K_m.',
    formula_hint: 'Competitive: K_m apparent = K_m(1 + [I]/K_i); V_max unchanged',
    default_marks: 1.5,
    section: 'Section B: Enzyme Kinetics & Catalysis',
  },
  {
    subject: 'Biology',
    topic: 'Biomolecules',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'Which level of protein architecture is stabilized primarily by hydrogen bonds between backbone amine and carbonyl groups (forming α-helices and β-pleated sheets)?',
    options: [
      { id: 'a', text: 'Primary structure' },
      { id: 'b', text: 'Secondary structure' },
      { id: 'c', text: 'Tertiary structure' },
      { id: 'd', text: 'Quaternary structure' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Secondary structure consists of regular, local spatial conformations (α-helices, β-sheets) stabilized specifically by recurring hydrogen bonds between the peptide backbone C=O and N-H groups, independent of side chains.',
    formula_hint: 'Secondary structure = localized peptide backbone H-bonding',
    default_marks: 2.0,
    section: 'Section A: Carbohydrates & Proteins',
  },
  {
    subject: 'Biology',
    topic: 'Biomolecules',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following nitrogenous bases are classified as purines?',
    options: [
      { id: 'a', text: 'Adenine' },
      { id: 'b', text: 'Guanine' },
      { id: 'c', text: 'Cytosine' },
      { id: 'd', text: 'Thymine' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'Adenine and guanine possess a double-ring heterocyclic purine core. Cytosine, thymine, and uracil are single-ring pyrimidines.',
    formula_hint: 'Purines = Adenine, Guanine (Pure As Gold)',
    default_marks: 2.0,
    section: 'Section A: Nucleic Acids & Lipids',
  },
  {
    subject: 'Biology',
    topic: 'Biomolecules',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Cellulose is an unbranched polymer of β-D-glucose linked by β-1,4-glycosidic bonds.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Linear chains of β-1,4-linked glucose units form hydrogen-bonded crystalline microfibrils providing structural rigidity to plant cell walls.',
    formula_hint: 'Cellulose = (β-1,4-glucan)ₙ',
    default_marks: 1.0,
    section: 'Section A: Carbohydrates & Proteins',
  },
  {
    subject: 'Biology',
    topic: 'Biomolecules',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What term defines the specific non-protein chemical compound or metallic ion required for an enzyme’s biological catalytic activity?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Cofactor',
    explanation: 'A cofactor (or coenzyme when organic) binds to the inactive apoenzyme to assemble the catalytically competent holoenzyme.',
    formula_hint: 'Holoenzyme = Apoenzyme + Cofactor',
    default_marks: 1.0,
    section: 'Section B: Enzyme Kinetics & Catalysis',
  },
  {
    subject: 'Biology',
    topic: 'Biomolecules',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'Which thermodynamic parameter of a chemical reaction is lowered by an enzyme to accelerate reaction velocity?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Activation energy',
    explanation: 'Enzymes stabilize the transition state, substantially lowering the activation energy barrier (ΔG‡) without shifting overall reaction free energy (ΔG).',
    formula_hint: 'Rate acceleration via reduction of ΔG‡',
    default_marks: 1.5,
    section: 'Section B: Enzyme Kinetics & Catalysis',
  },
  {
    subject: 'Biology',
    topic: 'Biomolecules',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Differentiate between the tertiary and quaternary structures of proteins, using myoglobin and hemoglobin as illustrative examples.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Tertiary structure is the complete three-dimensional folding of a single polypeptide chain, stabilized by interactions among R-groups (hydrophobic effects, ionic salt bridges, disulfide bonds, and hydrogen bonds). Myoglobin is a classic example: a monomeric single-chain protein. Quaternary structure is the spatial arrangement and non-covalent association of two or more distinct polypeptide subunits into a functional multi-subunit complex. Hemoglobin is an example: a tetramer composed of two α and two β subunits exhibiting allosteric cooperativity.',
    explanation: 'Tertiary concerns intra-chain folding of one subunit; quaternary involves inter-chain subunit assembly.',
    formula_hint: 'Myoglobin = monomer (3°); Hemoglobin = α₂β₂ tetramer (4°)',
    default_marks: 2.5,
    section: 'Section A: Carbohydrates & Proteins',
  },

  // ============================================================================
  // 3. Genetics (8 Questions)
  // ============================================================================
  {
    subject: 'Biology',
    topic: 'Genetics',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the expected phenotypic ratio in the F2 generation of a classic Mendelian monohybrid cross between two heterozygous individuals (Aa × Aa) with complete dominance?',
    options: [
      { id: 'a', text: '3:1' },
      { id: 'b', text: '1:2:1' },
      { id: 'c', text: '9:3:3:1' },
      { id: 'd', text: '1:1' },
    ],
    correct_option_ids: ['a'],
    explanation: 'The genotypic ratio is 1 AA : 2 Aa : 1 aa. Because dominant allele A masks recessive a in heterozygotes, both AA and Aa exhibit the dominant phenotype, giving 3 dominant to 1 recessive.',
    formula_hint: 'F2 Phenotypic ratio = 3 : 1',
    default_marks: 1.0,
    section: 'Section A: Mendelian Genetics',
  },
  {
    subject: 'Biology',
    topic: 'Genetics',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'A cross between a red-flowered plant and a white-flowered plant produces all pink-flowered offspring in the F1 generation. What genetic phenomenon does this illustrate?',
    options: [
      { id: 'a', text: 'Codominance' },
      { id: 'b', text: 'Incomplete dominance' },
      { id: 'c', text: 'Epistasis' },
      { id: 'd', text: 'Pleiotropy' },
    ],
    correct_option_ids: ['b'],
    explanation: 'In incomplete dominance, neither allele is completely dominant over the other, resulting in an intermediate blended phenotype in heterozygous individuals (e.g. Mirabilis jalapa, Snapdragon).',
    formula_hint: 'Genotypic = Phenotypic ratio = 1:2:1 in F2',
    default_marks: 1.5,
    section: 'Section A: Mendelian Genetics',
  },
  {
    subject: 'Biology',
    topic: 'Genetics',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'What genetic condition results from trisomy of chromosome 21 in humans?',
    options: [
      { id: 'a', text: 'Turner syndrome' },
      { id: 'b', text: 'Klinefelter syndrome' },
      { id: 'c', text: 'Down syndrome' },
      { id: 'd', text: 'Cri du chat syndrome' },
    ],
    correct_option_ids: ['c'],
    explanation: 'Down syndrome (47, XX,+21 or 47, XY,+21) is an autosomal aneuploidy caused by meiotic nondisjunction of homologous chromosome pair 21.',
    formula_hint: 'Trisomy 21 = Down syndrome',
    default_marks: 2.0,
    section: 'Section B: Chromosomal Disorders & Molecular Genetics',
  },
  {
    subject: 'Biology',
    topic: 'Genetics',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following characteristics accurately describe the process of DNA replication in prokaryotic cells?',
    options: [
      { id: 'a', text: 'Semiconservative replication' },
      { id: 'b', text: 'Bidirectional replication from a single origin (oriC)' },
      { id: 'c', text: 'DNA polymerase synthesizes the nascent strand strictly in the 5’ to 3’ direction' },
      { id: 'd', text: 'Requires RNA primers synthesized by primase' },
    ],
    correct_option_ids: ['a', 'b', 'c', 'd'],
    explanation: 'DNA replication is semiconservative (Meselson-Stahl), initiates bidirectionally from oriC in prokaryotes, requires an RNA primer, and elongates only in the 5’→3’ direction on both leading and lagging strands.',
    formula_hint: '5’ to 3’ synthesis; leading and lagging (Okazaki) strands',
    default_marks: 2.0,
    section: 'Section B: Chromosomal Disorders & Molecular Genetics',
  },
  {
    subject: 'Biology',
    topic: 'Genetics',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'In human sex determination, the father determines the biological sex of the offspring because males are heterogametic (XY).',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Human females produce only X-bearing eggs (homogametic XX), while males produce equal proportions of X-bearing and Y-bearing spermatozoa (heterogametic XY).',
    formula_hint: 'Female: XX; Male: XY',
    default_marks: 1.0,
    section: 'Section A: Mendelian Genetics',
  },
  {
    subject: 'Biology',
    topic: 'Genetics',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What is the universal start codon in mRNA that codes for methionine in eukaryotes?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'AUG',
    explanation: 'AUG serves as the initiator codon recognized by initiator tRNA loaded with methionine, establishing the reading frame for translation.',
    formula_hint: 'Start codon = AUG',
    default_marks: 1.0,
    section: 'Section B: Chromosomal Disorders & Molecular Genetics',
  },
  {
    subject: 'Biology',
    topic: 'Genetics',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'State Chargaff’s rule regarding base pairing ratios in double-stranded DNA.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'A = T and G = C',
    explanation: 'Chargaff demonstrated that in any double-stranded DNA molecule, the molar concentration of adenine equals thymine ([A]=[T]) and guanine equals cytosine ([G]=[C]), making purine to pyrimidine ratio 1:1.',
    formula_hint: '[A] + [G] = [T] + [C]',
    default_marks: 1.5,
    section: 'Section B: Chromosomal Disorders & Molecular Genetics',
  },
  {
    subject: 'Biology',
    topic: 'Genetics',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the mechanism of the lac operon in Escherichia coli in the presence and absence of lactose.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'In the absence of lactose, the constitutive repressor protein (encoded by lacI) binds tightly to the operator region (lacO), sterically blocking RNA polymerase from transcribing the structural genes (lacZ, lacY, lacA). In the presence of lactose, an isomer allolactose acts as an inducer by binding to the repressor protein, causing a conformational change that releases the repressor from the operator. RNA polymerase can then transcribe the polycistronic mRNA, expressing β-galactosidase, permease, and transacetylase.',
    explanation: 'Classic model of negative inducible transcriptional regulation in prokaryotes.',
    formula_hint: 'Inducer = allolactose; structural genes = lacZ, lacY, lacA',
    default_marks: 2.5,
    section: 'Section B: Chromosomal Disorders & Molecular Genetics',
  },

  // ============================================================================
  // 4. Evolution (8 Questions)
  // ============================================================================
  {
    subject: 'Biology',
    topic: 'Evolution',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which anatomical structures have common embryonic origin and basic structural framework but perform divergent functions (e.g. human arm and bat wing)?',
    options: [
      { id: 'a', text: 'Homologous organs' },
      { id: 'b', text: 'Analogous organs' },
      { id: 'c', text: 'Vestigial organs' },
      { id: 'd', text: 'Atavistic structures' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Homologous structures share common evolutionary ancestry and anatomical origins (e.g. pentadactyl limb bones in vertebrates) while adapting to divergent lifestyles (divergent evolution).',
    formula_hint: 'Common origin + divergent functions = Homology',
    default_marks: 1.0,
    section: 'Section A: Evolutionary Evidence & Principles',
  },
  {
    subject: 'Biology',
    topic: 'Evolution',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'In a population at Hardy-Weinberg equilibrium, the frequency of a recessive allele (a) is 0.3. What is the frequency of heterozygous individuals (Aa)?',
    options: [
      { id: 'a', text: '0.09' },
      { id: 'b', text: '0.42' },
      { id: 'c', text: '0.49' },
      { id: 'd', text: '0.21' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Given q = 0.3. Since p + q = 1, p = 1 - 0.3 = 0.7. Heterozygous frequency 2pq = 2 × 0.7 × 0.3 = 0.42 (or 42%).',
    formula_hint: 'p² + 2pq + q² = 1; 2pq = heterozygotes',
    default_marks: 1.5,
    section: 'Section B: Population Genetics & Speciation',
  },
  {
    subject: 'Biology',
    topic: 'Evolution',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'The famous Miller-Urey experiment (1953) simulated prebiotic primitive Earth conditions and successfully synthesized which class of organic molecules?',
    options: [
      { id: 'a', text: 'Amino acids' },
      { id: 'b', text: 'Polypeptides and enzymes' },
      { id: 'c', text: 'Complete DNA double helices' },
      { id: 'd', text: 'Phospholipid cellular vesicles' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Miller and Urey subjected methane (CH₄), ammonia (NH₃), hydrogen (H₂), and water vapor to continuous electrical discharge, synthesizing simple organic compounds, prominently including amino acids like glycine and alanine.',
    formula_hint: 'CH₄, NH₃, H₂, H₂O + electric sparks → amino acids',
    default_marks: 2.0,
    section: 'Section A: Evolutionary Evidence & Principles',
  },
  {
    subject: 'Biology',
    topic: 'Evolution',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following conditions must be satisfied for a population to remain in Hardy-Weinberg genetic equilibrium?',
    options: [
      { id: 'a', text: 'Large population size (no genetic drift)' },
      { id: 'b', text: 'Random mating without sexual selection' },
      { id: 'c', text: 'Absence of natural selection on the locus' },
      { id: 'd', text: 'High rate of directional mutation' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Hardy-Weinberg equilibrium assumes infinite/large population size (a), random mating (b), no natural selection (c), no gene flow/migration, and no mutation. Mutation disturbs equilibrium, so (d) is false.',
    formula_hint: 'H-W assumptions: No drift, no selection, no mutation, no migration, random mating',
    default_marks: 2.0,
    section: 'Section B: Population Genetics & Speciation',
  },
  {
    subject: 'Biology',
    topic: 'Evolution',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Natural selection operates directly on the phenotypic characteristics of individual organisms rather than directly on isolated genotypes.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Environmental selective pressures interact directly with the expressed phenotype of an organism, which indirectly shifts underlying allele frequencies over generations.',
    formula_hint: 'Selection acts on phenotypes, altering genotypic frequencies',
    default_marks: 1.0,
    section: 'Section A: Evolutionary Evidence & Principles',
  },
  {
    subject: 'Biology',
    topic: 'Evolution',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What term describes random fluctuations in allele frequencies from generation to generation due strictly to sampling error in small populations?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Genetic drift',
    explanation: 'Genetic drift (Sewall Wright effect) leads to stochastic loss or fixation of alleles regardless of their selective advantage, especially pronounced in founder events and bottlenecks.',
    formula_hint: 'Stochastic frequency change = Genetic drift',
    default_marks: 1.0,
    section: 'Section B: Population Genetics & Speciation',
  },
  {
    subject: 'Biology',
    topic: 'Evolution',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'Name the evolutionary phenomenon where ancestral species rapidly diversify into a multitude of new forms occupying distinct ecological niches (e.g. Darwin’s finches).',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Adaptive radiation',
    explanation: 'Adaptive radiation is the rapid speciation of a single common ancestor to exploit newly available ecological opportunities or geographic islands.',
    formula_hint: 'Diversification into multiple niches = Adaptive radiation',
    default_marks: 1.5,
    section: 'Section A: Evolutionary Evidence & Principles',
  },
  {
    subject: 'Biology',
    topic: 'Evolution',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Compare allopatric speciation and sympatric speciation, specifying the primary barrier in each.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Allopatric speciation occurs when a single biological population is physically divided by an extrinsic geographic barrier (such as mountain uplift, river formation, or continental drift) that completely prevents gene flow; isolated populations accumulate independent genetic mutations and diverge until reproductive isolation is established. Sympatric speciation occurs without any geographic separation, where reproductive isolation evolves within the same overlapping geographic territory through mechanisms like polyploidy (common in plants), sexual selection, or disruptive ecological niche partitioning.',
    explanation: 'Allopatric requires geographic isolation first; sympatric achieves reproductive isolation within the shared range.',
    formula_hint: 'Allopatric = geographic barrier; Sympatric = ecological/behavioral/genetic barrier',
    default_marks: 2.5,
    section: 'Section B: Population Genetics & Speciation',
  },

  // ============================================================================
  // 5. Plant Physiology (8 Questions)
  // ============================================================================
  {
    subject: 'Biology',
    topic: 'Plant Physiology',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which primary photosynthetic pigment absorbs blue-violet and red light while reflecting green light?',
    options: [
      { id: 'a', text: 'Chlorophyll a' },
      { id: 'b', text: 'Carotenoid' },
      { id: 'c', text: 'Anthocyanin' },
      { id: 'd', text: 'Xanthophyll' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Chlorophyll a is the essential reaction center pigment in oxygenic photosynthesis, absorbing primarily at ~430 nm (blue) and ~662 nm (red) while transmitting green wavelengths.',
    formula_hint: 'P680 (PSII) and P700 (PSI) reaction centers',
    default_marks: 1.0,
    section: 'Section A: Photosynthesis & Respiration',
  },
  {
    subject: 'Biology',
    topic: 'Plant Physiology',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'In C4 photosynthetic plants (such as maize and sugarcane), what is the initial atmospheric CO₂ acceptor molecule?',
    options: [
      { id: 'a', text: 'Ribulose-1,5-bisphosphate (RuBP)' },
      { id: 'b', text: 'Phosphoenolpyruvate (PEP)' },
      { id: 'c', text: 'Oxaloacetic acid (OAA)' },
      { id: 'd', text: '3-phosphoglyceric acid (PGA)' },
    ],
    correct_option_ids: ['b'],
    explanation: 'In C4 mesophyll cells, CO₂ is initially fixed by PEP carboxylase onto phosphoenolpyruvate (PEP, 3 carbons) to produce oxaloacetate (4 carbons), bypassing RuBisCO oxygenation.',
    formula_hint: 'PEP + CO₂ --(PEPcase)--> Oxaloacetate',
    default_marks: 1.5,
    section: 'Section A: Photosynthesis & Respiration',
  },
  {
    subject: 'Biology',
    topic: 'Plant Physiology',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'According to the cohesion-tension theory of Dixon and Joly, what is the primary driving physical force responsible for the long-distance ascent of sap in xylem vessels?',
    options: [
      { id: 'a', text: 'Active ATP-driven metabolic root pumping' },
      { id: 'b', text: 'Transpirational pull generating negative hydrostatic pressure tension' },
      { id: 'c', text: 'Atmospheric barometric pressure pushing sap upwards' },
      { id: 'd', text: 'Capillary rise due exclusively to vessel wall adhesion' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Transpiration from stomata creates high negative water potential (tension) in mesophyll cells, pulling a continuous water column upward through xylem vessels stabilized by water-water cohesion and water-wall adhesion.',
    formula_hint: 'Cohesion-Tension-Transpiration Pull Model',
    default_marks: 2.0,
    section: 'Section B: Transport & Hormones',
  },
  {
    subject: 'Biology',
    topic: 'Plant Physiology',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following plant hormones promote stem elongation, seed germination, and mobilization of seed endosperm enzymes?',
    options: [
      { id: 'a', text: 'Gibberellins (GA)' },
      { id: 'b', text: 'Abscisic acid (ABA)' },
      { id: 'c', text: 'Auxins' },
      { id: 'd', text: 'Ethylene' },
    ],
    correct_option_ids: ['a', 'c'],
    explanation: 'Gibberellins break seed dormancy, induce α-amylase, and cause internode elongation. Auxins promote cell elongation. Abscisic acid enforces seed dormancy and stomatal closure (stress hormone).',
    formula_hint: 'Gibberellins induce α-amylase in germinating seeds',
    default_marks: 2.0,
    section: 'Section B: Transport & Hormones',
  },
  {
    subject: 'Biology',
    topic: 'Plant Physiology',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Opening of stomata during daylight is driven by active potassium ion (K⁺) uptake into guard cells.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Proton pumps extrude H⁺, driving K⁺ and malate influx into guard cells. The increased osmotic concentration draws water in via osmosis, causing guard cells to swell and bow apart.',
    formula_hint: 'K⁺ influx => turgidity => stomatal pore opens',
    default_marks: 1.0,
    section: 'Section B: Transport & Hormones',
  },
  {
    subject: 'Biology',
    topic: 'Plant Physiology',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Name the gaseous phytohormone that promotes fruit ripening and leaf abscission.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Ethylene',
    explanation: 'Ethylene (C₂H₄) is a volatile hydrocarbon hormone responsible for climacteric fruit ripening, flower senescence, and petiole abscission.',
    formula_hint: 'Gaseous hormone = Ethylene',
    default_marks: 1.0,
    section: 'Section B: Transport & Hormones',
  },
  {
    subject: 'Biology',
    topic: 'Plant Physiology',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What is the end product of glycolysis synthesized from one molecule of glucose in the plant cell cytoplasm?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Pyruvate',
    explanation: 'Glycolysis degrades 1 six-carbon glucose molecule into 2 three-carbon molecules of pyruvate (along with net 2 ATP and 2 NADH).',
    formula_hint: 'Glucose (6C) → 2 Pyruvate (3C) + 2 ATP + 2 NADH',
    default_marks: 1.5,
    section: 'Section A: Photosynthesis & Respiration',
  },
  {
    subject: 'Biology',
    topic: 'Plant Physiology',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain photorespiration (C2 cycle) and discuss why it represents an energetically wasteful process in C3 plants.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Photorespiration occurs when the bifunctional enzyme RuBisCO binds oxygen (O₂) instead of CO₂ at high temperatures or low CO₂:O₂ ratios. RuBisCO oxygenates RuBP (5C) to produce 1 molecule of 3-phosphoglycerate (3C) and 1 molecule of toxic 2-phosphoglycolate (2C). Salvaging phosphoglycolate requires a complex metabolic pathway spanning chloroplast, peroxisome, and mitochondrion that consumes ATP and releases previously fixed CO₂ without synthesizing ATP, NADPH, or sugars, squandering up to 25–40% of photosynthetic energy.',
    explanation: 'Oxygenase activity of RuBisCO reduces net photosynthetic carbon assimilation in hot, dry conditions.',
    formula_hint: 'RuBP + O₂ --(RuBisCO)--> 3-PGA + 2-Phosphoglycolate',
    default_marks: 3.0,
    section: 'Section A: Photosynthesis & Respiration',
  },

  // ============================================================================
  // 6. Human Physiology (8 Questions)
  // ============================================================================
  {
    subject: 'Biology',
    topic: 'Human Physiology',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which human organ secretes insulin and glucagon directly into the bloodstream to regulate blood glucose homeostasis?',
    options: [
      { id: 'a', text: 'Liver' },
      { id: 'b', text: 'Pancreas' },
      { id: 'c', text: 'Gallbladder' },
      { id: 'd', text: 'Thyroid gland' },
    ],
    correct_option_ids: ['b'],
    explanation: 'The endocrine Islets of Langerhans in the pancreas secrete insulin (from β-cells) to lower blood glucose and glucagon (from α-cells) to elevate glucose levels.',
    formula_hint: 'Pancreas: Islets of Langerhans (α: glucagon, β: insulin)',
    default_marks: 1.0,
    section: 'Section A: Circulation, Digestion & Respiration',
  },
  {
    subject: 'Biology',
    topic: 'Human Physiology',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the functional structural unit of the human kidney responsible for blood filtration, reabsorption, and urine production?',
    options: [
      { id: 'a', text: 'Nephron' },
      { id: 'b', text: 'Neuron' },
      { id: 'c', text: 'Alveolus' },
      { id: 'd', text: 'Hepatocyte' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Each kidney contains approximately 1 million nephrons, consisting of a renal corpuscle (glomerulus and Bowman’s capsule) and a tubular system (PCT, loop of Henle, DCT, collecting duct).',
    formula_hint: 'Nephron = Glomerulus + Renal Tubule',
    default_marks: 1.5,
    section: 'Section B: Excretion & Neurobiology',
  },
  {
    subject: 'Biology',
    topic: 'Human Physiology',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'During the depolarization phase of a neuronal action potential, which ion channels open rapidly to cause voltage reversal across the axolemma?',
    options: [
      { id: 'a', text: 'Voltage-gated Sodium (Na⁺) channels' },
      { id: 'b', text: 'Voltage-gated Potassium (K⁺) channels' },
      { id: 'c', text: 'Chloride (Cl⁻) leak channels' },
      { id: 'd', text: 'Calcium (Ca²⁺) ATPase pumps' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Depolarization above threshold opens voltage-gated Na⁺ channels. Influx of Na⁺ down its electrochemical gradient drives membrane potential from -70 mV up to approximately +30 mV.',
    formula_hint: 'Action potential upstroke = rapid Na⁺ influx',
    default_marks: 2.0,
    section: 'Section B: Excretion & Neurobiology',
  },
  {
    subject: 'Biology',
    topic: 'Human Physiology',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following blood vessels carry oxygenated blood under normal physiological circulation in humans?',
    options: [
      { id: 'a', text: 'Aorta' },
      { id: 'b', text: 'Pulmonary veins' },
      { id: 'c', text: 'Pulmonary arteries' },
      { id: 'd', text: 'Carotid artery' },
    ],
    correct_option_ids: ['a', 'b', 'd'],
    explanation: 'The aorta and carotid arteries carry oxygen-rich systemic blood. Pulmonary veins carry freshly oxygenated blood from lungs back to the left atrium. Pulmonary arteries carry deoxygenated blood to the lungs.',
    formula_hint: 'Pulmonary veins are the only veins carrying oxygenated blood',
    default_marks: 2.0,
    section: 'Section A: Circulation, Digestion & Respiration',
  },
  {
    subject: 'Biology',
    topic: 'Human Physiology',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'The sinoatrial (SA) node acts as the natural primary physiological pacemaker of the human heart.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Located in the right atrium, the SA node exhibits the fastest intrinsic rate of spontaneous autorhythmic diastolic depolarization (~70–80 bpm), setting cardiac rhythm.',
    formula_hint: 'SA Node = Cardiac Pacemaker',
    default_marks: 1.0,
    section: 'Section A: Circulation, Digestion & Respiration',
  },
  {
    subject: 'Biology',
    topic: 'Human Physiology',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What major plasma enzyme converts soluble fibrinogen into insoluble fibrin strands during blood coagulation?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Thrombin',
    explanation: 'Prothrombin is cleaved into active thrombin by prothrombinase (Factor Xa). Thrombin then hydrolyzes fibrinogen into fibrin monomers that polymerize to form the blood clot mesh.',
    formula_hint: 'Fibrinogen --(Thrombin)--> Fibrin clot',
    default_marks: 1.0,
    section: 'Section A: Circulation, Digestion & Respiration',
  },
  {
    subject: 'Biology',
    topic: 'Human Physiology',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What is the principal respiratory gas exchange pigment found in human red blood cells?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Hemoglobin',
    explanation: 'Hemoglobin is an iron-containing tetrameric metalloprotein capable of reversibly binding up to four O₂ molecules per molecule.',
    formula_hint: 'Hb + 4 O₂ ⇌ Hb(O₂)₄',
    default_marks: 1.0,
    section: 'Section A: Circulation, Digestion & Respiration',
  },
  {
    subject: 'Biology',
    topic: 'Human Physiology',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the sliding filament mechanism of skeletal muscle contraction, highlighting the regulatory roles of Ca²⁺, troponin, and tropomyosin.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'In relaxed muscle, tropomyosin blocks the myosin-binding sites on actin filaments. When an action potential depolarizes the sarcolemma and T-tubules, Ca²⁺ is released from the sarcoplasmic reticulum into the sarcoplasm. Ca²⁺ binds to troponin C, inducing a conformational shift that pulls tropomyosin away from actin binding sites. Myosin heads (energized by ATP hydrolysis) bind actin to form cross-bridges, execute the power stroke pulling actin toward the sarcomere center (shortening the H-zone and I-band), and release upon binding a new ATP molecule.',
    explanation: 'Cross-bridge cycling driven by ATP hydrolysis slides thin actin over thick myosin filaments without either changing in physical length.',
    formula_hint: 'Ca²⁺ binds Troponin C -> Tropomyosin shifts -> Cross-bridge cycle',
    default_marks: 3.0,
    section: 'Section B: Excretion & Neurobiology',
  },

  // ============================================================================
  // 7. Reproduction (8 Questions)
  // ============================================================================
  {
    subject: 'Biology',
    topic: 'Reproduction',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Where does fertilization of the human ovum by a spermatozoon normally take place under healthy conditions?',
    options: [
      { id: 'a', text: 'Uterine cavity' },
      { id: 'b', text: 'Ampullary region of the Fallopian tube' },
      { id: 'c', text: 'Cervix' },
      { id: 'd', text: 'Ovary' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Fertilization occurs within the ampulla (ampullary-isthmic junction) of the oviduct/Fallopian tube.',
    formula_hint: 'Site of fertilization: Ampulla of Fallopian tube',
    default_marks: 1.0,
    section: 'Section A: Human Reproductive Biology',
  },
  {
    subject: 'Biology',
    topic: 'Reproduction',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Which pituitary hormone surge triggers ovulation (rupture of the mature Graafian follicle) around day 14 of the human menstrual cycle?',
    options: [
      { id: 'a', text: 'Follicle-stimulating hormone (FSH)' },
      { id: 'b', text: 'Luteinizing hormone (LH)' },
      { id: 'c', text: 'Progesterone' },
      { id: 'd', text: 'Prolactin' },
    ],
    correct_option_ids: ['b'],
    explanation: 'A sharp mid-cycle LH surge (positive feedback by peak estrogen levels) induces resumption of meiosis and proteolytic rupture of the Graafian follicle, expelling the secondary oocyte.',
    formula_hint: 'LH surge triggers ovulation at day ~14',
    default_marks: 1.5,
    section: 'Section A: Human Reproductive Biology',
  },
  {
    subject: 'Biology',
    topic: 'Reproduction',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'In angiosperm double fertilization, what are the ploidy levels of the resulting zygote and endosperm nucleus respectively?',
    options: [
      { id: 'a', text: 'Zygote is 2n (diploid); Endosperm is 3n (triploid)' },
      { id: 'b', text: 'Zygote is 2n; Endosperm is 2n' },
      { id: 'c', text: 'Zygote is 1n; Endosperm is 3n' },
      { id: 'd', text: 'Zygote is 3n; Endosperm is 2n' },
    ],
    correct_option_ids: ['a'],
    explanation: 'One haploid sperm (n) fertilizes the haploid egg (n) to form a diploid zygote (2n, syngamy). The second sperm (n) fuses with two diploid central polar nuclei (2n) to form the triploid primary endosperm nucleus (3n, triple fusion).',
    formula_hint: 'Double fertilization: Syngamy (2n) + Triple Fusion (3n)',
    default_marks: 2.0,
    section: 'Section B: Plant Reproduction & Embryology',
  },
  {
    subject: 'Biology',
    topic: 'Reproduction',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following male reproductive accessory glands contribute secretions to seminal plasma in humans?',
    options: [
      { id: 'a', text: 'Seminal vesicles' },
      { id: 'b', text: 'Prostate gland' },
      { id: 'c', text: 'Bulbourethral (Cowper’s) glands' },
      { id: 'd', text: 'Bartholin’s glands' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Seminal vesicles, prostate, and bulbourethral glands are male accessory glands that produce seminal fluid rich in fructose, citrate, and alkaline buffers. Bartholin’s glands are female homologous structures.',
    formula_hint: 'Male accessory glands: Seminal vesicles, Prostate, Bulbourethral',
    default_marks: 2.0,
    section: 'Section A: Human Reproductive Biology',
  },
  {
    subject: 'Biology',
    topic: 'Reproduction',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'The corpus luteum secretes large amounts of progesterone required for maintaining the uterine endometrium during early pregnancy.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Following ovulation, the collapsed follicle transforms into the corpus luteum, which secretes progesterone to maintain the secretory endometrium for blastocyst implantation.',
    formula_hint: 'Corpus luteum -> Progesterone -> Endometrial maintenance',
    default_marks: 1.0,
    section: 'Section A: Human Reproductive Biology',
  },
  {
    subject: 'Biology',
    topic: 'Reproduction',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What cap-like structure on the anterior sperm head contains digestive hydrolytic enzymes required to penetrate the zona pellucida?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Acrosome',
    explanation: 'The acrosome is derived from the Golgi apparatus and releases hyaluronidase and acrosin during the acrosome reaction to digest the ovum’s outer protective coats.',
    formula_hint: 'Acrosome reaction penetrates zona pellucida',
    default_marks: 1.0,
    section: 'Section A: Human Reproductive Biology',
  },
  {
    subject: 'Biology',
    topic: 'Reproduction',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'Name the female embryonic structure consisting of an inner cell mass and an outer trophoblast layer that implants into the uterine endometrium.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Blastocyst',
    explanation: 'The blastocyst (reached ~5–7 days post-fertilization) consists of a fluid-filled blastocoel, an outer trophoblast that forms the placenta, and an inner cell mass that develops into the embryo.',
    formula_hint: 'Implantation stage = Blastocyst',
    default_marks: 1.5,
    section: 'Section A: Human Reproductive Biology',
  },
  {
    subject: 'Biology',
    topic: 'Reproduction',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Differentiate between spermatogenesis and oogenesis in humans regarding timing of meiotic completion and number of functional gametes produced per primary germ cell.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Spermatogenesis begins at puberty and continues throughout life; each primary spermatocyte undergoes complete symmetrical meiosis to yield four equal, viable haploid spermatozoa. Oogenesis initiates during embryonic development, where primary oocytes arrest in prophase I until puberty, then resume meiosis one by one during menstrual cycles to arrest at metaphase II, which only finishes upon sperm fertilization. Meiotic divisions in oogenesis are highly unequal, producing only one single large functional ovum and up to two or three non-functional polar bodies.',
    explanation: 'Spermatogenesis produces 4 functional gametes continuously; oogenesis yields 1 ovum with unequal cytoplasmic distribution and two developmental arrests.',
    formula_hint: 'Spermatogenesis: 1 -> 4 viable sperm; Oogenesis: 1 -> 1 ovum + polar bodies',
    default_marks: 3.0,
    section: 'Section A: Human Reproductive Biology',
  },

  // ============================================================================
  // 8. Ecology (8 Questions)
  // ============================================================================
  {
    subject: 'Biology',
    topic: 'Ecology',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'According to Lindeman’s Ten Percent Law of trophic efficiency, what percentage of net energy is typically transferred from one trophic level to the next?',
    options: [
      { id: 'a', text: '1%' },
      { id: 'b', text: '10%' },
      { id: 'c', text: '50%' },
      { id: 'd', text: '90%' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Approximately 90% of energy is dissipated as metabolic heat, respiration, and unconsumed biomass, leaving only ~10% to be stored as organic tissue available to the next trophic level.',
    formula_hint: 'Trophic efficiency ≈ 10%',
    default_marks: 1.0,
    section: 'Section A: Ecosystem Dynamics',
  },
  {
    subject: 'Biology',
    topic: 'Ecology',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Which ecological interaction is characterized by one species benefiting while the host species is neither helped nor harmed (+/0)?',
    options: [
      { id: 'a', text: 'Mutualism' },
      { id: 'b', text: 'Commensalism' },
      { id: 'c', text: 'Amensalism' },
      { id: 'd', text: 'Parasitism' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Commensalism is a (+/0) relationship where one organism gains food, shelter, or transport without affecting the host (e.g. epiphytic orchids on a tree branch, barnacles on whales).',
    formula_hint: 'Commensalism = (+/0)',
    default_marks: 1.5,
    section: 'Section B: Population & Community Ecology',
  },
  {
    subject: 'Biology',
    topic: 'Ecology',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'What mathematical model describes population growth in a resource-limited environment with carrying capacity K?',
    options: [
      { id: 'a', text: 'Exponential growth: dN/dt = rN' },
      { id: 'b', text: 'Logistic growth: dN/dt = rN(1 - N/K)' },
      { id: 'c', text: 'Linear growth: dN/dt = c' },
      { id: 'd', text: 'Power law growth: dN/dt = N²' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Verhulst-Pearl logistic growth models density-dependent feedback: as population N approaches carrying capacity K, growth rate slows, producing a characteristic sigmoid (S-shaped) curve.',
    formula_hint: 'dN/dt = r N (1 - N/K)',
    default_marks: 2.0,
    section: 'Section B: Population & Community Ecology',
  },
  {
    subject: 'Biology',
    topic: 'Ecology',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following ecological pyramids can never be inverted in a natural, stable ecosystem?',
    options: [
      { id: 'a', text: 'Pyramid of energy' },
      { id: 'b', text: 'Pyramid of biomass in an open ocean' },
      { id: 'c', text: 'Pyramid of numbers in a single tree ecosystem' },
      { id: 'd', text: 'Pyramid of productivity' },
    ],
    correct_option_ids: ['a', 'd'],
    explanation: 'By the Second Law of Thermodynamics, energy is lost as heat at every step. Total energy content/productivity available at lower levels is always greater than higher levels, making energy pyramids strictly upright.',
    formula_hint: 'Energy pyramids are strictly upright (2nd Law of Thermodynamics)',
    default_marks: 2.0,
    section: 'Section A: Ecosystem Dynamics',
  },
  {
    subject: 'Biology',
    topic: 'Ecology',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Eutrophication of aquatic water bodies is triggered by excess nutrient enrichment of nitrates and phosphates, leading to algal blooms and oxygen depletion.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. High runoff of nitrogen/phosphorus spurs massive algal blooms; when algae die, bacterial decomposition consumes dissolved oxygen, causing hypoxia and fish mortality.',
    formula_hint: 'Excess N & P -> Algal bloom -> Deoxygenation (BOD increases)',
    default_marks: 1.0,
    section: 'Section A: Ecosystem Dynamics',
  },
  {
    subject: 'Biology',
    topic: 'Ecology',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Name the transition zone of junction between two distinct ecological communities or biomes (e.g. mangrove forest between land and sea).',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Ecotone',
    explanation: 'An ecotone is an edge transition region exhibiting high species richness and population density known as the "edge effect".',
    formula_hint: 'Tension/transition zone = Ecotone',
    default_marks: 1.0,
    section: 'Section B: Population & Community Ecology',
  },
  {
    subject: 'Biology',
    topic: 'Ecology',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'State Gause’s Competitive Exclusion Principle.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Two competing species cannot coexist indefinitely on the same limiting resource',
    explanation: 'Gause’s principle asserts that two species competing for the exact same limiting resource cannot stably coexist; the competitor with even a slight advantage will outcompete and displace the other.',
    formula_hint: 'Complete competitors cannot coexist in the same niche',
    default_marks: 1.5,
    section: 'Section B: Population & Community Ecology',
  },
  {
    subject: 'Biology',
    topic: 'Ecology',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Differentiate between primary and secondary ecological succession, citing typical initiating pioneer substrates for each.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Primary ecological succession occurs in newly formed, completely barren environments devoid of preexisting soil, organic matter, or seed banks (such as cooled volcanic lava flows, newly exposed sand dunes, or retreating glaciers); initial pioneer colonizers are crustose lichens and mosses that weather rock to produce soil. Secondary succession occurs in an area where an existing biological community has been disrupted or cleared by a disturbance (such as wildfire, deforestation, or abandoned farmland) but where intact soil, organic nutrients, and seeds remain; pioneer colonizers are fast-growing annual grasses and weeds, proceeding much faster than primary succession.',
    explanation: 'Primary starts on sterile bare rock without soil; secondary proceeds rapidly on existing soil after disturbance.',
    formula_hint: 'Primary = no initial soil; Secondary = intact soil substrate present',
    default_marks: 2.5,
    section: 'Section A: Ecosystem Dynamics',
  },

  // ============================================================================
  // 9. Biotechnology (8 Questions)
  // ============================================================================
  {
    subject: 'Biology',
    topic: 'Biotechnology',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which bacterial enzyme acts as molecular scissors to cleave double-stranded DNA at specific palindromic recognition sequences?',
    options: [
      { id: 'a', text: 'Restriction endonuclease' },
      { id: 'b', text: 'DNA ligase' },
      { id: 'c', text: 'DNA polymerase I' },
      { id: 'd', text: 'Reverse transcriptase' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Restriction endonucleases (such as EcoRI) recognize specific palindromic 4–8 base pair sequences and cleave phosphodiester backbones, generating sticky or blunt ends for recombinant cloning.',
    formula_hint: 'Molecular scissors = Restriction endonuclease',
    default_marks: 1.0,
    section: 'Section A: Recombinant DNA Technology',
  },
  {
    subject: 'Biology',
    topic: 'Biotechnology',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Why is Taq polymerase from Thermus aquaticus uniquely suited for the Polymerase Chain Reaction (PCR)?',
    options: [
      { id: 'a', text: 'It operates without divalent magnesium ions' },
      { id: 'b', text: 'It remains enzymatically active and stable during high-temperature DNA denaturation (~95 °C)' },
      { id: 'c', text: 'It synthesizes DNA without primers' },
      { id: 'd', text: 'It proofreads with 100% fidelity' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Isolated from hyperthermophilic hot-spring bacteria, Taq polymerase withstands repeated 94–96 °C denaturation steps without thermal denaturation, enabling automated cycling.',
    formula_hint: 'Thermostable DNA polymerase from Thermus aquaticus',
    default_marks: 1.5,
    section: 'Section B: PCR & Electrophoresis',
  },
  {
    subject: 'Biology',
    topic: 'Biotechnology',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'In agarose gel electrophoresis, in which direction and according to what physical property do DNA fragments migrate?',
    options: [
      { id: 'a', text: 'From cathode (-) to anode (+) separated by molecular size' },
      { id: 'b', text: 'From anode (+) to cathode (-) separated by base composition' },
      { id: 'c', text: 'From cathode to anode separated solely by electrical charge density' },
      { id: 'd', text: 'Randomly based on hydrogen bonding' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Due to negatively charged phosphate backbones, DNA fragments migrate toward the positive anode (+). Agarose mesh acts as a molecular sieve: smaller fragments navigate pores faster, separating logarithmically by base-pair length.',
    formula_hint: 'DNA is negatively charged; migration rate ∝ 1 / log(molecular weight)',
    default_marks: 2.0,
    section: 'Section B: PCR & Electrophoresis',
  },
  {
    subject: 'Biology',
    topic: 'Biotechnology',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following components are essential features of an engineered cloning vector like pBR322?',
    options: [
      { id: 'a', text: 'Origin of replication (ori)' },
      { id: 'b', text: 'Selectable marker genes (e.g. ampicillin resistance)' },
      { id: 'c', text: 'Unique restriction recognition cloning sites' },
      { id: 'd', text: 'Nuclear localization signal sequence' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Essential cloning vector elements are: 1. ori for autonomous replication in host; 2. selectable markers for identifying transformants; 3. multiple cloning sites (MCS) for insertion. Bacterial vectors do not require eukaryotic nuclear localization signals.',
    formula_hint: 'Vector requirements: ori, selectable marker, unique restriction sites',
    default_marks: 2.0,
    section: 'Section A: Recombinant DNA Technology',
  },
  {
    subject: 'Biology',
    topic: 'Biotechnology',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Bt crops (such as Bt cotton) express Cry endotoxin proteins derived from Bacillus thuringiensis that confer resistance against specific insect pests.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Inactive protoxins are solubilized in the alkaline midgut of susceptible lepidopteran insects, creating pores that cause cell lysis and death.',
    formula_hint: 'Cry genes from Bacillus thuringiensis -> insect resistance',
    default_marks: 1.0,
    section: 'Section A: Recombinant DNA Technology',
  },
  {
    subject: 'Biology',
    topic: 'Biotechnology',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Name the natural bacterial plant pathogen whose tumor-inducing (Ti) plasmid is widely used as a gene transfer vector in plant genetic engineering.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Agrobacterium tumefaciens',
    explanation: 'Agrobacterium tumefaciens transfers T-DNA from its Ti plasmid into host plant genomes, making disarmed Ti plasmids premier delivery vectors for transgenic crops.',
    formula_hint: 'Natural genetic engineer of plants = Agrobacterium tumefaciens',
    default_marks: 1.0,
    section: 'Section A: Recombinant DNA Technology',
  },
  {
    subject: 'Biology',
    topic: 'Biotechnology',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What are the three sequential thermal steps in one complete cycle of Polymerase Chain Reaction (PCR)?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Denaturation, Annealing, Extension',
    explanation: 'PCR consists of: 1. Denaturation (~94–96 °C) to separate strands; 2. Annealing (~50–65 °C) for primers to bind; 3. Extension (~72 °C) for Taq polymerase synthesis.',
    formula_hint: 'Denaturation -> Annealing -> Extension (DAE)',
    default_marks: 1.5,
    section: 'Section B: PCR & Electrophoresis',
  },
  {
    subject: 'Biology',
    topic: 'Biotechnology',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the mechanism of RNA interference (RNAi) as a cellular defense gene-silencing mechanism used in developing pest-resistant plants.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'RNA interference (RNAi) is a conserved post-transcriptional gene-silencing pathway triggered by double-stranded RNA (dsRNA). In transgenic plants engineered against root-knot nematode (Meloidogyne incognita), host plant cells express both sense and antisense RNA that form dsRNA. When ingested by the pest, the cellular ribonuclease Dicer cuts dsRNA into small interfering RNAs (siRNAs, ~21–23 nt). These siRNAs integrate into the RNA-Induced Silencing Complex (RISC), which binds and specifically degrades complementary target mRNA of the parasite, preventing translation of essential nematode proteins and conferring resistance.',
    explanation: 'Post-transcriptional gene silencing via targeted sequence-specific mRNA degradation mediated by siRNA and RISC.',
    formula_hint: 'dsRNA -> Dicer -> siRNA -> RISC -> target mRNA cleavage',
    default_marks: 3.0,
    section: 'Section A: Recombinant DNA Technology',
  },
];
