/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { CurriculumQuestion } from './types.js';

export const CHEMISTRY_QUESTIONS: CurriculumQuestion[] = [
  // ============================================================================
  // 1. Mole Concept (7 Questions)
  // ============================================================================
  {
    subject: 'Chemistry',
    topic: 'Mole Concept',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the number of molecules present in 18 grams of pure liquid water (H₂O)?',
    options: [
      { id: 'a', text: '3.011 × 10²³' },
      { id: 'b', text: '6.022 × 10²³' },
      { id: 'c', text: '1.204 × 10²⁴' },
      { id: 'd', text: '6.022 × 10²²' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Molar mass of H₂O = (2 × 1) + 16 = 18 g/mol. 18 g of water equals 1 mole of molecules, containing Avogadro’s number (N_A = 6.022 × 10²³) of molecules.',
    formula_hint: 'n = m / M, N = n · N_A',
    default_marks: 1.0,
    section: 'Section A: Stoichiometry Foundations',
  },
  {
    subject: 'Chemistry',
    topic: 'Mole Concept',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'At standard temperature and pressure (STP: 0°C, 1 atm), what volume is occupied by 4.4 grams of carbon dioxide (CO₂) gas?',
    options: [
      { id: 'a', text: '1.12 L' },
      { id: 'b', text: '2.24 L' },
      { id: 'c', text: '4.48 L' },
      { id: 'd', text: '22.4 L' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Molar mass of CO₂ = 12 + (2 × 16) = 44 g/mol. Moles n = 4.4 / 44 = 0.1 mol. At STP, 1 mol occupies 22.4 L, so volume V = 0.1 × 22.4 = 2.24 L.',
    formula_hint: 'V = n · 22.4 L (at STP)',
    default_marks: 1.5,
    section: 'Section A: Stoichiometry Foundations',
  },
  {
    subject: 'Chemistry',
    topic: 'Mole Concept',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'An organic compound contains 40.0% Carbon, 6.7% Hydrogen, and 53.3% Oxygen by mass. If its experimental molar mass is 180 g/mol, what is its molecular formula?',
    options: [
      { id: 'a', text: 'CH₂O' },
      { id: 'b', text: 'C₂H₄O₂' },
      { id: 'c', text: 'C₆H₁₂O₆' },
      { id: 'd', text: 'C₃H₆O₃' },
    ],
    correct_option_ids: ['c'],
    explanation: 'Moles in 100g: C = 40.0/12 = 3.33; H = 6.7/1 = 6.7; O = 53.3/16 = 3.33. Ratio C:H:O = 1:2:1 => Empirical formula CH₂O (molar mass = 30 g/mol). Multiplier n = 180 / 30 = 6. Molecular formula is C₆H₁₂O₆.',
    formula_hint: 'Molecular Formula = (Empirical Formula)_n, n = M_molecular / M_empirical',
    default_marks: 2.0,
    section: 'Section B: Quantitative Analysis',
  },
  {
    subject: 'Chemistry',
    topic: 'Mole Concept',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following sample quantities contain exactly the same number of atoms as 12 grams of Carbon-12?',
    options: [
      { id: 'a', text: '1 gram of Hydrogen atoms (H)' },
      { id: 'b', text: '23 grams of Sodium metal (Na)' },
      { id: 'c', text: '32 grams of Oxygen gas (O₂)' },
      { id: 'd', text: '4 grams of Helium gas (He)' },
    ],
    correct_option_ids: ['a', 'b', 'd'],
    explanation: '12g C-12 = 1 mole of atoms (N_A). 1g H atoms = 1 mol atoms (a). 23g Na = 1 mol atoms (b). 4g He = 1 mol atoms (d). 32g O₂ = 1 mol O₂ molecules = 2 mol atoms = 2 N_A atoms (c is incorrect).',
    formula_hint: 'Number of atoms = moles of element · N_A',
    default_marks: 2.0,
    section: 'Section A: Stoichiometry Foundations',
  },
  {
    subject: 'Chemistry',
    topic: 'Mole Concept',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'One mole of any ideal gas at standard temperature and pressure (0 °C, 1 bar) occupies approximately 22.7 liters.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Under IUPAC standard ambient conditions of 0 °C and 1 bar (100 kPa), molar volume of an ideal gas is 22.71 L/mol (compared to 22.41 L/mol at 1 atm = 101.325 kPa).',
    formula_hint: 'V_m = R T / P',
    default_marks: 1.0,
    section: 'Section A: Stoichiometry Foundations',
  },
  {
    subject: 'Chemistry',
    topic: 'Mole Concept',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Calculate the molality (m) of a solution prepared by dissolving 20 g of NaOH (molar mass = 40 g/mol) in 500 g of water.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '1',
    explanation: 'Moles of NaOH = 20 g / 40 g/mol = 0.5 mol. Mass of solvent = 500 g = 0.5 kg. Molality m = moles of solute / kg of solvent = 0.5 / 0.5 = 1.0 mol/kg.',
    formula_hint: 'm = n_solute / mass_solvent (kg)',
    default_marks: 1.5,
    section: 'Section B: Quantitative Analysis',
  },
  {
    subject: 'Chemistry',
    topic: 'Mole Concept',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'Define the term "limiting reagent" in a chemical reaction and explain how it determines theoretical product yield.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'The limiting reagent is the reactant that is entirely consumed first in a chemical reaction based on stoichiometric proportions. Once exhausted, reaction stops; hence, the initial amount of limiting reagent strictly dictates the maximum theoretical yield of all reaction products.',
    explanation: 'Stoichiometric ratios determine which reactant produces the smallest theoretical yield of product.',
    formula_hint: 'n_product = (n_limiting / stoichiometric_coefficient) · coefficient_product',
    default_marks: 2.5,
    section: 'Section B: Quantitative Analysis',
  },

  // ============================================================================
  // 2. Atomic Structure (7 Questions)
  // ============================================================================
  {
    subject: 'Chemistry',
    topic: 'Atomic Structure',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the maximum number of electrons that can be accommodated in a subshell with azimuthal quantum number l = 2 (d subshell)?',
    options: [
      { id: 'a', text: '6' },
      { id: 'b', text: '10' },
      { id: 'c', text: '14' },
      { id: 'd', text: '2' },
    ],
    correct_option_ids: ['b'],
    explanation: 'The number of orbitals in a subshell is 2l + 1. For l = 2, orbitals = 2(2) + 1 = 5. By Pauli’s exclusion principle, each orbital holds 2 electrons, giving 5 × 2 = 10 electrons.',
    formula_hint: 'Max electrons = 2(2l + 1)',
    default_marks: 1.0,
    section: 'Section A: Quantum Numbers & Orbitals',
  },
  {
    subject: 'Chemistry',
    topic: 'Atomic Structure',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Which electron transition in a hydrogen atom emits a photon belonging to the visible spectrum (Balmer series)?',
    options: [
      { id: 'a', text: 'n = 2 to n = 1' },
      { id: 'b', text: 'n = 3 to n = 2' },
      { id: 'c', text: 'n = 4 to n = 3' },
      { id: 'd', text: 'n = 5 to n = 4' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Balmer series transitions terminate at n = 2 and emit photons in the visible range (400–700 nm). The transition from n = 3 to n = 2 produces the H-alpha red spectral line (656 nm).',
    formula_hint: '1/λ = R_H · (1/n₁² - 1/n₂²), Balmer: n₁ = 2',
    default_marks: 1.5,
    section: 'Section A: Quantum Numbers & Orbitals',
  },
  {
    subject: 'Chemistry',
    topic: 'Atomic Structure',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'According to Heisenberg’s Uncertainty Principle, if the uncertainty in position of an electron is 1.0 × 10⁻¹⁰ m, what is the minimum uncertainty in its velocity? (m_e ≈ 9.1 × 10⁻³¹ kg, h ≈ 6.63 × 10⁻³⁴ J·s)',
    options: [
      { id: 'a', text: '5.8 × 10⁵ m/s' },
      { id: 'b', text: '5.8 × 10⁷ m/s' },
      { id: 'c', text: '1.2 × 10⁴ m/s' },
      { id: 'd', text: '3.0 × 10⁸ m/s' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Δx · Δp ≥ h / (4π) => Δx · m · Δv ≥ h / (4π). Δv ≥ h / (4π m Δx) = (6.63 × 10⁻³⁴) / (4 × 3.1416 × 9.1 × 10⁻³¹ × 1.0 × 10⁻¹⁰) ≈ 5.8 × 10⁵ m/s.',
    formula_hint: 'Δx · Δp ≥ h / (4π)',
    default_marks: 2.0,
    section: 'Section B: Quantum Mechanics',
  },
  {
    subject: 'Chemistry',
    topic: 'Atomic Structure',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following electronic configurations represent ground-state exceptions to the standard Aufbau principle due to half-filled or fully-filled d-subshell stability?',
    options: [
      { id: 'a', text: 'Chromium (Cr, Z = 24): [Ar] 4s¹ 3d⁵' },
      { id: 'b', text: 'Copper (Cu, Z = 29): [Ar] 4s¹ 3d¹⁰' },
      { id: 'c', text: 'Manganese (Mn, Z = 25): [Ar] 4s² 3d⁵' },
      { id: 'd', text: 'Zinc (Zn, Z = 30): [Ar] 4s² 3d¹⁰' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'Cr and Cu promote one 4s electron to 3d to achieve exceptionally stable half-filled (3d⁵) and fully-filled (3d¹⁰) configurations with maximum exchange energy.',
    formula_hint: 'Exchange energy stability: d⁵ and d¹⁰',
    default_marks: 2.0,
    section: 'Section A: Quantum Numbers & Orbitals',
  },
  {
    subject: 'Chemistry',
    topic: 'Atomic Structure',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'No two electrons in the same atom can possess an identical set of all four quantum numbers.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. This is the exact statement of Pauli’s Exclusion Principle. Even if n, l, and m_l are identical within an orbital, electrons must have opposite spin quantum numbers (m_s = +1/2 and -1/2).',
    formula_hint: 'Pauli Exclusion: (n, l, m_l, m_s) must be unique',
    default_marks: 1.0,
    section: 'Section A: Quantum Numbers & Orbitals',
  },
  {
    subject: 'Chemistry',
    topic: 'Atomic Structure',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What is the total number of nodal planes (angular nodes) present in a 3d orbital?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '2',
    explanation: 'The number of angular nodes (nodal planes) for any orbital equals its azimuthal quantum number l. For a d orbital, l = 2, so it has exactly 2 angular nodes.',
    formula_hint: 'Angular nodes = l; Radial nodes = n - l - 1',
    default_marks: 1.5,
    section: 'Section A: Quantum Numbers & Orbitals',
  },
  {
    subject: 'Chemistry',
    topic: 'Atomic Structure',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'State de Broglie’s matter-wave hypothesis. Derive de Broglie wavelength λ for an electron of mass m accelerated through potential difference V from rest.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'de Broglie hypothesized that dual wave-particle nature applies to all matter: a moving particle of momentum p possesses an associated wavelength λ = h/p. When an electron of charge e and mass m is accelerated through potential V, electric work done equals kinetic energy: K = e V = p² / (2m). Thus, momentum p = √(2 m e V). Substituting p gives λ = h / √(2 m e V). Substituting standard constants (h, m_e, e) yields λ ≈ 1.227 / √V nm (or 12.27 / √V Å).',
    explanation: 'de Broglie’s relationship links particle mass and kinetic energy to its quantum matter-wave behavior.',
    formula_hint: 'λ = h / p = h / √(2 m q V)',
    default_marks: 4.0,
    section: 'Section B: Quantum Mechanics',
  },

  // ============================================================================
  // 3. Periodic Classification (6 Questions)
  // ============================================================================
  {
    subject: 'Chemistry',
    topic: 'Periodic Classification',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which element has the highest electronegativity on the Pauling scale?',
    options: [
      { id: 'a', text: 'Oxygen' },
      { id: 'b', text: 'Chlorine' },
      { id: 'c', text: 'Fluorine' },
      { id: 'd', text: 'Nitrogen' },
    ],
    correct_option_ids: ['c'],
    explanation: 'Fluorine possesses the highest electronegativity (approximately 4.0 on the Pauling scale) due to its high effective nuclear charge and compact atomic radius.',
    formula_hint: 'Pauling Electronegativity: F ≈ 4.0 > O ≈ 3.5 > Cl ≈ 3.0 ≈ N ≈ 3.0',
    default_marks: 1.0,
    section: 'Section A: Periodic Trends',
  },
  {
    subject: 'Chemistry',
    topic: 'Periodic Classification',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Why is the first ionization enthalpy of Nitrogen higher than that of Oxygen?',
    options: [
      { id: 'a', text: 'Oxygen has a smaller atomic radius' },
      { id: 'b', text: 'Nitrogen has a stable half-filled 2p³ subshell' },
      { id: 'c', text: 'Nitrogen has higher shielding effect' },
      { id: 'd', text: 'Oxygen has more protons in its nucleus' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Nitrogen has an electronic configuration of 1s² 2s² 2p³, with a symmetrical, exceptionally stable half-filled 2p subshell. Removing an electron from Oxygen (2p⁴) relieves electron-electron pairing repulsion, so N requires more energy than O.',
    formula_hint: 'Configuration: N (2p³) vs O (2p⁴)',
    default_marks: 1.5,
    section: 'Section A: Periodic Trends',
  },
  {
    subject: 'Chemistry',
    topic: 'Periodic Classification',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'Which of the following atoms/ions has the smallest ionic/atomic radius?',
    options: [
      { id: 'a', text: 'N³⁻' },
      { id: 'b', text: 'O²⁻' },
      { id: 'c', text: 'F⁻' },
      { id: 'd', text: 'Al³⁺' },
    ],
    correct_option_ids: ['d'],
    explanation: 'N³⁻, O²⁻, F⁻, and Al³⁺ are isoelectronic (each has 10 electrons). As nuclear charge (atomic number Z) increases from N (Z=7) to Al (Z=13), the effective nuclear charge pulling the 10 electrons increases, making Al³⁺ significantly the smallest.',
    formula_hint: 'For isoelectronic species, radius ∝ 1 / Z',
    default_marks: 2.0,
    section: 'Section A: Periodic Trends',
  },
  {
    subject: 'Chemistry',
    topic: 'Periodic Classification',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following elemental properties generally increase as one moves from left to right across a period in the Modern Periodic Table?',
    options: [
      { id: 'a', text: 'Effective nuclear charge (Z_eff)' },
      { id: 'b', text: 'Atomic radius' },
      { id: 'c', text: 'Electronegativity' },
      { id: 'd', text: 'Ionization enthalpy' },
    ],
    correct_option_ids: ['a', 'c', 'd'],
    explanation: 'Across a period, nuclear charge increases while screening remains in the same shell, causing Z_eff to increase (a), electronegativity to rise (c), and ionization enthalpy to generally trend upwards (d). Atomic radius decreases, so (b) is false.',
    formula_hint: 'Across period: Z_eff ↑, Radius ↓, EN ↑, IE ↑',
    default_marks: 2.0,
    section: 'Section A: Periodic Trends',
  },
  {
    subject: 'Chemistry',
    topic: 'Periodic Classification',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Chlorine has a more negative electron gain enthalpy than Fluorine.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. In fluorine, the added electron enters a compact 2p subshell where it experiences significant interelectronic repulsion. In chlorine, the 3p subshell is larger with less repulsion, making Cl release more energy upon electron capture (-349 kJ/mol vs -328 kJ/mol).',
    formula_hint: 'Δ_egH: Cl (-349 kJ/mol) < F (-328 kJ/mol)',
    default_marks: 1.0,
    section: 'Section A: Periodic Trends',
  },
  {
    subject: 'Chemistry',
    topic: 'Periodic Classification',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'Explain the Lanthanoid Contraction and state its major structural consequence on the atomic radii of 4d and 5d transition elements.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Lanthanoid Contraction is the steady decrease in atomic and ionic radii along the 14 lanthanoid elements (Z = 57 to 71) caused by the imperfect shielding of the 4f electrons. Because 4f orbitals are diffuse, the effective nuclear charge increases rapidly. Consequently, the covalent and atomic radii of 5d transition series elements (e.g. Hf, Zr) are virtually identical to their preceding 4d congeners (Zr ≈ 160 pm, Hf ≈ 159 pm).',
    explanation: 'Poor shielding by 4f electrons contracts subsequent outer shells, neutralizing standard period-to-period size expansion.',
    formula_hint: 'Z_eff increases due to poor shielding of 4f electrons',
    default_marks: 2.5,
    section: 'Section B: Transition & Inner-Transition Trends',
  },

  // ============================================================================
  // 4. Chemical Bonding (7 Questions)
  // ============================================================================
  {
    subject: 'Chemistry',
    topic: 'Chemical Bonding',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the hybridization of the central Carbon atom in ethene (C₂H₄)?',
    options: [
      { id: 'a', text: 'sp' },
      { id: 'b', text: 'sp²' },
      { id: 'c', text: 'sp³' },
      { id: 'd', text: 'dsp²' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Each carbon atom in ethene forms three σ bonds (two with hydrogen, one with carbon) and one unhybridized p-orbital forming a π bond, resulting in sp² hybridization with trigonal planar geometry.',
    formula_hint: 'Steric number = 3 σ bonds + 0 lone pairs = 3 (sp²)',
    default_marks: 1.0,
    section: 'Section A: Molecular Geometry & Hybridization',
  },
  {
    subject: 'Chemistry',
    topic: 'Chemical Bonding',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'According to VSEPR theory, what is the molecular geometry of sulfur tetrafluoride (SF₄)?',
    options: [
      { id: 'a', text: 'Square planar' },
      { id: 'b', text: 'Tetrahedral' },
      { id: 'c', text: 'See-saw' },
      { id: 'd', text: 'Trigonal bipyramidal' },
    ],
    correct_option_ids: ['c'],
    explanation: 'Sulfur has 6 valence electrons, forming 4 single bonds with fluorine and retaining 1 lone pair (AX₄E type, steric number 5). The lone pair occupies an equatorial position to minimize repulsion, yielding a see-saw molecular shape.',
    formula_hint: 'VSEPR AX₄E = See-saw geometry',
    default_marks: 1.5,
    section: 'Section A: Molecular Geometry & Hybridization',
  },
  {
    subject: 'Chemistry',
    topic: 'Chemical Bonding',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'According to Molecular Orbital Theory, what is the bond order and magnetic nature of the Oxygen molecule (O₂)?',
    options: [
      { id: 'a', text: 'Bond order = 2, diamagnetic' },
      { id: 'b', text: 'Bond order = 2, paramagnetic' },
      { id: 'c', text: 'Bond order = 2.5, paramagnetic' },
      { id: 'd', text: 'Bond order = 1.5, diamagnetic' },
    ],
    correct_option_ids: ['b'],
    explanation: 'O₂ has 16 electrons. MO configuration: (σ1s)²(σ*1s)²(σ2s)²(σ*2s)²(σ2p_z)²(π2p_x)²(π2p_y)²(π*2p_x)¹(π*2p_y)¹. Bonding = 10, Antibonding = 6. Bond order = (10 - 6)/2 = 2. Two unpaired electrons in degenerate π* antibonding orbitals confer paramagnetism.',
    formula_hint: 'Bond Order = (N_b - N_a) / 2',
    default_marks: 2.0,
    section: 'Section B: Molecular Orbital Theory',
  },
  {
    subject: 'Chemistry',
    topic: 'Chemical Bonding',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following molecules exhibit a permanent non-zero net dipole moment (polar molecule)?',
    options: [
      { id: 'a', text: 'H₂O' },
      { id: 'b', text: 'NH₃' },
      { id: 'c', text: 'BF₃' },
      { id: 'd', text: 'CO₂' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'H₂O (bent) and NH₃ (trigonal pyramidal) are asymmetrical, so their bond dipoles do not cancel (μ > 0). BF₃ (trigonal planar) and CO₂ (linear) are highly symmetric, causing bond dipoles to vectorially cancel to zero (μ = 0).',
    formula_hint: 'μ_net = ∑ μ_vectors',
    default_marks: 2.0,
    section: 'Section A: Molecular Geometry & Hybridization',
  },
  {
    subject: 'Chemistry',
    topic: 'Chemical Bonding',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'A sigma (σ) bond is generally stronger than a pi (π) bond formed between the same pair of atoms.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Sigma bonds result from direct end-to-end (head-on) overlap along the internuclear axis, which provides greater orbital overlap than lateral (sideways) parallel overlap in pi bonds.',
    formula_hint: 'Extent of overlap: head-on (σ) > sideways (π)',
    default_marks: 1.0,
    section: 'Section A: Molecular Geometry & Hybridization',
  },
  {
    subject: 'Chemistry',
    topic: 'Chemical Bonding',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What is the theoretical bond angle in degrees in an ideal methane (CH₄) molecule?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '109.5',
    explanation: 'Methane has sp³ hybridization with four equivalent C-H bonds arranged in a regular tetrahedron, giving mutual bond angles of 109.5° (or 109° 28’).',
    formula_hint: 'Ideal tetrahedral angle = 109.5°',
    default_marks: 1.0,
    section: 'Section A: Molecular Geometry & Hybridization',
  },
  {
    subject: 'Chemistry',
    topic: 'Chemical Bonding',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'Define hydrogen bonding and contrast intermolecular hydrogen bonding with intramolecular hydrogen bonding using ethanol and o-nitrophenol as examples.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'A hydrogen bond is an attractive electrostatic dipole-dipole force between a hydrogen atom covalently bonded to a highly electronegative atom (N, O, F) and a lone pair on another electronegative atom. Intermolecular hydrogen bonding occurs between separate molecules (e.g. ethanol), leading to molecular association, high boiling points, and water solubility. Intramolecular hydrogen bonding occurs within the same molecule (e.g. o-nitrophenol between phenolic -OH and adjacent -NO₂), forming a chelate ring that lowers boiling point and reduces water solubility.',
    explanation: 'Intermolecular bonding raises boiling points via association; intramolecular bonding prevents association with external molecules.',
    formula_hint: 'X-H ··· :Y (where X, Y ∈ {N, O, F})',
    default_marks: 2.5,
    section: 'Section B: Intermolecular Forces',
  },

  // ============================================================================
  // 5. Thermodynamics (6 Questions)
  // ============================================================================
  {
    subject: 'Chemistry',
    topic: 'Thermodynamics',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'For a process to be spontaneous under constant temperature and pressure, the change in Gibbs free energy (ΔG) must be:',
    options: [
      { id: 'a', text: 'Greater than zero (ΔG > 0)' },
      { id: 'b', text: 'Less than zero (ΔG < 0)' },
      { id: 'c', text: 'Equal to zero (ΔG = 0)' },
      { id: 'd', text: 'Infinite' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Spontaneity requires total entropy of the universe to increase, which translates to a decrease in Gibbs free energy (ΔG = ΔH - TΔS < 0) at constant T and P.',
    formula_hint: 'ΔG = ΔH - T ΔS < 0',
    default_marks: 1.0,
    section: 'Section A: Enthalpy & Spontaneity',
  },
  {
    subject: 'Chemistry',
    topic: 'Thermodynamics',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'For the reaction N₂(g) + 3H₂(g) ⇌ 2NH₃(g) at 298 K, what is the value of Δn_g (change in moles of gaseous species)?',
    options: [
      { id: 'a', text: '+2' },
      { id: 'b', text: '-2' },
      { id: 'c', text: '-1' },
      { id: 'd', text: '0' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Δn_g = ∑ n_g(products) - ∑ n_g(reactants) = 2 - (1 + 3) = 2 - 4 = -2.',
    formula_hint: 'Δn_g = n_g(products) - n_g(reactants), ΔH = ΔU + Δn_g R T',
    default_marks: 1.5,
    section: 'Section A: Enthalpy & Spontaneity',
  },
  {
    subject: 'Chemistry',
    topic: 'Thermodynamics',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'A reaction has ΔH = +40 kJ/mol and ΔS = +100 J/(mol·K). At what temperature does the reaction transition from non-spontaneous to spontaneous?',
    options: [
      { id: 'a', text: '400 K' },
      { id: 'b', text: '250 K' },
      { id: 'c', text: '300 K' },
      { id: 'd', text: '500 K' },
    ],
    correct_option_ids: ['a'],
    explanation: 'At equilibrium ΔG = 0 => ΔH - T ΔS = 0 => T = ΔH / ΔS. T = (40,000 J/mol) / (100 J/mol·K) = 400 K. For T > 400 K, ΔG becomes negative and spontaneous.',
    formula_hint: 'T_eq = ΔH / ΔS',
    default_marks: 2.0,
    section: 'Section B: Free Energy Calculations',
  },
  {
    subject: 'Chemistry',
    topic: 'Thermodynamics',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following thermodynamic quantities are state functions (independent of the path taken)?',
    options: [
      { id: 'a', text: 'Enthalpy (H)' },
      { id: 'b', text: 'Entropy (S)' },
      { id: 'c', text: 'Work (w)' },
      { id: 'd', text: 'Internal energy (U)' },
    ],
    correct_option_ids: ['a', 'b', 'd'],
    explanation: 'Enthalpy, entropy, internal energy, and Gibbs free energy depend solely on initial and final thermodynamic equilibrium states. Work and heat are path functions that vary with the trajectory taken.',
    formula_hint: 'State functions: ΔX = X_final - X_initial',
    default_marks: 2.0,
    section: 'Section A: Enthalpy & Spontaneity',
  },
  {
    subject: 'Chemistry',
    topic: 'Thermodynamics',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'The standard enthalpy of formation (Δ_f H°) of an element in its most stable standard reference state is zero by definition.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. By thermodynamic convention, Δ_f H° = 0 for pure elements in their standard state at 298.15 K and 1 bar (e.g. O₂(g), C(graphite), N₂(g), Br₂(l)).',
    formula_hint: 'Δ_f H°[element in reference state] = 0',
    default_marks: 1.0,
    section: 'Section A: Enthalpy & Spontaneity',
  },
  {
    subject: 'Chemistry',
    topic: 'Thermodynamics',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'State Hess’s Law of Constant Heat Summation and illustrate how it applies to multistep thermochemical cycles.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Hess’s Law states that the total enthalpy change for a chemical reaction is identical whether the reaction takes place in one single step or through a series of intermediate steps: ΔH_net = ∑ ΔH_steps. Because enthalpy is a state function, enthalpy changes can be added, subtracted, and manipulated algebraically according to thermochemical equations (e.g. Born-Haber cycle for lattice energy).',
    explanation: 'Enthalpy conservation in reaction paths allows determination of unknown formation enthalpies from known intermediate values.',
    formula_hint: 'ΔH_reaction = ∑ Δ_f H°(products) - ∑ Δ_f H°(reactants)',
    default_marks: 2.5,
    section: 'Section B: Free Energy Calculations',
  },

  // ============================================================================
  // 6. Equilibrium (7 Questions)
  // ============================================================================
  {
    subject: 'Chemistry',
    topic: 'Equilibrium',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the pH of a 0.001 M aqueous solution of strong hydrochloric acid (HCl) at 25 °C?',
    options: [
      { id: 'a', text: '1' },
      { id: 'b', text: '2' },
      { id: 'c', text: '3' },
      { id: 'd', text: '11' },
    ],
    correct_option_ids: ['c'],
    explanation: 'HCl completely dissociates: [H⁺] = 0.001 M = 1.0 × 10⁻³ M. pH = -log₁₀[H⁺] = -log₁₀(10⁻³) = 3.',
    formula_hint: 'pH = -log₁₀[H⁺]',
    default_marks: 1.0,
    section: 'Section A: Ionic Equilibrium',
  },
  {
    subject: 'Chemistry',
    topic: 'Equilibrium',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'For the exothermic synthesis of ammonia: N₂(g) + 3H₂(g) ⇌ 2NH₃(g) (ΔH < 0), which condition shifts equilibrium forward to increase yield?',
    options: [
      { id: 'a', text: 'Increasing temperature' },
      { id: 'b', text: 'Decreasing pressure' },
      { id: 'c', text: 'Increasing total pressure' },
      { id: 'd', text: 'Removing H₂ continuously' },
    ],
    correct_option_ids: ['c'],
    explanation: 'By Le Chatelier’s Principle, increasing pressure favors the side with fewer gas moles (4 moles of reactants vs 2 moles of product), driving equilibrium forward toward NH₃. Low temperature also favors exothermic forward reaction.',
    formula_hint: 'Le Chatelier: P ↑ shifts toward fewer moles of gas',
    default_marks: 1.5,
    section: 'Section B: Chemical Equilibrium & Le Chatelier',
  },
  {
    subject: 'Chemistry',
    topic: 'Equilibrium',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'The solubility product K_sp of AgCl is 1.8 × 10⁻¹⁰ at 25 °C. What is its molar solubility in a 0.1 M NaCl aqueous solution?',
    options: [
      { id: 'a', text: '1.34 × 10⁻⁵ M' },
      { id: 'b', text: '1.8 × 10⁻⁹ M' },
      { id: 'c', text: '1.8 × 10⁻¹¹ M' },
      { id: 'd', text: '3.6 × 10⁻¹⁰ M' },
    ],
    correct_option_ids: ['b'],
    explanation: 'AgCl(s) ⇌ Ag⁺ + Cl⁻. In 0.1 M NaCl, [Cl⁻] ≈ 0.1 M due to common ion effect. K_sp = [Ag⁺][Cl⁻] = s × 0.1 = 1.8 × 10⁻¹⁰ => s = 1.8 × 10⁻⁹ M.',
    formula_hint: 'K_sp = [Ag⁺][Cl⁻], s = K_sp / [Cl⁻]',
    default_marks: 2.0,
    section: 'Section A: Ionic Equilibrium',
  },
  {
    subject: 'Chemistry',
    topic: 'Equilibrium',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following conjugate acid-base pairs can form an effective buffer solution when mixed in equimolar amounts?',
    options: [
      { id: 'a', text: 'Acetic acid (CH₃COOH) and Sodium acetate (CH₃COONa)' },
      { id: 'b', text: 'Ammonium hydroxide (NH₄OH) and Ammonium chloride (NH₄Cl)' },
      { id: 'c', text: 'Hydrochloric acid (HCl) and Sodium chloride (NaCl)' },
      { id: 'd', text: 'Nitric acid (HNO₃) and Potassium nitrate (KNO₃)' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'A buffer requires a weak acid and its conjugate base (a) or a weak base and its conjugate acid (b). Strong acids like HCl and HNO₃ dissociate completely and do not provide conjugate equilibrium buffering reserve (c, d are false).',
    formula_hint: 'Henderson-Hasselbalch: pH = pK_a + log([A⁻]/[HA])',
    default_marks: 2.0,
    section: 'Section A: Ionic Equilibrium',
  },
  {
    subject: 'Chemistry',
    topic: 'Equilibrium',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Adding a catalyst to a reversible chemical reaction shifts the position of chemical equilibrium to favor the products.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['false'],
    explanation: 'False. A catalyst lowers activation energy equally for both forward and reverse reactions. It accelerates the rate at which equilibrium is reached but does not alter the equilibrium constant K_eq or equilibrium concentrations.',
    formula_hint: 'Catalyst changes kinetics (k_f, k_b), not thermodynamics (K_eq)',
    default_marks: 1.0,
    section: 'Section B: Chemical Equilibrium & Le Chatelier',
  },
  {
    subject: 'Chemistry',
    topic: 'Equilibrium',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'If K_c for A ⇌ B is 4, what is the equilibrium constant K_c’ for the reverse reaction 2B ⇌ 2A?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '0.0625',
    explanation: 'Reversing a reaction inverts K (1/4). Multiplying coefficients by 2 squares the equilibrium constant: K_c’ = (1/K)² = (1/4)² = 1/16 = 0.0625.',
    formula_hint: 'K_rev = 1 / K_fwd; K_n = (K)^n',
    default_marks: 1.5,
    section: 'Section B: Chemical Equilibrium & Le Chatelier',
  },
  {
    subject: 'Chemistry',
    topic: 'Equilibrium',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'State the relationship between standard Gibbs free energy change ΔG° and the thermodynamic equilibrium constant K. Explain what K > 1 implies.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'The fundamental relation is ΔG° = -RT ln K. When K > 1, ln K is positive, which makes ΔG° negative. This implies that under standard state conditions (all species at 1 M or 1 bar), the forward reaction is thermodynamically favorable and product formation predominates at equilibrium.',
    explanation: 'Direct link between thermodynamic driving force (free energy) and composition ratio at dynamic equilibrium.',
    formula_hint: 'ΔG° = - R T ln K',
    default_marks: 2.5,
    section: 'Section B: Chemical Equilibrium & Le Chatelier',
  },

  // ============================================================================
  // 7. Redox Reactions (6 Questions)
  // ============================================================================
  {
    subject: 'Chemistry',
    topic: 'Redox Reactions',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the oxidation state of Manganese in the permanganate ion (MnO₄⁻)?',
    options: [
      { id: 'a', text: '+4' },
      { id: 'b', text: '+6' },
      { id: 'c', text: '+7' },
      { id: 'd', text: '+2' },
    ],
    correct_option_ids: ['c'],
    explanation: 'Let oxidation state of Mn be x. Oxygen has -2: x + 4(-2) = -1 => x - 8 = -1 => x = +7.',
    formula_hint: '∑ Oxidation Numbers = Net Charge',
    default_marks: 1.0,
    section: 'Section A: Oxidation Numbers & Balancing',
  },
  {
    subject: 'Chemistry',
    topic: 'Redox Reactions',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the oxidation state of Chromium in potassium dichromate (K₂Cr₂O₇)?',
    options: [
      { id: 'a', text: '+3' },
      { id: 'b', text: '+6' },
      { id: 'c', text: '+7' },
      { id: 'd', text: '+4' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Potassium is +1, Oxygen is -2: 2(+1) + 2(Cr) + 7(-2) = 0 => 2 + 2(Cr) - 14 = 0 => 2(Cr) = 12 => Cr = +6.',
    formula_hint: '2(+1) + 2(x) + 7(-2) = 0',
    default_marks: 1.5,
    section: 'Section A: Oxidation Numbers & Balancing',
  },
  {
    subject: 'Chemistry',
    topic: 'Redox Reactions',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'In the acidic redox reaction: Cr₂O₇²⁻ + 14H⁺ + 6e⁻ → 2Cr³⁺ + 7H₂O, how many moles of Fe²⁺ are oxidized to Fe³⁺ by 1 mole of Cr₂O₇²⁻?',
    options: [
      { id: 'a', text: '1 mole' },
      { id: 'b', text: '3 moles' },
      { id: 'c', text: '6 moles' },
      { id: 'd', text: '7 moles' },
    ],
    correct_option_ids: ['c'],
    explanation: 'Each mole of Cr₂O₇²⁻ accepts 6 moles of electrons (Cr drops from +6 to +3, 2 × 3 = 6e⁻). Oxidation of Fe²⁺ to Fe³⁺ releases 1 electron: Fe²⁺ → Fe³⁺ + e⁻. To balance electrons, 6 moles of Fe²⁺ are required per mole of dichromate.',
    formula_hint: 'Cr₂O₇²⁻ + 6Fe²⁺ + 14H⁺ → 2Cr³⁺ + 6Fe³⁺ + 7H₂O',
    default_marks: 2.0,
    section: 'Section A: Oxidation Numbers & Balancing',
  },
  {
    subject: 'Chemistry',
    topic: 'Redox Reactions',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following chemical reactions represent disproportionation redox reactions?',
    options: [
      { id: 'a', text: '2H₂O₂ → 2H₂O + O₂' },
      { id: 'b', text: 'Cl₂ + 2OH⁻ → Cl⁻ + ClO⁻ + H₂O' },
      { id: 'c', text: 'Zn + 2HCl → ZnCl₂ + H₂' },
      { id: 'd', text: '2Na + Cl₂ → 2NaCl' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'In disproportionation, the same element is simultaneously oxidized and reduced. In H₂O₂, O (-1) goes to -2 in H₂O and 0 in O₂. In Cl₂ in base, Cl (0) goes to -1 in Cl⁻ and +1 in ClO⁻. Zn + HCl and Na + Cl₂ involve two separate reducing and oxidizing elements.',
    formula_hint: 'Disproportionation: same species oxidizes and reduces',
    default_marks: 2.0,
    section: 'Section B: Redox Mechanisms',
  },
  {
    subject: 'Chemistry',
    topic: 'Redox Reactions',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'In any redox reaction, the oxidizing agent is the chemical species that gains electrons and undergoes reduction.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. An oxidizing agent facilitates the oxidation of another substance by accepting electrons from it, thereby itself being reduced (decrease in oxidation state).',
    formula_hint: 'Oxidizing agent: electron acceptor (reduced)',
    default_marks: 1.0,
    section: 'Section A: Oxidation Numbers & Balancing',
  },
  {
    subject: 'Chemistry',
    topic: 'Redox Reactions',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What is the oxidation number of Oxygen in fluorine monoxide (OF₂)?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '+2',
    explanation: 'Because fluorine is more electronegative than oxygen, F is assigned an oxidation state of -1. In OF₂: x + 2(-1) = 0 => x = +2.',
    formula_hint: 'F is always -1 in compounds',
    default_marks: 1.0,
    section: 'Section A: Oxidation Numbers & Balancing',
  },

  // ============================================================================
  // 8. Organic Chemistry (7 Questions)
  // ============================================================================
  {
    subject: 'Chemistry',
    topic: 'Organic Chemistry',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the correct IUPAC name for CH₃-CH(CH₃)-CH₂-OH?',
    options: [
      { id: 'a', text: '2-methylpropan-1-ol' },
      { id: 'b', text: '1-methylpropan-2-ol' },
      { id: 'c', text: 'Isobutanol' },
      { id: 'd', text: 'Butan-2-ol' },
    ],
    correct_option_ids: ['a'],
    explanation: 'The principal functional group (-OH) takes lowest locant 1 on a three-carbon chain (propan-1-ol). Carbon-2 carries a methyl group, giving 2-methylpropan-1-ol.',
    formula_hint: 'Longest chain with -OH: propane; numbering from -OH end',
    default_marks: 1.0,
    section: 'Section A: Nomenclature & Isomerism',
  },
  {
    subject: 'Chemistry',
    topic: 'Organic Chemistry',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Which of the following organic carbocations exhibits the highest thermodynamic stability?',
    options: [
      { id: 'a', text: 'Methyl carbocation (CH₃⁺)' },
      { id: 'b', text: 'Ethyl carbocation (CH₃CH₂⁺)' },
      { id: 'c', text: 'Isopropyl carbocation ((CH₃)₂CH⁺)' },
      { id: 'd', text: 'tert-Butyl carbocation ((CH₃)₃C⁺)' },
    ],
    correct_option_ids: ['d'],
    explanation: 'The tertiary carbocation ((CH₃)₃C⁺) has 9 hyperconjugative α-hydrogens and three electron-donating inductive (+I) methyl groups that disperse the positive charge most effectively.',
    formula_hint: 'Carbocation stability: 3° > 2° > 1° > methyl (hyperconjugation)',
    default_marks: 1.5,
    section: 'Section B: Reaction Intermediates & Mechanisms',
  },
  {
    subject: 'Chemistry',
    topic: 'Organic Chemistry',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'Which pair of compounds represents enantiomers (non-superimposable mirror images)?',
    options: [
      { id: 'a', text: '(2R,3R)-tartaric acid and (2S,3S)-tartaric acid' },
      { id: 'b', text: '(2R,3R)-tartaric acid and meso-tartaric acid' },
      { id: 'c', text: 'cis-but-2-ene and trans-but-2-ene' },
      { id: 'd', text: 'Ethanol and dimethyl ether' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Enantiomers must have inverted stereocenters at all chiral carbons ((2R,3R) vs (2S,3S)). (2R,3R) and meso-tartaric acid are diastereomers (non-mirror image stereoisomers). cis/trans are geometrical isomers; ethanol/dimethyl ether are functional isomers.',
    formula_hint: 'Enantiomers: inversion of ALL stereocenters (R->S, S->R)',
    default_marks: 2.0,
    section: 'Section A: Nomenclature & Isomerism',
  },
  {
    subject: 'Chemistry',
    topic: 'Organic Chemistry',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following conditions must be satisfied for a compound to be classified as aromatic according to Hückel’s Rule?',
    options: [
      { id: 'a', text: 'Planar cyclic ring system' },
      { id: 'b', text: 'Complete conjugation of p-orbitals throughout the ring' },
      { id: 'c', text: 'Contains exactly (4n + 2) delocalized π electrons (where n is a non-negative integer)' },
      { id: 'd', text: 'Contains exactly 4n delocalized π electrons' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Hückel’s rule requires a planar, cyclic, fully conjugated ring with (4n + 2) π electrons (a, b, c). Systems with 4n π electrons are anti-aromatic and destabilized (d is false).',
    formula_hint: 'Hückel’s Rule: (4n + 2) π electrons, n = 0, 1, 2...',
    default_marks: 2.0,
    section: 'Section B: Reaction Intermediates & Mechanisms',
  },
  {
    subject: 'Chemistry',
    topic: 'Organic Chemistry',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'An SN2 nucleophilic substitution reaction proceeds with complete inversion of optical configuration (Walden inversion).',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. In an SN2 reaction, the incoming nucleophile attacks the electrophilic carbon from the backside directly opposite to the leaving group, causing an umbrella-like inversion of stereochemistry.',
    formula_hint: 'SN2: Backside attack => 100% Walden Inversion',
    default_marks: 1.0,
    section: 'Section B: Reaction Intermediates & Mechanisms',
  },
  {
    subject: 'Chemistry',
    topic: 'Organic Chemistry',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Name the reactive neutral intermediate with two non-bonding electrons and a sextet of valence electrons derived from diazomethane (formula :CH₂).',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Carbene',
    explanation: 'Carbenes (such as methylene :CH₂) are neutral divalent carbon intermediates having six valence electrons, acting as strong electrophiles.',
    formula_hint: 'Divalent carbon intermediate: :CR₂',
    default_marks: 1.5,
    section: 'Section B: Reaction Intermediates & Mechanisms',
  },
  {
    subject: 'Chemistry',
    topic: 'Organic Chemistry',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Differentiate between an inductive effect (I effect) and an electromeric effect (E effect) in organic reaction mechanisms.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Inductive effect is a permanent polarization of σ bonds caused by differences in electronegativity along a carbon chain that diminishes with distance and does not require an external reagent. Electromeric effect is a temporary phenomenon occurring in multiple bonds (π bonds) involving complete transfer of a shared π-electron pair to one of the atoms at the demand of an attacking electrophile or nucleophile, vanishing when the reagent is removed.',
    explanation: 'Inductive involves partial σ-displacement permanently; electromeric involves total π-displacement temporarily.',
    formula_hint: 'Inductive: σ-bond permanent; Electromeric: π-bond temporary',
    default_marks: 2.5,
    section: 'Section B: Reaction Intermediates & Mechanisms',
  },

  // ============================================================================
  // 9. Hydrocarbons (6 Questions)
  // ============================================================================
  {
    subject: 'Chemistry',
    topic: 'Hydrocarbons',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'According to Markovnikov’s Rule, what is the major organic product when propene reacts with gaseous hydrogen bromide (HBr)?',
    options: [
      { id: 'a', text: '1-bromopropane' },
      { id: 'b', text: '2-bromopropane' },
      { id: 'c', text: '1,2-dibromopropane' },
      { id: 'd', text: 'Cyclopropane' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Markovnikov’s rule states that the electrophile (H⁺) adds to the double-bond carbon with more hydrogen atoms to generate the more stable secondary carbocation (CH₃-CH⁺-CH₃). Bromide then attacks C-2, producing 2-bromopropane.',
    formula_hint: 'CH₃-CH=CH₂ + HBr → CH₃-CH(Br)-CH₃',
    default_marks: 1.0,
    section: 'Section A: Alkenes & Addition Mechanisms',
  },
  {
    subject: 'Chemistry',
    topic: 'Hydrocarbons',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Which reagent combination causes anti-Markovnikov addition of HBr to an unsymmetrical alkene?',
    options: [
      { id: 'a', text: 'HBr in carbon tetrachloride (CCl₄)' },
      { id: 'b', text: 'HBr in the presence of organic peroxides (R-O-O-R)' },
      { id: 'c', text: 'Aqueous HBr' },
      { id: 'd', text: 'HBr with AlCl₃ catalyst' },
    ],
    correct_option_ids: ['b'],
    explanation: 'The Peroxide Effect (Kharasch effect) operates via a free-radical mechanism. Bromine radical (Br•) adds first to form the more stable secondary radical, resulting in anti-Markovnikov addition (1-bromopropane).',
    formula_hint: 'Alkene + HBr + Peroxide → Anti-Markovnikov bromide',
    default_marks: 1.5,
    section: 'Section A: Alkenes & Addition Mechanisms',
  },
  {
    subject: 'Chemistry',
    topic: 'Hydrocarbons',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'What are the products of reductive ozonolysis (O₃ followed by Zn/H₂O) of 2-methylbut-2-ene?',
    options: [
      { id: 'a', text: 'Acetone and Acetaldehyde (propan-2-one and ethanal)' },
      { id: 'b', text: 'Two moles of ethanal' },
      { id: 'c', text: 'Acetone and Formaldehyde' },
      { id: 'd', text: 'Acetic acid and Propanoic acid' },
    ],
    correct_option_ids: ['a'],
    explanation: '2-methylbut-2-ene is (CH₃)₂C=CH-CH₃. Cleaving the double bond reductively with Zn/H₂O yields (CH₃)₂C=O (propan-2-one / acetone) and O=CH-CH₃ (ethanal / acetaldehyde).',
    formula_hint: 'R₁R₂C=CHR₃ + O₃/Zn → R₁R₂C=O + R₃CHO',
    default_marks: 2.0,
    section: 'Section B: Ozonolysis & Cleavage Reactions',
  },
  {
    subject: 'Chemistry',
    topic: 'Hydrocarbons',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following compounds react with ammoniacal cuprous chloride or Tollens’ reagent to form a distinctive precipitate due to acidic terminal hydrogen?',
    options: [
      { id: 'a', text: 'Propyne (CH₃-C≡CH)' },
      { id: 'b', text: 'Ethyne (HC≡CH)' },
      { id: 'c', text: 'But-2-yne (CH₃-C≡C-CH₃)' },
      { id: 'd', text: 'Propene (CH₃-CH=CH₂)' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'Terminal alkynes (propyne, ethyne) have acidic sp-hybridized C-H bonds that react with heavy metal salts (Tollens’, ammoniacal Cu₂Cl₂) to form insoluble metal acetylides. Internal alkynes like but-2-yne lack terminal acidic hydrogen.',
    formula_hint: 'R-C≡C-H + Ag⁺ → R-C≡C-Ag (white precipitate)',
    default_marks: 2.0,
    section: 'Section A: Alkynes & Aromatic Systems',
  },
  {
    subject: 'Chemistry',
    topic: 'Hydrocarbons',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Benzene readily undergoes electrophilic substitution reactions rather than electrophilic addition reactions in order to preserve its resonance stabilization energy.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Addition across benzene’s double bonds would destroy aromaticity and forfeit ~150 kJ/mol of resonance energy. Electrophilic aromatic substitution restores the intact aromatic sextet.',
    formula_hint: 'Preservation of aromatic sextet (150 kJ/mol resonance energy)',
    default_marks: 1.0,
    section: 'Section A: Alkynes & Aromatic Systems',
  },
  {
    subject: 'Chemistry',
    topic: 'Hydrocarbons',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'State the mechanism of Friedel-Crafts alkylation of benzene with chloromethane in the presence of anhydrous AlCl₃, identifying the electrophile.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Anhydrous AlCl₃ acts as a Lewis acid and extracts the chlorine atom from chloromethane to form a methyl carbocation electrophile: CH₃Cl + AlCl₃ ⇌ CH₃⁺ + AlCl₄⁻. The electrophilic methyl cation attacks the π cloud of benzene to generate a resonance-stabilized arenium ion (sigma complex). Finally, AlCl₄⁻ abstracts the ring proton to restore aromaticity, yielding toluene (methylbenzene) and regenerating AlCl₃ with HCl as byproduct.',
    explanation: 'Classic electrophilic aromatic substitution where a Lewis acid catalyst generates a reactive carbocation.',
    formula_hint: 'C₆H₆ + CH₃Cl --(AlCl₃)--> C₆H₅CH₃ + HCl',
    default_marks: 2.5,
    section: 'Section B: Electrophilic Aromatic Substitution',
  },

  // ============================================================================
  // 10. Solutions (7 Questions)
  // ============================================================================
  {
    subject: 'Chemistry',
    topic: 'Solutions',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which of the following colligative properties is most commonly employed for determining the molecular masses of polymers and biomolecules like proteins?',
    options: [
      { id: 'a', text: 'Relative lowering of vapor pressure' },
      { id: 'b', text: 'Depression of freezing point' },
      { id: 'c', text: 'Elevation of boiling point' },
      { id: 'd', text: 'Osmotic pressure' },
    ],
    correct_option_ids: ['d'],
    explanation: 'Osmotic pressure (Π = CRT) produces measurable magnitudes even at very low molar concentrations and can be safely measured at room temperature without denaturing delicate biomolecules.',
    formula_hint: 'Π = C R T = (w₂ R T) / (M₂ V)',
    default_marks: 1.0,
    section: 'Section A: Colligative Properties',
  },
  {
    subject: 'Chemistry',
    topic: 'Solutions',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the van ’t Hoff factor (i) for an aqueous solution of potassium sulfate (K₂SO₄) assuming 100% complete ionic dissociation?',
    options: [
      { id: 'a', text: '1' },
      { id: 'b', text: '2' },
      { id: 'c', text: '3' },
      { id: 'd', text: '4' },
    ],
    correct_option_ids: ['c'],
    explanation: 'Potassium sulfate dissociates according to: K₂SO₄(aq) → 2K⁺(aq) + SO₄²⁻(aq), producing 2 + 1 = 3 moles of ions per mole of salt dissolved. For complete dissociation, i = 3.',
    formula_hint: 'i = 1 + (n - 1)α, with α = 1 => i = n = 3',
    default_marks: 1.5,
    section: 'Section A: Colligative Properties',
  },
  {
    subject: 'Chemistry',
    topic: 'Solutions',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'Pure benzene freezes at 5.5 °C. When 1.8 g of a non-volatile solute is dissolved in 90 g of benzene (K_f = 5.12 K·kg/mol), the freezing point drops to 4.48 °C. What is the molar mass of the solute?',
    options: [
      { id: 'a', text: '50 g/mol' },
      { id: 'b', text: '100.4 g/mol' },
      { id: 'c', text: '128.0 g/mol' },
      { id: 'd', text: '204.8 g/mol' },
    ],
    correct_option_ids: ['b'],
    explanation: 'ΔT_f = 5.50 - 4.48 = 1.02 K. Molality m = ΔT_f / K_f = 1.02 / 5.12 ≈ 0.1992 mol/kg. Solute moles n = m × 0.090 kg = 0.01793 mol. Molar mass M = 1.8 g / 0.01793 mol ≈ 100.4 g/mol.',
    formula_hint: 'M₂ = (1000 · K_f · w₂) / (ΔT_f · w₁)',
    default_marks: 2.0,
    section: 'Section B: Quantitative Solution Properties',
  },
  {
    subject: 'Chemistry',
    topic: 'Solutions',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following binary liquid mixtures exhibit negative deviations from Raoult’s Law due to stronger solute-solvent interactions (A-B > A-A, B-B)?',
    options: [
      { id: 'a', text: 'Chloroform and Acetone' },
      { id: 'b', text: 'Phenol and Aniline' },
      { id: 'c', text: 'Ethanol and Acetone' },
      { id: 'd', text: 'Benzene and Toluene' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'Chloroform and acetone form intermolecular hydrogen bonds between the acidic C-H of chloroform and the carbonyl oxygen of acetone, causing negative deviation (ΔV_mix < 0, ΔH_mix < 0). Phenol and aniline form strong H-bonds. Ethanol/acetone shows positive deviation; benzene/toluene is ideal.',
    formula_hint: 'Negative deviation: P_total < P_A° x_A + P_B° x_B',
    default_marks: 2.0,
    section: 'Section A: Colligative Properties',
  },
  {
    subject: 'Chemistry',
    topic: 'Solutions',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'According to Henry’s Law, the solubility of a gas in a liquid is directly proportional to the partial pressure of the gas above the liquid.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Henry’s Law states that at constant temperature, the mole fraction x or concentration of a dissolved gas is proportional to its partial pressure P: P = K_H · x.',
    formula_hint: 'p = K_H · x',
    default_marks: 1.0,
    section: 'Section A: Colligative Properties',
  },
  {
    subject: 'Chemistry',
    topic: 'Solutions',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What is the molarity (M) of a 1.0 L aqueous solution containing 58.5 g of dissolved NaCl (molar mass = 58.5 g/mol)?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '1',
    explanation: 'Moles of NaCl = 58.5 g / 58.5 g/mol = 1.0 mol. Molarity = 1.0 mol / 1.0 L = 1.0 M.',
    formula_hint: 'M = n / V (L)',
    default_marks: 1.0,
    section: 'Section B: Quantitative Solution Properties',
  },
  {
    subject: 'Chemistry',
    topic: 'Solutions',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'State Raoult’s Law for a volatile binary solution and explain what characterizes an ideal solution in terms of thermodynamic mixing properties.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Raoult’s Law states that for a solution of volatile liquids, the partial vapor pressure of each component is equal to its mole fraction multiplied by the vapor pressure of the pure component: P_A = x_A · P_A°. An ideal solution strictly obeys Raoult’s Law across all concentrations and is characterized by: 1. Zero enthalpy of mixing (ΔH_mix = 0); 2. Zero volume change on mixing (ΔV_mix = 0); 3. Intermolecular forces between solute and solvent molecules (A-B) are identical in magnitude to A-A and B-B forces.',
    explanation: 'Ideal behavior stems from energetic and structural equivalence of interacting molecular pairs.',
    formula_hint: 'P_total = x_A P_A° + x_B P_B°',
    default_marks: 2.5,
    section: 'Section A: Colligative Properties',
  },

  // ============================================================================
  // 11. Electrochemistry (6 Questions)
  // ============================================================================
  {
    subject: 'Chemistry',
    topic: 'Electrochemistry',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the standard cell potential (E°_cell) for the Daniell cell: Zn(s) | Zn²⁺(1M) || Cu²⁺(1M) | Cu(s)? (Given: E°(Zn²⁺/Zn) = -0.76 V, E°(Cu²⁺/Cu) = +0.34 V)',
    options: [
      { id: 'a', text: '+0.42 V' },
      { id: 'b', text: '+1.10 V' },
      { id: 'c', text: '-1.10 V' },
      { id: 'd', text: '+0.76 V' },
    ],
    correct_option_ids: ['b'],
    explanation: 'E°_cell = E°_cathode - E°_anode = E°(Cu²⁺/Cu) - E°(Zn²⁺/Zn) = +0.34 V - (-0.76 V) = +0.34 + 0.76 = +1.10 V.',
    formula_hint: 'E°_cell = E°_cathode - E°_anode',
    default_marks: 1.0,
    section: 'Section A: Galvanic Cells & Nernst Equation',
  },
  {
    subject: 'Chemistry',
    topic: 'Electrochemistry',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'According to the Nernst equation at 298 K, what happens to the electrode potential of the half-cell Cu²⁺ + 2e⁻ → Cu when [Cu²⁺] increases tenfold?',
    options: [
      { id: 'a', text: 'Increases by 0.0591 V' },
      { id: 'b', text: 'Increases by 0.0295 V' },
      { id: 'c', text: 'Decreases by 0.0295 V' },
      { id: 'd', text: 'Decreases by 0.0591 V' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Nernst equation: E = E° - (0.0591/n) log(1/[Cu²⁺]) = E° + (0.0591/2) log[Cu²⁺]. Increasing [Cu²⁺] by a factor of 10 adds (0.0591/2) log(10) = 0.0295 V.',
    formula_hint: 'E = E° + (0.0591 / n) · log[Mⁿ⁺]',
    default_marks: 1.5,
    section: 'Section A: Galvanic Cells & Nernst Equation',
  },
  {
    subject: 'Chemistry',
    topic: 'Electrochemistry',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'How much electric charge (in Coulombs) is required to reduce 1 mole of aluminum ions (Al³⁺) to elemental aluminum metal? (F ≈ 96500 C/mol)',
    options: [
      { id: 'a', text: '96,500 C' },
      { id: 'b', text: '193,000 C' },
      { id: 'c', text: '289,500 C' },
      { id: 'd', text: '32,166 C' },
    ],
    correct_option_ids: ['c'],
    explanation: 'Reduction reaction: Al³⁺ + 3e⁻ → Al. 1 mole of Al³⁺ requires 3 moles of electrons. Q = n · F = 3 × 96,500 C = 289,500 C.',
    formula_hint: 'Q = n · F',
    default_marks: 2.0,
    section: 'Section B: Electrolysis & Faraday’s Laws',
  },
  {
    subject: 'Chemistry',
    topic: 'Electrochemistry',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following statements regarding Kohlrausch’s Law of Independent Migration of Ions are correct?',
    options: [
      { id: 'a', text: 'Molar conductivity at infinite dilution of an electrolyte equals the sum of individual ionic molar conductivities.' },
      { id: 'b', text: 'It enables calculation of limiting molar conductivity (Λ°_m) for weak electrolytes like acetic acid.' },
      { id: 'c', text: 'It applies only to non-aqueous solvent systems.' },
      { id: 'd', text: 'It can be used to calculate degree of dissociation α = Λ_m / Λ°_m.' },
    ],
    correct_option_ids: ['a', 'b', 'd'],
    explanation: 'Kohlrausch’s law states Λ°_m = ν₊ λ°₊ + ν₋ λ°₋ (a), allowing determination of Λ°_m for weak electrolytes from strong electrolyte combinations (b), and calculating α = Λ_m / Λ°_m (d). It applies universally to aqueous electrolyte solutions (c is false).',
    formula_hint: 'Λ°_m = ν₊ λ°₊ + ν₋ λ°₋',
    default_marks: 2.0,
    section: 'Section B: Conductance & Electrolysis',
  },
  {
    subject: 'Chemistry',
    topic: 'Electrochemistry',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'In an electrolytic cell, oxidation occurs at the anode while reduction occurs at the cathode.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. By universal definition (An Ox, Red Cat), oxidation always occurs at the anode and reduction always occurs at the cathode in both galvanic and electrolytic cells.',
    formula_hint: 'Anode = Oxidation; Cathode = Reduction',
    default_marks: 1.0,
    section: 'Section A: Galvanic Cells & Nernst Equation',
  },
  {
    subject: 'Chemistry',
    topic: 'Electrochemistry',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'Explain the purpose and functioning of a salt bridge in a galvanic cell.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'A salt bridge contains an inert electrolyte (such as KCl or KNO₃ in agar-agar gel) whose cations and anions have approximately equal ionic mobilities. Its two essential functions are: 1. Completing the internal electrical circuit by allowing ionic transport between half-cells; 2. Maintaining electrical neutrality in both anodic and cathodic compartments by migrating anions to the anode to neutralize excess positive ions and cations to the cathode to replace consumed cations, preventing liquid junction potential buildup.',
    explanation: 'Prevents charge polarization from prematurely halting the galvanic redox reaction.',
    formula_hint: 'Preserves electroneutrality: K⁺ migrates to cathode, Cl⁻ to anode',
    default_marks: 2.5,
    section: 'Section A: Galvanic Cells & Nernst Equation',
  },
];
