/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { CurriculumQuestion } from './types.js';

export const COMPUTER_SCIENCE_QUESTIONS: CurriculumQuestion[] = [
  // ============================================================================
  // 1. Programming Fundamentals (9 Questions)
  // ============================================================================
  {
    subject: 'Computer Science',
    topic: 'Programming Fundamentals',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which programming paradigm emphasizes immutable data, pure functions, and the elimination of side effects?',
    options: [
      { id: 'a', text: 'Object-Oriented Programming' },
      { id: 'b', text: 'Functional Programming' },
      { id: 'c', text: 'Imperative Programming' },
      { id: 'd', text: 'Procedural Programming' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Functional programming treats computation as evaluation of mathematical functions, avoiding state changes, mutable data structures, and side effects.',
    formula_hint: 'Pure functions: f(x) always yields identical output for x',
    default_marks: 1.0,
    section: 'Section A: Paradigms & Core Principles',
  },
  {
    subject: 'Computer Science',
    topic: 'Programming Fundamentals',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the primary difference between pass-by-value and pass-by-reference parameter passing mechanisms?',
    options: [
      { id: 'a', text: 'Pass-by-value copies the argument data so modifications do not affect the caller; pass-by-reference passes memory addresses allowing in-place mutation' },
      { id: 'b', text: 'Pass-by-reference is only available in interpreted languages' },
      { id: 'c', text: 'Pass-by-value allocates memory on heap; pass-by-reference allocates on stack' },
      { id: 'd', text: 'Pass-by-value passes pointers while pass-by-reference passes values' },
    ],
    correct_option_ids: ['a'],
    explanation: 'In pass-by-value, the formal parameter receives a copy of the actual argument’s value. In pass-by-reference, the parameter references the original memory location directly.',
    formula_hint: 'Call-by-value: copy; Call-by-reference: alias/pointer',
    default_marks: 1.5,
    section: 'Section A: Paradigms & Core Principles',
  },
  {
    subject: 'Computer Science',
    topic: 'Programming Fundamentals',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'In compiler design, what is the role of lexical analysis (scanning) in the translation pipeline?',
    options: [
      { id: 'a', text: 'Converts raw character source streams into a linear stream of atomic tokens' },
      { id: 'b', text: 'Constructs an Abstract Syntax Tree (AST) from grammar rules' },
      { id: 'c', text: 'Performs type inference and semantic type checking' },
      { id: 'd', text: 'Generates target assembly code from three-address code' },
    ],
    correct_option_ids: ['a'],
    explanation: 'The lexical analyzer reads source code character-by-character, strips whitespace/comments, and groups character sequences into tokens matching regular expressions.',
    formula_hint: 'Source characters → Lexer → Token stream → Parser → AST',
    default_marks: 2.0,
    section: 'Section B: Compilation & Runtime',
  },
  {
    subject: 'Computer Science',
    topic: 'Programming Fundamentals',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following are foundational pillars of Object-Oriented Programming (OOP)?',
    options: [
      { id: 'a', text: 'Encapsulation' },
      { id: 'b', text: 'Inheritance' },
      { id: 'c', text: 'Polymorphism' },
      { id: 'd', text: 'Static single assignment' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'The core OOP principles are Encapsulation (data hiding), Inheritance (code reuse), Polymorphism (multiple implementations), and Abstraction. Static single assignment is a compiler IR technique.',
    formula_hint: 'OOP pillars: Encapsulation, Abstraction, Inheritance, Polymorphism',
    default_marks: 2.0,
    section: 'Section A: Paradigms & Core Principles',
  },
  {
    subject: 'Computer Science',
    topic: 'Programming Fundamentals',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'In strongly typed statically checked languages like Java or C++, variable data types are resolved and verified at compile-time rather than runtime.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Static typing performs type checking at compile-time, catching type mismatch errors prior to execution, whereas dynamic typing checks types at runtime.',
    formula_hint: 'Static typing: compile-time check; Dynamic: runtime check',
    default_marks: 1.0,
    section: 'Section A: Paradigms & Core Principles',
  },
  {
    subject: 'Computer Science',
    topic: 'Programming Fundamentals',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What software design principle states that software entities (classes, modules) should be open for extension, but closed for modification?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Open-Closed Principle',
    explanation: 'The Open-Closed Principle (the "O" in SOLID) requires that module behavior can be extended via polymorphism or inheritance without editing existing, tested source code.',
    formula_hint: 'SOLID principles: S, O, L, I, D',
    default_marks: 1.5,
    section: 'Section A: Paradigms & Core Principles',
  },
  {
    subject: 'Computer Science',
    topic: 'Programming Fundamentals',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What segment of program memory stores local variables and handles function call return frames in a LIFO manner?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Call stack',
    explanation: 'The call stack allocates activation records (stack frames) for local variables and return addresses, unwinding automatically when functions return.',
    formula_hint: 'Stack: LIFO function frames; Heap: dynamic allocation',
    default_marks: 1.0,
    section: 'Section B: Compilation & Runtime',
  },
  {
    subject: 'Computer Science',
    topic: 'Programming Fundamentals',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the difference between compile-time (static) polymorphism and runtime (dynamic) polymorphism in C++ or Java.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Compile-time (static) polymorphism is resolved during compilation and is achieved through function overloading and operator overloading (or C++ templates); the compiler binds the function call to the specific signature based on static parameter types (early binding). Runtime (dynamic) polymorphism is resolved during program execution through method overriding and virtual functions; the runtime environment resolves the method call based on the dynamic runtime type of the underlying object using virtual method tables (vtable and vptr, late binding).',
    explanation: 'Static uses early binding via signatures; dynamic uses late binding via vtables across inheritance hierarchies.',
    formula_hint: 'Overloading = Static/Early binding; Overriding = Dynamic/Late binding (vtable)',
    default_marks: 2.5,
    section: 'Section A: Paradigms & Core Principles',
  },
  {
    subject: 'Computer Science',
    topic: 'Programming Fundamentals',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'Describe the five SOLID design principles of object-oriented architecture and explain how following them enhances code maintainability.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '1. Single Responsibility Principle (SRP): A class should have only one reason to change, encapsulating a single well-defined responsibility. 2. Open-Closed Principle (OCP): Classes should be open for extension but closed for modification, achieved through interfaces and abstract base classes. 3. Liskov Substitution Principle (LSP): Subtypes must be substitutable for their base types without altering program correctness or violating contracts. 4. Interface Segregation Principle (ISP): Clients should not be forced to depend on interfaces they do not use; lean, cohesive interfaces are preferred over fat monolithic ones. 5. Dependency Inversion Principle (DIP): High-level modules should not depend on low-level modules; both should depend on abstractions. Adhering to SOLID minimizes tight coupling, maximizes modularity, isolates changes, simplifies unit testing, and reduces technical debt in evolving software systems.',
    explanation: 'SOLID architectural guidelines enforce loose coupling and high cohesion in enterprise software design.',
    formula_hint: 'SOLID = SRP, OCP, LSP, ISP, DIP',
    default_marks: 4.0,
    section: 'Section A: Paradigms & Core Principles',
  },

  // ============================================================================
  // 2. Python (9 Questions)
  // ============================================================================
  {
    subject: 'Computer Science',
    topic: 'Python',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which of the following built-in Python data types is immutable?',
    options: [
      { id: 'a', text: 'List' },
      { id: 'b', text: 'Dictionary' },
      { id: 'c', text: 'Tuple' },
      { id: 'd', text: 'Set' },
    ],
    correct_option_ids: ['c'],
    explanation: 'Tuples (and strings, integers, floats, frozensets) are immutable in Python; their contents cannot be altered, appended, or reassigned after creation without generating a new object.',
    formula_hint: 'Immutable types: int, float, str, tuple, frozenset',
    default_marks: 1.0,
    section: 'Section A: Python Core & Data Structures',
  },
  {
    subject: 'Computer Science',
    topic: 'Python',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What will be the output of the expression `[x**2 for x in range(5) if x % 2 != 0]` in Python?',
    options: [
      { id: 'a', text: '[1, 9]' },
      { id: 'b', text: '[0, 4, 16]' },
      { id: 'c', text: '[1, 4, 9]' },
      { id: 'd', text: '[1, 9, 25]' },
    ],
    correct_option_ids: ['a'],
    explanation: 'range(5) gives 0, 1, 2, 3, 4. The odd numbers (x % 2 != 0) are 1 and 3. Squaring them yields [1² = 1, 3² = 9].',
    formula_hint: 'List comprehension: [expr for var in iterable if condition]',
    default_marks: 1.5,
    section: 'Section A: Python Core & Data Structures',
  },
  {
    subject: 'Computer Science',
    topic: 'Python',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'How does CPython’s Global Interpreter Lock (GIL) impact multithreaded CPU-bound Python programs?',
    options: [
      { id: 'a', text: 'It prevents multiple native threads from executing Python bytecode simultaneously on separate CPU cores' },
      { id: 'b', text: 'It automatically distributes bytecode across multiple CPU sockets' },
      { id: 'c', text: 'It halts all I/O network operations when threads switch' },
      { id: 'd', text: 'It guarantees lock-free concurrent writes to dictionaries' },
    ],
    correct_option_ids: ['a'],
    explanation: 'CPython uses the GIL to ensure thread-safe memory management (reference counts). Because only one thread holds the GIL to execute bytecode at any instant, CPU-bound tasks cannot achieve true multi-core parallelism with threading (requiring multiprocessing instead).',
    formula_hint: 'GIL restricts bytecode execution to one native thread at a time',
    default_marks: 2.0,
    section: 'Section B: Advanced Python & Memory Model',
  },
  {
    subject: 'Computer Science',
    topic: 'Python',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following functions or constructs create lazy generators in Python without allocating the entire collection in memory?',
    options: [
      { id: 'a', text: 'A function containing the `yield` keyword' },
      { id: 'b', text: 'Generator expressions enclosed in parentheses: `(x*2 for x in range(1000))`' },
      { id: 'c', text: 'List comprehension: `[x*2 for x in range(1000)]`' },
      { id: 'd', text: '`itertools.count()`' },
    ],
    correct_option_ids: ['a', 'b', 'd'],
    explanation: 'Functions with yield produce generator objects (a), parenthesized comprehensions are generator expressions (b), and itertools creates lazy infinite iterators (d). List comprehensions eagerly materialize the whole list in RAM.',
    formula_hint: 'yield creates lazy generator objects that yield values via next()',
    default_marks: 2.0,
    section: 'Section A: Python Core & Data Structures',
  },
  {
    subject: 'Computer Science',
    topic: 'Python',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'In Python, default function argument values are evaluated once when the function definition is executed, not each time the function is called.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Default arguments are evaluated at function definition time, making mutable default arguments (like `def func(lst=[]):`) persist across multiple function invocations.',
    formula_hint: 'Mutable defaults (e.g. `def f(arg=[])`) retain state across calls',
    default_marks: 1.0,
    section: 'Section A: Python Core & Data Structures',
  },
  {
    subject: 'Computer Science',
    topic: 'Python',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What special dunder method must be implemented on a Python class to support the context manager protocol using the `with` statement alongside `__exit__`?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '__enter__',
    explanation: 'The context management protocol requires implementing `__enter__(self)` (which initializes the resource and returns the target) and `__exit__(self, exc_type, exc_val, exc_tb)` (which cleans up resources).',
    formula_hint: 'Context managers implement `__enter__` and `__exit__`',
    default_marks: 1.0,
    section: 'Section B: Advanced Python & Memory Model',
  },
  {
    subject: 'Computer Science',
    topic: 'Python',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What built-in Python module provides higher-order functions that act on or return other functions, such as `lru_cache` and `partial`?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'functools',
    explanation: 'The `functools` standard library module contains tools for functional programming patterns, memoization (`@lru_cache`), function composition, and partial application.',
    formula_hint: 'import functools; @functools.lru_cache',
    default_marks: 1.0,
    section: 'Section B: Advanced Python & Memory Model',
  },
  {
    subject: 'Computer Science',
    topic: 'Python',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain how decorators work in Python and write the structure of a function decorator that measures execution time.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'A Python decorator is a higher-order function that takes another function as an argument, extends or alters its behavior without modifying its source code, and returns a new callable wrapper. Typical structure:\n```python\nimport time\nfrom functools import wraps\n\ndef time_it(func):\n    @wraps(func)\n    def wrapper(*args, **kwargs):\n        start = time.perf_counter()\n        result = func(*args, **kwargs)\n        print(f"{func.__name__} took {time.perf_counter() - start:.4f}s")\n        return result\n    return wrapper\n```',
    explanation: 'Syntactic sugar `@decorator` transforms `func = decorator(func)` using closure and callable wrapper.',
    formula_hint: '@decorator => func = decorator(func)',
    default_marks: 2.5,
    section: 'Section B: Advanced Python & Memory Model',
  },
  {
    subject: 'Computer Science',
    topic: 'Python',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'Describe Python’s memory management model, detailing reference counting, cyclic garbage collection, and memory pooling via PyMalloc.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'CPython employs a multi-tiered memory architecture: 1. Reference Counting: Every Python object header (`PyObject`) stores an `ob_refcnt`. When an object is referenced, its count increments; when a reference goes out of scope or is deleted, it decrements. When `ob_refcnt` hits 0, deallocation is instantaneous. 2. Cyclic Garbage Collector (gc module): Reference counting cannot reclaim cyclic references (e.g. A references B, B references A). CPython uses a generational cyclic collector that partitions heap objects into three generations (G0, G1, G2). It uses a pointer traversal algorithm to isolate and deallocate unreferenced isolated reference cycles. 3. PyMalloc (Arena/Pool/Block allocator): To avoid frequent, fragmented OS malloc calls for small allocations (≤512 bytes), CPython uses PyMalloc to carve 256 KB Arenas into 4 KB Pools consisting of uniform fixed-size memory Blocks.',
    explanation: 'CPython combines deterministic immediate ref-count destruction with generational cycle detection and small-object arena pooling.',
    formula_hint: 'Memory = Ref Counting + Generational GC + PyMalloc Arenas',
    default_marks: 4.0,
    section: 'Section B: Advanced Python & Memory Model',
  },

  // ============================================================================
  // 3. Data Structures (9 Questions)
  // ============================================================================
  {
    subject: 'Computer Science',
    topic: 'Data Structures',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the average time complexity for searching an element in a balanced Binary Search Tree (such as an AVL or Red-Black tree) with n nodes?',
    options: [
      { id: 'a', text: 'O(1)' },
      { id: 'b', text: 'O(log n)' },
      { id: 'c', text: 'O(n)' },
      { id: 'd', text: 'O(n log n)' },
    ],
    correct_option_ids: ['b'],
    explanation: 'A balanced binary search tree maintains a height bounded strictly by O(log n). Each comparison at a node halves the search space, yielding O(log n) search, insertion, and deletion.',
    formula_hint: 'Tree height h = O(log n) => Time = O(h) = O(log n)',
    default_marks: 1.0,
    section: 'Section A: Trees & Graphs',
  },
  {
    subject: 'Computer Science',
    topic: 'Data Structures',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the worst-case time complexity of inserting a key into a hash table that resolves collisions using separate chaining with singly linked lists?',
    options: [
      { id: 'a', text: 'O(1)' },
      { id: 'b', text: 'O(log n)' },
      { id: 'c', text: 'O(n)' },
      { id: 'd', text: 'O(n²)' },
    ],
    correct_option_ids: ['c'],
    explanation: 'In the worst case, an adversarial hash function maps all n keys to the identical bucket. The bucket degenerates into a linked list of length n, requiring O(n) traversal to verify duplicates before insertion.',
    formula_hint: 'Average case = O(1); Worst case (all keys collide) = O(n)',
    default_marks: 1.5,
    section: 'Section B: Linear Structures & Hashing',
  },
  {
    subject: 'Computer Science',
    topic: 'Data Structures',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'In a Red-Black tree with n nodes, what is the maximum possible height of the tree?',
    options: [
      { id: 'a', text: 'log₂(n)' },
      { id: 'b', text: '2 log₂(n + 1)' },
      { id: 'c', text: '3 log₂(n)' },
      { id: 'd', text: 'n / 2' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Because every simple path from root to leaf has the same black-height and no two red nodes can appear consecutively, the longest path (alternating red-black) is at most twice the shortest path (all black), bounding total height to at most 2 log₂(n + 1).',
    formula_hint: 'h ≤ 2 log₂(n + 1)',
    default_marks: 2.0,
    section: 'Section A: Trees & Graphs',
  },
  {
    subject: 'Computer Science',
    topic: 'Data Structures',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following data structures can be used to efficiently implement an abstract Priority Queue?',
    options: [
      { id: 'a', text: 'Binary Min/Max Heap' },
      { id: 'b', text: 'Fibonacci Heap' },
      { id: 'c', text: 'Self-balancing Binary Search Tree' },
      { id: 'd', text: 'FIFO circular ring buffer' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Binary heaps, Fibonacci heaps, and balanced BSTs allow logarithmic insertion and priority extraction. A circular FIFO buffer maintains insertion order, not priority order.',
    formula_hint: 'Heaps and balanced BSTs provide priority ordering in O(log n)',
    default_marks: 2.0,
    section: 'Section A: Trees & Graphs',
  },
  {
    subject: 'Computer Science',
    topic: 'Data Structures',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'A singly linked list allows O(1) worst-case time insertion at the beginning of the list (head).',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Prepending to a linked list only requires setting new_node.next = head and head = new_node, taking constant O(1) time regardless of list size.',
    formula_hint: 'Head insertion requires 2 pointer reassignments = O(1)',
    default_marks: 1.0,
    section: 'Section B: Linear Structures & Hashing',
  },
  {
    subject: 'Computer Science',
    topic: 'Data Structures',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'In a complete binary tree stored in an array indexed from 0, what is the index of the left child of node at index i?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '2i + 1',
    explanation: 'For zero-based indexing, the left child of node i is located at index 2i + 1, and the right child is at 2i + 2.',
    formula_hint: 'Left child = 2i + 1; Right child = 2i + 2; Parent = (i - 1) // 2',
    default_marks: 1.0,
    section: 'Section A: Trees & Graphs',
  },
  {
    subject: 'Computer Science',
    topic: 'Data Structures',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What graph representation format is most space-efficient for representing a sparse graph with V vertices and E edges where E << V²?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Adjacency list',
    explanation: 'An adjacency list consumes O(V + E) memory space, vastly superior to an adjacency matrix which requires O(V²) space regardless of edge density.',
    formula_hint: 'Sparse: Adjacency List O(V + E); Dense: Adjacency Matrix O(V²)',
    default_marks: 1.5,
    section: 'Section A: Trees & Graphs',
  },
  {
    subject: 'Computer Science',
    topic: 'Data Structures',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the working of a Disjoint Set Union (DSU / Union-Find) data structure and state the purpose of Path Compression and Union by Rank.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'DSU maintains a collection of disjoint partitions with two core operations: `find(x)` (identifies the root representative of the set containing x) and `union(x, y)` (merges sets containing x and y). Union by Rank attaches the shallower tree root beneath the deeper tree root, ensuring tree height does not grow unnecessarily. Path Compression flattens the tree during `find(x)` by pointing every visited node directly to the root. Together, they reduce the amortized time complexity per operation to O(α(n)), where α is the extremely slow-growing inverse Ackermann function.',
    explanation: 'Path compression + Union by rank yields practically constant amortized complexity O(α(n)).',
    formula_hint: 'Amortized time = O(α(n)) per find/union',
    default_marks: 2.5,
    section: 'Section A: Trees & Graphs',
  },
  {
    subject: 'Computer Science',
    topic: 'Data Structures',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'Describe the structure and balancing invariants of an AVL tree. Detail the four rotation cases (LL, RR, LR, RL) used to restore balance upon node insertion.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'An AVL tree is a self-balancing binary search tree where the balance factor BF(node) = height(left) - height(right) must be in {-1, 0, +1} for every node. When an insertion causes BF to become ±2, rebalancing is performed using rotations: 1. Left-Left (LL) Case: Inserted into left subtree of left child (BF = +2, left child BF = +1). Resolved by a single Right Rotation around the unbalanced root. 2. Right-Right (RR) Case: Inserted into right subtree of right child (BF = -2, right child BF = -1). Resolved by a single Left Rotation around the root. 3. Left-Right (LR) Case: Inserted into right subtree of left child (BF = +2, left child BF = -1). Resolved by a Left Rotation on the left child followed by a Right Rotation on the root. 4. Right-Left (RL) Case: Inserted into left subtree of right child (BF = -2, right child BF = +1). Resolved by a Right Rotation on the right child followed by a Left Rotation on the root. These rotations restore height balance in O(1) time per imbalance, preserving strict O(log n) operations.',
    explanation: 'Rotations restore the strict height invariant |BF| ≤ 1 in logarithmic time.',
    formula_hint: 'BF = h_left - h_right ∈ {-1, 0, 1}',
    default_marks: 4.0,
    section: 'Section A: Trees & Graphs',
  },

  // ============================================================================
  // 4. Algorithms (9 Questions)
  // ============================================================================
  {
    subject: 'Computer Science',
    topic: 'Algorithms',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the worst-case asymptotic time complexity of standard Merge Sort on an array of n elements?',
    options: [
      { id: 'a', text: 'O(n)' },
      { id: 'b', text: 'O(n log n)' },
      { id: 'c', text: 'O(n²)' },
      { id: 'd', text: 'O(log n)' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Merge sort divides the array in half at each recursion level (log n levels) and performs O(n) work merging sorted subarrays at each level, guaranteeing O(n log n) in all cases (best, average, worst).',
    formula_hint: 'T(n) = 2T(n/2) + O(n) => O(n log n) by Master Theorem',
    default_marks: 1.0,
    section: 'Section A: Sorting & Searching',
  },
  {
    subject: 'Computer Science',
    topic: 'Algorithms',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Dijkstra’s algorithm for finding single-source shortest paths requires which fundamental condition to hold for all edge weights?',
    options: [
      { id: 'a', text: 'All edge weights must be strictly non-negative (w(u, v) ≥ 0)' },
      { id: 'b', text: 'The graph must be a Directed Acyclic Graph (DAG)' },
      { id: 'c', text: 'All edge weights must be integers' },
      { id: 'd', text: 'The graph must be planar' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Dijkstra’s greedy approach assumes that visiting a node via the shortest known distance settles its final optimal shortest path. Negative edge weights violate this assumption (requiring Bellman-Ford instead).',
    formula_hint: 'Dijkstra requires w(e) ≥ 0; Bellman-Ford handles negative weights',
    default_marks: 1.5,
    section: 'Section B: Graph Algorithms & Optimization',
  },
  {
    subject: 'Computer Science',
    topic: 'Algorithms',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'According to the Master Theorem, what is the asymptotic solution to the recurrence relation T(n) = 4T(n/2) + n²?',
    options: [
      { id: 'a', text: 'Θ(n²)' },
      { id: 'b', text: 'Θ(n² log n)' },
      { id: 'c', text: 'Θ(n³)' },
      { id: 'd', text: 'Θ(n log n)' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Here a = 4, b = 2, f(n) = n². Compare f(n) with n^{log_b a} = n^{log₂ 4} = n². Since f(n) = Θ(n^{log_b a}) = Θ(n²), this falls into Master Theorem Case 2, giving T(n) = Θ(n² log n).',
    formula_hint: 'Case 2: f(n) = Θ(n^(log_b a)) => T(n) = Θ(n^(log_b a) log n)',
    default_marks: 2.0,
    section: 'Section A: Asymptotic Analysis',
  },
  {
    subject: 'Computer Science',
    topic: 'Algorithms',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following problems can be solved in polynomial time (belong to class P)?',
    options: [
      { id: 'a', text: 'Minimum Spanning Tree (Prim / Kruskal)' },
      { id: 'b', text: 'Single-Source Shortest Paths (Dijkstra)' },
      { id: 'c', text: '0/1 Knapsack Problem (fractional items prohibited)' },
      { id: 'd', text: 'Traveling Salesperson Problem (decision version)' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'MST (O(E log V)) and Shortest Paths (O(E + V log V)) are solved in polynomial time (P). 0/1 Knapsack and TSP decision problem are NP-complete problems.',
    formula_hint: 'MST and Shortest Path are in P; 0/1 Knapsack and TSP are NP-complete',
    default_marks: 2.0,
    section: 'Section B: Complexity Classes & P vs NP',
  },
  {
    subject: 'Computer Science',
    topic: 'Algorithms',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Dynamic Programming is applicable to problems that exhibit optimal substructure and overlapping subproblems.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Optimal substructure means the globally optimal solution contains optimal solutions to subproblems; overlapping subproblems allows memoization/tabulation to avoid recomputation.',
    formula_hint: 'DP prerequisites: Optimal substructure + Overlapping subproblems',
    default_marks: 1.0,
    section: 'Section B: Dynamic Programming & Greedy',
  },
  {
    subject: 'Computer Science',
    topic: 'Algorithms',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What algorithm design paradigm does QuickSort employ to sort an array around a chosen pivot element?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Divide and conquer',
    explanation: 'QuickSort divides the problem into partitioning around a pivot, recursively conquering the subarrays on either side.',
    formula_hint: 'Divide, Conquer, Combine',
    default_marks: 1.0,
    section: 'Section A: Sorting & Searching',
  },
  {
    subject: 'Computer Science',
    topic: 'Algorithms',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What is the time complexity of the Floyd-Warshall algorithm for all-pairs shortest paths in a graph with V vertices?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'O(V³)',
    explanation: 'Floyd-Warshall uses three nested loops over all vertices k, i, and j to compute intermediate shortest paths, running in Θ(V³) time.',
    formula_hint: '3 nested loops over V => O(V³)',
    default_marks: 1.5,
    section: 'Section B: Graph Algorithms & Optimization',
  },
  {
    subject: 'Computer Science',
    topic: 'Algorithms',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Differentiate between the Greedy method and Dynamic Programming, explaining why Greedy fails for the 0/1 Knapsack problem.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'The Greedy approach makes locally optimal choices at each decision step without backtracking, trusting they lead to a global optimum. Dynamic Programming evaluates all overlapping subproblem choices systematically, caching results to ensure global optimality. In the 0/1 Knapsack problem, choosing items greedily based on highest value-to-weight ratio fails because taking a high-ratio item may leave unusable slack capacity, missing combinations of lower-ratio items that sum to higher total value. Fractional knapsack allows partial items, so greedy works; 0/1 knapsack requires indivisible decisions, requiring DP.',
    explanation: 'Greedy makes irrevocable local choices; DP systematically searches subproblem state space.',
    formula_hint: 'Fractional Knapsack = Greedy; 0/1 Knapsack = Dynamic Programming',
    default_marks: 2.5,
    section: 'Section B: Dynamic Programming & Greedy',
  },
  {
    subject: 'Computer Science',
    topic: 'Algorithms',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'Define the complexity classes P, NP, NP-Complete, and NP-Hard. Explain how polynomial-time reductions are used to prove a problem is NP-Complete.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '1. Class P: Decision problems solvable by a deterministic Turing machine in polynomial time (O(n^k)). 2. Class NP (Nondeterministic Polynomial): Decision problems where a candidate solution can be verified in polynomial time by a deterministic Turing machine. 3. NP-Hard: A problem X is NP-Hard if every problem Y in NP can be reduced to X in polynomial time (Y ≤_p X); X is at least as hard as any problem in NP, though X does not need to be in NP itself. 4. NP-Complete: A problem X is NP-Complete if and only if: (i) X ∈ NP, and (ii) X is NP-Hard. To prove a new problem B is NP-Complete: Step 1: Prove B ∈ NP by constructing a polynomial-time verification algorithm. Step 2: Select a known NP-Complete problem A (e.g. 3-SAT). Step 3: Construct a polynomial-time reduction function f mapping any instance of A to an instance of B (A ≤_p B). Step 4: Prove correctness: instance x of A is a YES-instance if and only if f(x) is a YES-instance of B. Since f runs in poly-time, solving B solves A, establishing B is NP-Complete.',
    explanation: 'Rigorous foundation of computational complexity theory and Karp reduction methodology.',
    formula_hint: 'B is NP-Complete if B ∈ NP and known NP-Complete A ≤_p B',
    default_marks: 4.0,
    section: 'Section B: Complexity Classes & P vs NP',
  },

  // ============================================================================
  // 5. DBMS (9 Questions)
  // ============================================================================
  {
    subject: 'Computer Science',
    topic: 'DBMS',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'In database transaction management, what does the "A" in ACID properties stand for?',
    options: [
      { id: 'a', text: 'Atomicity' },
      { id: 'b', text: 'Availability' },
      { id: 'c', text: 'Asynchrony' },
      { id: 'd', text: 'Authentication' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Atomicity guarantees that all statements within a transaction either execute completely and commit successfully, or all changes are rolled back with no partial effects (all-or-nothing).',
    formula_hint: 'ACID = Atomicity, Consistency, Isolation, Durability',
    default_marks: 1.0,
    section: 'Section A: Relational Models & Transactions',
  },
  {
    subject: 'Computer Science',
    topic: 'DBMS',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Which normal form requires that a relational schema is in 2NF and has NO transitive functional dependencies of non-prime attributes on the primary key?',
    options: [
      { id: 'a', text: 'First Normal Form (1NF)' },
      { id: 'b', text: 'Third Normal Form (3NF)' },
      { id: 'c', text: 'Boyce-Codd Normal Form (BCNF)' },
      { id: 'd', text: 'Fourth Normal Form (4NF)' },
    ],
    correct_option_ids: ['b'],
    explanation: '1NF eliminates repeating groups; 2NF eliminates partial dependencies; 3NF eliminates transitive dependencies (X → Y where Y is non-prime and X is not a superkey).',
    formula_hint: '3NF = 2NF + No transitive dependencies',
    default_marks: 1.5,
    section: 'Section B: Normalization & Indexing',
  },
  {
    subject: 'Computer Science',
    topic: 'DBMS',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'Why are B+ Trees preferred over B Trees for indexing relational databases on disk storage?',
    options: [
      { id: 'a', text: 'All actual data records/pointers are stored exclusively in leaf nodes, which are linked sequentially to enable high-speed range scans' },
      { id: 'b', text: 'B+ Trees have fewer nodes and smaller height than binary search trees' },
      { id: 'c', text: 'B+ Trees eliminate disk I/O completely' },
      { id: 'd', text: 'B+ Trees do not require balancing upon deletion' },
    ],
    correct_option_ids: ['a'],
    explanation: 'In a B+ Tree, non-leaf nodes contain only keys and child pointers (maximizing node fan-out and reducing tree height). All data records/pointers reside in leaf nodes, which are linked in a doubly linked list, enabling efficient sequential range queries.',
    formula_hint: 'B+ Tree: Leaf-only data storage + sequential leaf linked list',
    default_marks: 2.0,
    section: 'Section B: Normalization & Indexing',
  },
  {
    subject: 'Computer Science',
    topic: 'DBMS',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following anomalies can occur at the Read Committed transaction isolation level that are prevented at Serializable level?',
    options: [
      { id: 'a', text: 'Non-repeatable read' },
      { id: 'b', text: 'Phantom read' },
      { id: 'c', text: 'Dirty read' },
      { id: 'd', text: 'Lost update' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'Read Committed prevents Dirty Reads (reading uncommitted data). However, it permits Non-Repeatable Reads (values change between reads in the same transaction) and Phantom Reads (new rows appear in range queries). Serializable prevents all anomalies.',
    formula_hint: 'Read Committed: prevents dirty read; allows non-repeatable & phantom',
    default_marks: 2.0,
    section: 'Section A: Relational Models & Transactions',
  },
  {
    subject: 'Computer Science',
    topic: 'DBMS',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'A foreign key in a relational database table can contain NULL values unless explicitly declared with a NOT NULL constraint.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Referential integrity requires that non-null foreign key values match an existing primary key in the referenced parent table, but NULL is permitted to represent the absence of a relationship.',
    formula_hint: 'Foreign keys permit NULL unless NOT NULL is enforced',
    default_marks: 1.0,
    section: 'Section A: Relational Models & Transactions',
  },
  {
    subject: 'Computer Science',
    topic: 'DBMS',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What concurrency control protocol uses Growing and Shrinking phases to guarantee conflict serializability of schedules?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Two-Phase Locking',
    explanation: 'Two-Phase Locking (2PL) requires transactions to acquire locks during a growing phase without releasing any, and release locks during a shrinking phase without acquiring new ones.',
    formula_hint: '2PL = Growing Phase (locks acquired) + Shrinking Phase (locks released)',
    default_marks: 1.5,
    section: 'Section A: Relational Models & Transactions',
  },
  {
    subject: 'Computer Science',
    topic: 'DBMS',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What SQL clause is used to filter aggregated group results produced by a GROUP BY statement?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'HAVING',
    explanation: 'WHERE filters individual row records before grouping; HAVING filters aggregated group metrics (e.g. `HAVING COUNT(*) > 5`) after grouping.',
    formula_hint: 'GROUP BY column HAVING aggregate_condition',
    default_marks: 1.0,
    section: 'Section A: Relational Models & Transactions',
  },
  {
    subject: 'Computer Science',
    topic: 'DBMS',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the difference between a Clustered Index and a Non-Clustered (Secondary) Index in relational databases.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'A Clustered Index dictates the physical ordering of the actual data rows on the disk storage pages; leaf nodes of a clustered index contain the actual data rows themselves. Because physical storage can have only one ordering, a table can possess at most one clustered index (usually on the primary key). A Non-Clustered Index maintains a separate search structure whose leaf nodes contain index keys paired with row locator pointers (such as clustered index keys or RID file offsets) pointing to the physical data rows. A table can have multiple non-clustered indexes to accelerate distinct search predicates.',
    explanation: 'Clustered determines physical disk layout (max 1); non-clustered stores pointers to data (multiple allowed).',
    formula_hint: 'Clustered = physical row order; Non-clustered = secondary pointer lookup',
    default_marks: 2.5,
    section: 'Section B: Normalization & Indexing',
  },
  {
    subject: 'Computer Science',
    topic: 'DBMS',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'Explain the write-ahead logging (WAL) protocol and the ARIES recovery algorithm (Analysis, Redo, Undo phases) used by relational databases to guarantee atomicity and durability.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Write-Ahead Logging (WAL) requires that all log records describing database modifications must be flushed to stable non-volatile storage before the corresponding dirty data pages are written to disk, and before a transaction commit returns to the client. This guarantees durability and recovery. ARIES (Algorithm for Recovery and Isolation Exploiting Semantics) recovers after a crash using three distinct sequential passes: 1. Analysis Phase: Scans the log forward from the most recent checkpoint to reconstruct the state of the database at crash time, identifying all active uncommitted transactions (the Transaction Table) and all dirty pages in buffer pool (Dirty Page Table). 2. Redo Phase: Scans forward from the oldest unwritten dirty page (RecLSN) and reapplies all logged operations (both committed and uncommitted) to repeat history exactly, restoring the database to the exact pre-crash state. 3. Undo Phase: Scans backward through the log, rolling back all operations performed by active, uncommitted loser transactions in reverse order. For each undone operation, it logs a Compensation Log Record (CLR) to prevent repeating undos if a secondary crash occurs during recovery.',
    explanation: 'WAL ensures persistent write ordering; ARIES repeats history (Redo) and rolls back uncommitted losers (Undo) using CLRs.',
    formula_hint: 'ARIES = Analysis (find state) -> Redo (repeat history) -> Undo (rollback losers)',
    default_marks: 4.0,
    section: 'Section A: Relational Models & Transactions',
  },

  // ============================================================================
  // 6. Operating Systems (9 Questions)
  // ============================================================================
  {
    subject: 'Computer Science',
    topic: 'Operating Systems',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which CPU scheduling algorithm gives the lowest theoretical average waiting time for a set of stationary processes?',
    options: [
      { id: 'a', text: 'First-Come, First-Served (FCFS)' },
      { id: 'b', text: 'Shortest Job First (SJF)' },
      { id: 'c', text: 'Round Robin (RR)' },
      { id: 'd', text: 'Priority Scheduling' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Shortest Job First (SJF) is mathematically optimal: executing shorter jobs first minimizes the cumulative queuing delay experienced by subsequent processes.',
    formula_hint: 'SJF minimizes average waiting time',
    default_marks: 1.0,
    section: 'Section A: Process Management & Scheduling',
  },
  {
    subject: 'Computer Science',
    topic: 'Operating Systems',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Which of the following conditions is NOT one of Coffman’s four necessary conditions for a system deadlock to occur?',
    options: [
      { id: 'a', text: 'Mutual Exclusion' },
      { id: 'b', text: 'Hold and Wait' },
      { id: 'c', text: 'Preemption of resources' },
      { id: 'd', text: 'Circular Wait' },
    ],
    correct_option_ids: ['c'],
    explanation: 'The four Coffman conditions are: Mutual Exclusion, Hold and Wait, No Preemption (resources cannot be forcibly taken), and Circular Wait. Preemption breaks deadlock, so "No Preemption" is required, not "Preemption".',
    formula_hint: 'Deadlock requires: Mutual Exclusion, Hold & Wait, No Preemption, Circular Wait',
    default_marks: 1.5,
    section: 'Section B: Concurrency & Synchronization',
  },
  {
    subject: 'Computer Science',
    topic: 'Operating Systems',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'What is Belady’s Anomaly in operating systems virtual memory management?',
    options: [
      { id: 'a', text: 'Increasing the number of allocated physical page frames results in an increased number of page faults for FIFO replacement' },
      { id: 'b', text: 'The CPU spends more time paging than executing processes' },
      { id: 'c', text: 'LRU replacement behaves identical to Optimal replacement' },
      { id: 'd', text: 'Translation Lookaside Buffer (TLB) misses cause system crashes' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Belady’s anomaly occurs in certain non-stack page replacement algorithms (such as FIFO), where giving a process more memory frames paradoxically leads to more page faults for specific reference strings.',
    formula_hint: 'Belady’s Anomaly: FIFO page frames ↑ => Page faults ↑',
    default_marks: 2.0,
    section: 'Section B: Memory Management & Paging',
  },
  {
    subject: 'Computer Science',
    topic: 'Operating Systems',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following memory management page replacement algorithms are "stack algorithms" that are mathematically immune to Belady’s Anomaly?',
    options: [
      { id: 'a', text: 'Least Recently Used (LRU)' },
      { id: 'b', text: 'Optimal Page Replacement (OPT / MIN)' },
      { id: 'c', text: 'First-In, First-Out (FIFO)' },
      { id: 'd', text: 'Most Frequently Used (MFU)' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'In stack algorithms (LRU, OPT), the set of pages in memory for n frames is always a strict subset of the pages in memory for n + 1 frames, guaranteeing freedom from Belady’s anomaly. FIFO and MFU can suffer from it.',
    formula_hint: 'Stack algorithms: S(n) ⊆ S(n+1)',
    default_marks: 2.0,
    section: 'Section B: Memory Management & Paging',
  },
  {
    subject: 'Computer Science',
    topic: 'Operating Systems',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'A Translation Lookaside Buffer (TLB) is an associative hardware cache that speeds up virtual-to-physical address translation.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. The TLB caches recently accessed Virtual Page Number to Physical Frame Number mappings in high-speed hardware, avoiding multi-level page table memory lookups on hits.',
    formula_hint: 'TLB Hit: 1 memory access; TLB Miss: page table walk',
    default_marks: 1.0,
    section: 'Section B: Memory Management & Paging',
  },
  {
    subject: 'Computer Science',
    topic: 'Operating Systems',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What state is an operating system in when it spends more time swapping pages between RAM and disk than executing productive user instructions?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Thrashing',
    explanation: 'Thrashing occurs when the sum of working set sizes across all active processes exceeds available physical memory, causing continuous page faults and near-zero CPU utilization.',
    formula_hint: 'Working sets > Total RAM => Thrashing',
    default_marks: 1.0,
    section: 'Section B: Memory Management & Paging',
  },
  {
    subject: 'Computer Science',
    topic: 'Operating Systems',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What algorithm is used by operating systems to safely avoid deadlock by evaluating resource allocation requests against a state matrix?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Banker’s Algorithm',
    explanation: 'Dijkstra’s Banker’s Algorithm tests whether granting a resource request leaves the system in a "safe state" where at least one execution sequence can finish without deadlock.',
    formula_hint: 'Safe state verification = Banker’s Algorithm',
    default_marks: 1.5,
    section: 'Section B: Concurrency & Synchronization',
  },
  {
    subject: 'Computer Science',
    topic: 'Operating Systems',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain how a context switch works between two user-space processes and identify the overheads involved.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'A context switch stops the currently executing process and resumes another: 1. A timer interrupt or system call triggers a transition to kernel mode. 2. The OS saves the CPU register state (Program Counter, general-purpose registers, stack pointer, condition codes) into the outgoing process’s Process Control Block (PCB). 3. The scheduler selects the next process to run. 4. The OS updates memory management hardware registers (e.g. CR3 page table base register), invalidates TLB entries (or switches address space identifiers), and restores CPU registers from the incoming PCB. 5. Execution switches to user mode. Overheads include saving/restoring registers, CPU cache pollution, TLB invalidation, and pipeline flushes.',
    explanation: 'Context switches transition state via PCB saves and address space remapping, introducing direct CPU and indirect cache/TLB overhead.',
    formula_hint: 'Context switch = Save PCB_A -> Load PCB_B + Address Space Switch',
    default_marks: 2.5,
    section: 'Section A: Process Management & Scheduling',
  },
  {
    subject: 'Computer Science',
    topic: 'Operating Systems',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'Define the Critical Section problem in concurrent computing. State the three mandatory requirements (Mutual Exclusion, Progress, Bounded Waiting) and demonstrate how Peterson’s Algorithm satisfies them for two processes.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'The Critical Section is a code block accessing shared mutable resources that cannot be executed concurrently by multiple processes without causing race conditions. Three mandatory requirements: 1. Mutual Exclusion: If process P_i is executing in its critical section, no other processes can be executing in their critical sections. 2. Progress: If no process is in its critical section and some wish to enter, only processes not in their remainder section can participate in deciding who enters next, and selection cannot be postponed indefinitely. 3. Bounded Waiting: A bound must exist on the number of times other processes are allowed to enter their critical sections after a process has requested entry before its request is granted. Peterson’s Algorithm uses two shared variables: `flag[2]` (boolean array indicating interest) and `turn` (integer indicating whose turn it is). For process P_i (with peer P_j): Entry code:\n```c\nflag[i] = true;\nturn = j;\nwhile (flag[j] && turn == j);\n// Critical Section\nflag[i] = false;\n```\nProof: 1. Mutual Exclusion: For both P_0 and P_1 to enter, `flag[0] == true` and `flag[1] == true`, but `turn` can only be 0 or 1 simultaneously. The one matching turn waits while the other proceeds. 2. Progress: If P_j is not interested (`flag[j] == false`), the while condition is false immediately, letting P_i enter. 3. Bounded Waiting: P_i sets `turn = j`, ensuring P_j gets priority; once P_j exits and clears `flag[j]`, P_i enters next without waiting more than one turn.',
    explanation: 'Peterson’s algorithm guarantees mutual exclusion, progress, and bounded waiting in software for two processes on sequentially consistent hardware.',
    formula_hint: 'Peterson: flag[i] = true; turn = j; while(flag[j] && turn == j);',
    default_marks: 4.0,
    section: 'Section B: Concurrency & Synchronization',
  },

  // ============================================================================
  // 7. Computer Networks (9 Questions)
  // ============================================================================
  {
    subject: 'Computer Science',
    topic: 'Computer Networks',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which layer of the OSI reference model is responsible for logical IP addressing and end-to-end packet routing across networks?',
    options: [
      { id: 'a', text: 'Data Link Layer' },
      { id: 'b', text: 'Network Layer' },
      { id: 'c', text: 'Transport Layer' },
      { id: 'd', text: 'Session Layer' },
    ],
    correct_option_ids: ['b'],
    explanation: 'The Network layer (Layer 3) handles logical host addressing (IPv4/IPv6), subnetting, and optimal path selection (routing protocols such as OSPF, BGP).',
    formula_hint: 'Layer 3 = Network Layer (IP, Routers)',
    default_marks: 1.0,
    section: 'Section A: OSI & TCP/IP Architecture',
  },
  {
    subject: 'Computer Science',
    topic: 'Computer Networks',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What sequence of flags is exchanged during the standard TCP three-way handshake to establish a reliable connection?',
    options: [
      { id: 'a', text: 'SYN → SYN-ACK → ACK' },
      { id: 'b', text: 'ACK → SYN → ACK' },
      { id: 'c', text: 'FIN → ACK → FIN-ACK' },
      { id: 'd', text: 'SYN → ACK → SYN-ACK' },
    ],
    correct_option_ids: ['a'],
    explanation: 'The client sends a SYN packet with initial sequence number x; the server replies with SYN-ACK (acknowledging x+1 with server sequence number y); the client confirms with an ACK (acknowledging y+1).',
    formula_hint: 'Client: SYN -> Server: SYN-ACK -> Client: ACK',
    default_marks: 1.5,
    section: 'Section B: Transport Protocols & Congestion',
  },
  {
    subject: 'Computer Science',
    topic: 'Computer Networks',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'An IPv4 subnet has the network address 192.168.1.0/26. How many usable host IP addresses are available in this subnet?',
    options: [
      { id: 'a', text: '64' },
      { id: 'b', text: '62' },
      { id: 'c', text: '30' },
      { id: 'd', text: '126' },
    ],
    correct_option_ids: ['b'],
    explanation: '/26 leaves 32 - 26 = 6 host bits. Total addresses = 2⁶ = 64. Subtracting 2 reserved addresses (network ID 192.168.1.0 and directed broadcast 192.168.1.63) yields 64 - 2 = 62 usable host addresses.',
    formula_hint: 'Usable hosts = 2^(32 - prefix) - 2',
    default_marks: 2.0,
    section: 'Section A: OSI & TCP/IP Architecture',
  },
  {
    subject: 'Computer Science',
    topic: 'Computer Networks',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following application layer protocols run over the User Datagram Protocol (UDP) by default?',
    options: [
      { id: 'a', text: 'DNS (standard short queries)' },
      { id: 'b', text: 'DHCP' },
      { id: 'c', text: 'TFTP' },
      { id: 'd', text: 'HTTPS' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'DNS (port 53), DHCP (ports 67/68), and TFTP (port 69) use UDP for low-overhead, connectionless datagram transmission. Standard HTTPS runs over TCP (port 443).',
    formula_hint: 'UDP services: DNS, DHCP, TFTP, NTP, SNMP',
    default_marks: 2.0,
    section: 'Section B: Transport Protocols & Congestion',
  },
  {
    subject: 'Computer Science',
    topic: 'Computer Networks',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'The Address Resolution Protocol (ARP) resolves a known logical IP address to a physical MAC address on a local area network.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. ARP broadcasts a request frame across the local ethernet broadcast domain ("Who has IP x.x.x.x?") to discover the corresponding hardware MAC address.',
    formula_hint: 'ARP: IP address → MAC address',
    default_marks: 1.0,
    section: 'Section A: OSI & TCP/IP Architecture',
  },
  {
    subject: 'Computer Science',
    topic: 'Computer Networks',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What TCP congestion control mechanism doubles the congestion window (CWND) every round-trip time (RTT) until reaching ssthresh?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Slow Start',
    explanation: 'In Slow Start, CWND begins at 1 MSS and increments by 1 MSS for every received ACK, leading to exponential growth (doubling every RTT) until slow start threshold (ssthresh) is reached.',
    formula_hint: 'Slow start grows exponentially (CWND = 2^t)',
    default_marks: 1.5,
    section: 'Section B: Transport Protocols & Congestion',
  },
  {
    subject: 'Computer Science',
    topic: 'Computer Networks',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What protocol is used by routers to exchange routing reachability information between different Autonomous Systems across the global Internet?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'BGP',
    explanation: 'Border Gateway Protocol (BGP) is the standardized exterior gateway path-vector protocol that routes traffic between Internet Service Providers and autonomous systems.',
    formula_hint: 'Exterior Gateway Protocol = BGP',
    default_marks: 1.0,
    section: 'Section A: OSI & TCP/IP Architecture',
  },
  {
    subject: 'Computer Science',
    topic: 'Computer Networks',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the Count-to-Infinity problem in Distance Vector routing protocols (e.g. RIP) and state two mechanisms used to prevent it.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'The Count-to-Infinity problem occurs in Distance Vector protocols using the Bellman-Ford algorithm when a link fails: two neighboring nodes repeatedly update their routing tables referencing each other’s outdated metrics, incrementing hop count indefinitely until reaching a ceiling (e.g. 16 in RIP). Two preventive mechanisms are: 1. Split Horizon: A router is prohibited from advertising a route back out the same interface through which it learned that route. 2. Poison Reverse: When advertising a route back to the neighbor it learned it from, the router explicitly advertises the distance as infinity (metric 16), immediately terminating looping dependency.',
    explanation: 'Distance vector routing loops arise from blind neighbor reliance; split horizon and poison reverse suppress circular misinformation.',
    formula_hint: 'Count-to-infinity solved by Split Horizon + Poison Reverse',
    default_marks: 2.5,
    section: 'Section A: OSI & TCP/IP Architecture',
  },
  {
    subject: 'Computer Science',
    topic: 'Computer Networks',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'Detail the four phases of TCP congestion control (Slow Start, Congestion Avoidance, Fast Retransmit, Fast Recovery) according to RFC 5681.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '1. Slow Start: The sender initializes Congestion Window CWND = 1 MSS. For each incoming non-duplicate ACK, CWND increases by 1 MSS, resulting in exponential doubling of CWND every Round-Trip Time (RTT). This continues until CWND reaches the slow start threshold (ssthresh). 2. Congestion Avoidance: Once CWND ≥ ssthresh, growth shifts from exponential to linear: CWND increases by approximately 1 MSS per RTT (specifically, CWND += MSS × MSS / CWND on each ACK), probing for bandwidth conservatively (AIMD: Additive Increase). 3. Fast Retransmit: When the sender receives 3 duplicate ACKs for the same sequence number, it assumes packet loss has occurred without waiting for a retransmission timeout (RTO). The missing segment is retransmitted immediately. 4. Fast Recovery: Instead of resetting CWND back to 1 MSS (which would trigger Slow Start), ssthresh is set to max(FlightSize/2, 2 MSS) and CWND is set to ssthresh + 3 MSS. For each additional duplicate ACK received, CWND is incremented by 1 MSS. When an ACK for the new unacknowledged data arrives, CWND is set to ssthresh and the algorithm resumes normal Congestion Avoidance.',
    explanation: 'Standard TCP Reno congestion framework providing graceful AIMD bandwidth convergence and rapid packet loss recovery.',
    formula_hint: 'AIMD: Additive Increase in avoidance, Multiplicative Decrease upon loss',
    default_marks: 4.0,
    section: 'Section B: Transport Protocols & Congestion',
  },

  // ============================================================================
  // 8. Computer Architecture (9 Questions)
  // ============================================================================
  {
    subject: 'Computer Science',
    topic: 'Computer Architecture',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which computer architecture model shares a single unified bus and memory space for both program instructions and data?',
    options: [
      { id: 'a', text: 'Von Neumann Architecture' },
      { id: 'b', text: 'Harvard Architecture' },
      { id: 'c', text: 'Dataflow Architecture' },
      { id: 'd', text: 'SIMD Vector Architecture' },
    ],
    correct_option_ids: ['a'],
    explanation: 'The Von Neumann architecture features a shared physical bus and memory for instructions and data (subject to the Von Neumann bottleneck). Harvard architecture utilizes separate physical memories and buses.',
    formula_hint: 'Von Neumann = Shared instruction/data memory',
    default_marks: 1.0,
    section: 'Section A: CPU Architecture & Instruction Sets',
  },
  {
    subject: 'Computer Science',
    topic: 'Computer Architecture',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'In a 5-stage classic RISC processor pipeline (IF, ID, EX, MEM, WB), what hazard arises when an instruction depends on the result of a preceding instruction that has not yet written back to the register file?',
    options: [
      { id: 'a', text: 'Data Hazard (Read-After-Write / RAW)' },
      { id: 'b', text: 'Structural Hazard' },
      { id: 'c', text: 'Control Hazard' },
      { id: 'd', text: 'Write-After-Write (WAW) hazard' },
    ],
    correct_option_ids: ['a'],
    explanation: 'A Read-After-Write (RAW) data hazard occurs when instruction j tries to read a register value before instruction i writes it, requiring pipeline stalling or operand forwarding to resolve.',
    formula_hint: 'RAW data hazard resolved by forwarding or bubbles',
    default_marks: 1.5,
    section: 'Section B: Pipelining & Cache Memory',
  },
  {
    subject: 'Computer Science',
    topic: 'Computer Architecture',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'A computer system has a 32-bit byte-addressable physical address space and a 64 KB 4-way set-associative cache with 64-byte cache lines. How many bits are used for the Cache Tag, Set Index, and Block Offset?',
    options: [
      { id: 'a', text: 'Tag = 18 bits, Index = 8 bits, Offset = 6 bits' },
      { id: 'b', text: 'Tag = 16 bits, Index = 10 bits, Offset = 6 bits' },
      { id: 'c', text: 'Tag = 20 bits, Index = 6 bits, Offset = 6 bits' },
      { id: 'd', text: 'Tag = 14 bits, Index = 12 bits, Offset = 6 bits' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Block size = 64 bytes = 2⁶ bytes => Offset = 6 bits. Total lines = 64 KB / 64 B = 1024 lines. Since it is 4-way set associative, Number of Sets = 1024 / 4 = 256 = 2⁸ sets => Set Index = 8 bits. Tag bits = 32 - (8 + 6) = 32 - 14 = 18 bits.',
    formula_hint: 'Bits: Tag = Address - (Index + Offset); Index = log₂(Sets); Offset = log₂(BlockSize)',
    default_marks: 2.0,
    section: 'Section B: Pipelining & Cache Memory',
  },
  {
    subject: 'Computer Science',
    topic: 'Computer Architecture',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following techniques are used in modern superscalar microprocessors to mitigate pipeline branch penalties caused by control hazards?',
    options: [
      { id: 'a', text: 'Dynamic Branch Prediction (e.g. 2-bit saturating counter, gshare)' },
      { id: 'b', text: 'Branch Target Buffer (BTB)' },
      { id: 'c', text: 'Speculative Execution with out-of-order execution' },
      { id: 'd', text: 'Vector register strip mining' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Dynamic branch predictors guess outcome, BTBs cache target branch addresses to eliminate bubble cycles, and speculative execution executes anticipated instructions ahead of branch resolution. Strip mining is a vector loop technique.',
    formula_hint: 'Branch penalty mitigated by prediction, BTB, and speculative execution',
    default_marks: 2.0,
    section: 'Section B: Pipelining & Cache Memory',
  },
  {
    subject: 'Computer Science',
    topic: 'Computer Architecture',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'In a write-through cache policy, memory writes update both the cache line and main memory simultaneously on every write operation.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Write-through writes to cache and main memory concurrently, ensuring main memory is always consistent, unlike write-back which delays writing until eviction.',
    formula_hint: 'Write-through = immediate memory write; Write-back = write upon eviction',
    default_marks: 1.0,
    section: 'Section B: Pipelining & Cache Memory',
  },
  {
    subject: 'Computer Science',
    topic: 'Computer Architecture',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What fundamental law of parallel computing states that the maximum theoretical speedup S of a program is limited by S = 1 / [(1 - P) + P/N], where P is the parallelizable fraction?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Amdahl’s Law',
    explanation: 'Amdahl’s Law shows that serial fractions (1 - P) inherently bottleneck maximum parallel speedup, placing an asymptotic upper bound of 1/(1 - P) even with infinite processors.',
    formula_hint: 'S_max = 1 / (1 - P)',
    default_marks: 1.5,
    section: 'Section A: CPU Architecture & Instruction Sets',
  },
  {
    subject: 'Computer Science',
    topic: 'Computer Architecture',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What CPU register holds the memory address of the next instruction to be fetched and executed?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Program Counter',
    explanation: 'The Program Counter (PC / Instruction Pointer) holds the instruction memory address and auto-increments or branches during the fetch stage.',
    formula_hint: 'Program Counter (PC) = address of next instruction',
    default_marks: 1.0,
    section: 'Section A: CPU Architecture & Instruction Sets',
  },
  {
    subject: 'Computer Science',
    topic: 'Computer Architecture',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the principle of operand forwarding (bypassing) in a pipelined CPU and identify which data hazards it completely eliminates.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Operand forwarding routes the computed output of an ALU operation directly from pipeline registers (EX/MEM or MEM/WB) back to the input multiplexers of the EX stage for subsequent dependent instructions, bypassing the requirement to wait for write-back into the register file in the WB stage. This eliminates pipeline stalls for EX-to-EX data dependencies (such as an ALU operation immediately following another ALU operation). However, it cannot eliminate the load-use data hazard, where a dependent instruction immediately follows a memory LOAD, still necessitating a 1-cycle pipeline bubble.',
    explanation: 'Hardware forwarding multiplexers route intermediate pipeline results to ALU inputs, eliminating ALU-ALU RAW stalls.',
    formula_hint: 'Forwarding: EX/MEM -> EX stage inputs',
    default_marks: 2.5,
    section: 'Section B: Pipelining & Cache Memory',
  },
  {
    subject: 'Computer Science',
    topic: 'Computer Architecture',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'Explain the Memory Hierarchy design in modern computer architecture. Detail the principles of temporal and spatial locality, and compute the Average Memory Access Time (AMAT) for a two-level cache hierarchy.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'The memory hierarchy balances speed, cost, and capacity by cascading storage tiers from smallest and fastest (Registers, L1 Cache, L2 Cache, L3 Cache) down to larger and slower (Main Memory DRAM, NVMe SSD). Locality of Reference principles: 1. Temporal Locality: If a memory location is accessed, it is likely to be accessed again in the near future (e.g. loops, induction variables, stack frames); exploited by retaining recently accessed items in high-speed cache. 2. Spatial Locality: If a memory location is accessed, nearby memory locations are likely to be accessed soon (e.g. sequential array traversal, sequential instruction execution); exploited by fetching data in multi-byte cache blocks/lines rather than individual bytes. Average Memory Access Time (AMAT) formula for two-level cache:\nAMAT = Hit_Time(L1) + Miss_Rate(L1) × Miss_Penalty(L1)\nwhere Miss_Penalty(L1) = Hit_Time(L2) + Miss_Rate(L2) × Miss_Penalty(L2).\nExpanding gives: AMAT = Hit_Time(L1) + Miss_Rate(L1) × [Hit_Time(L2) + Miss_Rate(L2) × Memory_Access_Time]. This tiered layout yields near-L1 access speeds on average while maintaining gigabyte-scale storage capacity.',
    explanation: 'Hierarchical caching leverages temporal and spatial locality to minimize AMAT while preserving economic viability.',
    formula_hint: 'AMAT = H1 + M1(H2 + M2 · M_penalty)',
    default_marks: 4.0,
    section: 'Section B: Pipelining & Cache Memory',
  },
];
