/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { CurriculumQuestion } from './types.js';

export const DATA_SCIENCE_QUESTIONS: CurriculumQuestion[] = [
  // ============================================================================
  // 1. Python for Data Science (7 Questions)
  // ============================================================================
  {
    subject: 'Data Science',
    topic: 'Python for Data Science',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which built-in Python function applies a given transformation function to all items in an iterable and returns an iterator?',
    options: [
      { id: 'a', text: 'filter()' },
      { id: 'b', text: 'map()' },
      { id: 'c', text: 'reduce()' },
      { id: 'd', text: 'zip()' },
    ],
    correct_option_ids: ['b'],
    explanation: 'The map(function, iterable) function returns a lazy iterator that applies the function to every element of the iterable without materializing the whole collection upfront.',
    formula_hint: 'map(f, [x1, x2, ...]) = [f(x1), f(x2), ...]',
    default_marks: 1.0,
    section: 'Section A: Data Manipulation & Functional Python',
  },
  {
    subject: 'Data Science',
    topic: 'Python for Data Science',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What will be the output of `list(zip([1, 2, 3], ["a", "b"]))` in Python?',
    options: [
      { id: 'a', text: '[(1, "a"), (2, "b"), (3, None)]' },
      { id: 'b', text: '[(1, "a"), (2, "b")]' },
      { id: 'c', text: 'Raises a ValueError due to mismatched sequence lengths' },
      { id: 'd', text: '[(1, 2, 3), ("a", "b")]' },
    ],
    correct_option_ids: ['b'],
    explanation: 'By default, Python’s zip() stops yielding pairs when the shortest input iterable is exhausted, producing [(1, "a"), (2, "b")]. (Use itertools.zip_longest for padding).',
    formula_hint: 'zip(*iterables) stops at the shortest iterable',
    default_marks: 1.5,
    section: 'Section A: Data Manipulation & Functional Python',
  },
  {
    subject: 'Data Science',
    topic: 'Python for Data Science',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'In Python, what is the key difference between `copy.copy()` (shallow copy) and `copy.deepcopy()` (deep copy) when copying nested data structures?',
    options: [
      { id: 'a', text: 'Shallow copy duplicates nested objects; deep copy creates references' },
      { id: 'b', text: 'Shallow copy constructs a new compound object and inserts references to the original nested objects; deep copy constructs a new compound object and recursively inserts copies of nested objects' },
      { id: 'c', text: 'Shallow copy only works on primitive types' },
      { id: 'd', text: 'Deep copy converts all nested lists into immutable tuples' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Shallow copy duplicates the outer container while preserving references to internal mutable items. Deep copy recursively duplicates all child objects, creating a fully isolated copy hierarchy.',
    formula_hint: 'Shallow = outer duplicate + inner references; Deep = recursive duplicate',
    default_marks: 2.0,
    section: 'Section A: Data Manipulation & Functional Python',
  },
  {
    subject: 'Data Science',
    topic: 'Python for Data Science',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following expressions evaluate to True in Python?',
    options: [
      { id: 'a', text: 'bool([]) == False' },
      { id: 'b', text: 'bool(0) == False' },
      { id: 'c', text: 'bool("False") == True' },
      { id: 'd', text: 'bool(None) == True' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Empty containers ([]), zero (0), and None evaluate to False in boolean contexts. Any non-empty string, including "False", evaluates to True (c). bool(None) is False (d is false).',
    formula_hint: 'Falsy values: 0, None, "", [], {}, set()',
    default_marks: 2.0,
    section: 'Section A: Data Manipulation & Functional Python',
  },
  {
    subject: 'Data Science',
    topic: 'Python for Data Science',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'A lambda function in Python can contain multiple arbitrary statements and explicit return keywords.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['false'],
    explanation: 'False. Python lambda functions are restricted syntactically to a single expression whose evaluated value is implicitly returned; statements and assignments are disallowed.',
    formula_hint: 'lambda args: single_expression',
    default_marks: 1.0,
    section: 'Section A: Data Manipulation & Functional Python',
  },
  {
    subject: 'Data Science',
    topic: 'Python for Data Science',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What built-in standard library module provides specialized dictionary subclasses such as `defaultdict`, `Counter`, and `OrderedDict`?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'collections',
    explanation: 'The `collections` module implements high-performance container datatypes extending general-purpose dict, list, set, and tuple.',
    formula_hint: 'from collections import Counter, defaultdict',
    default_marks: 1.0,
    section: 'Section A: Data Manipulation & Functional Python',
  },
  {
    subject: 'Data Science',
    topic: 'Python for Data Science',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain how list comprehensions provide memory and execution speed advantages over manual `for` loops in standard CPython.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'List comprehensions execute in CPython at optimized C-level speed: the bytecode uses specialized instructions (`LIST_APPEND`) without the overhead of repeatedly looking up and calling the `.append()` method on the list object in the Python virtual machine loop frame. While both allocate the resulting list in memory, list comprehensions avoid the function call overhead of method resolution per iteration, typically resulting in 20–35% faster execution time for data processing loops.',
    explanation: 'LIST_APPEND opcode eliminates attribute lookup and frame stack overhead compared to .append().',
    formula_hint: 'Optimized bytecode instruction LIST_APPEND',
    default_marks: 2.5,
    section: 'Section A: Data Manipulation & Functional Python',
  },

  // ============================================================================
  // 2. NumPy (7 Questions)
  // ============================================================================
  {
    subject: 'Data Science',
    topic: 'NumPy',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the attribute used to inspect the dimensional shape of a NumPy ndarray?',
    options: [
      { id: 'a', text: 'arr.shape' },
      { id: 'b', text: 'arr.size' },
      { id: 'c', text: 'arr.ndim' },
      { id: 'd', text: 'arr.dimensions' },
    ],
    correct_option_ids: ['a'],
    explanation: 'The .shape attribute returns a tuple of integers indicating the size of the array along each axis (e.g. (3, 4) for 3 rows and 4 columns).',
    formula_hint: 'arr.shape = tuple of axis lengths',
    default_marks: 1.0,
    section: 'Section A: Array Operations & Vectorization',
  },
  {
    subject: 'Data Science',
    topic: 'NumPy',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Under NumPy broadcasting rules, what is the resulting shape of adding an array of shape (4, 1) to an array of shape (1, 5)?',
    options: [
      { id: 'a', text: '(4, 5)' },
      { id: 'b', text: '(5, 4)' },
      { id: 'c', text: '(4, 1)' },
      { id: 'd', text: 'Incompatible dimensions; raises a ValueError' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Trailing dimensions are aligned right-to-left. Dimensions are compatible if they are equal or if one of them is 1. Dimensions of size 1 are stretched to match the larger dimension: (4, 1) and (1, 5) broadcast to (4, 5).',
    formula_hint: 'Broadcasting: max(dim1, dim2) when one is 1',
    default_marks: 1.5,
    section: 'Section A: Array Operations & Vectorization',
  },
  {
    subject: 'Data Science',
    topic: 'NumPy',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'What is the fundamental difference between array slicing (`arr[1:3]`) and fancy integer indexing (`arr[[1, 3]]`) in NumPy?',
    options: [
      { id: 'a', text: 'Slicing returns a view of the original memory; fancy indexing always constructs a new copy of the data' },
      { id: 'b', text: 'Fancy indexing returns a view; slicing creates a copy' },
      { id: 'c', text: 'Both always create deep copies' },
      { id: 'd', text: 'Both always return views' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Basic slicing manipulates strides and offset to create a zero-copy view of the underlying memory buffer. Advanced / fancy indexing (using lists/arrays of integer indices or boolean masks) always allocates a newly copied array.',
    formula_hint: 'Basic slicing = View (zero-copy); Fancy indexing = Copy',
    default_marks: 2.0,
    section: 'Section A: Array Operations & Vectorization',
  },
  {
    subject: 'Data Science',
    topic: 'NumPy',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following matrix multiplication operations can be performed in NumPy?',
    options: [
      { id: 'a', text: 'np.dot(A, B)' },
      { id: 'b', text: 'A @ B' },
      { id: 'c', text: 'np.matmul(A, B)' },
      { id: 'd', text: 'A * B' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'np.dot, np.matmul, and the `@` infix operator perform true matrix multiplication (linear algebra dot product). `A * B` performs element-wise Hadamard multiplication.',
    formula_hint: '@ and np.matmul compute matrix product; * is element-wise',
    default_marks: 2.0,
    section: 'Section A: Array Operations & Vectorization',
  },
  {
    subject: 'Data Science',
    topic: 'NumPy',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'In NumPy, `np.nan == np.nan` evaluates to True.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['false'],
    explanation: 'False. In IEEE 754 floating-point standard, NaN (Not a Number) does not equal any value, including itself (`np.nan == np.nan` is False). Use `np.isnan()` to check for NaN values.',
    formula_hint: 'IEEE 754: NaN ≠ NaN; use np.isnan()',
    default_marks: 1.0,
    section: 'Section A: Array Operations & Vectorization',
  },
  {
    subject: 'Data Science',
    topic: 'NumPy',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What NumPy function is used to compute the inverse of a square non-singular matrix A?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'np.linalg.inv',
    explanation: '`np.linalg.inv(A)` computes the multiplicative inverse of square matrix A such that A @ inv(A) = I.',
    formula_hint: 'np.linalg.inv(A)',
    default_marks: 1.0,
    section: 'Section A: Array Operations & Vectorization',
  },
  {
    subject: 'Data Science',
    topic: 'NumPy',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain NumPy strides and how they allow multidimensional arrays to transpose and slice without copying data.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'A NumPy array stores elements in a contiguous 1D memory buffer. The `strides` attribute is a tuple specifying the number of bytes to step across memory to advance one element along each axis. For example, in a C-contiguous float64 array of shape (3, 4), strides are (32, 8). Operations like slicing or transposing (`arr.T`) simply swap or multiply stride values and adjust the memory pointer offset without copying or allocating any underlying buffer data, enabling zero-copy O(1) metadata transformations.',
    explanation: 'Stride metadata defines multi-dimensional indexing over flat 1D memory buffers.',
    formula_hint: 'Byte offset = sum(index[i] * strides[i])',
    default_marks: 2.5,
    section: 'Section A: Array Operations & Vectorization',
  },

  // ============================================================================
  // 3. Pandas (7 Questions)
  // ============================================================================
  {
    subject: 'Data Science',
    topic: 'Pandas',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which method is used in Pandas to inspect the first n rows of a DataFrame (defaulting to 5)?',
    options: [
      { id: 'a', text: 'df.head()' },
      { id: 'b', text: 'df.first()' },
      { id: 'c', text: 'df.tail()' },
      { id: 'd', text: 'df.top()' },
    ],
    correct_option_ids: ['a'],
    explanation: '`df.head(n=5)` displays the first n records of the DataFrame; `df.tail()` displays the final n records.',
    formula_hint: 'df.head(n=5)',
    default_marks: 1.0,
    section: 'Section A: DataFrame Manipulation & Indexing',
  },
  {
    subject: 'Data Science',
    topic: 'Pandas',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the key difference between `.loc[]` and `.iloc[]` indexers in Pandas?',
    options: [
      { id: 'a', text: '`.loc` is label-based indexing (inclusive of end bounds); `.iloc` is integer position-based indexing (exclusive of end bounds)' },
      { id: 'b', text: '`.loc` only selects rows; `.iloc` selects columns' },
      { id: 'c', text: '`.iloc` operates only on Series' },
      { id: 'd', text: 'Both behave identically' },
    ],
    correct_option_ids: ['a'],
    explanation: '`.loc` queries indices and columns by labels/names and includes the end slice boundary. `.iloc` queries strictly by integer offsets (0 to length-1) following standard Python slicing semantics (exclusive of end bound).',
    formula_hint: '.loc = label-based (inclusive); .iloc = integer-based (exclusive)',
    default_marks: 1.5,
    section: 'Section A: DataFrame Manipulation & Indexing',
  },
  {
    subject: 'Data Science',
    topic: 'Pandas',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'What does the `how="outer"` argument specify when executing `pd.merge(df1, df2, on="key", how="outer")`?',
    options: [
      { id: 'a', text: 'Retains only matching keys present in both DataFrames' },
      { id: 'b', text: 'Retains all keys from both DataFrames, filling unmatched fields with NaN' },
      { id: 'c', text: 'Retains keys exclusive to df1' },
      { id: 'd', text: 'Raises a merge conflict if keys are missing' },
    ],
    correct_option_ids: ['b'],
    explanation: 'An outer join takes the union of keys from both DataFrames, preserving all rows and populating missing corresponding columns with NaN.',
    formula_hint: 'Full outer join = Union of keys with NaN padding',
    default_marks: 2.0,
    section: 'Section B: Grouping, Merging & Reshaping',
  },
  {
    subject: 'Data Science',
    topic: 'Pandas',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following methods can be used to handle missing values (NaN) in a Pandas DataFrame?',
    options: [
      { id: 'a', text: 'df.dropna()' },
      { id: 'b', text: 'df.fillna(value)' },
      { id: 'c', text: 'df.interpolate()' },
      { id: 'd', text: 'df.drop_duplicates()' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: '`dropna()` drops rows/columns with nulls; `fillna()` replaces nulls with constants or statistics; `interpolate()` fills via linear/polynomial interpolation. `drop_duplicates()` removes duplicate rows, not nulls.',
    formula_hint: 'Missing data handling: dropna(), fillna(), interpolate()',
    default_marks: 2.0,
    section: 'Section A: DataFrame Manipulation & Indexing',
  },
  {
    subject: 'Data Science',
    topic: 'Pandas',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'The `groupby().agg()` method in Pandas allows applying different aggregation functions to distinct columns simultaneously.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Supplying a dictionary like `agg({"colA": "mean", "colB": ["min", "max"]})` enables targeted multi-column aggregation.',
    formula_hint: 'df.groupby("key").agg({"colA": "mean", "colB": "sum"})',
    default_marks: 1.0,
    section: 'Section B: Grouping, Merging & Reshaping',
  },
  {
    subject: 'Data Science',
    topic: 'Pandas',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What Pandas method transforms wide-format DataFrames into long-format by unpivoting columns into key-value pairs?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'pd.melt',
    explanation: '`pd.melt()` unpivots a DataFrame from wide to long format, leaving identifier variables set and unrolling value variables into variable and value columns.',
    formula_hint: 'pd.melt(df, id_vars=[...])',
    default_marks: 1.5,
    section: 'Section B: Grouping, Merging & Reshaping',
  },
  {
    subject: 'Data Science',
    topic: 'Pandas',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the difference between `df.apply()` and vectorized NumPy operations on Pandas columns, highlighting computational performance.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Vectorized NumPy operations (such as `df["A"] + df["B"]` or `np.log(df["A"])`) execute in compiled C code over contiguous memory blocks with SIMD hardware optimization, operating at near C-speeds. In contrast, `df.apply(func)` iterates row-by-row in Python user-space, invoking a Python function call frame for every single record and incurring substantial interpreter overhead. Vectorized operations are frequently 50× to 300× faster than `.apply()`.',
    explanation: 'Vectorization operates directly on compiled memory; .apply() introduces per-row Python interpreter loop overhead.',
    formula_hint: 'Vectorized C-speed >> Python user-space loop apply()',
    default_marks: 2.5,
    section: 'Section A: DataFrame Manipulation & Indexing',
  },

  // ============================================================================
  // 4. Descriptive Statistics (7 Questions)
  // ============================================================================
  {
    subject: 'Data Science',
    topic: 'Descriptive Statistics',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which measure of central tendency is most robust to extreme outliers in a skewed numerical dataset?',
    options: [
      { id: 'a', text: 'Mean' },
      { id: 'b', text: 'Median' },
      { id: 'c', text: 'Mid-range' },
      { id: 'd', text: 'Variance' },
    ],
    correct_option_ids: ['b'],
    explanation: 'The median depends solely on the order and middle value(s) of sorted data, making it invariant to extreme values at the tails, unlike the mean which is pulled toward outliers.',
    formula_hint: 'Median is the 50th percentile; immune to extreme tail shifts',
    default_marks: 1.0,
    section: 'Section A: Central Tendency & Dispersion',
  },
  {
    subject: 'Data Science',
    topic: 'Descriptive Statistics',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'In a right-skewed (positively skewed) unimodal distribution, what is the typical ordering of the three central tendency measures?',
    options: [
      { id: 'a', text: 'Mode < Median < Mean' },
      { id: 'b', text: 'Mean < Median < Mode' },
      { id: 'c', text: 'Median < Mode < Mean' },
      { id: 'd', text: 'Mean = Median = Mode' },
    ],
    correct_option_ids: ['a'],
    explanation: 'In a right-skewed distribution, extreme high values pull the mean rightward. The peak remains at the mode, and the median sits between them: Mode < Median < Mean.',
    formula_hint: 'Right-skewed: Mode < Median < Mean',
    default_marks: 1.5,
    section: 'Section A: Central Tendency & Dispersion',
  },
  {
    subject: 'Data Science',
    topic: 'Descriptive Statistics',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'According to Tukey’s boxplot rule, what threshold defines an outlier based on quartiles Q1, Q3, and Interquartile Range (IQR)?',
    options: [
      { id: 'a', text: 'Values < Q1 - 1.5 × IQR or > Q3 + 1.5 × IQR' },
      { id: 'b', text: 'Values outside ± 1 standard deviation from mean' },
      { id: 'c', text: 'Values < Q1 - 3 × IQR only' },
      { id: 'd', text: 'Values outside the 10th and 90th percentiles' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Tukey’s fences define mild outliers as data points lying below Q1 - 1.5·IQR or above Q3 + 1.5·IQR (and extreme outliers beyond 3·IQR).',
    formula_hint: 'Outlier bounds = [Q1 - 1.5(IQR), Q3 + 1.5(IQR)]',
    default_marks: 2.0,
    section: 'Section B: Distribution Shape & Outlier Detection',
  },
  {
    subject: 'Data Science',
    topic: 'Descriptive Statistics',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following statements about Pearson’s correlation coefficient r are true?',
    options: [
      { id: 'a', text: 'The value of r is strictly bounded within [-1.0, +1.0]' },
      { id: 'b', text: 'An r of 0 implies no linear relationship, but non-linear relationships may still exist' },
      { id: 'c', text: 'It is sensitive to outliers' },
      { id: 'd', text: 'Correlation directly proves causal dependency' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Pearson’s r is bounded between -1 and +1, measures only linear associations (so quadratic relationships can have r = 0), and is sensitive to outliers. Correlation does not imply causation (d is false).',
    formula_hint: '-1 ≤ r ≤ 1; measures linear association only',
    default_marks: 2.0,
    section: 'Section B: Distribution Shape & Outlier Detection',
  },
  {
    subject: 'Data Science',
    topic: 'Descriptive Statistics',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'A distribution with positive kurtosis (leptokurtic) has heavier tails and a sharper central peak than a standard normal distribution.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Excess kurtosis > 0 indicates heavier tails and higher peak density than the Gaussian bell curve (mesokurtic, excess kurtosis = 0).',
    formula_hint: 'Excess kurtosis > 0 = Leptokurtic (fat tails)',
    default_marks: 1.0,
    section: 'Section B: Distribution Shape & Outlier Detection',
  },
  {
    subject: 'Data Science',
    topic: 'Descriptive Statistics',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Compute the z-score of an observation x = 85 from a normal distribution with mean μ = 70 and standard deviation σ = 10.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '1.5',
    explanation: 'z = (x - μ) / σ = (85 - 70) / 10 = 15 / 10 = 1.5.',
    formula_hint: 'z = (x - μ) / σ',
    default_marks: 1.0,
    section: 'Section A: Central Tendency & Dispersion',
  },
  {
    subject: 'Data Science',
    topic: 'Descriptive Statistics',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain Bessel’s correction (dividing by n - 1 instead of n) when computing sample variance s².',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'When estimating population variance σ² from a sample, deviations are measured from the sample mean x̄ rather than the true unknown population mean μ. Because the sample mean minimizes the sum of squared deviations for that specific sample, ∑(x_i - x̄)² is systematically smaller than ∑(x_i - μ)², making the uncorrected formula s_n² = (1/n)∑(x_i - x̄)² a biased underestimate of σ². Bessel’s correction divides by degrees of freedom n - 1 instead of n, rendering the sample variance an unbiased estimator: E[s²] = σ².',
    explanation: 'Dividing by n - 1 corrects for the loss of 1 degree of freedom incurred by estimating the mean.',
    formula_hint: 's² = ∑(x_i - x̄)² / (n - 1)',
    default_marks: 2.5,
    section: 'Section A: Central Tendency & Dispersion',
  },

  // ============================================================================
  // 5. Probability (7 Questions)
  // ============================================================================
  {
    subject: 'Data Science',
    topic: 'Probability',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'According to the Central Limit Theorem (CLT), as sample size n increases (typically n ≥ 30), what distribution does the sample mean approach?',
    options: [
      { id: 'a', text: 'Uniform distribution' },
      { id: 'b', text: 'Normal (Gaussian) distribution' },
      { id: 'c', text: 'Poisson distribution' },
      { id: 'd', text: 'Exponential distribution' },
    ],
    correct_option_ids: ['b'],
    explanation: 'The CLT states that the sampling distribution of the sample mean approaches a normal distribution N(μ, σ²/n) regardless of the underlying population distribution shape, provided variance is finite.',
    formula_hint: 'x̄ ~ N(μ, σ²/n) as n → ∞',
    default_marks: 1.0,
    section: 'Section A: Probability Distributions & Theorems',
  },
  {
    subject: 'Data Science',
    topic: 'Probability',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'If a discrete random variable X follows a Poisson distribution with parameter λ = 4, what are the expected value E[X] and variance Var(X)?',
    options: [
      { id: 'a', text: 'E[X] = 4, Var(X) = 4' },
      { id: 'b', text: 'E[X] = 4, Var(X) = 16' },
      { id: 'c', text: 'E[X] = 4, Var(X) = 2' },
      { id: 'd', text: 'E[X] = 2, Var(X) = 4' },
    ],
    correct_option_ids: ['a'],
    explanation: 'For a Poisson distribution, the mean and variance are uniquely equal to the rate parameter λ: E[X] = Var(X) = λ = 4.',
    formula_hint: 'Poisson: E[X] = Var(X) = λ',
    default_marks: 1.5,
    section: 'Section A: Probability Distributions & Theorems',
  },
  {
    subject: 'Data Science',
    topic: 'Probability',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'What is the empirical rule percentage of values lying within ±2 standard deviations of the mean in a perfectly normal distribution?',
    options: [
      { id: 'a', text: '68.27%' },
      { id: 'b', text: '95.45%' },
      { id: 'c', text: '99.73%' },
      { id: 'd', text: '90.00%' },
    ],
    correct_option_ids: ['b'],
    explanation: 'The 68-95-99.7 rule states that ~68.3% of observations fall within ±1σ, ~95.45% fall within ±2σ, and ~99.73% fall within ±3σ.',
    formula_hint: 'Empirical Rule: ±1σ = 68.3%, ±2σ = 95.4%, ±3σ = 99.7%',
    default_marks: 2.0,
    section: 'Section A: Probability Distributions & Theorems',
  },
  {
    subject: 'Data Science',
    topic: 'Probability',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following probability distributions are continuous rather than discrete?',
    options: [
      { id: 'a', text: 'Normal distribution' },
      { id: 'b', text: 'Exponential distribution' },
      { id: 'c', text: 'Binomial distribution' },
      { id: 'd', text: 'Beta distribution' },
    ],
    correct_option_ids: ['a', 'b', 'd'],
    explanation: 'Normal, Exponential, and Beta distributions are continuous random variables defined by probability density functions (PDF). Binomial distribution is discrete (integer counts).',
    formula_hint: 'Continuous: defined over real intervals; Discrete: countable support',
    default_marks: 2.0,
    section: 'Section A: Probability Distributions & Theorems',
  },
  {
    subject: 'Data Science',
    topic: 'Probability',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'In Bayesian inference, Posterior probability is proportional to Likelihood multiplied by Prior probability.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Bayes’ theorem states P(θ | D) = [P(D | θ) · P(θ)] / P(D), which in proportional form is Posterior ∝ Likelihood × Prior.',
    formula_hint: 'P(θ | D) ∝ P(D | θ) × P(θ)',
    default_marks: 1.0,
    section: 'Section A: Probability Distributions & Theorems',
  },
  {
    subject: 'Data Science',
    topic: 'Probability',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'In hypothesis testing, rejecting a true null hypothesis (false positive) is known as a Type _____ error. (Enter I or II)',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'I',
    explanation: 'A Type I error (α) is a false positive: rejecting H₀ when H₀ is actually true. A Type II error (β) is a false negative: failing to reject H₀ when H₁ is true.',
    formula_hint: 'Type I = False positive; Type II = False negative',
    default_marks: 1.0,
    section: 'Section A: Probability Distributions & Theorems',
  },
  {
    subject: 'Data Science',
    topic: 'Probability',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Define p-value in inferential hypothesis testing and explain a common misconception regarding its interpretation.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'The p-value is the probability, assuming the null hypothesis (H₀) is strictly true, of obtaining test results at least as extreme as the observed sample data. A widespread misconception is interpreting the p-value as the probability that the null hypothesis is true (P(H₀ | Data)) or that the finding occurred by pure chance. The p-value only calculates P(Data as extreme | H₀ is true), not the posterior probability of the hypothesis.',
    explanation: 'p-value is P(extreme data | H₀), never the probability that H₀ is true.',
    formula_hint: 'p-value = P(T ≥ t_obs | H₀)',
    default_marks: 2.5,
    section: 'Section A: Probability Distributions & Theorems',
  },

  // ============================================================================
  // 6. Data Visualization (7 Questions)
  // ============================================================================
  {
    subject: 'Data Science',
    topic: 'Data Visualization',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which type of chart is best suited for visualizing the frequency distribution and continuous shape of a single numerical feature?',
    options: [
      { id: 'a', text: 'Histogram' },
      { id: 'b', text: 'Pie chart' },
      { id: 'c', text: 'Scatter plot' },
      { id: 'd', text: 'Treemap' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Histograms partition continuous data into adjacent bins and plot frequency counts, revealing skewness, modality, and dispersion.',
    formula_hint: 'Binned continuous distribution = Histogram / KDE',
    default_marks: 1.0,
    section: 'Section A: Plot Types & Chart Selection',
  },
  {
    subject: 'Data Science',
    topic: 'Data Visualization',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What feature does a box plot’s central line, box boundary, and whiskers represent?',
    options: [
      { id: 'a', text: 'Line = Median; Box = Q1 to Q3 (IQR); Whiskers = min/max within 1.5 IQR' },
      { id: 'b', text: 'Line = Mean; Box = ±1 Standard Deviation; Whiskers = ±3 Standard Deviations' },
      { id: 'c', text: 'Line = Mode; Box = 95% Confidence Interval' },
      { id: 'd', text: 'Line = Mid-range; Box = 10th to 90th percentiles' },
    ],
    correct_option_ids: ['a'],
    explanation: 'A standard Tukey box plot represents the 5-number summary: median (line), 25th percentile Q1 and 75th percentile Q3 (interquartile box), and whiskers extending to the most extreme data point within 1.5 × IQR.',
    formula_hint: 'Box = [Q1, Q3]; Center line = Median',
    default_marks: 1.5,
    section: 'Section A: Plot Types & Chart Selection',
  },
  {
    subject: 'Data Science',
    topic: 'Data Visualization',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'In Anscombe’s Quartet, four distinct datasets have nearly identical descriptive statistics (mean, variance, correlation, regression line). What fundamental data science lesson does it demonstrate?',
    options: [
      { id: 'a', text: 'Numerical summary statistics alone can be misleading without graphical visualization' },
      { id: 'b', text: 'Linear regression always fails on small sample sizes' },
      { id: 'c', text: 'Outliers should always be trimmed before modeling' },
      { id: 'd', text: 'Variance cannot be calculated for nonlinear data' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Francis Anscombe constructed the quartet in 1973 to prove that datasets with identical summary statistics can have radically different underlying distributions and relationships, underscoring the necessity of visual exploration.',
    formula_hint: 'Anscombe’s Quartet: Visual inspection reveals hidden structural patterns',
    default_marks: 2.0,
    section: 'Section B: Principles of Visual Analysis',
  },
  {
    subject: 'Data Science',
    topic: 'Data Visualization',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which Python libraries are built on top of Matplotlib to provide high-level statistical plotting interfaces?',
    options: [
      { id: 'a', text: 'Seaborn' },
      { id: 'b', text: 'Pandas built-in plotting (`df.plot`)' },
      { id: 'c', text: 'Scikit-learn' },
      { id: 'd', text: 'PyTorch' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'Seaborn and Pandas plotting leverage Matplotlib backends and objects, wrapping low-level artists in declarative statistical syntax. Scikit-learn and PyTorch are ML frameworks.',
    formula_hint: 'Seaborn and df.plot() build directly on Matplotlib',
    default_marks: 2.0,
    section: 'Section A: Plot Types & Chart Selection',
  },
  {
    subject: 'Data Science',
    topic: 'Data Visualization',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'A heatmap is commonly used to display a pairwise correlation matrix of multiple numerical features with color gradients.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. `sns.heatmap(df.corr(), annot=True)` represents pairwise correlation values mapped to a diverging color gradient.',
    formula_hint: 'sns.heatmap(df.corr())',
    default_marks: 1.0,
    section: 'Section A: Plot Types & Chart Selection',
  },
  {
    subject: 'Data Science',
    topic: 'Data Visualization',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What type of plot graphs two continuous variables against each other on Cartesian coordinates to inspect relationships and clusters?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Scatter plot',
    explanation: 'Scatter plots map individual data points on X and Y axes, making them the primary visual tool for inspecting bivariate correlations, clusters, and outliers.',
    formula_hint: 'Bivariate continuous = Scatter plot',
    default_marks: 1.0,
    section: 'Section A: Plot Types & Chart Selection',
  },
  {
    subject: 'Data Science',
    topic: 'Data Visualization',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain Edward Tufte’s "Data-Ink Ratio" concept and explain how removing "chartjunk" improves graphical integrity.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Edward Tufte defines Data-Ink Ratio as the proportion of ink used in a graphic that presents actual empirical data compared to total ink used: Data-Ink Ratio = (Data-Ink) / (Total Ink). "Chartjunk" comprises non-data elements that distract from data communication: 3D decorative effects, fake shadows, excessive heavy grid lines, redundant legends, and moiré vibration textures. Maximizing the data-ink ratio by eradicating chartjunk improves readability, clarifies patterns, and prevents visual distortion.',
    explanation: 'High data-ink ratio ensures visual elements communicate statistical information efficiently.',
    formula_hint: 'Data-Ink Ratio = Data-Ink / Total Ink',
    default_marks: 2.5,
    section: 'Section B: Principles of Visual Analysis',
  },

  // ============================================================================
  // 7. Linear Regression (7 Questions)
  // ============================================================================
  {
    subject: 'Data Science',
    topic: 'Linear Regression',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Ordinary Least Squares (OLS) regression estimates model coefficients by minimizing which objective loss function?',
    options: [
      { id: 'a', text: 'Sum of Squared Residuals (SSR)' },
      { id: 'b', text: 'Sum of Absolute Errors (MAE)' },
      { id: 'c', text: 'Log-Loss' },
      { id: 'd', text: 'Hinge Loss' },
    ],
    correct_option_ids: ['a'],
    explanation: 'OLS minimizes the residual sum of squares: ∑(y_i - ŷ_i)², providing a closed-form analytical solution via the normal equations.',
    formula_hint: 'min ∑(y_i - (β₀ + β₁ x_i))²',
    default_marks: 1.0,
    section: 'Section A: OLS & Normal Equations',
  },
  {
    subject: 'Data Science',
    topic: 'Linear Regression',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What closed-form normal equation computes the optimal parameter vector β̂ in multiple linear regression (assuming XᵀX is invertible)?',
    options: [
      { id: 'a', text: 'β̂ = (Xᵀ X)⁻¹ Xᵀ y' },
      { id: 'b', text: 'β̂ = Xᵀ (X Xᵀ)⁻¹ y' },
      { id: 'c', text: 'β̂ = (X Xᵀ)⁻¹ X y' },
      { id: 'd', text: 'β̂ = X (Xᵀ X) y' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Setting the gradient of the squared loss with respect to β to zero: ∇_β ||y - Xβ||² = -2 Xᵀ(y - Xβ) = 0 => XᵀX β = Xᵀy => β̂ = (XᵀX)⁻¹ Xᵀy.',
    formula_hint: 'β̂ = (Xᵀ X)⁻¹ Xᵀ y',
    default_marks: 1.5,
    section: 'Section A: OLS & Normal Equations',
  },
  {
    subject: 'Data Science',
    topic: 'Linear Regression',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'What diagnostic problem arises in multiple regression when two or more predictor features are highly linearly correlated with each other?',
    options: [
      { id: 'a', text: 'Multicollinearity' },
      { id: 'b', text: 'Heteroscedasticity' },
      { id: 'c', text: 'Autocorrelation' },
      { id: 'd', text: 'Under-dispersion' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Multicollinearity makes XᵀX near-singular, resulting in high variance of estimated coefficients, inflated standard errors, and unstable coefficient signs (diagnosed via Variance Inflation Factor VIF > 5–10).',
    formula_hint: 'Correlated predictors => Multicollinearity (high VIF)',
    default_marks: 2.0,
    section: 'Section B: Diagnostics & Assumptions',
  },
  {
    subject: 'Data Science',
    topic: 'Linear Regression',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following are foundational Gauss-Markov assumptions for OLS estimators to be BLUE (Best Linear Unbiased Estimators)?',
    options: [
      { id: 'a', text: 'Errors have zero conditional mean: E[ε | X] = 0' },
      { id: 'b', text: 'Homoscedasticity: Var(ε | X) = σ² (constant error variance)' },
      { id: 'c', text: 'No autocorrelation: Cov(ε_i, ε_j) = 0 for i ≠ j' },
      { id: 'd', text: 'The target variable must be strictly non-negative' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'The Gauss-Markov theorem requires linearity in parameters, random sampling, zero conditional mean, homoscedasticity, no autocorrelation, and no perfect collinearity. Target positivity is not an assumption.',
    formula_hint: 'Gauss-Markov: E[ε]=0, Var(ε)=σ²I, Cov(ε_i, ε_j)=0',
    default_marks: 2.0,
    section: 'Section B: Diagnostics & Assumptions',
  },
  {
    subject: 'Data Science',
    topic: 'Linear Regression',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Adding more predictor variables to an OLS linear regression model will never cause R² to decrease, even if the predictors are pure noise.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Additional features allow OLS to fit noise in the training set, meaning R² monotonically increases or stays constant. Adjusted R² penalizes degrees of freedom to address this.',
    formula_hint: 'R² monotonically non-decreasing with feature count',
    default_marks: 1.0,
    section: 'Section A: OLS & Normal Equations',
  },
  {
    subject: 'Data Science',
    topic: 'Linear Regression',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What diagnostic metric measures the inflation of coefficient variance due to collinearity, where values > 5–10 indicate severe issues? (Enter abbreviation)',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'VIF',
    explanation: 'Variance Inflation Factor VIF = 1 / (1 - R_j²), measuring how much the variance of an estimated regression coefficient increases when predictors are correlated.',
    formula_hint: 'VIF = 1 / (1 - R_j²)',
    default_marks: 1.0,
    section: 'Section B: Diagnostics & Assumptions',
  },
  {
    subject: 'Data Science',
    topic: 'Linear Regression',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain Heteroscedasticity, its visual manifestation in residual plots, and its consequence on OLS inference.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Heteroscedasticity occurs when the variance of the residuals ε_i is not constant across observations (violating Var(ε_i | X) = σ²). In a residual plot (residuals vs fitted values), it manifests visually as a fan-shaped or cone-shaped spread where variance expands or contracts systematically. While OLS coefficient estimates β̂ remain unbiased, the standard errors of the coefficients become biased and incorrect. This invalidates standard hypothesis tests (t-tests, F-tests) and confidence intervals, requiring heteroscedasticity-consistent robust standard errors (White’s standard errors) or weighted least squares (WLS).',
    explanation: 'Non-constant residual variance invalidates standard error estimates and statistical inference.',
    formula_hint: 'Fan-shaped residuals => Heteroscedasticity',
    default_marks: 2.5,
    section: 'Section B: Diagnostics & Assumptions',
  },

  // ============================================================================
  // 8. Classification (7 Questions)
  // ============================================================================
  {
    subject: 'Data Science',
    topic: 'Classification',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which activation/link function is used in Logistic Regression to map any real-valued number into a valid probability between 0 and 1?',
    options: [
      { id: 'a', text: 'Sigmoid (Standard Logistic) function' },
      { id: 'b', text: 'ReLU function' },
      { id: 'c', text: 'Signum function' },
      { id: 'd', text: 'Linear function' },
    ],
    correct_option_ids: ['a'],
    explanation: 'The sigmoid function σ(z) = 1 / (1 + e⁻ᶻ) maps the real line (-∞, +∞) onto the open interval (0, 1), representing P(y=1 | x).',
    formula_hint: 'σ(z) = 1 / (1 + e^(-z))',
    default_marks: 1.0,
    section: 'Section A: Logistic Regression & Probabilistic Models',
  },
  {
    subject: 'Data Science',
    topic: 'Classification',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Why is the Naive Bayes classifier called "naive"?',
    options: [
      { id: 'a', text: 'It assumes that all features are mutually conditionally independent given the class label' },
      { id: 'b', text: 'It assumes that data has no outliers' },
      { id: 'c', text: 'It cannot handle categorical variables' },
      { id: 'd', text: 'It does not use prior probabilities' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Naive Bayes assumes conditional independence among features given class y: P(x₁, x₂, ..., x_n | y) = ∏ P(x_i | y), a simplifying assumption that is rarely strictly true in real data.',
    formula_hint: 'P(X|y) = ∏ P(x_i | y)',
    default_marks: 1.5,
    section: 'Section A: Logistic Regression & Probabilistic Models',
  },
  {
    subject: 'Data Science',
    topic: 'Classification',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'Support Vector Machines (SVM) find the optimal separating hyperplane by maximizing which geometric quantity?',
    options: [
      { id: 'a', text: 'The margin of separation between the closest training points (support vectors) of opposite classes' },
      { id: 'b', text: 'The entropy between classes' },
      { id: 'c', text: 'The variance of projected data points' },
      { id: 'd', text: 'The log-likelihood of class probabilities' },
    ],
    correct_option_ids: ['a'],
    explanation: 'SVM is a maximum-margin classifier: it finds the hyperplane that maximizes the geometric distance 2 / ||w|| to the closest support vectors of each class.',
    formula_hint: 'Max margin = 2 / ||w|| <=> min 1/2 ||w||²',
    default_marks: 2.0,
    section: 'Section B: SVM & Decision Trees',
  },
  {
    subject: 'Data Science',
    topic: 'Classification',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which splitting criteria are commonly used by Decision Tree algorithms to evaluate candidate splits for classification tasks?',
    options: [
      { id: 'a', text: 'Gini Impurity (used in CART)' },
      { id: 'b', text: 'Information Gain / Entropy (used in ID3, C4.5)' },
      { id: 'c', text: 'Mean Squared Error' },
      { id: 'd', text: 'Classification Error Rate' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'Classification trees evaluate impurity reduction using Gini Impurity (CART) or Shannon Entropy / Information Gain (C4.5). MSE is used for regression trees.',
    formula_hint: 'Gini = 1 - ∑ p_i²; Entropy = -∑ p_i log₂(p_i)',
    default_marks: 2.0,
    section: 'Section B: SVM & Decision Trees',
  },
  {
    subject: 'Data Science',
    topic: 'Classification',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'In the K-Nearest Neighbors (KNN) classification algorithm, scaling numerical features (e.g. via standardization) is essential because distance metrics like Euclidean distance are sensitive to feature scales.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Distance-based algorithms like KNN calculate distances across dimensions: features with larger numerical magnitudes dominate the distance calculations unless standardized.',
    formula_hint: 'KNN uses Euclidean distance d = √(∑(x_i - y_i)²)',
    default_marks: 1.0,
    section: 'Section B: SVM & Decision Trees',
  },
  {
    subject: 'Data Science',
    topic: 'Classification',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What mathematical technique allows Support Vector Machines to operate in high-dimensional implicit feature spaces without explicitly computing coordinates? (Enter two words)',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Kernel trick',
    explanation: 'The kernel trick replaces dot products ⟨Φ(x), Φ(z)⟩ in higher-dimensional Hilbert spaces with an evaluation of a kernel function K(x, z) (e.g. RBF, Polynomial) in input space.',
    formula_hint: 'K(x, z) = ⟨Φ(x), Φ(z)⟩',
    default_marks: 1.5,
    section: 'Section B: SVM & Decision Trees',
  },
  {
    subject: 'Data Science',
    topic: 'Classification',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the difference between Hard-Margin and Soft-Margin Support Vector Machines and describe the role of the C hyperparameter.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'A Hard-Margin SVM assumes data is strictly linearly separable with zero margin violations, requiring all points to satisfy y_i(w·x_i + b) ≥ 1; it fails completely on non-separable or noisy datasets. A Soft-Margin SVM introduces slack variables ξ_i ≥ 0, allowing some points to violate the margin or be misclassified. The objective becomes: min 1/2 ||w||² + C ∑ ξ_i. The regularization hyperparameter C controls the tradeoff: a large C penalizes margin violations heavily (narrow margin, risks overfitting); a small C tolerates more violations to prioritize a wider, more generalizable margin (risks underfitting).',
    explanation: 'Soft-margin balances margin width with slack penalty controlled by C.',
    formula_hint: 'min 1/2 ||w||² + C ∑ ξ_i',
    default_marks: 2.5,
    section: 'Section B: SVM & Decision Trees',
  },

  // ============================================================================
  // 9. Model Evaluation (7 Questions)
  // ============================================================================
  {
    subject: 'Data Science',
    topic: 'Model Evaluation',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the formula for Classification Accuracy based on a confusion matrix containing TP, TN, FP, and FN?',
    options: [
      { id: 'a', text: '(TP + TN) / (TP + TN + FP + FN)' },
      { id: 'b', text: 'TP / (TP + FP)' },
      { id: 'c', text: 'TP / (TP + FN)' },
      { id: 'd', text: '2TP / (2TP + FP + FN)' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Accuracy is the ratio of correct predictions (True Positives + True Negatives) to total predictions made.',
    formula_hint: 'Accuracy = (TP + TN) / Total',
    default_marks: 1.0,
    section: 'Section A: Classification Metrics & Validation',
  },
  {
    subject: 'Data Science',
    topic: 'Model Evaluation',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'A medical diagnostic test has high Recall (Sensitivity) but low Precision. What does this mean in clinical practice?',
    options: [
      { id: 'a', text: 'It catches almost all true sick patients, but produces many false alarm positive diagnoses' },
      { id: 'b', text: 'It produces very few false alarms, but misses many sick patients' },
      { id: 'c', text: 'The model has high accuracy on imbalanced data' },
      { id: 'd', text: 'The model is completely random' },
    ],
    correct_option_ids: ['a'],
    explanation: 'High recall (TP / (TP + FN)) means false negatives are rare (nearly all disease cases are detected). Low precision (TP / (TP + FP)) means many healthy individuals are falsely flagged positive.',
    formula_hint: 'Recall = TP / (TP + FN); Precision = TP / (TP + FP)',
    default_marks: 1.5,
    section: 'Section A: Classification Metrics & Validation',
  },
  {
    subject: 'Data Science',
    topic: 'Model Evaluation',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'What two rates are plotted against each other on the axes of a Receiver Operating Characteristic (ROC) curve across varying classification thresholds?',
    options: [
      { id: 'a', text: 'True Positive Rate (y-axis) vs False Positive Rate (x-axis)' },
      { id: 'b', text: 'Precision (y-axis) vs Recall (x-axis)' },
      { id: 'c', text: 'True Positive Rate vs True Negative Rate' },
      { id: 'd', text: 'Accuracy vs Threshold' },
    ],
    correct_option_ids: ['a'],
    explanation: 'The ROC curve plots True Positive Rate (Sensitivity, y-axis) against False Positive Rate (1 - Specificity, x-axis) across all possible decision thresholds from 0 to 1.',
    formula_hint: 'ROC: TPR vs FPR; AUC = Area Under Curve',
    default_marks: 2.0,
    section: 'Section A: Classification Metrics & Validation',
  },
  {
    subject: 'Data Science',
    topic: 'Model Evaluation',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following metrics are specifically designed for evaluating numerical continuous regression models?',
    options: [
      { id: 'a', text: 'Root Mean Squared Error (RMSE)' },
      { id: 'b', text: 'Mean Absolute Percentage Error (MAPE)' },
      { id: 'c', text: 'F1-Score' },
      { id: 'd', text: 'Log-Loss' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'RMSE, MAE, and MAPE evaluate regression predictions. F1-Score and Log-Loss evaluate classification predictions.',
    formula_hint: 'Regression metrics: MSE, RMSE, MAE, R², MAPE',
    default_marks: 2.0,
    section: 'Section B: Regression Metrics & Cross-Validation',
  },
  {
    subject: 'Data Science',
    topic: 'Model Evaluation',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Stratified K-Fold cross-validation ensures that each fold maintains approximately the same percentage of samples of each target class as the complete dataset.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Stratification prevents class distribution skews across training/validation splits, which is critical for imbalanced classification.',
    formula_hint: 'Stratified K-Fold preserves class ratios across splits',
    default_marks: 1.0,
    section: 'Section A: Classification Metrics & Validation',
  },
  {
    subject: 'Data Science',
    topic: 'Model Evaluation',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'The harmonic mean of Precision and Recall is known as the _____ score. (Enter letter and hyphen)',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'F1',
    explanation: 'The F1 score = 2 · (Precision · Recall) / (Precision + Recall), providing a balanced harmonic summary metric that penalizes extreme imbalances.',
    formula_hint: 'F1 = 2 · P · R / (P + R)',
    default_marks: 1.0,
    section: 'Section A: Classification Metrics & Validation',
  },
  {
    subject: 'Data Science',
    topic: 'Model Evaluation',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain why ROC-AUC can present an overly optimistic assessment of model performance on severely imbalanced datasets, and describe what alternative metric should be used.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'In severely imbalanced datasets (e.g. 99.9% negative class, 0.1% positive class in fraud detection), the False Positive Rate (FPR = FP / (FP + TN)) has an enormous True Negative denominator. Even if thousands of false alarms occur (large FP), FPR remains small because TN dominates the denominator. This keeps the ROC curve close to the top-left corner, giving an inflated ROC-AUC (>0.95). In such cases, the Precision-Recall curve (PR-AUC / Average Precision) should be used instead: Precision directly compares true positives against false positives without including true negatives in the calculation.',
    explanation: 'Large TN denominator masks high false positive counts in ROC-AUC; PR-AUC isolates minority class performance.',
    formula_hint: 'Imbalanced data: PR-AUC preferred over ROC-AUC',
    default_marks: 2.5,
    section: 'Section A: Classification Metrics & Validation',
  },

  // ============================================================================
  // 10. Machine Learning Fundamentals (7 Questions)
  // ============================================================================
  {
    subject: 'Data Science',
    topic: 'Machine Learning Fundamentals',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'In the Bias-Variance tradeoff, a model that suffers from high bias typically exhibits which behavior?',
    options: [
      { id: 'a', text: 'Underfitting: fails to capture the underlying pattern of both training and testing data' },
      { id: 'b', text: 'Overfitting: fits training data perfectly but fails to generalize to testing data' },
      { id: 'c', text: 'High sensitivity to minor training data fluctuations' },
      { id: 'd', text: 'Zero training error' },
    ],
    correct_option_ids: ['a'],
    explanation: 'High bias stems from oversimplified modeling assumptions, leading to underfitting with high error on both training and test data.',
    formula_hint: 'High Bias = Underfitting; High Variance = Overfitting',
    default_marks: 1.0,
    section: 'Section A: Bias-Variance & Generalization',
  },
  {
    subject: 'Data Science',
    topic: 'Machine Learning Fundamentals',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the distinguishing feature of L1 Regularization (Lasso) compared to L2 Regularization (Ridge)?',
    options: [
      { id: 'a', text: 'L1 adds the sum of absolute values of coefficients, driving non-essential coefficients strictly to zero (inducing sparsity)' },
      { id: 'b', text: 'L1 adds the sum of squared coefficients' },
      { id: 'c', text: 'L1 cannot be used with gradient descent' },
      { id: 'd', text: 'L2 produces exact sparse feature selection' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Lasso adds λ ∑ |β_j| to the loss function. The diamond-shaped L1 constraint geometry forces corner solutions along coordinate axes, shrinking non-informative feature coefficients to exactly zero for automatic feature selection.',
    formula_hint: 'Lasso: L1 penalty λ ∑ |β| => Sparse weights',
    default_marks: 1.5,
    section: 'Section B: Regularization & Ensembles',
  },
  {
    subject: 'Data Science',
    topic: 'Machine Learning Fundamentals',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'What is the fundamental architectural difference between Bagging (e.g. Random Forest) and Boosting (e.g. XGBoost, AdaBoost)?',
    options: [
      { id: 'a', text: 'Bagging trains diverse base learners in parallel on bootstrap samples to reduce variance; Boosting trains base learners sequentially, where each model focuses on errors of previous models to reduce bias' },
      { id: 'b', text: 'Bagging trains sequentially to reduce bias; Boosting trains in parallel' },
      { id: 'c', text: 'Bagging only works with decision trees' },
      { id: 'd', text: 'Boosting increases variance without affecting bias' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Bagging (Bootstrap Aggregation) reduces variance by averaging predictions of independent parallel models trained on bootstrap subsets. Boosting fits sequential weak learners to the pseudo-residuals of predecessors, reducing bias.',
    formula_hint: 'Bagging = Parallel, variance reduction; Boosting = Sequential, bias reduction',
    default_marks: 2.0,
    section: 'Section B: Regularization & Ensembles',
  },
  {
    subject: 'Data Science',
    topic: 'Machine Learning Fundamentals',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following techniques help prevent overfitting in machine learning models?',
    options: [
      { id: 'a', text: 'Cross-validation' },
      { id: 'b', text: 'L1/L2 Regularization' },
      { id: 'c', text: 'Early stopping during gradient descent' },
      { id: 'd', text: 'Training indefinitely on training data with zero regularization' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Cross-validation, regularization penalties, and early stopping halt model over-specialization on training noise. Training indefinitely without constraints promotes overfitting.',
    formula_hint: 'Regularization + Early stopping + CV mitigate overfitting',
    default_marks: 2.0,
    section: 'Section A: Bias-Variance & Generalization',
  },
  {
    subject: 'Data Science',
    topic: 'Machine Learning Fundamentals',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'K-Means clustering is an unsupervised machine learning algorithm that groups unlabeled data into k clusters by minimizing within-cluster sum of squares (inertia).',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. K-Means iterates assignment of points to the closest cluster centroid and recalculation of centroids to minimize inertia without target labels.',
    formula_hint: 'min ∑ ||x_i - μ_k||²',
    default_marks: 1.0,
    section: 'Section A: Unsupervised Learning',
  },
  {
    subject: 'Data Science',
    topic: 'Machine Learning Fundamentals',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What unsupervised dimensionality reduction technique finds orthogonal axes of maximal variance using eigendecomposition or SVD? (Enter abbreviation)',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'PCA',
    explanation: 'Principal Component Analysis (PCA) projects data onto orthogonal eigenvectors of the covariance matrix corresponding to the largest eigenvalues.',
    formula_hint: 'PCA maximizes projection variance',
    default_marks: 1.0,
    section: 'Section A: Unsupervised Learning',
  },
  {
    subject: 'Data Science',
    topic: 'Machine Learning Fundamentals',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Decompose expected test error into its three mathematical components: Bias, Variance, and Irreducible Error.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'For a true data-generating process y = f(x) + ε where E[ε] = 0 and Var(ε) = σ_ε², the expected mean squared prediction error of a model f̂(x) decomposes into: E[(y - f̂(x))²] = [Bias(f̂(x))]² + Var(f̂(x)) + σ_ε².\n1. Bias²: [E[f̂(x)] - f(x)]² represents the systematic error introduced by simplifying approximations.\n2. Variance: E[(f̂(x) - E[f̂(x)])²] measures how much predictions fluctuate across different training sets.\n3. Irreducible Error: σ_ε² represents inherent ambient noise in the data that no model can eliminate.',
    explanation: 'Expected test error = Bias² + Variance + Irreducible Error.',
    formula_hint: 'E[MSE] = Bias² + Variance + σ²',
    default_marks: 2.5,
    section: 'Section A: Bias-Variance & Generalization',
  },
];
