/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { CurriculumQuestion } from './types.js';

export const ENGLISH_QUESTIONS: CurriculumQuestion[] = [
  // ============================================================================
  // 1. Grammar (10 Questions)
  // ============================================================================
  {
    subject: 'English',
    topic: 'Grammar',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Choose the correct verb form: "Neither the manager nor the employees _____ present at yesterday’s meeting."',
    options: [
      { id: 'a', text: 'were' },
      { id: 'b', text: 'was' },
      { id: 'c', text: 'is' },
      { id: 'd', text: 'are' },
    ],
    correct_option_ids: ['a'],
    explanation: 'When subjects are joined by "neither... nor", the verb agrees in person and number with the closer subject ("employees", which is plural), and past tense is indicated by "yesterday". Thus, "were" is correct.',
    formula_hint: 'Rule of proximity: verb agrees with the nearest subject',
    default_marks: 1.0,
    section: 'Section A: Syntax & Agreement',
  },
  {
    subject: 'English',
    topic: 'Grammar',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Identify the mood of the underlined verb: "If I *were* you, I would accept the scholarship immediately."',
    options: [
      { id: 'a', text: 'Subjunctive mood' },
      { id: 'b', text: 'Indicative mood' },
      { id: 'c', text: 'Imperative mood' },
      { id: 'd', text: 'Interrogative mood' },
    ],
    correct_option_ids: ['a'],
    explanation: 'The past subjunctive "were" expresses a hypothetical, counter-to-fact, or unreal present condition.',
    formula_hint: 'Counterfactual hypothetical = Subjunctive mood',
    default_marks: 1.5,
    section: 'Section A: Syntax & Agreement',
  },
  {
    subject: 'English',
    topic: 'Grammar',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'Which sentence correctly utilizes the past perfect tense to express the earlier of two completed past actions?',
    options: [
      { id: 'a', text: 'The train had already departed before we arrived at the station.' },
      { id: 'b', text: 'The train departed before we had arrived at the station.' },
      { id: 'c', text: 'The train already departed before we were arriving.' },
      { id: 'd', text: 'The train has departed before we arrived.' },
    ],
    correct_option_ids: ['a'],
    explanation: 'The past perfect tense ("had departed") is required for the earlier of two completed events in the past, while the subsequent past event takes the simple past ("arrived").',
    formula_hint: 'Earlier past event: Had + Past Participle (V3)',
    default_marks: 2.0,
    section: 'Section B: Tenses & Voice',
  },
  {
    subject: 'English',
    topic: 'Grammar',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following sentences contain correct grammatical subject-verb agreement?',
    options: [
      { id: 'a', text: 'A bouquet of yellow roses was delivered to her doorstep.' },
      { id: 'b', text: 'The committee has submitted its final annual report.' },
      { id: 'c', text: 'Ten miles is a long distance to walk in the snow.' },
      { id: 'd', text: 'Each of the participants have received a certificate.' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'In (a), subject is singular "bouquet" -> "was". In (b), collective noun "committee" acting as single entity takes singular verb "has". In (c), quantity of distance "Ten miles" treated as a single measurement takes "is". (d) is incorrect because "Each" is singular and requires "has received".',
    formula_hint: 'Prepositional phrases do not change the subject number',
    default_marks: 2.0,
    section: 'Section A: Syntax & Agreement',
  },
  {
    subject: 'English',
    topic: 'Grammar',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'A gerund is a non-finite verb form ending in "-ing" that functions as a noun in a sentence.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Gerunds (e.g. "Swimming is great exercise") are formed with verb + -ing and function syntactically as subjects, direct objects, or objects of prepositions.',
    formula_hint: 'Gerund = Verb + -ing functioning as Noun',
    default_marks: 1.0,
    section: 'Section A: Syntax & Agreement',
  },
  {
    subject: 'English',
    topic: 'Grammar',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Fill in the appropriate preposition: "The professor abstained _____ voting during the department election."',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'from',
    explanation: 'The verb "abstain" is followed by the fixed preposition "from" (e.g. abstain from voting / drinking).',
    formula_hint: 'Fixed preposition: Abstain from',
    default_marks: 1.0,
    section: 'Section A: Syntax & Agreement',
  },
  {
    subject: 'English',
    topic: 'Grammar',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What type of clause is introduced by subordinating conjunctions such as "although", "because", or "since"?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Subordinate clause',
    explanation: 'Subordinate (or dependent) clauses cannot stand alone as complete sentences and provide qualifying circumstantial detail to the main clause.',
    formula_hint: 'Subordinating conjunctions introduce Dependent/Subordinate clauses',
    default_marks: 1.0,
    section: 'Section A: Syntax & Agreement',
  },
  {
    subject: 'English',
    topic: 'Grammar',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Identify the part of speech of the word "enthusiastically" in the sentence: "The audience clapped enthusiastically."',
    options: [
      { id: 'a', text: 'Adverb' },
      { id: 'b', text: 'Adjective' },
      { id: 'c', text: 'Verb' },
      { id: 'd', text: 'Noun' },
    ],
    correct_option_ids: ['a'],
    explanation: '"Enthusiastically" modifies the verb "clapped", describing manner, making it an adverb.',
    formula_hint: 'Modifies verb = Adverb',
    default_marks: 1.0,
    section: 'Section A: Syntax & Agreement',
  },
  {
    subject: 'English',
    topic: 'Grammar',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Differentiate between the active voice and passive voice, and explain when passive voice is stylistically preferred in academic writing.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'In active voice, the grammatical subject performs the action denoted by the verb ("Dr. Smith analyzed the samples"). In passive voice, the subject is the recipient of the action while the agent is omitted or placed in a prepositional phrase ("The samples were analyzed by Dr. Smith"). Passive voice is preferred in scientific and academic writing when: 1. The action or research finding is more important than the individual researcher; 2. The actor/agent is unknown, irrelevant, or obvious from context; 3. Maintaining objective distance and focus on experimental procedures (e.g., "The solution was heated to 100 °C").',
    explanation: 'Passive shifts topical focus to the patient/result rather than the human actor.',
    formula_hint: 'Active: Subject does action; Passive: Subject receives action (Object promoted)',
    default_marks: 2.5,
    section: 'Section B: Tenses & Voice',
  },
  {
    subject: 'English',
    topic: 'Grammar',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'Explain conditional sentences in English, describing the structure and usage of Zero, First, Second, and Third conditionals.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '1. Zero Conditional: Expresses universal truths and scientific facts. Structure: If + Simple Present, ... Simple Present. Example: "If water reaches 100 °C, it boils."\n2. First Conditional: Expresses real, plausible future possibilities. Structure: If + Simple Present, ... will + bare infinitive. Example: "If it rains tomorrow, we will postpone the match."\n3. Second Conditional: Expresses unreal, hypothetical, or improbable present/future situations. Structure: If + Simple Past (were for subjunctive), ... would/could + bare infinitive. Example: "If I had a million dollars, I would travel around the world."\n4. Third Conditional: Expresses counterfactual regret or impossible alternatives about the past. Structure: If + Past Perfect, ... would have + past participle. Example: "If she had studied harder, she would have passed the examination."',
    explanation: 'Comprehensive taxonomy of English conditional mood and syntactic structures.',
    formula_hint: 'Zero: Pr+Pr; First: Pr+Will; Second: Pa+Would; Third: Had V3+Would have V3',
    default_marks: 4.0,
    section: 'Section B: Tenses & Voice',
  },

  // ============================================================================
  // 2. Vocabulary (10 Questions)
  // ============================================================================
  {
    subject: 'English',
    topic: 'Vocabulary',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the meaning of the word "benevolent"?',
    options: [
      { id: 'a', text: 'Well-meaning, kind, and charitable' },
      { id: 'b', text: 'Hostile and aggressive' },
      { id: 'c', text: 'Secretive and deceptive' },
      { id: 'd', text: 'Indifferent and aloof' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Derived from Latin bene (well) + volens (wishing), benevolent means characterized by goodwill and charitable intent.',
    formula_hint: 'Prefix "bene-" = good/well',
    default_marks: 1.0,
    section: 'Section A: Lexical Semantics & Word Origins',
  },
  {
    subject: 'English',
    topic: 'Vocabulary',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Which word best describes an attitude of unwavering, stubborn refusal to change one’s opinion?',
    options: [
      { id: 'a', text: 'Obdurate' },
      { id: 'b', text: 'Pliable' },
      { id: 'c', text: 'Vacillating' },
      { id: 'd', text: 'Gregarious' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Obdurate means stubbornly refusing to change one’s opinion or course of action; recalcitrant, intractable.',
    formula_hint: 'Latin "obdurare" = to harden',
    default_marks: 1.5,
    section: 'Section A: Lexical Semantics & Word Origins',
  },
  {
    subject: 'English',
    topic: 'Vocabulary',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'The term "ephemeral" refers to something that is:',
    options: [
      { id: 'a', text: 'Lasting for a very short, transient time' },
      { id: 'b', text: 'Everlasting and permanent' },
      { id: 'c', text: 'Unclear and ambiguous' },
      { id: 'd', text: 'Physically massive' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Ephemeral means fleeting, transient, or momentary (e.g. ephemeral pleasures).',
    formula_hint: 'Greek "ephemeros" = lasting only a day',
    default_marks: 2.0,
    section: 'Section A: Lexical Semantics & Word Origins',
  },
  {
    subject: 'English',
    topic: 'Vocabulary',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following words signify excessive praise, flattery, or subservient admiration?',
    options: [
      { id: 'a', text: 'Sycophancy' },
      { id: 'b', text: 'Adulation' },
      { id: 'c', text: 'Invective' },
      { id: 'd', text: 'Obsequiousness' },
    ],
    correct_option_ids: ['a', 'b', 'd'],
    explanation: 'Sycophancy, adulation, and obsequiousness describe servile flattery or excessive praise. Invective refers to harsh, abusive language.',
    formula_hint: 'Sycophant/Adulation = fawning praise',
    default_marks: 2.0,
    section: 'Section A: Lexical Semantics & Word Origins',
  },
  {
    subject: 'English',
    topic: 'Vocabulary',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'An "oxymoron" is a figure of speech in which two contradictory terms appear in conjunction (e.g. "deafening silence").',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. An oxymoron pairs contradictory words to reveal a paradoxical rhetorical truth (e.g. "bittersweet", "open secret").',
    formula_hint: 'Oxymoron = conjoined contradictory terms',
    default_marks: 1.0,
    section: 'Section B: Rhetorical & Literary Devices',
  },
  {
    subject: 'English',
    topic: 'Vocabulary',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What word denotes a person who dislikes humankind and avoids human society?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Misanthrope',
    explanation: 'From Greek misein (to hate) + anthropos (human), a misanthrope is someone who distrusts or dislikes humankind.',
    formula_hint: 'Mis- (hate) + anthropos (human)',
    default_marks: 1.0,
    section: 'Section A: Lexical Semantics & Word Origins',
  },
  {
    subject: 'English',
    topic: 'Vocabulary',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What adjective describes something that is present, appearing, or found everywhere simultaneously (omnipresent)?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Ubiquitous',
    explanation: 'Ubiquitous means existing or being everywhere at the same time; widespread or pervasive.',
    formula_hint: 'Latin "ubique" = everywhere',
    default_marks: 1.0,
    section: 'Section A: Lexical Semantics & Word Origins',
  },
  {
    subject: 'English',
    topic: 'Vocabulary',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What does the idiom "burn the midnight oil" mean?',
    options: [
      { id: 'a', text: 'To work or study late into the night' },
      { id: 'b', text: 'To waste resources recklessly' },
      { id: 'c', text: 'To cause an accidental fire' },
      { id: 'd', text: 'To sleep excessively' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Originating from using oil lamps to read after dark, "burn the midnight oil" means laboring late into the night.',
    formula_hint: 'Idiom: work late into night',
    default_marks: 1.0,
    section: 'Section B: Idioms & Phrasal Expressions',
  },
  {
    subject: 'English',
    topic: 'Vocabulary',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the difference between "denotation" and "connotation" using the words "cheap" and "inexpensive" as examples.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Denotation is the explicit, objective dictionary definition of a word. Connotation refers to the emotional, cultural, or evaluative associations that a word carries beyond its literal meaning. For example, "cheap" and "inexpensive" share the identical denotation: low in monetary price. However, "cheap" carries a negative connotation of shoddy craftsmanship, poor durability, or stinginess, whereas "inexpensive" carries a neutral or positive connotation of good financial value, affordability, and thrift.',
    explanation: 'Denotation is literal meaning; connotation is affective tone and cultural nuance.',
    formula_hint: 'Denotation = Dictionary meaning; Connotation = Emotional nuance',
    default_marks: 2.5,
    section: 'Section A: Lexical Semantics & Word Origins',
  },
  {
    subject: 'English',
    topic: 'Vocabulary',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Choose the word that accurately completes the analogy: Candid : Deceptive :: Taciturn : _____?',
    options: [
      { id: 'a', text: 'Loquacious' },
      { id: 'b', text: 'Reserved' },
      { id: 'c', text: 'Reticent' },
      { id: 'd', text: 'Laconic' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Candid (honest/frank) is the antonym of Deceptive. Taciturn (silent/untalkative) is the antonym of Loquacious (talkative).',
    formula_hint: 'Antonym analogy: A is opposite of B, so C is opposite of D',
    default_marks: 1.5,
    section: 'Section A: Lexical Semantics & Word Origins',
  },

  // ============================================================================
  // 3. Sentence Correction (10 Questions)
  // ============================================================================
  {
    subject: 'English',
    topic: 'Sentence Correction',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Identify the error in: "She has been living in London since five years."',
    options: [
      { id: 'a', text: 'Replace "since" with "for"' },
      { id: 'b', text: 'Replace "has been living" with "is living"' },
      { id: 'c', text: 'Replace "in" with "at"' },
      { id: 'd', text: 'No error' },
    ],
    correct_option_ids: ['a'],
    explanation: '"For" is used with a duration/period of time ("for five years"), whereas "since" is reserved for a specific point in time in the past ("since 2018").',
    formula_hint: '"For" + period of time; "Since" + starting point',
    default_marks: 1.0,
    section: 'Section A: Error Detection & Correction',
  },
  {
    subject: 'English',
    topic: 'Sentence Correction',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Select the grammatically correct sentence free of dangling modifier errors:',
    options: [
      { id: 'a', text: 'Walking down the foggy street, the clock tower loomed in the distance.' },
      { id: 'b', text: 'Walking down the foggy street, we saw the clock tower looming in the distance.' },
      { id: 'c', text: 'Walking down the foggy street, the cold air froze our breath.' },
      { id: 'd', text: 'Walking down the foggy street, our footsteps echoed.' },
    ],
    correct_option_ids: ['b'],
    explanation: 'In (a), (c), and (d), the participial phrase "Walking down the foggy street" incorrectly modifies "clock tower", "air", or "footsteps" (which cannot walk). In (b), the modifier logically modifies "we", who are actually walking.',
    formula_hint: 'Participial modifier must logically describe the immediate subject',
    default_marks: 1.5,
    section: 'Section A: Error Detection & Correction',
  },
  {
    subject: 'English',
    topic: 'Sentence Correction',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'Choose the sentence with correct parallel grammatical construction:',
    options: [
      { id: 'a', text: 'The internship gave her experience in researching cases, drafting briefs, and interviewing clients.' },
      { id: 'b', text: 'The internship gave her experience in researching cases, to draft briefs, and client interviews.' },
      { id: 'c', text: 'The internship gave her experience in research, drafting briefs, and how to interview clients.' },
      { id: 'd', text: 'The internship gave her experience to research, drafting briefs, and clients.' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Parallel structure requires items in a series to share the same grammatical form: "researching", "drafting", and "interviewing" are all parallel gerund phrases.',
    formula_hint: 'Parallelism: items in a series must maintain identical grammatical form',
    default_marks: 2.0,
    section: 'Section A: Error Detection & Correction',
  },
  {
    subject: 'English',
    topic: 'Sentence Correction',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following sentences contain misplaced modifier errors?',
    options: [
      { id: 'a', text: 'Covered in chocolate sauce, the child ate the ice cream sundae.' },
      { id: 'b', text: 'The child ate the ice cream sundae covered in chocolate sauce.' },
      { id: 'c', text: 'She served sandwiches to the children on paper plates.' },
      { id: 'd', text: 'On paper plates, she served sandwiches to the children.' },
    ],
    correct_option_ids: ['a', 'c'],
    explanation: 'In (a), "Covered in chocolate sauce" erroneously modifies "the child". In (c), "on paper plates" erroneously modifies "the children" instead of "sandwiches". Sentences (b) and (d) place modifiers appropriately.',
    formula_hint: 'Modifiers must be placed nearest to the words they modify',
    default_marks: 2.0,
    section: 'Section A: Error Detection & Correction',
  },
  {
    subject: 'English',
    topic: 'Sentence Correction',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'In standard formal English, "Scarcely had we entered the hall when the lecture began" is a grammatically valid sentence using negative inversion.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Negative/limiting adverbs (scarcely, hardly, barely) trigger subject-auxiliary inversion ("had we entered") and correlate with "when".',
    formula_hint: 'Scarcely/Hardly + had + S + V3 ... when ...',
    default_marks: 1.0,
    section: 'Section A: Error Detection & Correction',
  },
  {
    subject: 'English',
    topic: 'Sentence Correction',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Correct the pronoun error: "Between you and _____, the proposal needs substantial revision." (Enter I or me)',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'me',
    explanation: '"Between" is a preposition, and objects of prepositions must be in the objective case ("between you and me", never "between you and I").',
    formula_hint: 'Preposition requires objective pronoun case: between you and me',
    default_marks: 1.0,
    section: 'Section A: Error Detection & Correction',
  },
  {
    subject: 'English',
    topic: 'Sentence Correction',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What punctuation mark is used to link two closely related independent clauses without a coordinating conjunction?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Semicolon',
    explanation: 'A semicolon (;) joins two complete independent clauses that are conceptually related, avoiding a comma splice.',
    formula_hint: 'Independent clause; independent clause',
    default_marks: 1.0,
    section: 'Section A: Error Detection & Correction',
  },
  {
    subject: 'English',
    topic: 'Sentence Correction',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Identify the error in: "The climate of San Diego is warmer than Seattle."',
    options: [
      { id: 'a', text: 'Faulty comparison: compare "climate" with "that of Seattle"' },
      { id: 'b', text: 'Use "more warm" instead of "warmer"' },
      { id: 'c', text: 'Change "is" to "was"' },
      { id: 'd', text: 'No error' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Comparing "the climate of San Diego" directly to the city "Seattle" is an illogical comparison. It must read: "warmer than that of Seattle" or "warmer than Seattle’s climate".',
    formula_hint: 'Compare equivalent entities: climate vs climate ("that of")',
    default_marks: 1.0,
    section: 'Section A: Error Detection & Correction',
  },
  {
    subject: 'English',
    topic: 'Sentence Correction',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain what constitutes a "comma splice" and demonstrate two standard methods to correct it.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'A comma splice is a grammatical run-on error that occurs when two independent clauses are joined by a comma without an accompanying coordinating conjunction (e.g., "The weather was stormy, the flight was delayed"). Two standard correction methods: 1. Add a coordinating conjunction (FANBOYS) after the comma: "The weather was stormy, so the flight was delayed." 2. Replace the comma with a semicolon or period: "The weather was stormy; the flight was delayed." or "The weather was stormy. The flight was delayed."',
    explanation: 'Comma splices join independent clauses with inadequate connective syntax.',
    formula_hint: 'Fix comma splice: comma + FANBOYS, semicolon, or period',
    default_marks: 2.5,
    section: 'Section A: Error Detection & Correction',
  },
  {
    subject: 'English',
    topic: 'Sentence Correction',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Which sentence correctly avoids a split infinitive where separation creates awkward ambiguity?',
    options: [
      { id: 'a', text: 'He decided to carefully review the contract before signing.' },
      { id: 'b', text: 'He decided carefully to review the contract before signing.' },
      { id: 'c', text: 'He decided to review the contract carefully before signing.' },
      { id: 'd', text: 'Carefully he decided to review the contract before signing.' },
    ],
    correct_option_ids: ['c'],
    explanation: 'Placing the adverb "carefully" after the object ("review the contract carefully") maintains clarity and elegance without awkward separation of "to" and "review" or squinting modification.',
    formula_hint: 'Clear modifier placement avoiding awkward infinitive splitting',
    default_marks: 1.5,
    section: 'Section A: Error Detection & Correction',
  },

  // ============================================================================
  // 4. Reading Comprehension (10 Questions)
  // ============================================================================
  {
    subject: 'English',
    topic: 'Reading Comprehension',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'In expository reading passages, what is typically the primary function of a "topic sentence" in a paragraph?',
    options: [
      { id: 'a', text: 'To state the main idea or controlling focus of that paragraph' },
      { id: 'b', text: 'To present detailed statistical data' },
      { id: 'c', text: 'To provide a counterargument' },
      { id: 'd', text: 'To cite external references' },
    ],
    correct_option_ids: ['a'],
    explanation: 'A topic sentence encapsulates the central theme or argument of a paragraph, which the remaining supporting sentences develop.',
    formula_hint: 'Topic sentence = Core controlling idea of paragraph',
    default_marks: 1.0,
    section: 'Section A: Textual Analysis & Inference',
  },
  {
    subject: 'English',
    topic: 'Reading Comprehension',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Passage excerpt: "While the initial clinical trials demonstrated statistical efficacy, subsequent longitudinal follow-ups revealed that the therapeutic benefits degraded substantially after six months." What is the author’s primary purpose?',
    options: [
      { id: 'a', text: 'To qualify the long-term effectiveness of the therapy' },
      { id: 'b', text: 'To celebrate a definitive medical breakthrough' },
      { id: 'c', text: 'To dismiss the validity of initial clinical trials' },
      { id: 'd', text: 'To demand the immediate ban of the drug' },
    ],
    correct_option_ids: ['a'],
    explanation: 'The author acknowledges short-term success ("statistical efficacy") while adding a critical caveat regarding long-term durability, thereby qualifying the overall effectiveness.',
    formula_hint: 'Author purpose: Qualifying a claim with balanced evidence',
    default_marks: 1.5,
    section: 'Section A: Textual Analysis & Inference',
  },
  {
    subject: 'English',
    topic: 'Reading Comprehension',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'When an author adopts an "objective and detached" tone in an analytical essay, which stylistic feature is most likely absent?',
    options: [
      { id: 'a', text: 'Emotional, hyperbolic adjectives and first-person polemics' },
      { id: 'b', text: 'Empirical data and factual citations' },
      { id: 'c', text: 'Balanced evaluation of alternative hypotheses' },
      { id: 'd', text: 'Complex sentence structures' },
    ],
    correct_option_ids: ['a'],
    explanation: 'An objective, detached tone avoids passionate, emotional vocabulary, hyperbole, and personal polemical bias in favor of neutral evidence-based prose.',
    formula_hint: 'Objective tone excludes emotional polemics',
    default_marks: 2.0,
    section: 'Section A: Textual Analysis & Inference',
  },
  {
    subject: 'English',
    topic: 'Reading Comprehension',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following reading strategies are recommended for efficient synthesis during timed reading comprehension tests?',
    options: [
      { id: 'a', text: 'Skimming the opening and concluding paragraphs to identify the thesis' },
      { id: 'b', text: 'Tracking transition signal words (e.g. however, consequently, furthermore)' },
      { id: 'c', text: 'Reading every single supporting example with equal slow intensity' },
      { id: 'd', text: 'Distinguishing between factual claims and authorial opinions' },
    ],
    correct_option_ids: ['a', 'b', 'd'],
    explanation: 'Skimming thesis frames (a), following discourse transition markers (b), and separating opinion from fact (d) are proven reading comprehension techniques. Spending equal time on minor illustrative examples (c) is inefficient.',
    formula_hint: 'Active reading strategies: transitions, thesis mapping, fact vs opinion',
    default_marks: 2.0,
    section: 'Section A: Textual Analysis & Inference',
  },
  {
    subject: 'English',
    topic: 'Reading Comprehension',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'An inference in reading comprehension is a conclusion logically derived from stated premises, even if it is not explicitly written word-for-word in the text.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. An inference is an unstated truth logically deduced from explicit contextual clues and evidence.',
    formula_hint: 'Inference = Evidence + Logical deduction',
    default_marks: 1.0,
    section: 'Section A: Textual Analysis & Inference',
  },
  {
    subject: 'English',
    topic: 'Reading Comprehension',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What term describes an author’s attitude or emotional perspective toward the subject matter conveyed through word choice?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Tone',
    explanation: 'Tone reflects the author’s stance (e.g. skeptical, earnest, satirical, nostalgic) as manifested in diction, syntax, and imagery.',
    formula_hint: 'Author’s emotional stance = Tone',
    default_marks: 1.0,
    section: 'Section A: Textual Analysis & Inference',
  },
  {
    subject: 'English',
    topic: 'Reading Comprehension',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What rhetorical device repeats consonant sounds at the beginning of adjacent or closely connected words (e.g. "wild and woolly")?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Alliteration',
    explanation: 'Alliteration is the repetition of initial consonant sounds in neighboring words to create auditory rhythm and emphasis.',
    formula_hint: 'Repeated initial consonant sounds = Alliteration',
    default_marks: 1.0,
    section: 'Section B: Rhetorical & Literary Devices',
  },
  {
    subject: 'English',
    topic: 'Reading Comprehension',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is a metaphor?',
    options: [
      { id: 'a', text: 'A direct comparison of two dissimilar things without using "like" or "as"' },
      { id: 'b', text: 'A comparison that explicitly uses "like" or "as"' },
      { id: 'c', text: 'An intentional gross exaggeration for dramatic effect' },
      { id: 'd', text: 'The attribution of human traits to inanimate objects' },
    ],
    correct_option_ids: ['a'],
    explanation: 'A metaphor asserts that one thing is another (e.g. "Time is a thief"), whereas a simile uses "like" or "as".',
    formula_hint: 'Direct comparison without like/as = Metaphor',
    default_marks: 1.0,
    section: 'Section B: Rhetorical & Literary Devices',
  },
  {
    subject: 'English',
    topic: 'Reading Comprehension',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the difference between a passage’s "Main Idea" and its "Theme", providing an example of each.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'The Main Idea is the specific, concrete argument or factual summary of what the text is predominantly about (text-specific). The Theme is a broader, universal philosophical insight or underlying human truth that transcends the specific narrative characters or events. Example: In The Old Man and the Sea, the Main Idea is "an aging Cuban fisherman battles an enormous marlin alone in the Gulf Stream for days." The universal Theme is "the resilience of the human spirit in the face of struggle and defeat."',
    explanation: 'Main idea is specific text content; theme is the universal conceptual message.',
    formula_hint: 'Main Idea = Text-specific plot/thesis; Theme = Universal insight',
    default_marks: 2.5,
    section: 'Section A: Textual Analysis & Inference',
  },
  {
    subject: 'English',
    topic: 'Reading Comprehension',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Which transition phrase signals that the author is about to present a concession or opposing perspective?',
    options: [
      { id: 'a', text: 'On the other hand' },
      { id: 'b', text: 'Furthermore' },
      { id: 'c', text: 'In addition' },
      { id: 'd', text: 'Consequently' },
    ],
    correct_option_ids: ['a'],
    explanation: '"On the other hand", "conversely", and "nevertheless" signal contrast or concession. "Furthermore" and "in addition" indicate continuation; "consequently" indicates cause/effect.',
    formula_hint: 'Contrasting transition: On the other hand, However, Conversely',
    default_marks: 1.0,
    section: 'Section A: Textual Analysis & Inference',
  },

  // ============================================================================
  // 5. Synonyms & Antonyms (10 Questions)
  // ============================================================================
  {
    subject: 'English',
    topic: 'Synonyms & Antonyms',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which word is the closest synonym for "METICULOUS"?',
    options: [
      { id: 'a', text: 'Scrupulous' },
      { id: 'b', text: 'Careless' },
      { id: 'c', text: 'Hasty' },
      { id: 'd', text: 'Ambiguous' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Meticulous means showing great attention to detail; very careful and precise (scrupulous, punctilious).',
    formula_hint: 'Meticulous = Scrupulous, painstaking',
    default_marks: 1.0,
    section: 'Section A: Synonyms & Antonyms',
  },
  {
    subject: 'English',
    topic: 'Synonyms & Antonyms',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Which word is the most accurate antonym for "BELLIGERENT"?',
    options: [
      { id: 'a', text: 'Pacific' },
      { id: 'b', text: 'Pugnacious' },
      { id: 'c', text: 'Contentious' },
      { id: 'd', text: 'Truculent' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Belligerent means hostile and aggressive. Pacific means peace-loving or inclined to peace, making it the antonym. Pugnacious and truculent are synonyms.',
    formula_hint: 'Belligerent (warlike) <-> Pacific (peaceful)',
    default_marks: 1.5,
    section: 'Section A: Synonyms & Antonyms',
  },
  {
    subject: 'English',
    topic: 'Synonyms & Antonyms',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'Select the pair of words that are ANTONYMS of each other:',
    options: [
      { id: 'a', text: 'Ephemeral — Perennial' },
      { id: 'b', text: 'Furtive — Surreptitious' },
      { id: 'c', text: 'Copious — Profuse' },
      { id: 'd', text: 'Audacious — Bold' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Ephemeral means short-lived or transient; perennial means enduring or perpetual. All other pairs are near-synonyms.',
    formula_hint: 'Ephemeral (fleeting) vs Perennial (enduring)',
    default_marks: 2.0,
    section: 'Section A: Synonyms & Antonyms',
  },
  {
    subject: 'English',
    topic: 'Synonyms & Antonyms',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following words are valid synonyms for "LUCID"?',
    options: [
      { id: 'a', text: 'Intelligible' },
      { id: 'b', text: 'Pellucid' },
      { id: 'c', text: 'Coherent' },
      { id: 'd', text: 'Obscure' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Lucid means clear, easily understood, and rational (intelligible, pellucid, coherent). Obscure is an antonym.',
    formula_hint: 'Lucid = clear, coherent, transparent',
    default_marks: 2.0,
    section: 'Section A: Synonyms & Antonyms',
  },
  {
    subject: 'English',
    topic: 'Synonyms & Antonyms',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: '"Nadir" (the lowest point) is the exact antonym of "Zenith" (the highest point).',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Zenith represents the celestial culmination or highest peak, while nadir denotes the celestial bottom or lowest depth.',
    formula_hint: 'Zenith (peak) <-> Nadir (trough)',
    default_marks: 1.0,
    section: 'Section A: Synonyms & Antonyms',
  },
  {
    subject: 'English',
    topic: 'Synonyms & Antonyms',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Provide an antonym for "VERBOSE" beginning with the letter "C": _____ (e.g. concise).',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Concise',
    explanation: 'Verbose means using or expressed in more words than needed. Concise means giving a lot of information clearly and in few words.',
    formula_hint: 'Verbose (wordy) <-> Concise (brief and clear)',
    default_marks: 1.0,
    section: 'Section A: Synonyms & Antonyms',
  },
  {
    subject: 'English',
    topic: 'Synonyms & Antonyms',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What is the synonym of "PRAGMATIC"?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Practical',
    explanation: 'Pragmatic means dealing with matters realistically and sensibly based on practical rather than theoretical considerations.',
    formula_hint: 'Pragmatic = Practical, realistic',
    default_marks: 1.0,
    section: 'Section A: Synonyms & Antonyms',
  },
  {
    subject: 'English',
    topic: 'Synonyms & Antonyms',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which word is an antonym for "CANDID"?',
    options: [
      { id: 'a', text: 'Disingenuous' },
      { id: 'b', text: 'Frank' },
      { id: 'c', text: 'Blunt' },
      { id: 'd', text: 'Forthright' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Candid means truthful and straightforward. Disingenuous means insincere, deceitful, or hypocritical.',
    formula_hint: 'Candid (honest) <-> Disingenuous (insincere)',
    default_marks: 1.0,
    section: 'Section A: Synonyms & Antonyms',
  },
  {
    subject: 'English',
    topic: 'Synonyms & Antonyms',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the difference in connotation between the synonyms "arrogant", "confident", and "presumptuous".',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'While all three words describe someone’s belief in their abilities, they possess radically different evaluative connotations: "Confident" has a positive connotation of healthy, justified self-assurance and poise. "Arrogant" has a negative connotation of an overbearing sense of superiority, condescension, and disdain for others. "Presumptuous" carries a specific negative connotation of overstepping boundaries of propriety, etiquette, or authority by taking too much for granted without permission.',
    explanation: 'Nuanced semantic distinctions among related personality adjectives.',
    formula_hint: 'Confident (positive assurance) vs Arrogant (superiority) vs Presumptuous (overstepping)',
    default_marks: 2.5,
    section: 'Section A: Synonyms & Antonyms',
  },
  {
    subject: 'English',
    topic: 'Synonyms & Antonyms',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the closest synonym for "ANOMALOUS"?',
    options: [
      { id: 'a', text: 'Atypical' },
      { id: 'b', text: 'Uniform' },
      { id: 'c', text: 'Predictable' },
      { id: 'd', text: 'Conventional' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Anomalous means deviating from what is standard, normal, or expected; atypical, irregular, aberrant.',
    formula_hint: 'Anomalous = Atypical, abnormal',
    default_marks: 1.0,
    section: 'Section A: Synonyms & Antonyms',
  },

  // ============================================================================
  // 6. Writing Skills (10 Questions)
  // ============================================================================
  {
    subject: 'English',
    topic: 'Writing Skills',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Where is the thesis statement typically positioned in a formal five-paragraph academic essay?',
    options: [
      { id: 'a', text: 'At or near the end of the introductory paragraph' },
      { id: 'b', text: 'In the middle of the second body paragraph' },
      { id: 'c', text: 'As the very first sentence of the conclusion' },
      { id: 'd', text: 'In the title only' },
    ],
    correct_option_ids: ['a'],
    explanation: 'In standard academic prose, the introductory paragraph moves from general context to narrow focus, positioning the definitive thesis statement as the final sentence of the introduction.',
    formula_hint: 'Thesis placement: end of introductory paragraph',
    default_marks: 1.0,
    section: 'Section A: Composition & Cohesion',
  },
  {
    subject: 'English',
    topic: 'Writing Skills',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Which transitional device best establishes a cause-and-effect logical relationship between two paragraphs?',
    options: [
      { id: 'a', text: 'Consequently' },
      { id: 'b', text: 'Meanwhile' },
      { id: 'c', text: 'For instance' },
      { id: 'd', text: 'Admittedly' },
    ],
    correct_option_ids: ['a'],
    explanation: '"Consequently", "as a result", and "therefore" establish causal progression. "Meanwhile" indicates temporal simultaneity; "for instance" indicates exemplification; "admittedly" indicates concession.',
    formula_hint: 'Causal transition = Consequently, As a result',
    default_marks: 1.5,
    section: 'Section A: Composition & Cohesion',
  },
  {
    subject: 'English',
    topic: 'Writing Skills',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'In Aristotle’s classical rhetoric, what are the three modes of persuasion?',
    options: [
      { id: 'a', text: 'Ethos (credibility), Pathos (emotion), and Logos (logic)' },
      { id: 'b', text: 'Thesis, Antithesis, and Synthesis' },
      { id: 'c', text: 'Introduction, Body, and Conclusion' },
      { id: 'd', text: 'Diction, Syntax, and Tone' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Aristotle’s Rhetoric identifies the three appeals: Ethos (moral character and credibility of speaker), Pathos (emotional appeal to the audience), and Logos (reasoning and factual proof).',
    formula_hint: 'Rhetorical appeals = Ethos, Pathos, Logos',
    default_marks: 2.0,
    section: 'Section B: Rhetoric & Style',
  },
  {
    subject: 'English',
    topic: 'Writing Skills',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following practices enhance sentence variety and stylistic fluency in expository writing?',
    options: [
      { id: 'a', text: 'Varying sentence openings with adverbial phrases and participial clauses' },
      { id: 'b', text: 'Alternating between simple, compound, and complex sentence structures' },
      { id: 'c', text: 'Starting every single sentence with the subject-verb formula "The author states..."' },
      { id: 'd', text: 'Controlling sentence length to create rhetorical cadence and emphasis' },
    ],
    correct_option_ids: ['a', 'b', 'd'],
    explanation: 'Varying sentence openers, diversifying syntactic complexity (simple/compound/complex), and modulating cadence enrich prose style. Monotonous repetitive openers (c) deaden readability.',
    formula_hint: 'Sentence variety combines differing lengths and syntactic structures',
    default_marks: 2.0,
    section: 'Section B: Rhetoric & Style',
  },
  {
    subject: 'English',
    topic: 'Writing Skills',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'In formal academic writing, contractions (such as "can’t", "won’t", and "shouldn’t") should generally be avoided in favor of full words.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Standard academic style manuals (APA, MLA, Chicago) recommend spelling out words ("cannot", "will not") to preserve formal tone.',
    formula_hint: 'Formal academic style avoids colloquial contractions',
    default_marks: 1.0,
    section: 'Section B: Rhetoric & Style',
  },
  {
    subject: 'English',
    topic: 'Writing Skills',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What organizational acronym is commonly used for paragraph structure: Point, Evidence, Explanation, _____?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Link',
    explanation: 'PEEL paragraph structure stands for Point, Evidence, Explanation, and Link (linking back to the overall thesis or transitioning to the next paragraph).',
    formula_hint: 'PEEL: Point, Evidence, Explanation, Link',
    default_marks: 1.0,
    section: 'Section A: Composition & Cohesion',
  },
  {
    subject: 'English',
    topic: 'Writing Skills',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What term describes unintentional repetition of words or ideas that adds no new meaning (e.g. "free gift" or "past history")?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Tautology',
    explanation: 'Tautology (or pleonasm / redundancy) is the needless repetition of an idea using different words that express what has already been stated.',
    formula_hint: 'Needless conceptual repetition = Tautology',
    default_marks: 1.0,
    section: 'Section B: Rhetoric & Style',
  },
  {
    subject: 'English',
    topic: 'Writing Skills',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which sentence best exemplifies concise, direct prose without bureaucratic wordiness?',
    options: [
      { id: 'a', text: 'We must quickly resolve the budget deficit.' },
      { id: 'b', text: 'It is of the utmost importance that a resolution with respect to the deficit of our budget be reached in an expeditious manner.' },
      { id: 'c', text: 'Due to the fact that money is short, action must be taken immediately at this point in time.' },
      { id: 'd', text: 'There is a necessity for us to make a decision quickly.' },
    ],
    correct_option_ids: ['a'],
    explanation: '(a) uses strong active verbs and eliminates circumlocutions, wordy nominalizations, and padding.',
    formula_hint: 'Concise style favors active verbs over nominalizations',
    default_marks: 1.0,
    section: 'Section B: Rhetoric & Style',
  },
  {
    subject: 'English',
    topic: 'Writing Skills',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the difference between a "summary" and a "synthesis" in literature review writing.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'A summary is a concise, objective restatement of the main points of a single individual text or study, organized source-by-source. A synthesis integrates multiple diverse sources and studies together, identifying overarching themes, agreements, contradictions, and gaps across literature. While a summary says "Author A found X; Author B found Y", a synthesis says "Although Authors A and B agree that X occurs, their divergent methodologies produce conflicting explanations regarding Y, suggesting that Z remains unaddressed."',
    explanation: 'Summary is source-by-source reduction; synthesis weaves multiple sources into a coherent analytical argument.',
    formula_hint: 'Summary = Restate one source; Synthesis = Integrate multiple sources',
    default_marks: 2.5,
    section: 'Section A: Composition & Cohesion',
  },
  {
    subject: 'English',
    topic: 'Writing Skills',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'Describe the key components of an argumentative essay, explaining how to effectively construct and refute a counterargument (rebuttal).',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '1. Introduction: Hooks the reader, establishes relevant contextual background, and articulates a clear, arguable, and falsifiable thesis statement.\n2. Body Paragraphs: Each structured with a clear claim/point (topic sentence), backed by credible empirical evidence (statistics, scholarly studies, citations), and supported by critical analysis explaining how evidence proves the claim.\n3. Counterargument and Rebuttal: Anticipating objections is essential for persuasive credibility. First, the writer fairly and accurately presents an opposing viewpoint (concession) without creating a straw man fallacy. Second, the writer immediately follows with a cogent rebuttal: demonstrating why the counterargument is flawed, based on outdated data, logically inconsistent, or outweighed by greater positive consequences.\n4. Conclusion: Re-synthesizes the main claims in a fresh light without simple verbatim repetition, underscores the broader significance of the argument, and offers a compelling final call to action or thought-provoking takeaway.',
    explanation: 'Comprehensive architectural framework of persuasive argumentation and rebuttal.',
    formula_hint: 'Intro (Thesis) -> Claims + Evidence -> Concession & Rebuttal -> Synthesis Conclusion',
    default_marks: 4.0,
    section: 'Section B: Rhetoric & Style',
  },
];
