/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { CurriculumQuestion } from './types.js';

export const MATHEMATICS_QUESTIONS: CurriculumQuestion[] = [
  // ============================================================================
  // 1. Sets (6 Questions)
  // ============================================================================
  {
    subject: 'Mathematics',
    topic: 'Sets',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'If set A has 5 elements, how many subsets does the power set P(A) contain?',
    options: [
      { id: 'a', text: '10' },
      { id: 'b', text: '25' },
      { id: 'c', text: '32' },
      { id: 'd', text: '64' },
    ],
    correct_option_ids: ['c'],
    explanation: 'The cardinality of the power set of any finite set with n elements is |P(A)| = 2ⁿ. Here, 2⁵ = 32.',
    formula_hint: '|P(A)| = 2^n',
    default_marks: 1.0,
    section: 'Section A: Set Theory Basics',
  },
  {
    subject: 'Mathematics',
    topic: 'Sets',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'In a group of 100 students, 60 study Mathematics, 45 study Physics, and 20 study both. How many study neither subject?',
    options: [
      { id: 'a', text: '15' },
      { id: 'b', text: '25' },
      { id: 'c', text: '35' },
      { id: 'd', text: '5' },
    ],
    correct_option_ids: ['a'],
    explanation: 'By the Principle of Inclusion-Exclusion: n(M ∪ P) = n(M) + n(P) - n(M ∩ P) = 60 + 45 - 20 = 85. Neither = Total - n(M ∪ P) = 100 - 85 = 15.',
    formula_hint: 'n(A ∪ B) = n(A) + n(B) - n(A ∩ B)',
    default_marks: 1.5,
    section: 'Section A: Set Theory Basics',
  },
  {
    subject: 'Mathematics',
    topic: 'Sets',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'For any two sets A and B, which set expression is identically equal to the symmetric difference A Δ B?',
    options: [
      { id: 'a', text: '(A ∪ B) \\ (A ∩ B)' },
      { id: 'b', text: '(A ∩ B) \\ (A ∪ B)' },
      { id: 'c', text: 'A \\ B' },
      { id: 'd', text: '(A ∪ B) ∩ (A \\ B)' },
    ],
    correct_option_ids: ['a'],
    explanation: 'The symmetric difference contains elements in either A or B but not in both, which is precisely (A \\ B) ∪ (B \\ A) = (A ∪ B) \\ (A ∩ B).',
    formula_hint: 'A Δ B = (A ∪ B) \\ (A ∩ B)',
    default_marks: 2.0,
    section: 'Section B: Set Operations & Logic',
  },
  {
    subject: 'Mathematics',
    topic: 'Sets',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following statements represent De Morgan’s Laws in set theory?',
    options: [
      { id: 'a', text: '(A ∪ B)′ = A′ ∩ B′' },
      { id: 'b', text: '(A ∩ B)′ = A′ ∪ B′' },
      { id: 'c', text: '(A ∪ B)′ = A′ ∪ B′' },
      { id: 'd', text: 'A \\ (B ∪ C) = (A \\ B) ∩ (A \\ C)' },
    ],
    correct_option_ids: ['a', 'b', 'd'],
    explanation: 'Statements (a) and (b) are De Morgan’s laws for complements. Statement (d) is the set difference equivalent of De Morgan’s law. Statement (c) is false.',
    formula_hint: '(A ∪ B)′ = A′ ∩ B′, (A ∩ B)′ = A′ ∪ B′',
    default_marks: 2.0,
    section: 'Section B: Set Operations & Logic',
  },
  {
    subject: 'Mathematics',
    topic: 'Sets',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'The empty set ∅ is a subset of every set.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Vacuously, for any set A, the condition "for all x ∈ ∅, x ∈ A" is true since there is no element in ∅ to violate it. Hence ∅ ⊆ A for every set A.',
    formula_hint: '∅ ⊆ A for all sets A',
    default_marks: 1.0,
    section: 'Section A: Set Theory Basics',
  },
  {
    subject: 'Mathematics',
    topic: 'Sets',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'Define what it means for two sets to be disjoint and give a formal mathematical condition.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Two sets A and B are said to be disjoint if and only if they have no common elements, meaning their intersection is the empty set: A ∩ B = ∅.',
    explanation: 'Disjoint sets represent mutually exclusive collections with zero overlap.',
    formula_hint: 'A ∩ B = ∅',
    default_marks: 2.0,
    section: 'Section A: Set Theory Basics',
  },

  // ============================================================================
  // 2. Relations & Functions (6 Questions)
  // ============================================================================
  {
    subject: 'Mathematics',
    topic: 'Relations & Functions',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'A relation R on a set A is an equivalence relation if and only if it is:',
    options: [
      { id: 'a', text: 'Reflexive and symmetric only' },
      { id: 'b', text: 'Reflexive, symmetric, and transitive' },
      { id: 'c', text: 'Symmetric and transitive only' },
      { id: 'd', text: 'Reflexive and antisymmetric' },
    ],
    correct_option_ids: ['b'],
    explanation: 'By standard mathematical definition, an equivalence relation partitions a set into disjoint equivalence classes and must satisfy reflexivity (aRa), symmetry (aRb => bRa), and transitivity (aRb and bRc => aRc).',
    formula_hint: 'Equivalence = Reflexive + Symmetric + Transitive',
    default_marks: 1.0,
    section: 'Section A: Relations & Equivalence',
  },
  {
    subject: 'Mathematics',
    topic: 'Relations & Functions',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'If f: R → R is defined by f(x) = 2x + 5, what is the inverse function f⁻¹(x)?',
    options: [
      { id: 'a', text: '(x - 5) / 2' },
      { id: 'b', text: '(x + 5) / 2' },
      { id: 'c', text: '2x - 5' },
      { id: 'd', text: '1 / (2x + 5)' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Let y = 2x + 5. Solving for x gives 2x = y - 5 => x = (y - 5)/2. Replacing y with x gives f⁻¹(x) = (x - 5)/2.',
    formula_hint: 'y = f(x) => x = f⁻¹(y)',
    default_marks: 1.5,
    section: 'Section B: Function Types & Inverses',
  },
  {
    subject: 'Mathematics',
    topic: 'Relations & Functions',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'Let A have 4 elements and B have 3 elements. How many surjective (onto) functions can be formed from A to B?',
    options: [
      { id: 'a', text: '24' },
      { id: 'b', text: '36' },
      { id: 'c', text: '81' },
      { id: 'd', text: '64' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Using the formula for onto functions from m=4 to n=3: ∑_{k=0}^{3} (-1)^k · C(3,k) · (3-k)⁴ = 3⁴ - 3(2⁴) + 3(1⁴) = 81 - 3(16) + 3(1) = 81 - 48 + 3 = 36.',
    formula_hint: 'Onto count = ∑ (-1)^k C(n,k) (n-k)^m',
    default_marks: 2.0,
    section: 'Section B: Function Types & Inverses',
  },
  {
    subject: 'Mathematics',
    topic: 'Relations & Functions',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'A function f: A → B is invertible if and only if it is both injective (one-to-one) and surjective (onto).',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. A bijection (both one-to-one and onto) ensures that every element in codomain B has a unique pre-image in domain A, guaranteeing a well-defined inverse function f⁻¹: B → A.',
    formula_hint: 'Bijective <=> Invertible',
    default_marks: 1.0,
    section: 'Section B: Function Types & Inverses',
  },
  {
    subject: 'Mathematics',
    topic: 'Relations & Functions',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'If f(x) = x² + 1 and g(x) = 2x - 3, calculate the composite value (f ∘ g)(2).',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '2',
    explanation: 'First evaluate inner function: g(2) = 2(2) - 3 = 4 - 3 = 1. Then evaluate outer function: f(g(2)) = f(1) = 1² + 1 = 2.',
    formula_hint: '(f ∘ g)(x) = f(g(x))',
    default_marks: 1.5,
    section: 'Section B: Function Types & Inverses',
  },
  {
    subject: 'Mathematics',
    topic: 'Relations & Functions',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Define an injective (one-to-one) function and prove whether f: R → R defined by f(x) = 3x - 7 is injective.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'A function f: A → B is injective if f(x₁) = f(x₂) implies x₁ = x₂ for all x₁, x₂ ∈ A. To prove for f(x) = 3x - 7: assume f(x₁) = f(x₂). Then 3x₁ - 7 = 3x₂ - 7. Adding 7 to both sides gives 3x₁ = 3x₂. Dividing by 3 gives x₁ = x₂. Because f(x₁) = f(x₂) strictly implies x₁ = x₂, the function is strictly injective.',
    explanation: 'Direct algebraic verification shows unique outputs for distinct inputs.',
    formula_hint: 'f(a) = f(b) => a = b',
    default_marks: 2.5,
    section: 'Section B: Function Types & Inverses',
  },

  // ============================================================================
  // 3. Trigonometry (6 Questions)
  // ============================================================================
  {
    subject: 'Mathematics',
    topic: 'Trigonometry',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the exact value of sin(15°)?',
    options: [
      { id: 'a', text: '(√6 - √2) / 4' },
      { id: 'b', text: '(√6 + √2) / 4' },
      { id: 'c', text: '(√3 - 1) / 2' },
      { id: 'd', text: '(√3 + 1) / (2√2)' },
    ],
    correct_option_ids: ['a'],
    explanation: 'sin(15°) = sin(45° - 30°) = sin 45° cos 30° - cos 45° sin 30° = (1/√2)(√3/2) - (1/√2)(1/2) = (√3 - 1) / (2√2) = (√6 - √2) / 4.',
    formula_hint: 'sin(A - B) = sin A cos B - cos A sin B',
    default_marks: 1.0,
    section: 'Section A: Trigonometric Identities',
  },
  {
    subject: 'Mathematics',
    topic: 'Trigonometry',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'If tan θ = 3/4 and θ lies in the third quadrant, what is the value of cos θ?',
    options: [
      { id: 'a', text: '4/5' },
      { id: 'b', text: '-4/5' },
      { id: 'c', text: '-3/5' },
      { id: 'd', text: '3/5' },
    ],
    correct_option_ids: ['b'],
    explanation: 'In the third quadrant, both sine and cosine are negative while tangent is positive. Using sec² θ = 1 + tan² θ = 1 + 9/16 = 25/16 => sec θ = -5/4 => cos θ = -4/5.',
    formula_hint: 'cos θ = -1 / √(1 + tan² θ) in Q3',
    default_marks: 1.5,
    section: 'Section A: Trigonometric Identities',
  },
  {
    subject: 'Mathematics',
    topic: 'Trigonometry',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'What is the general solution for the trigonometric equation sin(2x) = cos(x)?',
    options: [
      { id: 'a', text: 'x = nπ + π/2 or x = nπ + (-1)ⁿ π/6' },
      { id: 'b', text: 'x = 2nπ ± π/3' },
      { id: 'c', text: 'x = nπ/2' },
      { id: 'd', text: 'x = nπ ± π/4' },
    ],
    correct_option_ids: ['a'],
    explanation: '2 sin x cos x - cos x = 0 => cos x (2 sin x - 1) = 0. Either cos x = 0 => x = nπ + π/2, or sin x = 1/2 => x = nπ + (-1)ⁿ(π/6).',
    formula_hint: 'sin 2x = 2 sin x cos x',
    default_marks: 2.0,
    section: 'Section B: Trigonometric Equations',
  },
  {
    subject: 'Mathematics',
    topic: 'Trigonometry',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following expressions are equivalent to cos(2θ)?',
    options: [
      { id: 'a', text: 'cos² θ - sin² θ' },
      { id: 'b', text: '2 cos² θ - 1' },
      { id: 'c', text: '1 - 2 sin² θ' },
      { id: 'd', text: '(1 - tan² θ) / (1 + tan² θ)' },
    ],
    correct_option_ids: ['a', 'b', 'c', 'd'],
    explanation: 'All four formulas are standard valid double-angle identities for cos(2θ), derived from Euler’s formula and standard Pythagorean identities.',
    formula_hint: 'cos 2θ = cos² θ - sin² θ = 2 cos² θ - 1 = 1 - 2 sin² θ',
    default_marks: 2.0,
    section: 'Section A: Trigonometric Identities',
  },
  {
    subject: 'Mathematics',
    topic: 'Trigonometry',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'The principal value branch of arcsin(x) is [-π/2, π/2].',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. To make sine bijective, domain is restricted to [-π/2, π/2], which defines the principal range of y = arcsin(x).',
    formula_hint: 'Range of arcsin(x) = [-π/2, π/2]',
    default_marks: 1.0,
    section: 'Section B: Inverse Trigonometry',
  },
  {
    subject: 'Mathematics',
    topic: 'Trigonometry',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Evaluate the exact numerical value of tan(45°) + cos(60°). (Express as a decimal)',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '1.5',
    explanation: 'tan(45°) = 1 and cos(60°) = 1/2 = 0.5. Sum = 1 + 0.5 = 1.5.',
    formula_hint: 'tan 45° = 1, cos 60° = 0.5',
    default_marks: 1.0,
    section: 'Section A: Trigonometric Identities',
  },

  // ============================================================================
  // 4. Complex Numbers (6 Questions)
  // ============================================================================
  {
    subject: 'Mathematics',
    topic: 'Complex Numbers',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the modulus of the complex number z = 3 - 4i?',
    options: [
      { id: 'a', text: '7' },
      { id: 'b', text: '5' },
      { id: 'c', text: '1' },
      { id: 'd', text: '25' },
    ],
    correct_option_ids: ['b'],
    explanation: '|z| = √(a² + b²) = √(3² + (-4)²) = √(9 + 16) = √25 = 5.',
    formula_hint: '|z| = √(Re(z)² + Im(z)²)',
    default_marks: 1.0,
    section: 'Section A: Complex Arithmetic & Modulus',
  },
  {
    subject: 'Mathematics',
    topic: 'Complex Numbers',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the principal argument (arg z ∈ (-π, π]) of the complex number z = -1 + i√3?',
    options: [
      { id: 'a', text: 'π/3' },
      { id: 'b', text: '2π/3' },
      { id: 'c', text: '-2π/3' },
      { id: 'd', text: '5π/6' },
    ],
    correct_option_ids: ['b'],
    explanation: 'z lies in the second quadrant (Re < 0, Im > 0). tan α = |√3 / (-1)| = √3 => α = π/3. In quadrant II, arg(z) = π - α = π - π/3 = 2π/3.',
    formula_hint: 'arg(z) = π - arctan(|y/x|) in Quadrant II',
    default_marks: 1.5,
    section: 'Section A: Polar Form & Arguments',
  },
  {
    subject: 'Mathematics',
    topic: 'Complex Numbers',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'If ω is a non-real complex cube root of unity (ω³ = 1, ω ≠ 1), what is the value of (1 + ω - ω²)⁷?',
    options: [
      { id: 'a', text: '128' },
      { id: 'b', text: '-128 ω²' },
      { id: 'c', text: '128 ω' },
      { id: 'd', text: '-128' },
    ],
    correct_option_ids: ['b'],
    explanation: 'From 1 + ω + ω² = 0, we have 1 + ω = -ω². Thus 1 + ω - ω² = -ω² - ω² = -2ω². Raising to the 7th power: (-2ω²)⁷ = (-2)⁷ · ω¹⁴ = -128 · (ω³)⁴ · ω² = -128 ω².',
    formula_hint: '1 + ω + ω² = 0, ω³ = 1',
    default_marks: 2.0,
    section: 'Section B: Roots of Unity & De Moivre',
  },
  {
    subject: 'Mathematics',
    topic: 'Complex Numbers',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following statements about complex conjugate z̄ of z = x + iy are true?',
    options: [
      { id: 'a', text: 'z · z̄ = |z|²' },
      { id: 'b', text: 'z + z̄ = 2 Re(z)' },
      { id: 'c', text: 'z - z̄ = 2i Im(z)' },
      { id: 'd', text: '|z| = |z̄|' },
    ],
    correct_option_ids: ['a', 'b', 'c', 'd'],
    explanation: 'All four properties are fundamental identities of complex conjugation: (x+iy)(x-iy)=x²+y²=|z|²; (x+iy)+(x-iy)=2x; (x+iy)-(x-iy)=2iy; and |x+iy|=√(x²+y²)=|x-iy|.',
    formula_hint: 'z · z̄ = |z|²',
    default_marks: 2.0,
    section: 'Section A: Complex Arithmetic & Modulus',
  },
  {
    subject: 'Mathematics',
    topic: 'Complex Numbers',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'For any two complex numbers z₁ and z₂, the triangle inequality states that |z₁ + z₂| ≤ |z₁| + |z₂|.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. In the Argand plane, z₁, z₂, and z₁ + z₂ form a triangle whose third side length cannot exceed the sum of the other two sides.',
    formula_hint: '|z₁ + z₂| ≤ |z₁| + |z₂|',
    default_marks: 1.0,
    section: 'Section A: Complex Arithmetic & Modulus',
  },
  {
    subject: 'Mathematics',
    topic: 'Complex Numbers',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Calculate the simplified value of i²⁰²⁴ where i = √(-1).',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '1',
    explanation: 'Since 2024 is divisible by 4 (2024 = 4 × 506 with remainder 0), i²⁰²⁴ = (i⁴)⁵⁰⁶ = (1)⁵⁰⁶ = 1.',
    formula_hint: 'i⁴ᵏ = 1',
    default_marks: 1.0,
    section: 'Section A: Complex Arithmetic & Modulus',
  },

  // ============================================================================
  // 5. Quadratic Equations (6 Questions)
  // ============================================================================
  {
    subject: 'Mathematics',
    topic: 'Quadratic Equations',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What are the roots of the quadratic equation x² - 7x + 12 = 0?',
    options: [
      { id: 'a', text: 'x = 3 and x = 4' },
      { id: 'b', text: 'x = -3 and x = -4' },
      { id: 'c', text: 'x = 2 and x = 6' },
      { id: 'd', text: 'x = 1 and x = 12' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Factoring: (x - 3)(x - 4) = 0 => x = 3 or x = 4. Check sum: 3 + 4 = 7; product: 3 × 4 = 12.',
    formula_hint: 'x² - (sum)x + (product) = 0',
    default_marks: 1.0,
    section: 'Section A: Roots & Discriminant',
  },
  {
    subject: 'Mathematics',
    topic: 'Quadratic Equations',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'For what values of k does the quadratic equation kx² - 6x + 1 = 0 have real and distinct roots?',
    options: [
      { id: 'a', text: 'k < 9 and k ≠ 0' },
      { id: 'b', text: 'k > 9' },
      { id: 'c', text: 'k = 9' },
      { id: 'd', text: 'k ≤ 9' },
    ],
    correct_option_ids: ['a'],
    explanation: 'For real and distinct roots, discriminant D > 0: b² - 4ac > 0 => (-6)² - 4(k)(1) > 0 => 36 - 4k > 0 => 4k < 36 => k < 9. For the equation to remain quadratic, k ≠ 0.',
    formula_hint: 'D = b² - 4ac > 0',
    default_marks: 1.5,
    section: 'Section A: Roots & Discriminant',
  },
  {
    subject: 'Mathematics',
    topic: 'Quadratic Equations',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'If α and β are roots of ax² + bx + c = 0, what is the value of α³ + β³?',
    options: [
      { id: 'a', text: '(3abc - b³) / a³' },
      { id: 'b', text: '(b³ - 3abc) / a³' },
      { id: 'c', text: '(b² - 2ac) / a²' },
      { id: 'd', text: '3abc / a³' },
    ],
    correct_option_ids: ['a'],
    explanation: 'α + β = -b/a and αβ = c/a. α³ + β³ = (α + β)³ - 3αβ(α + β) = (-b/a)³ - 3(c/a)(-b/a) = -b³/a³ + 3bc/a² = (3abc - b³) / a³.',
    formula_hint: 'α³ + β³ = (α + β)³ - 3αβ(α + β)',
    default_marks: 2.0,
    section: 'Section B: Symmetric Functions of Roots',
  },
  {
    subject: 'Mathematics',
    topic: 'Quadratic Equations',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'If the discriminant D = b² - 4ac < 0 for a quadratic equation with real coefficients, its roots are complex conjugates.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. By the quadratic formula, x = (-b ± i√|D|) / (2a), which forms a complex conjugate pair p ± iq.',
    formula_hint: 'D < 0 => roots are p ± i q',
    default_marks: 1.0,
    section: 'Section A: Roots & Discriminant',
  },
  {
    subject: 'Mathematics',
    topic: 'Quadratic Equations',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'If the product of roots of 2x² + 8x + c = 0 is 5, find the value of c.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '10',
    explanation: 'By Vieta’s formulas, product of roots = c / a = c / 2. Setting c / 2 = 5 gives c = 10.',
    formula_hint: 'Product of roots = c / a',
    default_marks: 1.0,
    section: 'Section A: Roots & Discriminant',
  },
  {
    subject: 'Mathematics',
    topic: 'Quadratic Equations',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'State the conditions under which both roots of the quadratic equation ax² + bx + c = 0 (with a > 0) are strictly greater than a real number k.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'For both roots of f(x) = ax² + bx + c = 0 to be strictly greater than k (when a > 0), three conditions must hold simultaneously: 1. Discriminant D ≥ 0 (roots must be real); 2. The vertex x-coordinate must be greater than k: -b / (2a) > k; 3. The function evaluated at k must be positive: f(k) = a k² + b k + c > 0.',
    explanation: 'Location of roots criteria combine discriminant reality with vertex position and boundary evaluation sign.',
    formula_hint: 'D ≥ 0, -b/(2a) > k, a·f(k) > 0',
    default_marks: 2.5,
    section: 'Section B: Location of Roots',
  },

  // ============================================================================
  // 6. Sequences & Series (6 Questions)
  // ============================================================================
  {
    subject: 'Mathematics',
    topic: 'Sequences & Series',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the sum of the first 20 terms of the arithmetic progression 3, 7, 11, 15, ...?',
    options: [
      { id: 'a', text: '780' },
      { id: 'b', text: '820' },
      { id: 'c', text: '800' },
      { id: 'd', text: '760' },
    ],
    correct_option_ids: ['b'],
    explanation: 'a = 3, d = 4, n = 20. S_n = (n/2)[2a + (n-1)d] = (20/2)[2(3) + 19(4)] = 10[6 + 76] = 10 × 82 = 820.',
    formula_hint: 'S_n = (n/2)[2a + (n - 1)d]',
    default_marks: 1.0,
    section: 'Section A: Arithmetic & Geometric Progressions',
  },
  {
    subject: 'Mathematics',
    topic: 'Sequences & Series',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the sum of the infinite geometric series: 12 + 4 + 4/3 + 4/9 + ...?',
    options: [
      { id: 'a', text: '16' },
      { id: 'b', text: '18' },
      { id: 'c', text: '24' },
      { id: 'd', text: '20' },
    ],
    correct_option_ids: ['b'],
    explanation: 'First term a = 12, common ratio r = 4/12 = 1/3. Since |r| < 1, S_∞ = a / (1 - r) = 12 / (1 - 1/3) = 12 / (2/3) = 18.',
    formula_hint: 'S_∞ = a / (1 - r) for |r| < 1',
    default_marks: 1.5,
    section: 'Section A: Arithmetic & Geometric Progressions',
  },
  {
    subject: 'Mathematics',
    topic: 'Sequences & Series',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'What is the sum of the series ∑_{k=1}^{n} k²?',
    options: [
      { id: 'a', text: '[n(n + 1)(2n + 1)] / 6' },
      { id: 'b', text: '[n(n + 1)] / 2' },
      { id: 'c', text: '[n(n + 1) / 2]²' },
      { id: 'd', text: '[n(2n + 1)] / 3' },
    ],
    correct_option_ids: ['a'],
    explanation: 'The standard summation formula for squares of first n positive integers is ∑ k² = n(n + 1)(2n + 1) / 6.',
    formula_hint: '∑ k² = n(n + 1)(2n + 1) / 6',
    default_marks: 2.0,
    section: 'Section B: Special Series & Telescoping',
  },
  {
    subject: 'Mathematics',
    topic: 'Sequences & Series',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'For any two positive distinct real numbers a and b, Arithmetic Mean (AM) > Geometric Mean (GM) > Harmonic Mean (HM).',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. AM - GM = (√a - √b)² / 2 > 0 for distinct positive reals, and GM² = AM · HM, establishing AM > GM > HM.',
    formula_hint: 'AM ≥ GM ≥ HM (strict inequality when a ≠ b)',
    default_marks: 1.0,
    section: 'Section A: Arithmetic & Geometric Progressions',
  },
  {
    subject: 'Mathematics',
    topic: 'Sequences & Series',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Find the 10th term of the geometric sequence: 2, 6, 18, 54, ...',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '39366',
    explanation: 'a = 2, r = 3. a₁₀ = a · r⁹ = 2 · (3)⁹ = 2 · 19683 = 39366.',
    formula_hint: 'T_n = a · r^(n - 1)',
    default_marks: 1.5,
    section: 'Section A: Arithmetic & Geometric Progressions',
  },
  {
    subject: 'Mathematics',
    topic: 'Sequences & Series',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'Explain the method of telescoping sums and evaluate S = ∑_{k=1}^{n} 1 / [k(k + 1)].',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'A telescoping sum is a finite series in which consecutive terms cancel each other out, leaving only the initial and final terms. Using partial fractions: 1/[k(k+1)] = 1/k - 1/(k+1). Expanding: S = (1 - 1/2) + (1/2 - 1/3) + ... + (1/n - 1/(n+1)). All intermediate terms cancel, leaving S = 1 - 1/(n+1) = n / (n+1).',
    explanation: 'Partial fraction decomposition transforms the summand into a difference of successive terms that collapse.',
    formula_hint: '∑ [f(k) - f(k+1)] = f(1) - f(n+1)',
    default_marks: 2.5,
    section: 'Section B: Special Series & Telescoping',
  },

  // ============================================================================
  // 7. Coordinate Geometry (6 Questions)
  // ============================================================================
  {
    subject: 'Mathematics',
    topic: 'Coordinate Geometry',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the perpendicular distance from point (2, 3) to the line 3x + 4y - 8 = 0?',
    options: [
      { id: 'a', text: '2 units' },
      { id: 'b', text: '1 unit' },
      { id: 'c', text: '3 units' },
      { id: 'd', text: '4 units' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Distance d = |Ax₁ + By₁ + C| / √(A² + B²) = |3(2) + 4(3) - 8| / √(3² + 4²) = |6 + 12 - 8| / 5 = 10 / 5 = 2 units.',
    formula_hint: 'd = |Ax₁ + By₁ + C| / √(A² + B²)',
    default_marks: 1.0,
    section: 'Section A: Straight Lines & Circles',
  },
  {
    subject: 'Mathematics',
    topic: 'Coordinate Geometry',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the radius of the circle given by x² + y² - 4x + 6y - 12 = 0?',
    options: [
      { id: 'a', text: '5' },
      { id: 'b', text: '25' },
      { id: 'c', text: '4' },
      { id: 'd', text: '√12' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Center is (-g, -f) = (2, -3). Radius r = √(g² + f² - c) = √(2² + (-3)² - (-12)) = √(4 + 9 + 12) = √25 = 5.',
    formula_hint: 'r = √(g² + f² - c)',
    default_marks: 1.5,
    section: 'Section A: Straight Lines & Circles',
  },
  {
    subject: 'Mathematics',
    topic: 'Coordinate Geometry',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'What is the eccentricity of the ellipse x²/25 + y²/16 = 1?',
    options: [
      { id: 'a', text: '3/5' },
      { id: 'b', text: '4/5' },
      { id: 'c', text: '9/25' },
      { id: 'd', text: '5/4' },
    ],
    correct_option_ids: ['a'],
    explanation: 'a² = 25, b² = 16. b² = a²(1 - e²) => 16 = 25(1 - e²) => 1 - e² = 16/25 => e² = 9/25 => e = 3/5 = 0.6.',
    formula_hint: 'e = √(1 - b²/a²)',
    default_marks: 2.0,
    section: 'Section B: Conic Sections',
  },
  {
    subject: 'Mathematics',
    topic: 'Coordinate Geometry',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following conditions ensure that the line y = mx + c is tangent to the circle x² + y² = r²?',
    options: [
      { id: 'a', text: 'c² = r²(1 + m²)' },
      { id: 'b', text: 'Perpendicular distance from origin to the line equals r' },
      { id: 'c', text: 'The quadratic equation in x resulting from substitution has discriminant D = 0' },
      { id: 'd', text: 'c = r / m' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Tangency requires distance from center to line to equal radius (b), leading directly to c = ± r√(1 + m²) => c² = r²(1 + m²) (a), which is algebraically equivalent to D = 0 for intersection points (c).',
    formula_hint: 'c² = r²(1 + m²)',
    default_marks: 2.0,
    section: 'Section A: Straight Lines & Circles',
  },
  {
    subject: 'Mathematics',
    topic: 'Coordinate Geometry',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Two non-vertical straight lines with slopes m₁ and m₂ are perpendicular if and only if m₁ · m₂ = -1.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. If line 2 is at θ + 90°, m₂ = tan(θ + 90°) = -cot θ = -1 / tan θ = -1 / m₁, giving m₁ · m₂ = -1.',
    formula_hint: 'm₁ · m₂ = -1 for perpendicular lines',
    default_marks: 1.0,
    section: 'Section A: Straight Lines & Circles',
  },
  {
    subject: 'Mathematics',
    topic: 'Coordinate Geometry',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Find the slope of the line passing through points A(1, 2) and B(4, 11).',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '3',
    explanation: 'Slope m = (y₂ - y₁) / (x₂ - x₁) = (11 - 2) / (4 - 1) = 9 / 3 = 3.',
    formula_hint: 'm = (y₂ - y₁) / (x₂ - x₁)',
    default_marks: 1.0,
    section: 'Section A: Straight Lines & Circles',
  },

  // ============================================================================
  // 8. Limits (6 Questions)
  // ============================================================================
  {
    subject: 'Mathematics',
    topic: 'Limits',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the value of lim_{x → 0} [sin(3x) / x]?',
    options: [
      { id: 'a', text: '1' },
      { id: 'b', text: '3' },
      { id: 'c', text: '0' },
      { id: 'd', text: 'Does not exist' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Multiply and divide by 3: lim_{x → 0} 3 · [sin(3x) / (3x)] = 3 × 1 = 3.',
    formula_hint: 'lim_{θ → 0} (sin θ / θ) = 1',
    default_marks: 1.0,
    section: 'Section A: Evaluation of Limits',
  },
  {
    subject: 'Mathematics',
    topic: 'Limits',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the value of lim_{x → 2} [(x³ - 8) / (x - 2)]?',
    options: [
      { id: 'a', text: '4' },
      { id: 'b', text: '8' },
      { id: 'c', text: '12' },
      { id: 'd', text: '0' },
    ],
    correct_option_ids: ['c'],
    explanation: 'Factor numerator: x³ - 8 = (x - 2)(x² + 2x + 4). Canceling (x - 2): lim_{x → 2} (x² + 2x + 4) = 4 + 4 + 4 = 12.',
    formula_hint: 'a³ - b³ = (a - b)(a² + ab + b²)',
    default_marks: 1.5,
    section: 'Section A: Evaluation of Limits',
  },
  {
    subject: 'Mathematics',
    topic: 'Limits',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'Evaluate the limit: lim_{x → 0} [(1 + 2x)^(1/x)].',
    options: [
      { id: 'a', text: 'e' },
      { id: 'b', text: 'e²' },
      { id: 'c', text: '1' },
      { id: 'd', text: '2e' },
    ],
    correct_option_ids: ['b'],
    explanation: 'This is of the indeterminate form 1^∞. Limit L = e^{lim_{x → 0} (1/x)[(1 + 2x) - 1]} = e^{lim_{x → 0} (2x/x)} = e².',
    formula_hint: 'lim (1 + ax)^(b/x) = e^(ab)',
    default_marks: 2.0,
    section: 'Section B: Indeterminate Forms & L’Hôpital',
  },
  {
    subject: 'Mathematics',
    topic: 'Limits',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'For which indeterminate forms can L’Hôpital’s Rule be directly applied without preliminary algebraic restructuring?',
    options: [
      { id: 'a', text: '0 / 0' },
      { id: 'b', text: '∞ / ∞' },
      { id: 'c', text: '0 · ∞' },
      { id: 'd', text: '1^∞' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'L’Hôpital’s rule applies directly only to the fractional quotient forms 0/0 and ±∞/±∞. Forms like 0·∞, 1^∞, and ∞ - ∞ must first be transformed into 0/0 or ∞/∞.',
    formula_hint: 'lim f(x)/g(x) = lim f’(x)/g’(x) for 0/0 or ∞/∞',
    default_marks: 2.0,
    section: 'Section B: Indeterminate Forms & L’Hôpital',
  },
  {
    subject: 'Mathematics',
    topic: 'Limits',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'If a function f(x) is differentiable at x = c, then f(x) is necessarily continuous at x = c.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Differentiability implies lim_{x → c} [f(x) - f(c)] = lim_{x → c} [(f(x) - f(c))/(x - c)](x - c) = f’(c) · 0 = 0 => lim f(x) = f(c), which is the definition of continuity.',
    formula_hint: 'Differentiability => Continuity',
    default_marks: 1.0,
    section: 'Section A: Evaluation of Limits',
  },
  {
    subject: 'Mathematics',
    topic: 'Limits',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'State the Squeeze Theorem (Sandwich Theorem) for limits of functions.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'The Squeeze Theorem states that if g(x) ≤ f(x) ≤ h(x) for all x in an open interval containing c (except possibly at c itself), and if lim_{x → c} g(x) = lim_{x → c} h(x) = L, then the limit of the sandwiched function exists and equals L: lim_{x → c} f(x) = L.',
    explanation: 'Upper and lower bounding functions force the intermediate function to share their common limit.',
    formula_hint: 'g(x) ≤ f(x) ≤ h(x) and lim g = lim h = L => lim f = L',
    default_marks: 2.0,
    section: 'Section A: Evaluation of Limits',
  },

  // ============================================================================
  // 9. Differentiation (6 Questions)
  // ============================================================================
  {
    subject: 'Mathematics',
    topic: 'Differentiation',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the derivative of f(x) = ln(cos x)?',
    options: [
      { id: 'a', text: '-tan x' },
      { id: 'b', text: 'tan x' },
      { id: 'c', text: '-cot x' },
      { id: 'd', text: 'sec x' },
    ],
    correct_option_ids: ['a'],
    explanation: 'By the chain rule: d/dx[ln(cos x)] = (1 / cos x) · d/dx(cos x) = (1 / cos x) · (-sin x) = -tan x.',
    formula_hint: 'd/dx [ln u] = u’ / u',
    default_marks: 1.0,
    section: 'Section A: Derivative Rules & Derivatives',
  },
  {
    subject: 'Mathematics',
    topic: 'Differentiation',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'If x² + y² = 25, what is dy/dx at the point (3, 4)?',
    options: [
      { id: 'a', text: '-3/4' },
      { id: 'b', text: '3/4' },
      { id: 'c', text: '-4/3' },
      { id: 'd', text: '4/3' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Differentiating implicitly: 2x + 2y(dy/dx) = 0 => dy/dx = -x/y. At (3, 4): dy/dx = -3/4.',
    formula_hint: 'dy/dx = -x / y',
    default_marks: 1.5,
    section: 'Section A: Derivative Rules & Derivatives',
  },
  {
    subject: 'Mathematics',
    topic: 'Differentiation',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'What is the derivative of y = xˣ with respect to x for x > 0?',
    options: [
      { id: 'a', text: 'xˣ (1 + ln x)' },
      { id: 'b', text: 'x · x^{x - 1}' },
      { id: 'c', text: 'xˣ · ln x' },
      { id: 'd', text: '(1 + ln x)' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Take ln: ln y = x ln x. Differentiate: (1/y)(dy/dx) = ln x + x(1/x) = 1 + ln x. dy/dx = y(1 + ln x) = xˣ (1 + ln x).',
    formula_hint: 'd/dx [x^x] = x^x (1 + ln x)',
    default_marks: 2.0,
    section: 'Section A: Derivative Rules & Derivatives',
  },
  {
    subject: 'Mathematics',
    topic: 'Differentiation',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'For a twice-differentiable function f(x), which conditions guarantee that x = c is a strict local maximum?',
    options: [
      { id: 'a', text: 'f’(c) = 0' },
      { id: 'b', text: 'f’’(c) < 0' },
      { id: 'c', text: 'f’’(c) > 0' },
      { id: 'd', text: 'f’(x) changes sign from positive to negative as x increases through c' },
    ],
    correct_option_ids: ['a', 'b', 'd'],
    explanation: 'By the second derivative test, f’(c) = 0 and f’’(c) < 0 indicates concave down, giving a local maximum (a, b). By the first derivative test, f’ switching from + to - also confirms a local maximum (d). Option (c) describes a local minimum.',
    formula_hint: 'Local Max: f’(c) = 0 and f’’(c) < 0',
    default_marks: 2.0,
    section: 'Section B: Applications of Derivatives',
  },
  {
    subject: 'Mathematics',
    topic: 'Differentiation',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Rolle’s Theorem requires that f(a) = f(b) on the closed interval [a, b].',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Rolle’s theorem hypotheses are: continuous on [a, b], differentiable on (a, b), and f(a) = f(b). Under these, there exists at least one c ∈ (a, b) such that f’(c) = 0.',
    formula_hint: 'f(a) = f(b) => ∃ c such that f’(c) = 0',
    default_marks: 1.0,
    section: 'Section B: Applications of Derivatives',
  },
  {
    subject: 'Mathematics',
    topic: 'Differentiation',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Find the slope of the tangent line to the parabola y = 2x² - 3x + 1 at the point where x = 2.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '5',
    explanation: 'dy/dx = 4x - 3. At x = 2: dy/dx = 4(2) - 3 = 8 - 3 = 5.',
    formula_hint: 'm = f’(x₀)',
    default_marks: 1.0,
    section: 'Section B: Applications of Derivatives',
  },

  // ============================================================================
  // 10. Integration (6 Questions)
  // ============================================================================
  {
    subject: 'Mathematics',
    topic: 'Integration',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the indefinite integral ∫ (3x² - 4x + 5) dx?',
    options: [
      { id: 'a', text: 'x³ - 2x² + 5x + C' },
      { id: 'b', text: '6x - 4 + C' },
      { id: 'c', text: '3x³ - 4x² + 5x + C' },
      { id: 'd', text: 'x³ - 4x² + 5x + C' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Integrating term by term: 3(x³/3) - 4(x²/2) + 5x + C = x³ - 2x² + 5x + C.',
    formula_hint: '∫ xⁿ dx = x^(n+1)/(n+1) + C',
    default_marks: 1.0,
    section: 'Section A: Indefinite Integration',
  },
  {
    subject: 'Mathematics',
    topic: 'Integration',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Evaluate the definite integral ∫₀¹ [1 / (1 + x²)] dx.',
    options: [
      { id: 'a', text: 'π/4' },
      { id: 'b', text: 'π/2' },
      { id: 'c', text: '1' },
      { id: 'd', text: 'ln 2' },
    ],
    correct_option_ids: ['a'],
    explanation: 'The antiderivative of 1/(1 + x²) is arctan(x). [arctan(x)]₀¹ = arctan(1) - arctan(0) = π/4 - 0 = π/4.',
    formula_hint: '∫ 1/(1+x²) dx = arctan x',
    default_marks: 1.5,
    section: 'Section B: Definite Integrals',
  },
  {
    subject: 'Mathematics',
    topic: 'Integration',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'Evaluate the definite integral: ∫_{-1}^{1} (x³ + x cos x + x⁵) dx.',
    options: [
      { id: 'a', text: '0' },
      { id: 'b', text: '2' },
      { id: 'c', text: '1/2' },
      { id: 'd', text: 'π' },
    ],
    correct_option_ids: ['a'],
    explanation: 'f(x) = x³ + x cos x + x⁵ is an odd function because f(-x) = (-x)³ + (-x)cos(-x) + (-x)⁵ = -(x³ + x cos x + x⁵) = -f(x). The definite integral of any odd function over a symmetric interval [-a, a] is identically 0.',
    formula_hint: '∫_{-a}^{a} f(x) dx = 0 for odd functions',
    default_marks: 2.0,
    section: 'Section B: Definite Integrals',
  },
  {
    subject: 'Mathematics',
    topic: 'Integration',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following integration by parts formulas and setups are mathematically correct?',
    options: [
      { id: 'a', text: '∫ u dv = u v - ∫ v du' },
      { id: 'b', text: '∫ x eˣ dx = (x - 1)eˣ + C' },
      { id: 'c', text: '∫ ln x dx = x ln x - x + C' },
      { id: 'd', text: '∫ u dv = u v + ∫ v du' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Formula (a) is the definition of integration by parts. For (b): u=x, dv=eˣ dx => x eˣ - eˣ + C. For (c): u=ln x, dv=dx => x ln x - x + C. Formula (d) has an incorrect plus sign.',
    formula_hint: '∫ u dv = u v - ∫ v du',
    default_marks: 2.0,
    section: 'Section A: Indefinite Integration',
  },
  {
    subject: 'Mathematics',
    topic: 'Integration',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'The Fundamental Theorem of Calculus links differentiation and integration as mutually inverse mathematical operations.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Part 1 states d/dx [∫ₐˣ f(t)dt] = f(x), and Part 2 states ∫ₐᵇ f(x)dx = F(b) - F(a) where F’(x) = f(x).',
    formula_hint: 'd/dx ∫ₐˣ f(t) dt = f(x)',
    default_marks: 1.0,
    section: 'Section B: Definite Integrals',
  },
  {
    subject: 'Mathematics',
    topic: 'Integration',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'State both parts of the Fundamental Theorem of Calculus. Use Part 1 and the Leibniz rule to compute d/dx [∫₀^{x²} sin(t) dt].',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'FTC Part 1: If f is continuous on [a, b], then the function g(x) = ∫ₐˣ f(t) dt is continuous on [a, b], differentiable on (a, b), and g’(x) = f(x). FTC Part 2: If f is continuous on [a, b] and F is any antiderivative of f (F’ = f), then ∫ₐᵇ f(x) dx = F(b) - F(a). By Leibniz Integral Rule / Chain Rule: d/dx [∫_{u(x)}^{v(x)} f(t) dt] = f(v(x))·v’(x) - f(u(x))·u’(x). For d/dx [∫₀^{x²} sin(t) dt]: upper limit v(x) = x² => v’(x) = 2x; lower limit is constant 0. Therefore, the derivative is sin(x²) · (2x) = 2x sin(x²).',
    explanation: 'Chain rule combined with the fundamental theorem allows differentiation of integral expressions with variable limits.',
    formula_hint: 'd/dx ∫ₐ^{u(x)} f(t) dt = f(u(x)) · u’(x)',
    default_marks: 4.0,
    section: 'Section C: Advanced Analytical Calculus',
  },

  // ============================================================================
  // 11. Probability (6 Questions)
  // ============================================================================
  {
    subject: 'Mathematics',
    topic: 'Probability',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Two fair six-sided dice are rolled simultaneously. What is the probability that the sum of the numbers showing is equal to 7?',
    options: [
      { id: 'a', text: '1/6' },
      { id: 'b', text: '7/36' },
      { id: 'c', text: '5/36' },
      { id: 'd', text: '1/12' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Total sample space outcomes = 6 × 6 = 36. Favorable outcomes summing to 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) = 6 pairs. P(sum=7) = 6 / 36 = 1/6.',
    formula_hint: 'P(E) = n(E) / n(S)',
    default_marks: 1.0,
    section: 'Section A: Classical Probability',
  },
  {
    subject: 'Mathematics',
    topic: 'Probability',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'If P(A) = 0.6, P(B) = 0.5, and P(A ∩ B) = 0.3, what is the conditional probability P(A | B)?',
    options: [
      { id: 'a', text: '0.6' },
      { id: 'b', text: '0.5' },
      { id: 'c', text: '0.3' },
      { id: 'd', text: '0.8' },
    ],
    correct_option_ids: ['a'],
    explanation: 'By definition of conditional probability: P(A | B) = P(A ∩ B) / P(B) = 0.3 / 0.5 = 0.6. Since P(A | B) = P(A), A and B are independent events.',
    formula_hint: 'P(A | B) = P(A ∩ B) / P(B)',
    default_marks: 1.5,
    section: 'Section B: Conditional Probability & Bayes',
  },
  {
    subject: 'Mathematics',
    topic: 'Probability',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'A factory has two machines: Machine A produces 60% of items (with 2% defect rate) and Machine B produces 40% (with 5% defect rate). An item selected at random is defective. What is the probability it was produced by Machine B?',
    options: [
      { id: 'a', text: '0.625 (5/8)' },
      { id: 'b', text: '0.375 (3/8)' },
      { id: 'c', text: '0.40' },
      { id: 'd', text: '0.50' },
    ],
    correct_option_ids: ['a'],
    explanation: 'By Bayes’ Theorem: P(D) = P(A)P(D|A) + P(B)P(D|B) = (0.60 × 0.02) + (0.40 × 0.05) = 0.012 + 0.020 = 0.032. P(B|D) = P(B ∩ D) / P(D) = 0.020 / 0.032 = 20 / 32 = 5/8 = 0.625.',
    formula_hint: 'P(B|D) = [P(B)P(D|B)] / P(D)',
    default_marks: 2.0,
    section: 'Section B: Conditional Probability & Bayes',
  },
  {
    subject: 'Mathematics',
    topic: 'Probability',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'For two independent random events E and F with non-zero probabilities, which of the following relations must hold?',
    options: [
      { id: 'a', text: 'P(E ∩ F) = P(E) · P(F)' },
      { id: 'b', text: 'P(E | F) = P(E)' },
      { id: 'c', text: 'P(E ∪ F) = P(E) + P(F) - P(E)P(F)' },
      { id: 'd', text: 'P(E ∩ F) = 0' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Independence means occurrence of F does not affect E, giving (a) and (b). From inclusion-exclusion, (c) follows. P(E ∩ F) = 0 describes mutually exclusive events, not independent events (d is false).',
    formula_hint: 'Independent: P(E ∩ F) = P(E) · P(F)',
    default_marks: 2.0,
    section: 'Section A: Classical Probability',
  },
  {
    subject: 'Mathematics',
    topic: 'Probability',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'For any random variable X, the variance Var(X) is always greater than or equal to zero.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Variance is defined as the expected value of a squared deviation: Var(X) = E[(X - μ)²]. Because squares of real numbers are non-negative, expectation must be non-negative (Var(X) ≥ 0).',
    formula_hint: 'Var(X) = E[(X - μ)²] ≥ 0',
    default_marks: 1.0,
    section: 'Section B: Random Variables & Distributions',
  },
  {
    subject: 'Mathematics',
    topic: 'Probability',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'In 5 independent flips of a fair coin, what is the number of outcomes that yield exactly 3 heads?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '10',
    explanation: 'The number of combinations is C(5, 3) = 5! / (3! × 2!) = (5 × 4) / 2 = 10.',
    formula_hint: 'C(n, k) = n! / (k! (n - k)!)',
    default_marks: 1.0,
    section: 'Section A: Classical Probability',
  },

  // ============================================================================
  // 12. Statistics (6 Questions)
  // ============================================================================
  {
    subject: 'Mathematics',
    topic: 'Statistics',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the median of the following dataset: 8, 3, 14, 9, 12, 6, 20?',
    options: [
      { id: 'a', text: '8' },
      { id: 'b', text: '9' },
      { id: 'c', text: '10.3' },
      { id: 'd', text: '12' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Sort data in ascending order: 3, 6, 8, 9, 12, 14, 20. With n = 7 values, the median is the 4th element, which is 9.',
    formula_hint: 'Median = ((n + 1)/2)-th value for odd n',
    default_marks: 1.0,
    section: 'Section A: Measures of Central Tendency',
  },
  {
    subject: 'Mathematics',
    topic: 'Statistics',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'The mean of 5 observations is 10 and their variance is 4. If each observation is multiplied by 3, what are the new mean and new variance?',
    options: [
      { id: 'a', text: 'Mean = 30, Variance = 12' },
      { id: 'b', text: 'Mean = 30, Variance = 36' },
      { id: 'c', text: 'Mean = 10, Variance = 36' },
      { id: 'd', text: 'Mean = 30, Variance = 4' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Multiplying every value by c = 3 scales the mean linearly: New Mean = c · Mean = 3 × 10 = 30. Variance scales by c²: New Variance = c² · Var = 3² × 4 = 9 × 4 = 36.',
    formula_hint: 'E[cX] = c E[X], Var(cX) = c² Var(X)',
    default_marks: 1.5,
    section: 'Section B: Dispersion & Variance',
  },
  {
    subject: 'Mathematics',
    topic: 'Statistics',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'For a moderately skewed distribution, what is the empirical relationship between Mean, Median, and Mode?',
    options: [
      { id: 'a', text: 'Mode = 3 Median - 2 Mean' },
      { id: 'b', text: 'Mode = 2 Median - 3 Mean' },
      { id: 'c', text: 'Mean - Mode = 2 (Mean - Median)' },
      { id: 'd', text: 'Median = 3 Mode - 2 Mean' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Karl Pearson’s empirical relationship states: Mean - Mode = 3(Mean - Median) => Mode = 3 Median - 2 Mean.',
    formula_hint: 'Mode = 3 Median - 2 Mean',
    default_marks: 2.0,
    section: 'Section A: Measures of Central Tendency',
  },
  {
    subject: 'Mathematics',
    topic: 'Statistics',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following statistical metrics are measures of data dispersion rather than central tendency?',
    options: [
      { id: 'a', text: 'Standard deviation' },
      { id: 'b', text: 'Interquartile range (IQR)' },
      { id: 'c', text: 'Geometric mean' },
      { id: 'd', text: 'Mean absolute deviation' },
    ],
    correct_option_ids: ['a', 'b', 'd'],
    explanation: 'Standard deviation, interquartile range (Q3 - Q1), and mean absolute deviation measure the spread/dispersion of values around a center. Geometric mean is a measure of central tendency.',
    formula_hint: 'Dispersion = spread of distribution',
    default_marks: 2.0,
    section: 'Section B: Dispersion & Variance',
  },
  {
    subject: 'Mathematics',
    topic: 'Statistics',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Adding a constant scalar k to every data point in a sample leaves the variance unchanged.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Shifting all observations by k increases the sample mean by k. The deviation (x_i + k) - (x̄ + k) = x_i - x̄ remains identical, so variance is invariant to location shifts: Var(X + k) = Var(X).',
    formula_hint: 'Var(X + c) = Var(X)',
    default_marks: 1.0,
    section: 'Section B: Dispersion & Variance',
  },
  {
    subject: 'Mathematics',
    topic: 'Statistics',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'If a sample dataset has a variance of 64, what is its standard deviation?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '8',
    explanation: 'Standard deviation is the positive square root of variance: σ = √64 = 8.',
    formula_hint: 'σ = √(Variance)',
    default_marks: 1.0,
    section: 'Section B: Dispersion & Variance',
  },
];
