/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { CurriculumQuestion } from './types.js';

export const PHYSICS_QUESTIONS: CurriculumQuestion[] = [
  // ============================================================================
  // 1. Units & Measurements (6 Questions)
  // ============================================================================
  {
    subject: 'Physics',
    topic: 'Units & Measurements',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Which of the following is NOT an SI base unit?',
    options: [
      { id: 'a', text: 'Kilogram' },
      { id: 'b', text: 'Second' },
      { id: 'c', text: 'Joule' },
      { id: 'd', text: 'Kelvin' },
    ],
    correct_option_ids: ['c'],
    explanation: 'The Joule is a derived unit (kg·m²·s⁻²) representing energy, whereas kilogram, second, and kelvin are fundamental SI base units.',
    formula_hint: '1 J = 1 kg·m²/s²',
    default_marks: 1.0,
    section: 'Section A: Fundamental Dimensions',
  },
  {
    subject: 'Physics',
    topic: 'Units & Measurements',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What are the dimensions of Planck’s constant (h)?',
    options: [
      { id: 'a', text: '[M L² T⁻¹]' },
      { id: 'b', text: '[M L² T⁻²]' },
      { id: 'c', text: '[M L T⁻¹]' },
      { id: 'd', text: '[M L² T⁻³]' },
    ],
    correct_option_ids: ['a'],
    explanation: 'From E = hν, [h] = [E] / [ν] = [M L² T⁻²] / [T⁻¹] = [M L² T⁻¹], which also matches the dimensions of angular momentum.',
    formula_hint: 'E = hν => h = E / ν',
    default_marks: 1.5,
    section: 'Section A: Fundamental Dimensions',
  },
  {
    subject: 'Physics',
    topic: 'Units & Measurements',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'The density of a cube is calculated from mass m and edge length L. If the percentage error in mass is 1.5% and the percentage error in length is 1.0%, what is the maximum percentage error in density?',
    options: [
      { id: 'a', text: '2.5%' },
      { id: 'b', text: '4.5%' },
      { id: 'c', text: '3.5%' },
      { id: 'd', text: '0.5%' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Density ρ = m / L³. Relative error is Δρ/ρ = Δm/m + 3(ΔL/L) = 1.5% + 3(1.0%) = 4.5%.',
    formula_hint: 'Δρ/ρ = (Δm/m) + 3·(ΔL/L)',
    default_marks: 2.0,
    section: 'Section B: Error Analysis',
  },
  {
    subject: 'Physics',
    topic: 'Units & Measurements',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'A physically dimensionless quantity can still possess physical units.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Plane angle (radian) and solid angle (steradian) are dimensionless quantities in terms of mass, length, and time ([M⁰ L⁰ T⁰]) but carry supplementary SI units.',
    formula_hint: 'θ = arc length / radius (m/m = dimensionless, unit: rad)',
    default_marks: 1.0,
    section: 'Section A: Fundamental Dimensions',
  },
  {
    subject: 'Physics',
    topic: 'Units & Measurements',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'Name the SI unit of luminous intensity.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Candela',
    explanation: 'Candela (symbol: cd) is the SI base unit measuring luminous intensity of a source in a given direction.',
    formula_hint: 'SI Base Units: m, kg, s, A, K, mol, cd',
    default_marks: 1.0,
    section: 'Section A: Fundamental Dimensions',
  },
  {
    subject: 'Physics',
    topic: 'Units & Measurements',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'Differentiate between systematic errors and random errors, citing one practical example of each.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Systematic errors occur unidirectionally due to calibration or zero error (e.g. worn screw gauge zero error) and can be minimized by calibration. Random errors fluctuate irregularly in sign and magnitude due to unpredictable experimental conditions (e.g. ambient temperature or voltage fluctuations) and are reduced by taking repeated measurements and averaging.',
    explanation: 'Systematic errors have identifiable causes and constant bias, whereas random errors follow statistical distributions and cancel out over numerous trials.',
    formula_hint: 'Mean value x̄ = (∑ x_i) / n',
    default_marks: 2.5,
    section: 'Section B: Error Analysis',
  },

  // ============================================================================
  // 2. Kinematics (6 Questions)
  // ============================================================================
  {
    subject: 'Physics',
    topic: 'Kinematics',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'A projectile is launched from ground level with speed u at an angle θ to the horizontal. At the highest point of its trajectory, what is its acceleration?',
    options: [
      { id: 'a', text: '0' },
      { id: 'b', text: 'g directed downwards' },
      { id: 'c', text: 'g sin θ' },
      { id: 'd', text: 'g cos θ' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Gravity is the sole force acting throughout ballistic flight in the absence of air resistance, maintaining constant downward acceleration g at every point, including the apex.',
    formula_hint: 'a_y = -g, a_x = 0',
    default_marks: 1.0,
    section: 'Section A: Kinematics Dynamics',
  },
  {
    subject: 'Physics',
    topic: 'Kinematics',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'A particle moves along a straight path such that its position is given by x(t) = 3t² - 12t + 4 (meters, seconds). At what time does the particle momentarily come to rest?',
    options: [
      { id: 'a', text: '1 s' },
      { id: 'b', text: '2 s' },
      { id: 'c', text: '3 s' },
      { id: 'd', text: '4 s' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Velocity v(t) = dx/dt = 6t - 12. Setting v(t) = 0 gives 6t = 12 => t = 2 seconds.',
    formula_hint: 'v(t) = dx/dt = 0',
    default_marks: 1.5,
    section: 'Section B: Differential Kinematics',
  },
  {
    subject: 'Physics',
    topic: 'Kinematics',
    difficulty: 'hard',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'For a projectile launched at an angle θ with speed u over flat ground, which of the following expressions are correct?',
    options: [
      { id: 'a', text: 'Maximum height H = (u² sin² θ) / (2g)' },
      { id: 'b', text: 'Total flight time T = (2u sin θ) / g' },
      { id: 'c', text: 'Horizontal range R = (u² sin 2θ) / g' },
      { id: 'd', text: 'Maximum horizontal range occurs when launch angle θ = 60°' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Formulas (a), (b), and (c) are standard kinematic derivations. Option (d) is incorrect because maximum range occurs at θ = 45° where sin(2θ) = 1.',
    formula_hint: 'R_max = u²/g at θ = 45°',
    default_marks: 2.5,
    section: 'Section A: Kinematics Dynamics',
  },
  {
    subject: 'Physics',
    topic: 'Kinematics',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'A particle moving with uniform speed along a circular path has non-zero acceleration.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Even though magnitude of velocity (speed) is constant, velocity direction continuously changes toward the circle center, creating centripetal acceleration a_c = v²/r.',
    formula_hint: 'a_c = v² / r',
    default_marks: 1.0,
    section: 'Section A: Kinematics Dynamics',
  },
  {
    subject: 'Physics',
    topic: 'Kinematics',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'A car decelerates uniformly from 20 m/s to rest over a displacement of 50 m. Calculate the magnitude of its deceleration in m/s².',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '4',
    explanation: 'Using v² = u² + 2as: 0 = (20)² + 2(-a)(50) => 100a = 400 => a = 4 m/s².',
    formula_hint: 'v² = u² + 2as',
    default_marks: 1.5,
    section: 'Section B: Numerical Kinematics',
  },
  {
    subject: 'Physics',
    topic: 'Kinematics',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'Derive the equation of trajectory for a projectile fired with velocity u at an angle θ to the horizontal, and prove that the trajectory is parabolic in nature.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Horizontal displacement: x = (u cos θ)t => t = x / (u cos θ). Vertical displacement: y = (u sin θ)t - (1/2)gt². Substituting t yields y = (u sin θ)(x / (u cos θ)) - (1/2)g(x / (u cos θ))² = (tan θ)x - [g / (2u² cos² θ)]x². Since this equation is of the form y = Ax - Bx² (where A and B are constants), the path represents a parabola opening downwards.',
    explanation: 'By eliminating time t between horizontal constant-velocity motion and vertical uniform-acceleration motion under gravity, the resulting coordinate relation y = f(x) is quadratic in x, demonstrating a downward parabolic trajectory.',
    formula_hint: 'y = x tan θ - (g x²) / (2 u² cos² θ)',
    default_marks: 4.0,
    section: 'Section C: Derivations & Analytical Physics',
  },

  // ============================================================================
  // 3. Laws of Motion (6 Questions)
  // ============================================================================
  {
    subject: 'Physics',
    topic: 'Laws of Motion',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'A body of mass 5 kg is accelerated across a frictionless surface from rest to 10 m/s in 2 seconds. What is the net applied force?',
    options: [
      { id: 'a', text: '15 N' },
      { id: 'b', text: '25 N' },
      { id: 'c', text: '50 N' },
      { id: 'd', text: '10 N' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Acceleration a = (v - u)/t = (10 - 0)/2 = 5 m/s². Force F = ma = 5 kg × 5 m/s² = 25 N.',
    formula_hint: 'F = ma = m(Δv / Δt)',
    default_marks: 1.0,
    section: 'Section A: Newtonian Mechanics',
  },
  {
    subject: 'Physics',
    topic: 'Laws of Motion',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'A block of mass m rests on a rough horizontal surface with coefficient of static friction μ_s. A horizontal force F is applied. If F < μ_s·m·g, the magnitude of the frictional force acting on the block is:',
    options: [
      { id: 'a', text: 'μ_s m g' },
      { id: 'b', text: 'F' },
      { id: 'c', text: 'Zero' },
      { id: 'd', text: 'μ_k m g' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Static friction is self-adjusting up to the limiting threshold f_max = μ_s N. When applied force F is below limiting friction, the static friction exactly equals the applied force F to maintain equilibrium.',
    formula_hint: 'f_static = F_applied (when F < μ_s N)',
    default_marks: 1.5,
    section: 'Section A: Newtonian Mechanics',
  },
  {
    subject: 'Physics',
    topic: 'Laws of Motion',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'A rocket of initial mass M ejects fuel gases at a constant relative exhaust velocity v_rel at rate dm/dt = α. In the absence of gravity, what is the rocket speed after its mass decreases to M/2?',
    options: [
      { id: 'a', text: 'v_rel · ln 2' },
      { id: 'b', text: '2 · v_rel' },
      { id: 'c', text: 'v_rel / 2' },
      { id: 'd', text: 'v_rel · (ln 2)²' },
    ],
    correct_option_ids: ['a'],
    explanation: 'From Tsiolkovsky’s rocket equation: v - v₀ = v_rel · ln(m₀ / m). With m₀ = M and m = M/2, Δv = v_rel · ln(M / (M/2)) = v_rel · ln 2.',
    formula_hint: 'v = v₀ + v_rel · ln(m₀ / m)',
    default_marks: 2.0,
    section: 'Section B: Variable Mass Systems',
  },
  {
    subject: 'Physics',
    topic: 'Laws of Motion',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following statements regarding Newton’s third law action-reaction pairs are physically valid?',
    options: [
      { id: 'a', text: 'Action and reaction act on two distinctly different bodies.' },
      { id: 'b', text: 'Action and reaction cancel each other out to produce equilibrium on a single body.' },
      { id: 'c', text: 'Action and reaction forces are equal in magnitude and opposite in direction.' },
      { id: 'd', text: 'Action and reaction forces occur simultaneously with zero time delay.' },
    ],
    correct_option_ids: ['a', 'c', 'd'],
    explanation: 'Action and reaction act on different bodies simultaneously (a, c, d). Because they act on different entities, they never cancel out on a single object (b is false).',
    formula_hint: 'F_AB = - F_BA',
    default_marks: 2.0,
    section: 'Section A: Newtonian Mechanics',
  },
  {
    subject: 'Physics',
    topic: 'Laws of Motion',
    difficulty: 'easy',
    question_type: 'VERY_SHORT',
    question_text: 'What physical quantity corresponds to the rate of change of linear momentum?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Net force',
    explanation: 'By Newton’s second law, net external force is defined as the time rate of change of linear momentum: F_net = dp/dt.',
    formula_hint: 'F = dp/dt',
    default_marks: 1.0,
    section: 'Section A: Newtonian Mechanics',
  },
  {
    subject: 'Physics',
    topic: 'Laws of Motion',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'Explain why a cricket player pulls their hands backwards while catching a fast-moving ball.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'By pulling hands backwards, the fielder extends the duration of impact (Δt) required to bring the momentum of the ball to zero. Since impulse J = F_avg · Δt = Δp is constant, increasing contact time Δt proportionally reduces the average impact force F_avg on the hands, preventing pain and injury.',
    explanation: 'From the impulse-momentum theorem: F = Δp / Δt. Increasing the contact time diminishes the peak stopping force exerted on the player’s palms.',
    formula_hint: 'Impulse J = F · Δt = m · Δv',
    default_marks: 2.5,
    section: 'Section A: Newtonian Mechanics',
  },

  // ============================================================================
  // 4. Work, Energy & Power (6 Questions)
  // ============================================================================
  {
    subject: 'Physics',
    topic: 'Work, Energy & Power',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'How much work is done by the centripetal force on a satellite orbiting Earth in a circular orbit of radius R during one complete revolution?',
    options: [
      { id: 'a', text: '2π R · F' },
      { id: 'b', text: 'π R · F' },
      { id: 'c', text: 'Zero' },
      { id: 'd', text: 'F · R' },
    ],
    correct_option_ids: ['c'],
    explanation: 'The centripetal force is always directed perpendicular to the displacement vector at every instant (θ = 90°). Thus dW = F · ds · cos(90°) = 0.',
    formula_hint: 'W = F · d · cos θ',
    default_marks: 1.0,
    section: 'Section A: Work & Conservative Forces',
  },
  {
    subject: 'Physics',
    topic: 'Work, Energy & Power',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'A spring with spring constant k = 200 N/m is compressed by 0.1 m from its natural length. How much elastic potential energy is stored in the spring?',
    options: [
      { id: 'a', text: '2 J' },
      { id: 'b', text: '1 J' },
      { id: 'c', text: '0.5 J' },
      { id: 'd', text: '4 J' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Elastic potential energy U = (1/2)kx² = (1/2) × 200 × (0.1)² = 100 × 0.01 = 1.0 Joule.',
    formula_hint: 'U = (1/2) k x²',
    default_marks: 1.5,
    section: 'Section B: Energy Principles',
  },
  {
    subject: 'Physics',
    topic: 'Work, Energy & Power',
    difficulty: 'hard',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following forces are classified as conservative forces?',
    options: [
      { id: 'a', text: 'Gravitational force' },
      { id: 'b', text: 'Kinetic friction force' },
      { id: 'c', text: 'Electrostatic force' },
      { id: 'd', text: 'Ideal spring restoring force' },
    ],
    correct_option_ids: ['a', 'c', 'd'],
    explanation: 'Gravitational, electrostatic, and elastic restoring forces are conservative because work done depends solely on endpoints (∮ F · dr = 0). Friction is non-conservative because energy is irreversibly dissipated as thermal energy.',
    formula_hint: '∮ F · dr = 0 for conservative fields',
    default_marks: 2.0,
    section: 'Section A: Work & Conservative Forces',
  },
  {
    subject: 'Physics',
    topic: 'Work, Energy & Power',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'In an inelastic collision between two isolated bodies, both total linear momentum and total kinetic energy are conserved.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['false'],
    explanation: 'False. In all isolated collisions linear momentum is conserved, but in an inelastic collision kinetic energy is partially converted into internal thermal, deformation, or acoustic energy.',
    formula_hint: 'p_total conserved; KE_initial > KE_final for inelastic',
    default_marks: 1.0,
    section: 'Section B: Collision Physics',
  },
  {
    subject: 'Physics',
    topic: 'Work, Energy & Power',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'An engine lifts a 200 kg mass through a vertical height of 10 m in 5 seconds. Taking g = 9.8 m/s², what is the average power developed by the engine in Watts?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '3920',
    explanation: 'Work done W = mgh = 200 × 9.8 × 10 = 19600 J. Average power P = W / t = 19600 / 5 = 3920 Watts.',
    formula_hint: 'P = W / t = (m g h) / t',
    default_marks: 1.5,
    section: 'Section B: Power Computations',
  },
  {
    subject: 'Physics',
    topic: 'Work, Energy & Power',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'State the Work-Energy Theorem and write its general mathematical formulation for variable forces.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'The Work-Energy Theorem states that the net work done on a particle by all external forces (conservative, non-conservative, and external) equals the net change in its kinetic energy: W_net = ΔK = (1/2)m(v_f² - v_i²). For a variable force along path C: W = ∫ F · dr = ΔK.',
    explanation: 'Derived directly from integrating Newton’s second law F = m(dv/dt) with respect to position dr = v dt.',
    formula_hint: 'W_net = ΔK = K_final - K_initial',
    default_marks: 2.5,
    section: 'Section B: Energy Principles',
  },

  // ============================================================================
  // 5. Gravitation (6 Questions)
  // ============================================================================
  {
    subject: 'Physics',
    topic: 'Gravitation',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'If the distance between two point masses is doubled, how does the gravitational force between them change?',
    options: [
      { id: 'a', text: 'Decreases to one-fourth' },
      { id: 'b', text: 'Halves' },
      { id: 'c', text: 'Doubles' },
      { id: 'd', text: 'Remains constant' },
    ],
    correct_option_ids: ['a'],
    explanation: 'By Newton’s law of universal gravitation, F ∝ 1/r². Doubling r multiplies the denominator by 4, reducing force to F/4.',
    formula_hint: 'F = G m₁ m₂ / r²',
    default_marks: 1.0,
    section: 'Section A: Gravitational Fields',
  },
  {
    subject: 'Physics',
    topic: 'Gravitation',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'What is the ratio of escape velocity from Earth’s surface to the orbital velocity of a satellite grazing the surface?',
    options: [
      { id: 'a', text: '√2' },
      { id: 'b', text: '2' },
      { id: 'c', text: '1/√2' },
      { id: 'd', text: '1' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Escape velocity is v_e = √(2gR) while surface orbital velocity is v_o = √(gR). The ratio is v_e / v_o = √(2gR) / √(gR) = √2 ≈ 1.414.',
    formula_hint: 'v_e = √(2GM/R), v_o = √(GM/R)',
    default_marks: 1.5,
    section: 'Section A: Orbital Mechanics',
  },
  {
    subject: 'Physics',
    topic: 'Gravitation',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'At what altitude h above Earth’s surface (radius R) does gravitational acceleration reduce to g/4?',
    options: [
      { id: 'a', text: 'R/2' },
      { id: 'b', text: 'R' },
      { id: 'c', text: '2R' },
      { id: 'd', text: '4R' },
    ],
    correct_option_ids: ['b'],
    explanation: 'g(h) = g(0) · [R / (R + h)]². Setting g(h)/g = 1/4 gives [R / (R + h)]² = 1/4 => R / (R + h) = 1/2 => R + h = 2R => h = R.',
    formula_hint: 'g_h = g · [R / (R + h)]²',
    default_marks: 2.0,
    section: 'Section B: Gravitational Potential & Field',
  },
  {
    subject: 'Physics',
    topic: 'Gravitation',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'The value of acceleration due to gravity is maximum at the Earth’s equator and minimum at the geographic poles.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['false'],
    explanation: 'False. Earth’s equatorial radius is greater (equatorial bulge) and centrifugal effect is maximum at the equator (g_eff = g - ω²R), making gravity minimum at the equator and maximum at the poles.',
    formula_hint: 'g_latitude = g - ω² R cos² λ',
    default_marks: 1.0,
    section: 'Section A: Gravitational Fields',
  },
  {
    subject: 'Physics',
    topic: 'Gravitation',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'What is the orbital period in hours of a geostationary satellite orbiting Earth?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '24',
    explanation: 'A geostationary satellite matches Earth’s sidereal rotational period, remaining fixed relative to the ground with an orbital period of approximately 24 hours.',
    formula_hint: 'T_geo = 24 hours (altitude ≈ 35,786 km)',
    default_marks: 1.0,
    section: 'Section A: Orbital Mechanics',
  },
  {
    subject: 'Physics',
    topic: 'Gravitation',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'State Kepler’s three laws of planetary motion. Provide the mathematical formulation for the Law of Periods and relate it to Newton’s law of universal gravitation for circular orbits.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '1. Law of Orbits: All planets move in elliptical orbits with the Sun at one focus. 2. Law of Areas: A line connecting a planet to the Sun sweeps out equal areas in equal intervals of time (dA/dt = L / (2m) = constant, expressing angular momentum conservation). 3. Law of Periods: The square of the orbital period T is proportional to the cube of semi-major axis a (T² ∝ a³). For a circular orbit of radius r, centripetal force is provided by gravity: m(4π²r/T²) = G M m / r² => T² = (4π² / GM) · r³.',
    explanation: 'Kepler’s empirical laws formed the foundation for Newton’s inverse-square gravitational law, where planetary period directly reflects orbital radius and central star mass.',
    formula_hint: 'T² = (4π² / G M) · r³',
    default_marks: 4.0,
    section: 'Section C: Derivations & Analytical Physics',
  },

  // ============================================================================
  // 6. Thermodynamics (6 Questions)
  // ============================================================================
  {
    subject: 'Physics',
    topic: 'Thermodynamics',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'In which thermodynamic process does a system perform mechanical work with zero heat exchange with its surroundings?',
    options: [
      { id: 'a', text: 'Isothermal' },
      { id: 'b', text: 'Isochoric' },
      { id: 'c', text: 'Adiabatic' },
      { id: 'd', text: 'Isobaric' },
    ],
    correct_option_ids: ['c'],
    explanation: 'An adiabatic process is thermally insulated (dQ = 0). By the first law of thermodynamics, dU = -dW, meaning work is done entirely at the expense of internal energy.',
    formula_hint: 'dQ = dU + dW = 0 => dW = -dU',
    default_marks: 1.0,
    section: 'Section A: Thermal Processes',
  },
  {
    subject: 'Physics',
    topic: 'Thermodynamics',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'A Carnot heat engine operates between reservoirs at 600 K and 300 K. What is its maximum theoretical thermodynamic efficiency?',
    options: [
      { id: 'a', text: '25%' },
      { id: 'b', text: '50%' },
      { id: 'c', text: '75%' },
      { id: 'd', text: '100%' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Carnot efficiency η = 1 - (T_cold / T_hot) = 1 - (300 / 600) = 1 - 0.5 = 0.50 or 50%.',
    formula_hint: 'η = 1 - (T_C / T_H)',
    default_marks: 1.5,
    section: 'Section B: Heat Engines & Entropy',
  },
  {
    subject: 'Physics',
    topic: 'Thermodynamics',
    difficulty: 'hard',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'For an ideal gas undergoing an isothermal expansion, which of the following properties remain constant throughout the process?',
    options: [
      { id: 'a', text: 'Temperature (T)' },
      { id: 'b', text: 'Internal energy (U)' },
      { id: 'c', text: 'Pressure (P)' },
      { id: 'd', text: 'Product of pressure and volume (PV)' },
    ],
    correct_option_ids: ['a', 'b', 'd'],
    explanation: 'Isothermal implies constant T. For an ideal gas, U depends solely on temperature, so U is constant (ΔU = 0). By Boyle’s Law, P · V = nRT = constant. Pressure decreases as volume expands, so P is not constant.',
    formula_hint: 'ΔU = n C_v ΔT = 0, P V = constant',
    default_marks: 2.0,
    section: 'Section A: Thermal Processes',
  },
  {
    subject: 'Physics',
    topic: 'Thermodynamics',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'The Zeroth Law of Thermodynamics establishes the concept and definition of temperature as a state variable.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. The Zeroth Law states that if two systems are in thermal equilibrium with a third system, they are in thermal equilibrium with each other, providing the mathematical basis for temperature measurement.',
    formula_hint: 'If A ~ C and B ~ C, then A ~ B',
    default_marks: 1.0,
    section: 'Section A: Thermal Processes',
  },
  {
    subject: 'Physics',
    topic: 'Thermodynamics',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'State the value of work done during an isochoric process.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Zero',
    explanation: 'In an isochoric process, volume remains constant (dV = 0). Because boundary work is W = ∫ P dV, no work is performed.',
    formula_hint: 'W = ∫ P dV = 0 (since dV = 0)',
    default_marks: 1.0,
    section: 'Section A: Thermal Processes',
  },
  {
    subject: 'Physics',
    topic: 'Thermodynamics',
    difficulty: 'hard',
    question_type: 'SHORT',
    question_text: 'State the Clausius and Kelvin-Planck formulations of the Second Law of Thermodynamics and explain why they are logically equivalent.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Kelvin-Planck statement: It is impossible to construct a heat engine operating in a cycle that absorbs heat from a single reservoir and produces an equivalent amount of work without rejecting heat. Clausius statement: It is impossible to construct a cyclical device whose sole effect is transferring heat from a cooler body to a hotter body without external work input. They are logically equivalent because violation of one implies violation of the other: coupling a perpetual motion machine of the second kind with a refrigerator would produce spontaneous heat transfer from cold to hot without external work.',
    explanation: 'The Second Law dictates the directionality of spontaneous processes and establishes entropy as an ever-increasing quantity in isolated systems.',
    formula_hint: 'ΔS_universe ≥ 0',
    default_marks: 3.0,
    section: 'Section B: Heat Engines & Entropy',
  },

  // ============================================================================
  // 7. Oscillations (6 Questions)
  // ============================================================================
  {
    subject: 'Physics',
    topic: 'Oscillations',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'For a simple harmonic oscillator with displacement x = A sin(ωt), what is the phase difference between displacement and acceleration?',
    options: [
      { id: 'a', text: '0 radians' },
      { id: 'b', text: 'π/2 radians' },
      { id: 'c', text: 'π radians (180°)' },
      { id: 'd', text: '3π/2 radians' },
    ],
    correct_option_ids: ['c'],
    explanation: 'Velocity is v = Aω cos(ωt) (leads x by π/2). Acceleration is a = -Aω² sin(ωt) = Aω² sin(ωt + π), which is exactly π radians (180°) out of phase with displacement.',
    formula_hint: 'a(t) = -ω² x(t)',
    default_marks: 1.0,
    section: 'Section A: Harmonic Motion Foundations',
  },
  {
    subject: 'Physics',
    topic: 'Oscillations',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'A simple pendulum has period T on Earth. If its length is quadrupled, its new period becomes:',
    options: [
      { id: 'a', text: 'T/2' },
      { id: 'b', text: '2T' },
      { id: 'c', text: '4T' },
      { id: 'd', text: 'T√2' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Period T = 2π√(L/g). Quadrupling L gives T’ = 2π√(4L/g) = 2 · (2π√(L/g)) = 2T.',
    formula_hint: 'T = 2π √(L / g)',
    default_marks: 1.5,
    section: 'Section A: Harmonic Motion Foundations',
  },
  {
    subject: 'Physics',
    topic: 'Oscillations',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'At what displacement from the mean position does the kinetic energy of a simple harmonic oscillator equal its potential energy?',
    options: [
      { id: 'a', text: 'x = A / 2' },
      { id: 'b', text: 'x = A / √2' },
      { id: 'c', text: 'x = A / 4' },
      { id: 'd', text: 'x = A · √3 / 2' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Potential energy U = (1/2)kx² and total energy E = (1/2)kA². Setting U = E/2 gives (1/2)kx² = (1/4)kA² => x² = A²/2 => x = A / √2.',
    formula_hint: 'U = (1/2) k x², E = (1/2) k A²',
    default_marks: 2.0,
    section: 'Section B: Energy in Oscillations',
  },
  {
    subject: 'Physics',
    topic: 'Oscillations',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'The period of oscillation of a simple pendulum is independent of the mass of the bob.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. The restoring torque depends on gravitational mass, while rotational inertia depends on inertial mass. By the equivalence principle, mass cancels out: T = 2π√(L/g).',
    formula_hint: 'T = 2π √(L/g) (independent of mass m)',
    default_marks: 1.0,
    section: 'Section A: Harmonic Motion Foundations',
  },
  {
    subject: 'Physics',
    topic: 'Oscillations',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'A block of mass 0.5 kg oscillates on a spring with stiffness k = 50 N/m. Calculate its angular frequency ω in rad/s.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '10',
    explanation: 'Angular frequency ω = √(k/m) = √(50 / 0.5) = √100 = 10 rad/s.',
    formula_hint: 'ω = √(k / m)',
    default_marks: 1.5,
    section: 'Section B: Energy in Oscillations',
  },
  {
    subject: 'Physics',
    topic: 'Oscillations',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'Define resonance in forced oscillations and describe the condition required for amplitude to peak.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Resonance occurs when the frequency of an external periodic driving force matches the natural frequency of the oscillating system (ω_driver = ω₀). Under this condition, energy transfer from the driver to the oscillator is maximized, causing vibration amplitude to reach its maximum peak, bounded only by system damping.',
    explanation: 'In the forced oscillator equation, the denominator of amplitude A = (F₀/m) / √[(ω₀² - ω²)² + (bω/m)²] is minimized when ω ≈ ω₀.',
    formula_hint: 'ω_driver = ω_natural',
    default_marks: 2.5,
    section: 'Section B: Forced & Damped Oscillations',
  },

  // ============================================================================
  // 8. Waves (6 Questions)
  // ============================================================================
  {
    subject: 'Physics',
    topic: 'Waves',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Sound waves traveling through air are best categorized as which type of wave?',
    options: [
      { id: 'a', text: 'Transverse electromagnetic waves' },
      { id: 'b', text: 'Longitudinal mechanical waves' },
      { id: 'c', text: 'Transverse mechanical waves' },
      { id: 'd', text: 'Surface torsional waves' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Sound in air propagates via alternating compressions and rarefactions where fluid particles oscillate parallel to the direction of wave propagation, characterizing longitudinal mechanical waves.',
    formula_hint: 'v = √(B / ρ)',
    default_marks: 1.0,
    section: 'Section A: Wave Properties',
  },
  {
    subject: 'Physics',
    topic: 'Waves',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Two tuning forks with frequencies 256 Hz and 260 Hz are sounded together. What is the beat frequency heard by an observer?',
    options: [
      { id: 'a', text: '2 Hz' },
      { id: 'b', text: '4 Hz' },
      { id: 'c', text: '8 Hz' },
      { id: 'd', text: '516 Hz' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Beat frequency is the absolute difference between the two interfering wave frequencies: f_beat = |f₁ - f₂| = |260 - 256| = 4 Hz.',
    formula_hint: 'f_beat = |f₁ - f₂|',
    default_marks: 1.5,
    section: 'Section B: Wave Interference',
  },
  {
    subject: 'Physics',
    topic: 'Waves',
    difficulty: 'hard',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following conditions produce standing waves on a stretched string fixed at both ends?',
    options: [
      { id: 'a', text: 'Two identical waves traveling in opposite directions' },
      { id: 'b', text: 'Nodes are formed at both fixed boundaries' },
      { id: 'c', text: 'String length satisfies L = n · (λ / 2) for integer n ≥ 1' },
      { id: 'd', text: 'Energy is continuously transported along the length of the string' },
    ],
    correct_option_ids: ['a', 'b', 'c'],
    explanation: 'Standing waves arise from superposition of identical counter-propagating waves (a), with zero-displacement nodes at the fixed ends (b), requiring L = nλ/2 (c). Energy does not propagate net across nodes; it is localized (d is false).',
    formula_hint: 'λ_n = 2L / n, f_n = n · (v / 2L)',
    default_marks: 2.0,
    section: 'Section B: Wave Interference',
  },
  {
    subject: 'Physics',
    topic: 'Waves',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'When a sound wave travels from air into water, its frequency remains unchanged while its wavelength increases.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. Wave frequency is determined solely by the vibrating source and does not change across medium boundaries. Because sound travels much faster in water (~1480 m/s) than in air (~343 m/s), λ = v/f increases proportionally.',
    formula_hint: 'v = f · λ => λ = v / f',
    default_marks: 1.0,
    section: 'Section A: Wave Properties',
  },
  {
    subject: 'Physics',
    topic: 'Waves',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'What term describes the apparent change in frequency of a wave due to relative motion between the source and observer?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Doppler Effect',
    explanation: 'The Doppler Effect describes the observed shift in frequency or pitch caused by relative velocity between wave source and observer.',
    formula_hint: 'f’ = f · (v ± v_o) / (v ∓ v_s)',
    default_marks: 1.0,
    section: 'Section B: Wave Interference',
  },
  {
    subject: 'Physics',
    topic: 'Waves',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'Derive the general Doppler frequency equation for sound when both source and observer are moving along the same line through stationary air with speeds v_s and v_o.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Let v be the speed of sound in air, v_s be the velocity of the source, and v_o be the velocity of the observer. During one period T = 1/f, the source moves a distance v_s T. The effective wavelength in front of the source is λ’ = (v - v_s)T = (v - v_s)/f. When the observer moves toward the source with speed v_o, the relative speed of the waves with respect to the observer is v_rel = v + v_o. The observed frequency is f’ = v_rel / λ’ = (v + v_o) / [(v - v_s)/f] = f · [(v + v_o) / (v - v_s)]. In general vector notation: f’ = f · [(v ± v_o) / (v ∓ v_s)].',
    explanation: 'The Doppler effect modifies perceived wavelength due to source movement and modifies rate of wavefront reception due to observer movement.',
    formula_hint: 'f’ = f · [(v ± v_o) / (v ∓ v_s)]',
    default_marks: 4.0,
    section: 'Section C: Derivations & Analytical Physics',
  },

  // ============================================================================
  // 9. Electrostatics (6 Questions)
  // ============================================================================
  {
    subject: 'Physics',
    topic: 'Electrostatics',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'Two point charges +4 μC and -4 μC are separated by 0.1 m in a vacuum. The magnitude of the electrostatic force between them is approximately (use k = 9 × 10⁹ N·m²/C²):',
    options: [
      { id: 'a', text: '1.44 N' },
      { id: 'b', text: '14.4 N' },
      { id: 'c', text: '144 N' },
      { id: 'd', text: '0.144 N' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Coulomb’s Law: F = k|q₁q₂|/r² = (9 × 10⁹)(4 × 10⁻⁶)(4 × 10⁻⁶) / (0.1)² = (144 × 10⁻³) / 0.01 = 14.4 N.',
    formula_hint: 'F = k |q₁ q₂| / r²',
    default_marks: 1.0,
    section: 'Section A: Electric Fields & Potentials',
  },
  {
    subject: 'Physics',
    topic: 'Electrostatics',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'An electric dipole with moment p is placed in a uniform electric field E. What is the maximum torque experienced by the dipole?',
    options: [
      { id: 'a', text: 'Zero' },
      { id: 'b', text: 'p · E' },
      { id: 'c', text: 'p / E' },
      { id: 'd', text: '2 p · E' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Torque is τ = p × E, whose magnitude is τ = p E sin θ. Maximum torque occurs when the dipole is perpendicular to the field (θ = 90°), yielding τ_max = p E.',
    formula_hint: 'τ = p × E => |τ| = p E sin θ',
    default_marks: 1.5,
    section: 'Section A: Electric Fields & Potentials',
  },
  {
    subject: 'Physics',
    topic: 'Electrostatics',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'A parallel plate capacitor with capacitance C is charged to potential difference V and disconnected from the battery. If a dielectric slab of dielectric constant κ = 4 is inserted between the plates, what is the new electrostatic energy stored in the capacitor?',
    options: [
      { id: 'a', text: '4 U₀' },
      { id: 'b', text: 'U₀ / 4' },
      { id: 'c', text: 'U₀' },
      { id: 'd', text: '16 U₀' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Because the battery is disconnected, charge Q remains constant. The capacitance increases to C’ = κ C = 4C. The stored energy becomes U’ = Q² / (2C’) = Q² / (2 × 4C) = U₀ / 4.',
    formula_hint: 'U = Q² / (2C)',
    default_marks: 2.0,
    section: 'Section B: Capacitance & Dielectrics',
  },
  {
    subject: 'Physics',
    topic: 'Electrostatics',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following statements regarding electrostatic equipotential surfaces are true?',
    options: [
      { id: 'a', text: 'Electric field lines are always perpendicular to equipotential surfaces.' },
      { id: 'b', text: 'No work is done moving a test charge between any two points on the same equipotential surface.' },
      { id: 'c', text: 'Two distinct equipotential surfaces can intersect at sharp corners.' },
      { id: 'd', text: 'Equipotential surfaces are closer together in regions of stronger electric fields.' },
    ],
    correct_option_ids: ['a', 'b', 'd'],
    explanation: 'E = -∇V ensures field lines are normal to equipotentials (a), W = qΔV = 0 on the same surface (b), and spacing Δr = ΔV/E is smaller where E is strong (d). Distinct equipotentials never intersect because potential is single-valued (c is false).',
    formula_hint: 'E = - dV / dr, W = q ΔV',
    default_marks: 2.0,
    section: 'Section A: Electric Fields & Potentials',
  },
  {
    subject: 'Physics',
    topic: 'Electrostatics',
    difficulty: 'easy',
    question_type: 'FILL_BLANK',
    question_text: 'What is the capacitance in picofarads (pF) of a capacitor storing 10 nC of charge at a potential difference of 100 V?',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '100',
    explanation: 'Capacitance C = Q / V = (10 × 10⁻⁹ C) / 100 V = 10⁻¹⁰ F = 100 × 10⁻¹² F = 100 pF.',
    formula_hint: 'C = Q / V',
    default_marks: 1.0,
    section: 'Section B: Capacitance & Dielectrics',
  },
  {
    subject: 'Physics',
    topic: 'Electrostatics',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'Define electrostatic shielding and explain how a Faraday cage protects delicate electronics from external electric fields.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Electrostatic shielding is the phenomenon where the interior cavity of a closed metallic conductor remains completely free from external electrostatic fields. When an external electric field is applied, free electrons in the conductor redistribute on the outer surface until the induced internal field precisely cancels the external field, ensuring E = 0 everywhere inside the hollow cavity.',
    explanation: 'Conductor equilibrium requires interior E = 0. Charge resides solely on the exterior surface, protecting interior components.',
    formula_hint: 'E_inside = 0 for electrostatic conductor cavity',
    default_marks: 2.5,
    section: 'Section A: Electric Fields & Potentials',
  },

  // ============================================================================
  // 10. Current Electricity (6 Questions)
  // ============================================================================
  {
    subject: 'Physics',
    topic: 'Current Electricity',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'A wire of resistance R is stretched uniformly to double its original length. What is its new resistance?',
    options: [
      { id: 'a', text: '2R' },
      { id: 'b', text: '4R' },
      { id: 'c', text: 'R/2' },
      { id: 'd', text: 'R/4' },
    ],
    correct_option_ids: ['b'],
    explanation: 'Since total volume V = A · L is constant, doubling length (L’ = 2L) halves cross-sectional area (A’ = A/2). Resistance R’ = ρ L’ / A’ = ρ (2L) / (A/2) = 4 (ρ L / A) = 4R.',
    formula_hint: 'R = ρ L / A, V = A · L = constant',
    default_marks: 1.0,
    section: 'Section A: Ohm’s Law & Resistance',
  },
  {
    subject: 'Physics',
    topic: 'Current Electricity',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'Three identical resistors of 6 Ω each are connected in parallel. What is the equivalent resistance of the combination?',
    options: [
      { id: 'a', text: '18 Ω' },
      { id: 'b', text: '2 Ω' },
      { id: 'c', text: '3 Ω' },
      { id: 'd', text: '6 Ω' },
    ],
    correct_option_ids: ['b'],
    explanation: 'For parallel resistors: 1/R_eq = 1/6 + 1/6 + 1/6 = 3/6 = 1/2 => R_eq = 2 Ω.',
    formula_hint: '1 / R_eq = ∑ (1 / R_i)',
    default_marks: 1.5,
    section: 'Section A: Ohm’s Law & Resistance',
  },
  {
    subject: 'Physics',
    topic: 'Current Electricity',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'A battery of EMF 12 V and internal resistance r = 2 Ω is connected across an external load resistor R. What value of R maximizes power dissipation in the load resistor?',
    options: [
      { id: 'a', text: '1 Ω' },
      { id: 'b', text: '2 Ω' },
      { id: 'c', text: '4 Ω' },
      { id: 'd', text: '6 Ω' },
    ],
    correct_option_ids: ['b'],
    explanation: 'By the Maximum Power Transfer Theorem, power transferred to the load is maximized when the load resistance equals the internal resistance of the power source: R = r = 2 Ω.',
    formula_hint: 'P_load is maximum when R_load = r_internal',
    default_marks: 2.0,
    section: 'Section B: Circuit Analysis & Kirchhoff',
  },
  {
    subject: 'Physics',
    topic: 'Current Electricity',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Kirchhoff’s Current Law (junction rule) is a direct consequence of the conservation of electric charge.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['true'],
    explanation: 'True. In a steady state circuit, charge cannot accumulate indefinitely at a junction node. Therefore, total current entering any junction must equal total current leaving it (∑ I = 0).',
    formula_hint: '∑ I_in = ∑ I_out',
    default_marks: 1.0,
    section: 'Section B: Circuit Analysis & Kirchhoff',
  },
  {
    subject: 'Physics',
    topic: 'Current Electricity',
    difficulty: 'medium',
    question_type: 'FILL_BLANK',
    question_text: 'State the name of the balanced bridge circuit used to measure an unknown electrical resistance with high precision using the null deflection method.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Wheatstone Bridge',
    explanation: 'A Wheatstone Bridge achieves null deflection when R₁/R₂ = R₃/R₄, allowing unknown resistance determination independent of galvanometer calibration.',
    formula_hint: 'P / Q = R / S',
    default_marks: 1.0,
    section: 'Section B: Circuit Analysis & Kirchhoff',
  },
  {
    subject: 'Physics',
    topic: 'Current Electricity',
    difficulty: 'hard',
    question_type: 'LONG',
    question_text: 'Define drift velocity of conduction electrons. Derive the relationship between electric current I, electron density n, charge e, cross-sectional area A, and drift velocity v_d.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Drift velocity is the average velocity acquired by free conduction electrons in a metal opposite to the direction of an applied electric field. Consider a conductor of length L and cross-sectional area A. Volume = A L. Total number of free electrons = n A L. Total free charge Q = n A L e. Time taken by electrons to traverse length L with drift velocity v_d is t = L / v_d. By definition of electric current: I = Q / t = (n A L e) / (L / v_d) = n A e v_d. Thus, I = n A e v_d.',
    explanation: 'Drift velocity describes slow microscopic net electron transport (~1 mm/s) superimposed upon rapid chaotic thermal motion (~10⁶ m/s).',
    formula_hint: 'I = n A e v_d, v_d = e E τ / m',
    default_marks: 4.0,
    section: 'Section C: Derivations & Analytical Physics',
  },

  // ============================================================================
  // 11. Magnetism (6 Questions)
  // ============================================================================
  {
    subject: 'Physics',
    topic: 'Magnetism',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What is the magnetic force on a stationary point charge q resting in a uniform magnetic field B?',
    options: [
      { id: 'a', text: 'q · B' },
      { id: 'b', text: 'Zero' },
      { id: 'c', text: 'q / B' },
      { id: 'd', text: 'q · v · B' },
    ],
    correct_option_ids: ['b'],
    explanation: 'The Lorentz magnetic force is F = q(v × B). When the charge is stationary, velocity v = 0, so the magnetic force is identically zero.',
    formula_hint: 'F_B = q(v × B)',
    default_marks: 1.0,
    section: 'Section A: Magnetic Fields & Forces',
  },
  {
    subject: 'Physics',
    topic: 'Magnetism',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'A charged particle enters a uniform magnetic field with its velocity perpendicular to the field lines. What is the trajectory followed by the particle?',
    options: [
      { id: 'a', text: 'Parabolic' },
      { id: 'b', text: 'Straight line' },
      { id: 'c', text: 'Circular' },
      { id: 'd', text: 'Helical' },
    ],
    correct_option_ids: ['c'],
    explanation: 'Because the magnetic force is always perpendicular to velocity, it acts as a pure centripetal force without changing speed, producing uniform circular motion with radius r = mv / (qB).',
    formula_hint: 'r = m v / (q B)',
    default_marks: 1.5,
    section: 'Section A: Magnetic Fields & Forces',
  },
  {
    subject: 'Physics',
    topic: 'Magnetism',
    difficulty: 'hard',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following materials exhibit negative magnetic susceptibility (χ < 0) and are repelled by magnetic field gradients?',
    options: [
      { id: 'a', text: 'Bismuth' },
      { id: 'b', text: 'Copper' },
      { id: 'c', text: 'Aluminum' },
      { id: 'd', text: 'Iron' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'Bismuth and copper are diamagnetic materials with negative susceptibility (χ < 0) that weakly expel magnetic fields. Aluminum is paramagnetic (χ > 0) and iron is ferromagnetic (χ >> 0).',
    formula_hint: 'χ_dia < 0, μ_r < 1',
    default_marks: 2.0,
    section: 'Section B: Magnetic Materials',
  },
  {
    subject: 'Physics',
    topic: 'Magnetism',
    difficulty: 'easy',
    question_type: 'TRUE_FALSE',
    question_text: 'Isolated magnetic monopoles have been observed and confirm Gauss’s Law for magnetism.',
    options: [
      { id: 'true', text: 'True' },
      { id: 'false', text: 'False' },
    ],
    correct_option_ids: ['false'],
    explanation: 'False. Gauss’s Law for magnetism states ∮ B · dA = 0, indicating that magnetic monopoles do not exist in classical electromagnetism; magnetic field lines are continuous closed loops.',
    formula_hint: '∇ · B = 0 or ∮ B · dA = 0',
    default_marks: 1.0,
    section: 'Section A: Magnetic Fields & Forces',
  },
  {
    subject: 'Physics',
    topic: 'Magnetism',
    difficulty: 'medium',
    question_type: 'VERY_SHORT',
    question_text: 'State Ampère’s Circuital Law in mathematical form for magnetostatics.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '∮ B · dl = μ₀ I_enc',
    explanation: 'Ampère’s Circuital Law states that the line integral of magnetic field B around any closed path equals μ₀ times the net steady current enclosed by the loop.',
    formula_hint: '∮ B · dl = μ₀ I_enclosed',
    default_marks: 1.0,
    section: 'Section A: Magnetic Fields & Forces',
  },
  {
    subject: 'Physics',
    topic: 'Magnetism',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'State Faraday’s Law of Electromagnetic Induction and Lenz’s Law, explaining how Lenz’s Law reflects energy conservation.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Faraday’s Law states that the induced electromotive force in any closed circuit equals the negative time rate of change of magnetic flux through the circuit: ε = -dΦ_B/dt. Lenz’s Law gives the negative sign: the induced current always flows in such a direction that its own magnetic field opposes the change in flux producing it. If the induced field instead aided the flux change, a perpetual motion machine would arise without external work, violating energy conservation.',
    explanation: 'External mechanical work done overcoming magnetic opposition is converted into electrical energy, satisfying the First Law of Thermodynamics.',
    formula_hint: 'ε = - dΦ_B / dt',
    default_marks: 2.5,
    section: 'Section B: Electromagnetic Induction',
  },

  // ============================================================================
  // 12. Optics (6 Questions)
  // ============================================================================
  {
    subject: 'Physics',
    topic: 'Optics',
    difficulty: 'easy',
    question_type: 'MCQ',
    question_text: 'What happens to the focal length of a glass convex lens when it is submerged in water (n_water = 1.33) compared to air (n_air = 1.0)?',
    options: [
      { id: 'a', text: 'It increases' },
      { id: 'b', text: 'It decreases' },
      { id: 'c', text: 'It remains unchanged' },
      { id: 'd', text: 'It becomes zero' },
    ],
    correct_option_ids: ['a'],
    explanation: 'By the Lens Maker’s Formula: 1/f = (n_lens/n_med - 1)(1/R₁ - 1/R₂). In water, the relative refractive index (1.5 / 1.33 = 1.13) is smaller than in air (1.5 / 1.0 = 1.5). Thus 1/f decreases and the focal length f increases.',
    formula_hint: '1/f = (n_rel - 1) · (1/R₁ - 1/R₂)',
    default_marks: 1.0,
    section: 'Section A: Geometrical Optics',
  },
  {
    subject: 'Physics',
    topic: 'Optics',
    difficulty: 'medium',
    question_type: 'MCQ',
    question_text: 'A light ray passes from diamond (n = 2.42) into water (n = 1.33). What is the critical angle for total internal reflection?',
    options: [
      { id: 'a', text: 'arcsin(1.33 / 2.42) ≈ 33.3°' },
      { id: 'b', text: 'arcsin(2.42 / 1.33)' },
      { id: 'c', text: '45°' },
      { id: 'd', text: '90°' },
    ],
    correct_option_ids: ['a'],
    explanation: 'Total internal reflection occurs when traveling from denser to rarer medium. The critical angle satisfies sin θ_c = n₂ / n₁ = 1.33 / 2.42 ≈ 0.55 => θ_c ≈ 33.3°.',
    formula_hint: 'sin θ_c = n_rarer / n_denser',
    default_marks: 1.5,
    section: 'Section A: Geometrical Optics',
  },
  {
    subject: 'Physics',
    topic: 'Optics',
    difficulty: 'hard',
    question_type: 'MCQ',
    question_text: 'In Young’s Double Slit Experiment, if slit separation d is halved and screen distance D is doubled, the fringe width β becomes:',
    options: [
      { id: 'a', text: 'Unchanged' },
      { id: 'b', text: 'Doubled' },
      { id: 'c', text: 'Quadrupled (4 times)' },
      { id: 'd', text: 'Halved' },
    ],
    correct_option_ids: ['c'],
    explanation: 'Fringe width is β = λ D / d. If D’ = 2D and d’ = d/2, then β’ = λ (2D) / (d/2) = 4 (λ D / d) = 4β.',
    formula_hint: 'β = λ D / d',
    default_marks: 2.0,
    section: 'Section B: Wave Optics',
  },
  {
    subject: 'Physics',
    topic: 'Optics',
    difficulty: 'medium',
    question_type: 'MULTIPLE_SELECT',
    question_text: 'Which of the following optical phenomena demonstrate the transverse wave nature of light?',
    options: [
      { id: 'a', text: 'Polarization' },
      { id: 'b', text: 'Brewster’s angle reflection' },
      { id: 'c', text: 'Diffraction' },
      { id: 'd', text: 'Interference' },
    ],
    correct_option_ids: ['a', 'b'],
    explanation: 'Polarization and Brewster’s angle reflection only occur for transverse oscillations. Longitudinal waves (like sound) cannot be polarized, whereas interference and diffraction occur in all wave types.',
    formula_hint: 'tan θ_B = n, I = I₀ cos² θ (Malus Law)',
    default_marks: 2.0,
    section: 'Section B: Wave Optics',
  },
  {
    subject: 'Physics',
    topic: 'Optics',
    difficulty: 'easy',
    question_type: 'FILL_BLANK',
    question_text: 'Calculate the optical power in diopters of a thin diverging lens with focal length -25 cm.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: '-4',
    explanation: 'Power P = 1 / f (in meters). With f = -0.25 m, P = 1 / (-0.25) = -4 Diopters.',
    formula_hint: 'P = 1 / f (meters)',
    default_marks: 1.0,
    section: 'Section A: Geometrical Optics',
  },
  {
    subject: 'Physics',
    topic: 'Optics',
    difficulty: 'medium',
    question_type: 'SHORT',
    question_text: 'State Brewster’s Law and explain the polarization state of light reflected from a dielectric boundary at Brewster’s angle.',
    options: [],
    correct_option_ids: [],
    correct_answer_text: 'Brewster’s Law states that when unpolarized light strikes a dielectric interface at an angle of incidence θ_B such that tan θ_B = n₂/n₁, the reflected ray is 100% linearly polarized with its electric field vector vibrating strictly perpendicular to the plane of incidence (s-polarized). At this angle, the reflected ray and refracted ray are mutually perpendicular (θ_B + r = 90°).',
    explanation: 'The oscillating electric dipoles in the medium radiate perpendicular to their dipole axis; along the reflection angle, dipole radiation is zero for p-polarization, leaving only s-polarized reflection.',
    formula_hint: 'tan θ_B = n₂ / n₁',
    default_marks: 2.5,
    section: 'Section B: Wave Optics',
  },
];
